/*
 Highcharts JS v8.0.0 (2020-02-08)

 Accessibility module

 (c) 2010-2019 Highsoft AS
 Author: Oystein Moseng

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/accessibility",["highcharts"],function(q){a(q);a.Highcharts=q;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function q(a,f,m,h){a.hasOwnProperty(f)||(a[f]=h.apply(null,m))}a=a?a._modules:{};q(a,"modules/accessibility/utils/htmlUtilities.js",[a["parts/Utilities.js"],a["parts/Globals.js"]],function(a,f){function v(a){return a.replace(/&/g,
"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")}var h=a.merge,l=f.win,e=l.document;return{addClass:function(a,g){a.classList?a.classList.add(g):0>a.className.indexOf(g)&&(a.className+=g)},escapeStringForHTML:v,getElement:function(a){return e.getElementById(a)},getFakeMouseEvent:function(a){if("function"===typeof l.MouseEvent)return new l.MouseEvent(a);if(e.createEvent){var g=e.createEvent("MouseEvent");if(g.initMouseEvent)return g.initMouseEvent(a,
!0,!0,l,"click"===a?1:0,0,0,0,0,!1,!1,!1,!1,0,null),g}return{type:a}},removeElement:function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},reverseChildNodes:function(a){for(var g=a.childNodes.length;g--;)a.appendChild(a.childNodes[g])},setElAttrs:function(a,g){Object.keys(g).forEach(function(e){var d=g[e];null===d?a.removeAttribute(e):(d=v(""+d),a.setAttribute(e,d))})},stripHTMLTagsFromString:function(a){return"string"===typeof a?a.replace(/<\/?[^>]+(>|$)/g,""):a},visuallyHideElement:function(a){h(!0,
a.style,{position:"absolute",width:"1px",height:"1px",overflow:"hidden",clip:"rect(1px, 1px, 1px, 1px)",marginTop:"-3px","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",filter:"alpha(opacity=1)",opacity:"0.01"})}}});q(a,"modules/accessibility/utils/chartUtilities.js",[a["modules/accessibility/utils/htmlUtilities.js"],a["parts/Globals.js"]],function(a,f){function v(a){if(a.points&&a.points.length&&a.points[0].graphic)return a.points[0].graphic.element}function h(a){var g=v(a);return g&&
g.parentNode||a.graph&&a.graph.element||a.group&&a.group.element}function l(a,e){e.setAttribute("aria-hidden",!1);e!==a.renderTo&&e.parentNode&&(Array.prototype.forEach.call(e.parentNode.childNodes,function(a){a.hasAttribute("aria-hidden")||a.setAttribute("aria-hidden",!0)}),l(a,e.parentNode))}var e=a.stripHTMLTagsFromString,k=f.find;return{getChartTitle:function(a){return e(a.options.title.text||a.langFormat("accessibility.defaultChartTitle",{chart:a}))},getAxisDescription:function(a){return e(a&&
(a.userOptions&&a.userOptions.accessibility&&a.userOptions.accessibility.description||a.axisTitle&&a.axisTitle.textStr||a.options.id||a.categories&&"categories"||a.isDatetimeAxis&&"Time"||"values"))},getPointFromXY:function(a,e,d){for(var c=a.length,b;c--;)if(b=k(a[c].points||[],function(b){return b.x===e&&b.y===d}))return b},getSeriesFirstPointElement:v,getSeriesFromName:function(a,e){return e?(a.series||[]).filter(function(a){return a.name===e}):a.series},getSeriesA11yElement:h,unhideChartElementFromAT:l,
hideSeriesFromAT:function(a){(a=h(a))&&a.setAttribute("aria-hidden",!0)}}});q(a,"modules/accessibility/KeyboardNavigationHandler.js",[a["parts/Globals.js"]],function(a){function f(a,f){this.chart=a;this.keyCodeMap=f.keyCodeMap||[];this.validate=f.validate;this.init=f.init;this.terminate=f.terminate;this.response={success:1,prev:2,next:3,noHandler:4,fail:5}}var v=a.find;f.prototype={run:function(a){var f=a.which||a.keyCode,e=this.response.noHandler,k=v(this.keyCodeMap,function(a){return-1<a[0].indexOf(f)});
k?e=k[1].call(this,f,a):9===f&&(e=this.response[a.shiftKey?"prev":"next"]);return e}};return f});q(a,"modules/accessibility/utils/EventProvider.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,f){var v=f.addEvent;f=f.extend;var h=function(){this.eventRemovers=[]};f(h.prototype,{addEvent:function(){var f=v.apply(a,arguments);this.eventRemovers.push(f);return f},removeAddedEvents:function(){this.eventRemovers.forEach(function(a){a()});this.eventRemovers=[]}});return h});q(a,"modules/accessibility/utils/DOMElementProvider.js",
[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,f,m){var v=a.win.document;a=f.extend;var l=m.removeElement;m=function(){this.elements=[]};a(m.prototype,{createElement:function(){var a=v.createElement.apply(v,arguments);this.elements.push(a);return a},destroyCreatedElements:function(){this.elements.forEach(function(a){l(a)});this.elements=[]}});return m});q(a,"modules/accessibility/AccessibilityComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],
a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/EventProvider.js"],a["modules/accessibility/utils/DOMElementProvider.js"]],function(a,f,m,h,l,e){function k(){}var g=a.win,p=g.document,d=a.fireEvent;a=f.extend;var c=f.merge,b=m.removeElement,r=m.getFakeMouseEvent,w=h.unhideChartElementFromAT;k.prototype={initBase:function(b){this.chart=b;this.eventProvider=new l;this.domElementProvider=new e;this.keyCodes={left:37,
right:39,up:38,down:40,enter:13,space:32,esc:27,tab:9}},addEvent:function(){return this.eventProvider.addEvent.apply(this.eventProvider,arguments)},createElement:function(){return this.domElementProvider.createElement.apply(this.domElementProvider,arguments)},fireEventOnWrappedOrUnwrappedElement:function(b,a){var c=a.type;p.createEvent&&(b.dispatchEvent||b.fireEvent)?b.dispatchEvent?b.dispatchEvent(a):b.fireEvent(c,a):d(b,c,a)},fakeClickEvent:function(b){if(b){var a=r("click");this.fireEventOnWrappedOrUnwrappedElement(b,
a)}},addProxyGroup:function(b){this.createOrUpdateProxyContainer();var a=this.createElement("div");Object.keys(b||{}).forEach(function(c){null!==b[c]&&a.setAttribute(c,b[c])});this.chart.a11yProxyContainer.appendChild(a);return a},createOrUpdateProxyContainer:function(){var b=this.chart,a=b.renderer.box;b.a11yProxyContainer=b.a11yProxyContainer||this.createProxyContainerElement();a.nextSibling!==b.a11yProxyContainer&&b.container.insertBefore(b.a11yProxyContainer,a.nextSibling)},createProxyContainerElement:function(){var b=
p.createElement("div");b.className="highcharts-a11y-proxy-container";return b},createProxyButton:function(b,a,r,d,e){var t=b.element,u=this.createElement("button"),f=c({"aria-label":t.getAttribute("aria-label")},r);b=this.getElementPosition(d||b);Object.keys(f).forEach(function(b){null!==f[b]&&u.setAttribute(b,f[b])});u.className="highcharts-a11y-proxy-button";e&&this.addEvent(u,"click",e);this.setProxyButtonStyle(u,b);this.proxyMouseEventsForButton(t,u);a.appendChild(u);f["aria-hidden"]||w(this.chart,
u);return u},getElementPosition:function(b){var a=b.element;return(b=this.chart.renderTo)&&a&&a.getBoundingClientRect?(a=a.getBoundingClientRect(),b=b.getBoundingClientRect(),{x:a.left-b.left,y:a.top-b.top,width:a.right-a.left,height:a.bottom-a.top}):{x:0,y:0,width:1,height:1}},setProxyButtonStyle:function(b,a){c(!0,b.style,{"border-width":0,"background-color":"transparent",cursor:"pointer",outline:"none",opacity:.001,filter:"alpha(opacity=1)","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",
zIndex:999,overflow:"hidden",padding:0,margin:0,display:"block",position:"absolute",width:(a.width||1)+"px",height:(a.height||1)+"px",left:(a.x||0)+"px",top:(a.y||0)+"px"})},proxyMouseEventsForButton:function(b,a){var c=this;"click touchstart touchend touchcancel touchmove mouseover mouseenter mouseleave mouseout".split(" ").forEach(function(r){c.addEvent(a,r,function(a){var r=c.cloneMouseEvent(a);b&&c.fireEventOnWrappedOrUnwrappedElement(b,r);a.stopPropagation();a.preventDefault()})})},cloneMouseEvent:function(b){if("function"===
typeof g.MouseEvent)return new g.MouseEvent(b.type,b);if(p.createEvent){var a=p.createEvent("MouseEvent");if(a.initMouseEvent)return a.initMouseEvent(b.type,b.bubbles,b.cancelable,b.view||g,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget),a}return r(b.type)},destroyBase:function(){b(this.chart.a11yProxyContainer);this.domElementProvider.destroyCreatedElements();this.eventProvider.removeAddedEvents()}};a(k.prototype,{init:function(){},
getKeyboardNavigation:function(){},onChartUpdate:function(){},onChartRender:function(){},destroy:function(){}});return k});q(a,"modules/accessibility/KeyboardNavigation.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/EventProvider.js"]],function(a,f,m,h,l){function e(b,a){this.init(b,a)}var k=a.win,g=k.document,p=f.addEvent,d=f.fireEvent,c=m.getElement;p(g,"keydown",
function(b){27===(b.which||b.keyCode)&&a.charts&&a.charts.forEach(function(b){b&&b.dismissPopupContent&&b.dismissPopupContent()})});a.Chart.prototype.dismissPopupContent=function(){var b=this;d(this,"dismissPopupContent",{},function(){b.tooltip&&b.tooltip.hide(0);b.hideExportMenu()})};e.prototype={init:function(b,a){var c=this,r=this.eventProvider=new l;this.chart=b;this.components=a;this.modules=[];this.currentModuleIx=0;r.addEvent(b.renderTo,"keydown",function(b){c.onKeydown(b)});r.addEvent(g,"mouseup",
function(){c.onMouseUp()});this.update();this.modules.length&&this.modules[0].init(1)},update:function(b){var a=this.chart.options.accessibility;a=a&&a.keyboardNavigation;var c=this.components;this.updateContainerTabindex();a&&a.enabled&&b&&b.length?(this.modules=b.reduce(function(b,a){a=c[a].getKeyboardNavigation();return b.concat(a)},[new h(this.chart,{init:function(){}})]),this.updateExitAnchor()):(this.modules=[],this.currentModuleIx=0,this.removeExitAnchor())},onMouseUp:function(){if(!(this.keyboardReset||
this.chart.pointer&&this.chart.pointer.chartPosition)){var b=this.chart,a=this.modules&&this.modules[this.currentModuleIx||0];a&&a.terminate&&a.terminate();b.focusElement&&b.focusElement.removeFocusBorder();this.currentModuleIx=0;this.keyboardReset=!0}},onKeydown:function(b){b=b||k.event;var a,c=this.modules&&this.modules.length&&this.modules[this.currentModuleIx];this.keyboardReset=!1;if(c){var d=c.run(b);d===c.response.success?a=!0:d===c.response.prev?a=this.prev():d===c.response.next&&(a=this.next());
a&&(b.preventDefault(),b.stopPropagation())}},prev:function(){return this.move(-1)},next:function(){return this.move(1)},move:function(b){var a=this.modules&&this.modules[this.currentModuleIx];a&&a.terminate&&a.terminate(b);this.chart.focusElement&&this.chart.focusElement.removeFocusBorder();this.currentModuleIx+=b;if(a=this.modules&&this.modules[this.currentModuleIx]){if(a.validate&&!a.validate())return this.move(b);if(a.init)return a.init(b),!0}this.currentModuleIx=0;0<b?(this.exiting=!0,this.exitAnchor.focus()):
this.chart.renderTo.focus();return!1},updateExitAnchor:function(){var b=c("highcharts-end-of-chart-marker-"+this.chart.index);this.removeExitAnchor();b?(this.makeElementAnExitAnchor(b),this.exitAnchor=b):this.createExitAnchor()},updateContainerTabindex:function(){var b=this.chart.options.accessibility;b=b&&b.keyboardNavigation;b=!(b&&!1===b.enabled);var a=this.chart.container,c=a.getAttribute("tabIndex");b&&!c?a.setAttribute("tabindex","0"):b||"0"!==c||a.removeAttribute("tabindex")},makeElementAnExitAnchor:function(b){b.setAttribute("class",
"highcharts-exit-anchor");b.setAttribute("tabindex","0");b.setAttribute("aria-hidden",!1);this.addExitAnchorEventsToEl(b)},createExitAnchor:function(){var b=this.chart,a=this.exitAnchor=g.createElement("div");b.renderTo.appendChild(a);this.makeElementAnExitAnchor(a)},removeExitAnchor:function(){this.exitAnchor&&this.exitAnchor.parentNode&&(this.exitAnchor.parentNode.removeChild(this.exitAnchor),delete this.exitAnchor)},addExitAnchorEventsToEl:function(b){var a=this.chart,c=this;this.eventProvider.addEvent(b,
"focus",function(b){b=b||k.event;b.relatedTarget&&a.container.contains(b.relatedTarget)||c.exiting?c.exiting=!1:(a.renderTo.focus(),b.preventDefault(),c.modules&&c.modules.length&&(c.currentModuleIx=c.modules.length-1,(b=c.modules[c.currentModuleIx])&&b.validate&&!b.validate()?c.prev():b&&b.init(-1)))})},destroy:function(){this.removeExitAnchor();this.eventProvider.removeAddedEvents();"0"===this.chart.container.getAttribute("tabindex")&&this.chart.container.removeAttribute("tabindex")}};return e});
q(a,"modules/accessibility/components/LegendComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,f,m,h,l){var e=f.addEvent,k=f.extend,g=f.fireEvent,p=l.stripHTMLTagsFromString,d=l.removeElement;a.Chart.prototype.highlightLegendItem=function(a){var b=this.legend.allItems,c=this.highlightedLegendItemIx;if(b[a]){b[c]&&g(b[c].legendGroup.element,
"mouseout");c=this.legend;var d=c.allItems[a].pageIx,e=c.currentPage;"undefined"!==typeof d&&d+1!==e&&c.scroll(1+d-e);this.setFocusToElement(b[a].legendItem,b[a].a11yProxyElement);g(b[a].legendGroup.element,"mouseover");return!0}return!1};e(a.Legend,"afterColorizeItem",function(a){var b=a.item;this.chart.options.accessibility.enabled&&b&&b.a11yProxyElement&&b.a11yProxyElement.setAttribute("aria-pressed",a.visible?"false":"true")});f=function(){};f.prototype=new m;k(f.prototype,{init:function(){var c=
this;this.addEvent(a.Legend,"afterScroll",function(){this.chart===c.chart&&c.updateProxies()})},updateLegendItemProxyVisibility:function(){var a=this.chart.legend,b=a.currentPage||1;(a.allItems||[]).forEach(function(a){var c=(a.pageIx||0)!==b-1;a.a11yProxyElement&&(a.a11yProxyElement.style.visibility=c?"hidden":"visible")})},onChartRender:function(){this.legendProxyButtonClicked?delete this.legendProxyButtonClicked:this.updateProxies()},updateProxies:function(){d(this.legendProxyGroup);var a=this.chart,
b=a.legend&&a.legend.allItems,r=a.options.legend.accessibility||{};!b||!b.length||a.colorAxis&&a.colorAxis.length||!1===r.enabled||(this.addLegendProxyGroup(),this.proxyLegendItems(),this.updateLegendItemProxyVisibility())},addLegendProxyGroup:function(){var a=this.chart.options.accessibility,b=this.chart.langFormat("accessibility.legend.legendLabel",{});this.legendProxyGroup=this.addProxyGroup({"aria-label":b,role:"all"===a.landmarkVerbosity?"region":null})},proxyLegendItems:function(){var a=this;
(this.chart.legend&&this.chart.legend.allItems||[]).forEach(function(b){b.legendItem&&b.legendItem.element&&a.proxyLegendItem(b)})},proxyLegendItem:function(a){var b=this,c=this.chart.langFormat("accessibility.legend.legendItem",{chart:this.chart,itemName:p(a.name)});a.a11yProxyElement=this.createProxyButton(a.legendItem,this.legendProxyGroup,{tabindex:-1,"aria-pressed":!a.visible,"aria-label":c},a.legendGroup.div?a.legendItem:a.legendGroup,function(){b.legendProxyButtonClicked=!0})},getKeyboardNavigation:function(){var a=
this.keyCodes,b=this;return new h(this.chart,{keyCodeMap:[[[a.left,a.right,a.up,a.down],function(a){return b.onKbdArrowKey(this,a)}],[[a.enter,a.space],function(){return b.onKbdClick(this)}]],validate:function(){return b.shouldHaveLegendNavigation()},init:function(a){return b.onKbdNavigationInit(a)}})},onKbdArrowKey:function(a,b){var c=this.keyCodes,d=a.response,e=this.chart,t=e.options.accessibility,u=e.legend.allItems.length;b=b===c.left||b===c.up?-1:1;return e.highlightLegendItem(this.highlightedLegendItemIx+
b)?(this.highlightedLegendItemIx+=b,d.success):1<u&&t.keyboardNavigation.wrapAround?(a.init(b),d.success):d[0<b?"next":"prev"]},onKbdClick:function(a){var b=this.chart.legend.allItems[this.highlightedLegendItemIx];b&&b.a11yProxyElement&&g(b.a11yProxyElement,"click");return a.response.success},shouldHaveLegendNavigation:function(){var a=this.chart,b=a.colorAxis&&a.colorAxis.length,d=(a.options.legend||{}).accessibility||{};return!!(a.legend&&a.legend.allItems&&a.legend.display&&!b&&d.enabled&&d.keyboardNavigation&&
d.keyboardNavigation.enabled)},onKbdNavigationInit:function(a){var b=this.chart,c=b.legend.allItems.length-1;a=0<a?0:c;b.highlightLegendItem(a);this.highlightedLegendItemIx=a}});return f});q(a,"modules/accessibility/components/MenuComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],
function(a,f,m,h,l,e){function k(a){return a.exportSVGElements&&a.exportSVGElements[0]}f=f.extend;var g=l.unhideChartElementFromAT,p=e.removeElement,d=e.getFakeMouseEvent;a.Chart.prototype.showExportMenu=function(){var a=k(this);if(a&&(a=a.element,a.onclick))a.onclick(d("click"))};a.Chart.prototype.hideExportMenu=function(){var a=this.exportDivElements;a&&this.exportContextMenu&&(a.forEach(function(a){if("highcharts-menu-item"===a.className&&a.onmouseout)a.onmouseout(d("mouseout"))}),this.highlightedExportItemIx=
0,this.exportContextMenu.hideMenu(),this.container.focus())};a.Chart.prototype.highlightExportItem=function(a){var b=this.exportDivElements&&this.exportDivElements[a],c=this.exportDivElements&&this.exportDivElements[this.highlightedExportItemIx];if(b&&"LI"===b.tagName&&(!b.children||!b.children.length)){var e=!!(this.renderTo.getElementsByTagName("g")[0]||{}).focus;b.focus&&e&&b.focus();if(c&&c.onmouseout)c.onmouseout(d("mouseout"));if(b.onmouseover)b.onmouseover(d("mouseover"));this.highlightedExportItemIx=
a;return!0}return!1};a.Chart.prototype.highlightLastExportItem=function(){var a;if(this.exportDivElements)for(a=this.exportDivElements.length;a--;)if(this.highlightExportItem(a))return!0;return!1};a=function(){};a.prototype=new m;f(a.prototype,{init:function(){var a=this.chart,b=this;this.addEvent(a,"exportMenuShown",function(){b.onMenuShown()});this.addEvent(a,"exportMenuHidden",function(){b.onMenuHidden()})},onMenuHidden:function(){var a=this.chart.exportContextMenu;a&&a.setAttribute("aria-hidden",
"true");this.isExportMenuShown=!1;this.setExportButtonExpandedState("false")},onMenuShown:function(){var a=this.chart,b=a.exportContextMenu;b&&(this.addAccessibleContextMenuAttribs(),g(a,b));this.isExportMenuShown=!0;this.setExportButtonExpandedState("true")},setExportButtonExpandedState:function(a){var b=this.exportButtonProxy;b&&b.setAttribute("aria-expanded",a)},onChartRender:function(){var a=this.chart,b=a.options.accessibility;p(this.exportProxyGroup);var d=a.options.exporting,e=k(a);d&&!1!==
d.enabled&&d.accessibility&&d.accessibility.enabled&&e&&e.element&&(this.exportProxyGroup=this.addProxyGroup("all"===b.landmarkVerbosity?{"aria-label":a.langFormat("accessibility.exporting.exportRegionLabel",{chart:a}),role:"region"}:{}),b=k(this.chart),this.exportButtonProxy=this.createProxyButton(b,this.exportProxyGroup,{"aria-label":a.langFormat("accessibility.exporting.menuButtonLabel",{chart:a}),"aria-expanded":"false"}))},addAccessibleContextMenuAttribs:function(){var a=this.chart,b=a.exportDivElements;
b&&b.length&&(b.forEach(function(a){"LI"!==a.tagName||a.children&&a.children.length?a.setAttribute("aria-hidden","true"):a.setAttribute("tabindex",-1)}),b=b[0].parentNode,b.removeAttribute("aria-hidden"),b.setAttribute("aria-label",a.langFormat("accessibility.exporting.chartMenuLabel",{chart:a})))},getKeyboardNavigation:function(){var a=this.keyCodes,b=this.chart,d=this;return new h(b,{keyCodeMap:[[[a.left,a.up],function(){return d.onKbdPrevious(this)}],[[a.right,a.down],function(){return d.onKbdNext(this)}],
[[a.enter,a.space],function(){return d.onKbdClick(this)}],[[a.esc],function(){return this.response.prev}]],validate:function(){return b.exportChart&&!1!==b.options.exporting.enabled&&!1!==b.options.exporting.accessibility.enabled},init:function(){b.setFocusToElement(b.exportingGroup,this.exportButtonProxy.element)},terminate:function(){b.hideExportMenu()}})},onKbdPrevious:function(a){var b=this.chart,d=b.options.accessibility;a=a.response;for(var c=b.highlightedExportItemIx||0;c--;)if(b.highlightExportItem(c))return a.success;
return d.keyboardNavigation.wrapAround?(b.highlightLastExportItem(),a.success):a.prev},onKbdNext:function(a){var b=this.chart,d=b.options.accessibility;a=a.response;for(var c=(b.highlightedExportItemIx||0)+1;c<b.exportDivElements.length;++c)if(b.highlightExportItem(c))return a.success;return d.keyboardNavigation.wrapAround?(b.highlightExportItem(0),a.success):a.next},onKbdClick:function(a){var b=this.chart,d=b.exportDivElements[b.highlightedExportItemIx],c=k(b).element;this.isExportMenuShown?this.fakeClickEvent(d):
(this.fakeClickEvent(c),b.highlightExportItem(0));return a.response.success}});return a});q(a,"modules/accessibility/components/SeriesComponent/SeriesKeyboardNavigation.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/EventProvider.js"],a["modules/accessibility/utils/chartUtilities.js"]],function(a,f,m,h,l){function e(a){var b=a.index,d=a.series.points,c=d.length;if(d[b]!==a)for(;c--;){if(d[c]===a)return c}else return b}
function k(a){var b=a.chart.options.accessibility.keyboardNavigation.seriesNavigation,d=a.options.accessibility||{},c=d.keyboardNavigation;return c&&!1===c.enabled||!1===d.enabled||!1===a.options.enableMouseTracking||!a.visible||b.pointNavigationEnabledThreshold&&b.pointNavigationEnabledThreshold<=a.points.length}function g(a){var b=a.series.chart.options.accessibility;return a.isNull&&b.keyboardNavigation.seriesNavigation.skipNullPoints||!1===a.visible||k(a.series)}function p(a,b,d,c){var n=Infinity,
u=b.points.length,e=function(a){return!(r(a.plotX)&&r(a.plotY))};if(!e(a)){for(;u--;){var t=b.points[u];if(!e(t)&&(t=(a.plotX-t.plotX)*(a.plotX-t.plotX)*(d||1)+(a.plotY-t.plotY)*(a.plotY-t.plotY)*(c||1),t<n)){n=t;var f=u}}return r(f)?b.points[f]:void 0}}function d(a){var b=!1;delete a.highlightedPoint;return b=a.series.reduce(function(a,b){return a||b.highlightFirstValidPoint()},!1)}function c(a,b){this.keyCodes=b;this.chart=a}var b=f.extend,r=f.defined,w=l.getPointFromXY,v=l.getSeriesFromName;a.Series.prototype.keyboardMoveVertical=
!0;["column","pie"].forEach(function(b){a.seriesTypes[b]&&(a.seriesTypes[b].prototype.keyboardMoveVertical=!1)});a.Point.prototype.highlight=function(){var a=this.series.chart;if(this.isNull)a.tooltip&&a.tooltip.hide(0);else this.onMouseOver();this.graphic&&a.setFocusToElement(this.graphic);a.highlightedPoint=this;return this};a.Chart.prototype.highlightAdjacentPoint=function(a){var b=this.series,d=this.highlightedPoint,c=d&&e(d)||0,n=d&&d.series.points,t=this.series&&this.series[this.series.length-
1];t=t&&t.points&&t.points[t.points.length-1];if(!b[0]||!b[0].points)return!1;if(d){if(b=b[d.series.index+(a?1:-1)],c=n[c+(a?1:-1)],!c&&b&&(c=b.points[a?0:b.points.length-1]),!c)return!1}else c=a?b[0].points[0]:t;return g(c)?(b=c.series,k(b)?this.highlightedPoint=a?b.points[b.points.length-1]:b.points[0]:this.highlightedPoint=c,this.highlightAdjacentPoint(a)):c.highlight()};a.Series.prototype.highlightFirstValidPoint=function(){var a=this.chart.highlightedPoint,b=(a&&a.series)===this?e(a):0;a=this.points;
var d=a.length;if(a&&d){for(var c=b;c<d;++c)if(!g(a[c]))return a[c].highlight();for(;0<=b;--b)if(!g(a[b]))return a[b].highlight()}return!1};a.Chart.prototype.highlightAdjacentSeries=function(a){var b,d=this.highlightedPoint;var c=(b=this.series&&this.series[this.series.length-1])&&b.points&&b.points[b.points.length-1];if(!this.highlightedPoint)return b=a?this.series&&this.series[0]:b,(c=a?b&&b.points&&b.points[0]:c)?c.highlight():!1;b=this.series[d.series.index+(a?-1:1)];if(!b)return!1;c=p(d,b,4);
if(!c)return!1;if(k(b))return c.highlight(),a=this.highlightAdjacentSeries(a),a?a:(d.highlight(),!1);c.highlight();return c.series.highlightFirstValidPoint()};a.Chart.prototype.highlightAdjacentPointVertical=function(a){var b=this.highlightedPoint,d=Infinity,c;if(!r(b.plotX)||!r(b.plotY))return!1;this.series.forEach(function(n){k(n)||n.points.forEach(function(e){if(r(e.plotY)&&r(e.plotX)&&e!==b){var t=e.plotY-b.plotY,u=Math.abs(e.plotX-b.plotX);u=Math.abs(t)*Math.abs(t)+u*u*4;n.yAxis&&n.yAxis.reversed&&
(t*=-1);!(0>=t&&a||0<=t&&!a||5>u||g(e))&&u<d&&(d=u,c=e)}})});return c?c.highlight():!1};b(c.prototype,{init:function(){var b=this,c=this.chart,e=this.eventProvider=new h;e.addEvent(a.Series,"destroy",function(){return b.onSeriesDestroy(this)});e.addEvent(c,"afterDrilldown",function(){d(this);this.focusElement&&this.focusElement.removeFocusBorder()});e.addEvent(c,"drilldown",function(a){a=a.point;var c=a.series;b.lastDrilledDownPoint={x:a.x,y:a.y,seriesName:c?c.name:""}});e.addEvent(c,"drillupall",
function(){setTimeout(function(){b.onDrillupAll()},10)})},onDrillupAll:function(){var a=this.lastDrilledDownPoint,b=this.chart,c=a&&v(b,a.seriesName),d;a&&c&&r(a.x)&&r(a.y)&&(d=w(c,a.x,a.y));b.container&&b.container.focus();d&&d.highlight&&d.highlight();b.focusElement&&b.focusElement.removeFocusBorder()},getKeyboardNavigationHandler:function(){var a=this,b=this.keyCodes,c=this.chart,d=c.inverted;return new m(c,{keyCodeMap:[[d?[b.up,b.down]:[b.left,b.right],function(b){return a.onKbdSideways(this,
b)}],[d?[b.left,b.right]:[b.up,b.down],function(b){return a.onKbdVertical(this,b)}],[[b.enter,b.space],function(){c.highlightedPoint&&c.highlightedPoint.firePointEvent("click");return this.response.success}]],init:function(b){return a.onHandlerInit(this,b)},terminate:function(){return a.onHandlerTerminate()}})},onKbdSideways:function(a,b){var c=this.keyCodes;return this.attemptHighlightAdjacentPoint(a,b===c.right||b===c.down)},onKbdVertical:function(a,b){var c=this.chart,d=this.keyCodes;b=b===d.down||
b===d.right;d=c.options.accessibility.keyboardNavigation.seriesNavigation;if(d.mode&&"serialize"===d.mode)return this.attemptHighlightAdjacentPoint(a,b);c[c.highlightedPoint&&c.highlightedPoint.series.keyboardMoveVertical?"highlightAdjacentPointVertical":"highlightAdjacentSeries"](b);return a.response.success},onHandlerInit:function(a,b){var c=this.chart;if(0<b)d(c);else{b=c.series.length;for(var e;b--&&!(c.highlightedPoint=c.series[b].points[c.series[b].points.length-1],e=c.series[b].highlightFirstValidPoint()););
}return a.response.success},onHandlerTerminate:function(){var a=this.chart;a.tooltip&&a.tooltip.hide(0);delete a.highlightedPoint},attemptHighlightAdjacentPoint:function(a,b){var c=this.chart,d=c.options.accessibility.keyboardNavigation.wrapAround;return c.highlightAdjacentPoint(b)?a.response.success:d?a.init(b?1:-1):a.response[b?"next":"prev"]},onSeriesDestroy:function(a){var b=this.chart;b.highlightedPoint&&b.highlightedPoint.series===a&&(delete b.highlightedPoint,b.focusElement&&b.focusElement.removeFocusBorder())},
destroy:function(){this.eventProvider.removeAddedEvents()}});return c});q(a,"modules/accessibility/components/SeriesComponent/SeriesDescriber.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"]],function(a,f,m,h){function l(a){var b=a.index;return a.series&&a.series.data&&z(b)?n(a.series.data,function(a){return!!(a&&"undefined"!==typeof a.index&&a.index>b&&a.graphic&&a.graphic.element)})||null:null}
function e(a){var b=a.chart.options.accessibility.series.pointDescriptionEnabledThreshold;return!!(!1!==b&&a.points&&a.points.length>=b)}function k(a){var b=a.options.accessibility||{};return!e(a)&&!b.exposeAsGroupOnly}function g(a){var b=a.chart.options.accessibility.keyboardNavigation.seriesNavigation;return!(!a.points||!(a.points.length<b.pointNavigationEnabledThreshold||!1===b.pointNavigationEnabledThreshold))}function p(a,b){var c=a.series.chart,d=c.options.accessibility.point||{};a=a.series.tooltipOptions||
{};c=c.options.lang;return D(b)?q(b,d.valueDecimals||a.valueDecimals||-1,c.decimalPoint,c.accessibility.thousandsSep||c.thousandsSep):b}function d(a){var b=(a.options.accessibility||{}).description;return b&&a.chart.langFormat("accessibility.series.description",{description:b,series:a})||""}function c(a,b){return a.chart.langFormat("accessibility.series."+b+"Description",{name:F(a[b]),series:a})}function b(b){var c=b.series,d=c.chart,e=d.options.accessibility.point||{};if(c.xAxis&&c.xAxis.isDatetimeAxis)return c=
a.Tooltip.prototype.getXDateFormat.call({getDateFormat:a.Tooltip.prototype.getDateFormat,chart:d},b,d.options.tooltip,c.xAxis),e=e.dateFormatter&&e.dateFormatter(b)||e.dateFormat||c,d.time.dateFormat(e,b.x,void 0)}function r(a){var c=b(a),d=(a.series.xAxis||{}).categories&&z(a.category)&&(""+a.category).replace("<br/>"," "),e=a.id&&0>a.id.indexOf("highcharts-"),n="x, "+a.x;return a.name||c||d||(e?a.id:n)}function w(a,b,c){var d=b||"",e=c||"";return a.series.pointArrayMap.reduce(function(b,c){b+=b.length?
", ":"";var n=p(a,x(a[c],a.options[c]));return b+(c+": "+d+n+e)},"")}function v(a){var b=a.series,c=b.chart.options.accessibility.point||{},d=b.tooltipOptions||{},e=c.valuePrefix||d.valuePrefix||"";c=c.valueSuffix||d.valueSuffix||"";d=p(a,a["undefined"!==typeof a.value?"value":"y"]);return a.isNull?b.chart.langFormat("accessibility.series.nullPointValue",{point:a}):b.pointArrayMap?w(a,e,c):e+d+c}function t(a){var b=a.series,c=b.chart,d=a.options&&a.options.accessibility&&a.options.accessibility.description,
e=x(b.xAxis&&b.xAxis.options.accessibility&&b.xAxis.options.accessibility.enabled,!c.angular),n=r(a),f=v(a);return(z(a.index)?a.index+1+". ":"")+(e?n+", ":"")+(f+".")+(d?" "+d:"")+(1<c.series.length&&b.name?" "+b.name+".":"")}function u(a){var b=k(a),c=g(a);(b||c)&&a.points.forEach(function(a){var c;if(!(c=a.graphic&&a.graphic.element)&&(c=a.series&&a.series.is("sunburst"),c=a.isNull&&!c)){var d=a.series,e=l(a);d=(c=e&&e.graphic)?c.parentGroup:d.graph||d.group;e=e?{x:x(a.plotX,e.plotX,0),y:x(a.plotY,
e.plotY,0)}:{x:x(a.plotX,0),y:x(a.plotY,0)};e=a.series.chart.renderer.rect(e.x,e.y,1,1);e.attr({"class":"highcharts-a11y-dummy-point",fill:"none",opacity:0,"fill-opacity":0,"stroke-opacity":0});d&&d.element?(a.graphic=e,a.hasDummyGraphic=!0,e.add(d),d.element.insertBefore(e.element,c?c.element:null),c=e.element):c=void 0}c&&(c.setAttribute("tabindex","-1"),b?(e=a.series,d=e.chart.options.accessibility.point||{},e=e.options.accessibility||{},a=A(e.pointDescriptionFormatter&&e.pointDescriptionFormatter(a)||
d.descriptionFormatter&&d.descriptionFormatter(a)||t(a)),c.setAttribute("role","img"),c.setAttribute("aria-label",a)):c.setAttribute("aria-hidden",!0))})}function y(a){var b=a.chart,e=b.types||[],n=d(a),f=function(c){return b[c]&&1<b[c].length&&a[c]},r=c(a,"xAxis"),g=c(a,"yAxis"),p={name:a.name||"",ix:a.index+1,numSeries:b.series&&b.series.length,numPoints:a.points&&a.points.length,series:a};e=1<e.length?"Combination":"";return(b.langFormat("accessibility.series.summary."+a.type+e,p)||b.langFormat("accessibility.series.summary.default"+
e,p))+(n?" "+n:"")+(f("yAxis")?" "+g:"")+(f("xAxis")?" "+r:"")}var q=a.numberFormat,n=a.find,D=f.isNumber,x=f.pick,z=f.defined,A=m.stripHTMLTagsFromString,E=m.reverseChildNodes,F=h.getAxisDescription,G=h.getSeriesFirstPointElement,H=h.getSeriesA11yElement,I=h.unhideChartElementFromAT;return{describeSeries:function(a){var b=a.chart,c=G(a),d=H(a),n=b.is3d&&b.is3d();if(d){d.lastChild!==c||n||E(d);u(a);I(b,d);n=a.chart;b=n.options.chart||{};c=1<n.series.length;n=n.options.accessibility.series.describeSingleSeries;
var f=(a.options.accessibility||{}).exposeAsGroupOnly;b.options3d&&b.options3d.enabled&&c||!(c||n||f||e(a))?d.setAttribute("aria-label",""):(b=a.chart.options.accessibility,c=b.landmarkVerbosity,(a.options.accessibility||{}).exposeAsGroupOnly?d.setAttribute("role","img"):"all"===c&&d.setAttribute("role","region"),d.setAttribute("tabindex","-1"),d.setAttribute("aria-label",A(b.series.descriptionFormatter&&b.series.descriptionFormatter(a)||y(a))))}},defaultPointDescriptionFormatter:t,defaultSeriesDescriptionFormatter:y,
getPointA11yTimeDescription:b,getPointXDescription:r,getPointValueDescription:v}});q(a,"modules/accessibility/components/SeriesComponent/NewDataAnnouncer.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/components/SeriesComponent/SeriesDescriber.js"],a["modules/accessibility/utils/EventProvider.js"],a["modules/accessibility/utils/DOMElementProvider.js"]],function(a,f,m,h,
l,e,k){function g(a){var b=a.series.data.filter(function(b){return a.x===b.x&&a.y===b.y});return 1===b.length?b[0]:a}function p(a,b){var c=(a||[]).concat(b||[]).reduce(function(a,b){a[b.name+b.index]=b;return a},{});return Object.keys(c).map(function(a){return c[a]})}var d=f.extend,c=f.defined,b=m.visuallyHideElement,r=h.getChartTitle,w=l.defaultPointDescriptionFormatter,v=l.defaultSeriesDescriptionFormatter;f=function(a){this.chart=a};d(f.prototype,{init:function(){this.lastAnnouncementTime=0;this.dirty=
{allSeries:{}};this.eventProvider=new e;this.domElementProvider=new k;this.announceRegion=this.addAnnounceRegion();this.addEventListeners()},destroy:function(){this.eventProvider.removeAddedEvents();this.domElementProvider.destroyCreatedElements()},addAnnounceRegion:function(){var a=this.chart,c=this.domElementProvider.createElement("div"),d=a.options.accessibility.announceNewData;c.setAttribute("aria-hidden",!1);c.setAttribute("aria-live",d.interruptUser?"assertive":"polite");b(c);a.renderTo.insertBefore(c,
a.renderTo.firstChild);return c},addEventListeners:function(){var b=this,c=this.chart,d=this.eventProvider;d.addEvent(c,"afterDrilldown",function(){b.lastAnnouncementTime=0});d.addEvent(a.Series,"updatedData",function(){b.onSeriesUpdatedData(this)});d.addEvent(c,"afterAddSeries",function(a){b.onSeriesAdded(a.series)});d.addEvent(a.Series,"addPoint",function(a){b.onPointAdded(a.point)});d.addEvent(c,"redraw",function(){b.announceDirtyData()})},onSeriesUpdatedData:function(a){var b=this.chart;a.chart===
b&&b.options.accessibility.announceNewData.enabled&&(this.dirty.hasDirty=!0,this.dirty.allSeries[a.name+a.index]=a)},onSeriesAdded:function(a){this.chart.options.accessibility.announceNewData.enabled&&(this.dirty.hasDirty=!0,this.dirty.allSeries[a.name+a.index]=a,this.dirty.newSeries=c(this.dirty.newSeries)?void 0:a)},onPointAdded:function(a){var b=a.series.chart;this.chart===b&&b.options.accessibility.announceNewData.enabled&&(this.dirty.newPoint=c(this.dirty.newPoint)?void 0:a)},announceDirtyData:function(){var a=
this;if(this.chart.options.accessibility.announceNewData&&this.dirty.hasDirty){var b=this.dirty.newPoint;b&&(b=g(b));this.queueAnnouncement(Object.keys(this.dirty.allSeries).map(function(b){return a.dirty.allSeries[b]}),this.dirty.newSeries,b);this.dirty={allSeries:{}}}},queueAnnouncement:function(a,b,c){var d=this.chart.options.accessibility.announceNewData;if(d.enabled){var e=this,f=+new Date;d=Math.max(0,d.minAnnounceInterval-(f-this.lastAnnouncementTime));a=p(this.queuedAnnouncement&&this.queuedAnnouncement.series,
a);if(b=this.buildAnnouncementMessage(a,b,c))this.queuedAnnouncement&&clearTimeout(this.queuedAnnouncementTimer),this.queuedAnnouncement={time:f,message:b,series:a},e.queuedAnnouncementTimer=setTimeout(function(){e&&e.announceRegion&&(e.lastAnnouncementTime=+new Date,e.liveRegionSpeak(e.queuedAnnouncement.message),delete e.queuedAnnouncement,delete e.queuedAnnouncementTimer)},d)}},liveRegionSpeak:function(a){var b=this;this.announceRegion.innerHTML=a;this.clearAnnouncementContainerTimer&&clearTimeout(this.clearAnnouncementContainerTimer);
this.clearAnnouncementContainerTimer=setTimeout(function(){b.announceRegion.innerHTML="";delete b.clearAnnouncementContainerTimer},1E3)},buildAnnouncementMessage:function(b,c,d){var e=this.chart,n=e.options.accessibility.announceNewData;if(n.announcementFormatter&&(b=n.announcementFormatter(b,c,d),!1!==b))return b.length?b:null;b=a.charts&&1<a.charts.length?"Multiple":"Single";b=c?"newSeriesAnnounce"+b:d?"newPointAnnounce"+b:"newDataAnnounce";n=r(e);return e.langFormat("accessibility.announceNewData."+
b,{chartTitle:n,seriesDesc:c?v(c):null,pointDesc:d?w(d):null,point:d,series:c})}});return f});q(a,"modules/accessibility/components/SeriesComponent/forcedMarkers.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,f){function v(a){l(!0,a,{marker:{enabled:!0,states:{normal:{opacity:0}}}})}var h=f.addEvent,l=f.merge;return function(){h(a.Series,"render",function(){var a=this.options,f=this.chart.options.accessibility.enabled,g=!1!==(this.options.accessibility&&this.options.accessibility.enabled);
var p=this.chart.options.accessibility;p=this.points.length<p.series.pointDescriptionEnabledThreshold||!1===p.series.pointDescriptionEnabledThreshold;var d=this.chart.options.accessibility.keyboardNavigation.seriesNavigation;d=this.points.length<d.pointNavigationEnabledThreshold||!1===d.pointNavigationEnabledThreshold;if(f&&g&&(p||d)){if(a.marker&&!1===a.marker.enabled&&(this.a11yMarkersForced=!0,v(this.options)),this._hasPointMarkers&&this.points&&this.points.length)for(a=this.points,f=a.length;f--;)g=
a[f].options,g.marker&&(g.marker.enabled?l(!0,g.marker,{states:{normal:{opacity:g.marker.states&&g.marker.states.normal&&g.marker.states.normal.opacity||1}}}):v(g))}else this.a11yMarkersForced&&this.resetMarkerOptions&&(delete this.a11yMarkersForced,a=this.resetA11yMarkerOptions,l(!0,this.options,{marker:{enabled:a.enabled,states:{normal:{opacity:a.states&&a.states.normal&&a.states.normal.opacity}}}}))});h(a.Series,"afterSetOptions",function(a){this.resetA11yMarkerOptions=l(a.options.marker||{},this.userOptions.marker||
{})})}});q(a,"modules/accessibility/components/SeriesComponent/SeriesComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/components/SeriesComponent/SeriesKeyboardNavigation.js"],a["modules/accessibility/components/SeriesComponent/NewDataAnnouncer.js"],a["modules/accessibility/components/SeriesComponent/forcedMarkers.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/components/SeriesComponent/SeriesDescriber.js"]],
function(a,f,m,h,l,e,k,g){f=f.extend;var p=k.hideSeriesFromAT,d=g.describeSeries;a.SeriesAccessibilityDescriber=g;e();e=function(){};e.prototype=new m;f(e.prototype,{init:function(){this.newDataAnnouncer=new l(this.chart);this.newDataAnnouncer.init();this.keyboardNavigation=new h(this.chart,this.keyCodes);this.keyboardNavigation.init();this.hideTooltipFromATWhenShown();this.hideSeriesLabelsFromATWhenShown()},hideTooltipFromATWhenShown:function(){var c=this;this.addEvent(a.Tooltip,"refresh",function(){this.chart===
c.chart&&this.label&&this.label.element&&this.label.element.setAttribute("aria-hidden",!0)})},hideSeriesLabelsFromATWhenShown:function(){this.addEvent(this.chart,"afterDrawSeriesLabels",function(){this.series.forEach(function(a){a.labelBySeries&&a.labelBySeries.attr("aria-hidden",!0)})})},onChartRender:function(){this.chart.series.forEach(function(a){!1!==(a.options.accessibility&&a.options.accessibility.enabled)&&a.visible?d(a):p(a)})},getKeyboardNavigation:function(){return this.keyboardNavigation.getKeyboardNavigationHandler()},
destroy:function(){this.newDataAnnouncer.destroy();this.keyboardNavigation.destroy()}});return e});q(a,"modules/accessibility/components/ZoomComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,f,m,h,l,e){var k=f.extend,g=f.pick,p=l.unhideChartElementFromAT,d=e.setElAttrs,
c=e.removeElement;a.Axis.prototype.panStep=function(a,c){var b=c||3;c=this.getExtremes();var d=(c.max-c.min)/b*a;b=c.max+d;d=c.min+d;var e=b-d;0>a&&d<c.dataMin?(d=c.dataMin,b=d+e):0<a&&b>c.dataMax&&(b=c.dataMax,d=b-e);this.setExtremes(d,b)};a=function(){};a.prototype=new m;k(a.prototype,{init:function(){var a=this,c=this.chart;["afterShowResetZoom","afterDrilldown","drillupall"].forEach(function(b){a.addEvent(c,b,function(){a.updateProxyOverlays()})})},onChartUpdate:function(){var a=this.chart,c=
this;a.mapNavButtons&&a.mapNavButtons.forEach(function(b,d){p(a,b.element);c.setMapNavButtonAttrs(b.element,"accessibility.zoom.mapZoom"+(d?"Out":"In"))})},setMapNavButtonAttrs:function(a,c){var b=this.chart;c=b.langFormat(c,{chart:b});d(a,{tabindex:-1,role:"button","aria-label":c})},onChartRender:function(){this.updateProxyOverlays()},updateProxyOverlays:function(){var a=this.chart;c(this.drillUpProxyGroup);c(this.resetZoomProxyGroup);a.resetZoomButton&&this.recreateProxyButtonAndGroup(a.resetZoomButton,
"resetZoomProxyButton","resetZoomProxyGroup",a.langFormat("accessibility.zoom.resetZoomButton",{chart:a}));a.drillUpButton&&this.recreateProxyButtonAndGroup(a.drillUpButton,"drillUpProxyButton","drillUpProxyGroup",a.langFormat("accessibility.drillUpButton",{chart:a,buttonText:a.getDrilldownBackText()}))},recreateProxyButtonAndGroup:function(a,d,e,f){c(this[e]);this[e]=this.addProxyGroup();this[d]=this.createProxyButton(a,this[e],{"aria-label":f,tabindex:-1})},getMapZoomNavigation:function(){var a=
this.keyCodes,c=this.chart,d=this;return new h(c,{keyCodeMap:[[[a.up,a.down,a.left,a.right],function(a){return d.onMapKbdArrow(this,a)}],[[a.tab],function(a,b){return d.onMapKbdTab(this,b)}],[[a.space,a.enter],function(){return d.onMapKbdClick(this)}]],validate:function(){return!!(c.mapZoom&&c.mapNavButtons&&c.mapNavButtons.length)},init:function(a){return d.onMapNavInit(a)}})},onMapKbdArrow:function(a,c){var b=this.keyCodes;this.chart[c===b.up||c===b.down?"yAxis":"xAxis"][0].panStep(c===b.left||
c===b.up?-1:1);return a.response.success},onMapKbdTab:function(a,c){var b=this.chart;a=a.response;var d=(c=c.shiftKey)&&!this.focusedMapNavButtonIx||!c&&this.focusedMapNavButtonIx;b.mapNavButtons[this.focusedMapNavButtonIx].setState(0);if(d)return b.mapZoom(),a[c?"prev":"next"];this.focusedMapNavButtonIx+=c?-1:1;c=b.mapNavButtons[this.focusedMapNavButtonIx];b.setFocusToElement(c.box,c.element);c.setState(2);return a.success},onMapKbdClick:function(a){this.fakeClickEvent(this.chart.mapNavButtons[this.focusedMapNavButtonIx].element);
return a.response.success},onMapNavInit:function(a){var b=this.chart,c=b.mapNavButtons[0],d=b.mapNavButtons[1];c=0<a?c:d;b.setFocusToElement(c.box,c.element);c.setState(2);this.focusedMapNavButtonIx=0<a?0:1},simpleButtonNavigation:function(a,c,d){var b=this.keyCodes,e=this,f=this.chart;return new h(f,{keyCodeMap:[[[b.tab,b.up,b.down,b.left,b.right],function(a,c){return this.response[a===b.tab&&c.shiftKey||a===b.left||a===b.up?"prev":"next"]}],[[b.space,b.enter],function(){var a=d(this,f);return g(a,
this.response.success)}]],validate:function(){return f[a]&&f[a].box&&e[c]},init:function(){f.setFocusToElement(f[a].box,e[c])}})},getKeyboardNavigation:function(){return[this.simpleButtonNavigation("resetZoomButton","resetZoomProxyButton",function(a,c){c.zoomOut()}),this.simpleButtonNavigation("drillUpButton","drillUpProxyButton",function(a,c){c.drillUp();return a.response.prev}),this.getMapZoomNavigation()]}});return a});q(a,"modules/accessibility/components/RangeSelectorComponent.js",[a["parts/Globals.js"],
a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,f,m,h,l,e){f=f.extend;var k=l.unhideChartElementFromAT,g=e.setElAttrs;a.Chart.prototype.highlightRangeSelectorButton=function(a){var d=this.rangeSelector.buttons,c=this.highlightedRangeSelectorItemIx;"undefined"!==typeof c&&d[c]&&d[c].setState(this.oldRangeSelectorItemState||
0);this.highlightedRangeSelectorItemIx=a;return d[a]?(this.setFocusToElement(d[a].box,d[a].element),this.oldRangeSelectorItemState=d[a].state,d[a].setState(2),!0):!1};a=function(){};a.prototype=new m;f(a.prototype,{onChartUpdate:function(){var a=this.chart,d=this,c=a.rangeSelector;c&&(c.buttons&&c.buttons.length&&c.buttons.forEach(function(b){k(a,b.element);d.setRangeButtonAttrs(b)}),c.maxInput&&c.minInput&&["minInput","maxInput"].forEach(function(b,e){if(b=c[b])k(a,b),d.setRangeInputAttrs(b,"accessibility.rangeSelector."+
(e?"max":"min")+"InputLabel")}))},setRangeButtonAttrs:function(a){var d=this.chart;d=d.langFormat("accessibility.rangeSelector.buttonText",{chart:d,buttonText:a.text&&a.text.textStr});g(a.element,{tabindex:-1,role:"button","aria-label":d})},setRangeInputAttrs:function(a,d){var c=this.chart;g(a,{tabindex:-1,role:"textbox","aria-label":c.langFormat(d,{chart:c})})},getRangeSelectorButtonNavigation:function(){var a=this.chart,d=this.keyCodes,c=this;return new h(a,{keyCodeMap:[[[d.left,d.right,d.up,d.down],
function(a){return c.onButtonNavKbdArrowKey(this,a)}],[[d.enter,d.space],function(){return c.onButtonNavKbdClick(this)}]],validate:function(){return a.rangeSelector&&a.rangeSelector.buttons&&a.rangeSelector.buttons.length},init:function(b){var c=a.rangeSelector.buttons.length-1;a.highlightRangeSelectorButton(0<b?0:c)}})},onButtonNavKbdArrowKey:function(a,d){var c=a.response,b=this.keyCodes,e=this.chart,f=e.options.accessibility.keyboardNavigation.wrapAround;d=d===b.left||d===b.up?-1:1;return e.highlightRangeSelectorButton(e.highlightedRangeSelectorItemIx+
d)?c.success:f?(a.init(d),c.success):c[0<d?"next":"prev"]},onButtonNavKbdClick:function(a){a=a.response;var d=this.chart;3!==d.oldRangeSelectorItemState&&this.fakeClickEvent(d.rangeSelector.buttons[d.highlightedRangeSelectorItemIx].element);return a.success},getRangeSelectorInputNavigation:function(){var a=this.chart,d=this.keyCodes,c=this;return new h(a,{keyCodeMap:[[[d.tab,d.up,d.down],function(a,e){return c.onInputKbdMove(this,a===d.tab&&e.shiftKey||a===d.up?-1:1)}]],validate:function(){return a.rangeSelector&&
a.rangeSelector.inputGroup&&"hidden"!==a.rangeSelector.inputGroup.element.getAttribute("visibility")&&!1!==a.options.rangeSelector.inputEnabled&&a.rangeSelector.minInput&&a.rangeSelector.maxInput},init:function(a){c.onInputNavInit(a)},terminate:function(){c.onInputNavTerminate()}})},onInputKbdMove:function(a,d){var c=this.chart;a=a.response;var b=c.highlightedInputRangeIx+=d;if(1<b||0>b)return a[0<d?"next":"prev"];c.rangeSelector[b?"maxInput":"minInput"].focus();return a.success},onInputNavInit:function(a){var d=
this.chart;a=0<a?0:1;d.highlightedInputRangeIx=a;d.rangeSelector[a?"maxInput":"minInput"].focus()},onInputNavTerminate:function(){var a=this.chart.rangeSelector||{};a.maxInput&&a.hideInput("max");a.minInput&&a.hideInput("min")},getKeyboardNavigation:function(){return[this.getRangeSelectorButtonNavigation(),this.getRangeSelectorInputNavigation()]}});return a});q(a,"modules/accessibility/components/InfoRegionsComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],
a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,f,m,h,l){function e(a){return a.replace(/&lt;(h[1-7]|p|div)&gt;/g,"<$1>").replace(/&lt;&#x2F;(h[1-7]|p|div|a|button)&gt;/g,"</$1>").replace(/&lt;(div|a|button) id=&quot;([a-zA-Z\-0-9#]*?)&quot;&gt;/g,'<$1 id="$2">')}var k=a.win.document,g=f.extend,p=f.format,d=f.pick,c=h.unhideChartElementFromAT,b=h.getChartTitle,r=h.getAxisDescription,v=l.addClass,q=l.setElAttrs,t=l.escapeStringForHTML,
u=l.stripHTMLTagsFromString,y=l.getElement,C=l.visuallyHideElement;a.Chart.prototype.getTypeDescription=function(a){var b=a[0],c=this.series&&this.series[0]||{};c={numSeries:this.series.length,numPoints:c.points&&c.points.length,chart:this,mapTitle:c.mapTitle};if(!b)return this.langFormat("accessibility.chartTypes.emptyChart",c);if("map"===b)return c.mapTitle?this.langFormat("accessibility.chartTypes.mapTypeDescription",c):this.langFormat("accessibility.chartTypes.unknownMap",c);if(1<this.types.length)return this.langFormat("accessibility.chartTypes.combinationChart",
c);a=a[0];b=this.langFormat("accessibility.seriesTypeDescriptions."+a,c);var d=this.series&&2>this.series.length?"Single":"Multiple";return(this.langFormat("accessibility.chartTypes."+a+d,c)||this.langFormat("accessibility.chartTypes.default"+d,c))+(b?" "+b:"")};f=function(){};f.prototype=new m;g(f.prototype,{init:function(){var a=this.chart,b=this;this.initRegionsDefinitions();this.addEvent(a,"afterGetTable",function(a){b.onDataTableCreated(a)});this.addEvent(a,"afterViewData",function(a){b.dataTableDiv=
a;setTimeout(function(){b.focusDataTable()},300)})},initRegionsDefinitions:function(){var a=this;this.screenReaderSections={before:{element:null,buildContent:function(b){var c=b.options.accessibility.screenReaderSection.beforeChartFormatter;return c?c(b):a.defaultBeforeChartFormatter(b)},insertIntoDOM:function(a,b){b.renderTo.insertBefore(a,b.renderTo.firstChild)},afterInserted:function(){"undefined"!==typeof a.dataTableButtonId&&a.initDataTableButton(a.dataTableButtonId)}},after:{element:null,buildContent:function(b){var c=
b.options.accessibility.screenReaderSection.afterChartFormatter;return c?c(b):a.defaultAfterChartFormatter()},insertIntoDOM:function(a,b){b.renderTo.insertBefore(a,b.container.nextSibling)}}}},onChartUpdate:function(){var a=this;this.linkedDescriptionElement=this.getLinkedDescriptionElement();this.setLinkedDescriptionAttrs();Object.keys(this.screenReaderSections).forEach(function(b){a.updateScreenReaderSection(b)})},getLinkedDescriptionElement:function(){var a=this.chart.options.accessibility.linkedDescription;
if(a){if("string"!==typeof a)return a;a=p(a,this.chart);a=k.querySelectorAll(a);if(1===a.length)return a[0]}},setLinkedDescriptionAttrs:function(){var a=this.linkedDescriptionElement;a&&(a.setAttribute("aria-hidden","true"),v(a,"highcharts-linked-description"))},updateScreenReaderSection:function(a){var b=this.chart,d=this.screenReaderSections[a],e=d.buildContent(b),f=d.element=d.element||this.createElement("div"),n=f.firstChild||this.createElement("div");this.setScreenReaderSectionAttribs(f,a);n.innerHTML=
e;f.appendChild(n);d.insertIntoDOM(f,b);C(n);c(b,n);d.afterInserted&&d.afterInserted()},setScreenReaderSectionAttribs:function(a,b){var c=this.chart,d=c.langFormat("accessibility.screenReaderSection."+b+"RegionLabel",{chart:c});q(a,{id:"highcharts-screen-reader-region-"+b+"-"+c.index,"aria-label":d});a.style.position="relative";"all"===c.options.accessibility.landmarkVerbosity&&d&&a.setAttribute("role","region")},defaultBeforeChartFormatter:function(){var c=this.chart,d=c.options.accessibility.screenReaderSection.beforeChartFormat,
f=this.getAxesDescription(),g="hc-linkto-highcharts-data-table-"+c.index;f={chartTitle:b(c),typeDescription:this.getTypeDescriptionText(),chartSubtitle:this.getSubtitleText(),chartLongdesc:this.getLongdescText(),xAxisDescription:f.xAxis,yAxisDescription:f.yAxis,viewTableButton:c.getCSV?this.getDataTableButtonText(g):""};c=a.i18nFormat(d,f,c);this.dataTableButtonId=g;return e(t(c)).replace(/<(\w+)[^>]*?>\s*<\/\1>/g,"")},defaultAfterChartFormatter:function(){var b=this.chart,c=b.options.accessibility.screenReaderSection.afterChartFormat,
d={endOfChartMarker:this.getEndOfChartMarkerText()};b=a.i18nFormat(c,d,b);return e(t(b)).replace(/<(\w+)[^>]*?>\s*<\/\1>/g,"")},getLinkedDescription:function(){var a=this.linkedDescriptionElement;return u(a&&a.innerHTML||"")},getLongdescText:function(){var a=this.chart.options,b=a.caption;b=b&&b.text;var c=this.getLinkedDescription();return a.accessibility.description||c||b||""},getTypeDescriptionText:function(){var a=this.chart;return a.types?a.options.accessibility.typeDescription||a.getTypeDescription(a.types):
""},getDataTableButtonText:function(a){var c=this.chart;c=c.langFormat("accessibility.table.viewAsDataTableButtonText",{chart:c,chartTitle:b(c)});return'<a id="'+a+'">'+c+"</a>"},getSubtitleText:function(){var a=this.chart.options.subtitle;return u(a&&a.text||"")},getEndOfChartMarkerText:function(){var a=this.chart,b=a.langFormat("accessibility.screenReaderSection.endOfChartMarker",{chart:a});return'<div id="highcharts-end-of-chart-marker-'+a.index+'">'+b+"</div>"},onDataTableCreated:function(a){var b=
this.chart;b.options.accessibility.enabled&&(this.viewDataTableButton&&this.viewDataTableButton.setAttribute("aria-expanded","true"),a.html=a.html.replace("<table ",'<table tabindex="0" summary="'+b.langFormat("accessibility.table.tableSummary",{chart:b})+'"'))},focusDataTable:function(){var a=this.dataTableDiv;(a=a&&a.getElementsByTagName("table")[0])&&a.focus&&a.focus()},initDataTableButton:function(a){var b=this.viewDataTableButton=y(a),c=this.chart;a=a.replace("hc-linkto-","");b&&(q(b,{role:"button",
tabindex:"-1","aria-expanded":!!y(a),href:"#"+a}),b.onclick=c.options.accessibility.screenReaderSection.onViewDataTableClick||function(){c.viewData()})},getAxesDescription:function(){var a=this.chart,b=function(b,c){b=a[b];return 1<b.length||b[0]&&d(b[0].options.accessibility&&b[0].options.accessibility.enabled,c)},c=!!a.types&&0>a.types.indexOf("map"),e=!!a.hasCartesianSeries,f=b("xAxis",!a.angular&&e&&c);b=b("yAxis",e&&c);c={};f&&(c.xAxis=this.getAxisDescriptionText("xAxis"));b&&(c.yAxis=this.getAxisDescriptionText("yAxis"));
return c},getAxisDescriptionText:function(a){var b=this,c=this.chart,d=c[a];return c.langFormat("accessibility.axis."+a+"Description"+(1<d.length?"Plural":"Singular"),{chart:c,names:d.map(function(a){return r(a)}),ranges:d.map(function(a){return b.getAxisRangeDescription(a)}),numAxes:d.length})},getAxisRangeDescription:function(a){var b=a.options||{};return b.accessibility&&"undefined"!==typeof b.accessibility.rangeDescription?b.accessibility.rangeDescription:a.categories?this.getCategoryAxisRangeDesc(a):
!a.isDatetimeAxis||0!==a.min&&0!==a.dataMin?this.getAxisFromToDescription(a):this.getAxisTimeLengthDesc(a)},getCategoryAxisRangeDesc:function(a){var b=this.chart;return a.dataMax&&a.dataMin?b.langFormat("accessibility.axis.rangeCategories",{chart:b,axis:a,numCategories:a.dataMax-a.dataMin+1}):""},getAxisTimeLengthDesc:function(a){var b=this.chart,c={},d="Seconds";c.Seconds=((a.max||0)-(a.min||0))/1E3;c.Minutes=c.Seconds/60;c.Hours=c.Minutes/60;c.Days=c.Hours/24;["Minutes","Hours","Days"].forEach(function(a){2<
c[a]&&(d=a)});var e=c[d].toFixed("Seconds"!==d&&"Minutes"!==d?1:0);return b.langFormat("accessibility.axis.timeRange"+d,{chart:b,axis:a,range:e.replace(".0","")})},getAxisFromToDescription:function(a){var b=this.chart,c=b.options.accessibility.screenReaderSection.axisRangeDateFormat,d=function(d){return a.isDatetimeAxis?b.time.dateFormat(c,a[d]):a[d]};return b.langFormat("accessibility.axis.rangeFromTo",{chart:b,axis:a,rangeFrom:d("min"),rangeTo:d("max")})}});return f});q(a,"modules/accessibility/components/ContainerComponent.js",
[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/AccessibilityComponent.js"]],function(a,f,m,h,l){var e=a.win.document;a=f.extend;var k=m.stripHTMLTagsFromString,g=h.unhideChartElementFromAT,p=h.getChartTitle;m=function(){};m.prototype=new l;a(m.prototype,{onChartUpdate:function(){this.handleSVGTitleElement();this.setSVGContainerLabel();this.setGraphicContainerAttrs();this.setRenderToAttrs();
this.makeCreditsAccessible()},handleSVGTitleElement:function(){var a=this.chart,c="highcharts-title-"+a.index,b=k(a.langFormat("accessibility.svgContainerTitle",{chartTitle:p(a)}));if(b.length){var f=this.svgTitleElement=this.svgTitleElement||e.createElementNS("http://www.w3.org/2000/svg","title");f.textContent=b;f.id=c;a.renderTo.insertBefore(f,a.renderTo.firstChild)}},setSVGContainerLabel:function(){var a=this.chart,c=k(a.langFormat("accessibility.svgContainerLabel",{chartTitle:p(a)}));a.renderer.box&&
c.length&&a.renderer.box.setAttribute("aria-label",c)},setGraphicContainerAttrs:function(){var a=this.chart,c=a.langFormat("accessibility.graphicContainerLabel",{chartTitle:p(a)});c.length&&a.container.setAttribute("aria-label",c)},setRenderToAttrs:function(){var a=this.chart;"disabled"!==a.options.accessibility.landmarkVerbosity?a.renderTo.setAttribute("role","region"):a.renderTo.removeAttribute("role");a.renderTo.setAttribute("aria-label",a.langFormat("accessibility.chartContainerLabel",{title:p(a),
chart:a}))},makeCreditsAccessible:function(){var a=this.chart,c=a.credits;c&&(c.textStr&&c.element.setAttribute("aria-label",k(a.langFormat("accessibility.credits",{creditsStr:c.textStr}))),g(a,c.element))},destroy:function(){this.chart.renderTo.setAttribute("aria-hidden",!0)}});return m});q(a,"modules/accessibility/high-contrast-mode.js",[a["parts/Globals.js"]],function(a){var f=a.isMS,m=a.win,h=m.document;return{isHighContrastModeActive:function(){var a=/(Edg)/.test(m.navigator.userAgent);if(m.matchMedia&&
a)return m.matchMedia("(-ms-high-contrast: active)").matches;if(f&&m.getComputedStyle){a=h.createElement("div");a.style.backgroundImage="url(#)";h.body.appendChild(a);var e=(a.currentStyle||m.getComputedStyle(a)).backgroundImage;h.body.removeChild(a);return"none"===e}return!1},setHighContrastTheme:function(a){a.highContrastModeActive=!0;var e=a.options.accessibility.highContrastTheme;a.update(e,!1);a.series.forEach(function(a){var f=e.plotOptions[a.type]||{};a.update({color:f.color||"windowText",
colors:[f.color||"windowText"],borderColor:f.borderColor||"window"});a.points.forEach(function(a){a.options&&a.options.color&&a.update({color:f.color||"windowText",borderColor:f.borderColor||"window"},!1)})});a.redraw()}}});q(a,"modules/accessibility/high-contrast-theme.js",[],function(){return{chart:{backgroundColor:"window"},title:{style:{color:"windowText"}},subtitle:{style:{color:"windowText"}},colorAxis:{minColor:"windowText",maxColor:"windowText",stops:[]},colors:["windowText"],xAxis:{gridLineColor:"windowText",
labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},yAxis:{gridLineColor:"windowText",labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},tooltip:{backgroundColor:"window",borderColor:"windowText",style:{color:"windowText"}},plotOptions:{series:{lineColor:"windowText",fillColor:"window",borderColor:"windowText",
edgeColor:"windowText",borderWidth:1,dataLabels:{connectorColor:"windowText",color:"windowText",style:{color:"windowText",textOutline:"none"}},marker:{lineColor:"windowText",fillColor:"windowText"}},pie:{color:"window",colors:["window"],borderColor:"windowText",borderWidth:1},boxplot:{fillColor:"window"},candlestick:{lineColor:"windowText",fillColor:"window"},errorbar:{fillColor:"window"}},legend:{backgroundColor:"window",itemStyle:{color:"windowText"},itemHoverStyle:{color:"windowText"},itemHiddenStyle:{color:"#555"},
title:{style:{color:"windowText"}}},credits:{style:{color:"windowText"}},labels:{style:{color:"windowText"}},drilldown:{activeAxisLabelStyle:{color:"windowText"},activeDataLabelStyle:{color:"windowText"}},navigation:{buttonOptions:{symbolStroke:"windowText",theme:{fill:"window"}}},rangeSelector:{buttonTheme:{fill:"window",stroke:"windowText",style:{color:"windowText"},states:{hover:{fill:"window",stroke:"windowText",style:{color:"windowText"}},select:{fill:"#444",stroke:"windowText",style:{color:"windowText"}}}},
inputBoxBorderColor:"windowText",inputStyle:{backgroundColor:"window",color:"windowText"},labelStyle:{color:"windowText"}},navigator:{handles:{backgroundColor:"window",borderColor:"windowText"},outlineColor:"windowText",maskFill:"transparent",series:{color:"windowText",lineColor:"windowText"},xAxis:{gridLineColor:"windowText"}},scrollbar:{barBackgroundColor:"#444",barBorderColor:"windowText",buttonArrowColor:"windowText",buttonBackgroundColor:"window",buttonBorderColor:"windowText",rifleColor:"windowText",
trackBackgroundColor:"window",trackBorderColor:"windowText"}}});q(a,"modules/accessibility/options/options.js",[],function(){return{accessibility:{enabled:!0,screenReaderSection:{beforeChartFormat:"<h5>{chartTitle}</h5><div>{typeDescription}</div><div>{chartSubtitle}</div><div>{chartLongdesc}</div><div>{xAxisDescription}</div><div>{yAxisDescription}</div><div>{viewTableButton}</div>",afterChartFormat:"{endOfChartMarker}",axisRangeDateFormat:"%Y-%m-%d %H:%M:%S"},series:{describeSingleSeries:!1,pointDescriptionEnabledThreshold:200},
landmarkVerbosity:"all",linkedDescription:'*[data-highcharts-chart="{index}"] + .highcharts-description',keyboardNavigation:{enabled:!0,focusBorder:{enabled:!0,hideBrowserFocusOutline:!0,style:{color:"#335cad",lineWidth:2,borderRadius:3},margin:2},order:["series","zoom","rangeSelector","legend","chartMenu"],wrapAround:!0,seriesNavigation:{skipNullPoints:!0,pointNavigationEnabledThreshold:!1}},announceNewData:{enabled:!1,minAnnounceInterval:5E3,interruptUser:!1}},legend:{accessibility:{enabled:!0,
keyboardNavigation:{enabled:!0}}},exporting:{accessibility:{enabled:!0}}}});q(a,"modules/accessibility/options/langOptions.js",[],function(){return{accessibility:{defaultChartTitle:"Chart",chartContainerLabel:"{title}. Highcharts interactive chart.",svgContainerLabel:"Interactive chart",drillUpButton:"{buttonText}",credits:"Chart credits: {creditsStr}",thousandsSep:",",svgContainerTitle:"",graphicContainerLabel:"",screenReaderSection:{beforeRegionLabel:"Chart screen reader information.",afterRegionLabel:"",
endOfChartMarker:"End of interactive chart."},legend:{legendLabel:"Toggle series visibility",legendItem:"Toggle visibility of {itemName}"},zoom:{mapZoomIn:"Zoom chart",mapZoomOut:"Zoom out chart",resetZoomButton:"Reset zoom"},rangeSelector:{minInputLabel:"Select start date.",maxInputLabel:"Select end date.",buttonText:"Select range {buttonText}"},table:{viewAsDataTableButtonText:"View as data table. {chartTitle}",tableSummary:"Table representation of chart."},announceNewData:{newDataAnnounce:"Updated data for chart {chartTitle}",
newSeriesAnnounceSingle:"New data series: {seriesDesc}",newPointAnnounceSingle:"New data point: {pointDesc}",newSeriesAnnounceMultiple:"New data series in chart {chartTitle}: {seriesDesc}",newPointAnnounceMultiple:"New data point in chart {chartTitle}: {pointDesc}"},seriesTypeDescriptions:{boxplot:"Box plot charts are typically used to display groups of statistical data. Each data point in the chart can have up to 5 values: minimum, lower quartile, median, upper quartile, and maximum.",arearange:"Arearange charts are line charts displaying a range between a lower and higher value for each point.",
areasplinerange:"These charts are line charts displaying a range between a lower and higher value for each point.",bubble:"Bubble charts are scatter charts where each data point also has a size value.",columnrange:"Columnrange charts are column charts displaying a range between a lower and higher value for each point.",errorbar:"Errorbar series are used to display the variability of the data.",funnel:"Funnel charts are used to display reduction of data in stages.",pyramid:"Pyramid charts consist of a single pyramid with item heights corresponding to each point value.",
waterfall:"A waterfall chart is a column chart where each column contributes towards a total end value."},chartTypes:{emptyChart:"Empty chart",mapTypeDescription:"Map of {mapTitle} with {numSeries} data series.",unknownMap:"Map of unspecified region with {numSeries} data series.",combinationChart:"Combination chart with {numSeries} data series.",defaultSingle:"Chart with {numPoints} data {#plural(numPoints, points, point)}.",defaultMultiple:"Chart with {numSeries} data series.",splineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",
splineMultiple:"Line chart with {numSeries} lines.",lineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",lineMultiple:"Line chart with {numSeries} lines.",columnSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",columnMultiple:"Bar chart with {numSeries} data series.",barSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",barMultiple:"Bar chart with {numSeries} data series.",pieSingle:"Pie chart with {numPoints} {#plural(numPoints, slices, slice)}.",
pieMultiple:"Pie chart with {numSeries} pies.",scatterSingle:"Scatter chart with {numPoints} {#plural(numPoints, points, point)}.",scatterMultiple:"Scatter chart with {numSeries} data series.",boxplotSingle:"Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotMultiple:"Boxplot with {numSeries} data series.",bubbleSingle:"Bubble chart with {numPoints} {#plural(numPoints, bubbles, bubble)}.",bubbleMultiple:"Bubble chart with {numSeries} data series."},axis:{xAxisDescriptionSingular:"The chart has 1 X axis displaying {names[0]}. {ranges[0]}",
xAxisDescriptionPlural:"The chart has {numAxes} X axes displaying {#each(names, -1) }and {names[-1]}.",yAxisDescriptionSingular:"The chart has 1 Y axis displaying {names[0]}. {ranges[0]}",yAxisDescriptionPlural:"The chart has {numAxes} Y axes displaying {#each(names, -1) }and {names[-1]}.",timeRangeDays:"Range: {range} days.",timeRangeHours:"Range: {range} hours.",timeRangeMinutes:"Range: {range} minutes.",timeRangeSeconds:"Range: {range} seconds.",rangeFromTo:"Range: {rangeFrom} to {rangeTo}.",rangeCategories:"Range: {numCategories} categories."},
exporting:{chartMenuLabel:"Chart menu",menuButtonLabel:"View chart menu",exportRegionLabel:"Chart menu"},series:{summary:{"default":"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",defaultCombination:"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",line:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",lineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",
spline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",splineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",column:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",columnCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",bar:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",
barCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",pie:"{name}, pie {ix} of {numSeries} with {numPoints} {#plural(numPoints, slices, slice)}.",pieCombination:"{name}, series {ix} of {numSeries}. Pie with {numPoints} {#plural(numPoints, slices, slice)}.",scatter:"{name}, scatter plot {ix} of {numSeries} with {numPoints} {#plural(numPoints, points, point)}.",scatterCombination:"{name}, series {ix} of {numSeries}, scatter plot with {numPoints} {#plural(numPoints, points, point)}.",
boxplot:"{name}, boxplot {ix} of {numSeries} with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotCombination:"{name}, series {ix} of {numSeries}. Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",bubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",bubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}.",map:"{name}, map {ix} of {numSeries} with {numPoints} {#plural(numPoints, areas, area)}.",
mapCombination:"{name}, series {ix} of {numSeries}. Map with {numPoints} {#plural(numPoints, areas, area)}.",mapline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",maplineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",mapbubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",mapbubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}."},
description:"{description}",xAxisDescription:"X axis, {name}",yAxisDescription:"Y axis, {name}",nullPointValue:"No value"}}}});q(a,"modules/accessibility/options/deprecatedOptions.js",[a["parts/Utilities.js"]],function(a){function f(a,c,b){g("Highcharts: Deprecated option "+c+" used. This will be removed from future versions of Highcharts. Use "+b+" instead.",!1,a)}function m(a,c,b){for(var d,e=0;e<c.length-1;++e)d=c[e],a=a[d]=p(a[d],{});a[c[c.length-1]]=b}function h(a,c,b,e){function d(a,b){return b.reduce(function(a,
b){return a[b]},a)}var g=d(a.options,c),k=d(a.options,b);Object.keys(e).forEach(function(d){var h=g[d];"undefined"!==typeof h&&(m(k,e[d],h),f(a,c.join(".")+"."+d,b.join(".")+"."+e[d].join(".")))})}function l(a){var c=a.options.chart||{},b=a.options.accessibility||{};["description","typeDescription"].forEach(function(d){c[d]&&(b[d]=c[d],f(a,"chart."+d,"accessibility."+d))})}function e(a){a.axes.forEach(function(c){(c=c.options)&&c.description&&(c.accessibility=c.accessibility||{},c.accessibility.description=
c.description,f(a,"axis.description","axis.accessibility.description"))})}function k(a){var c={description:["accessibility","description"],exposeElementToA11y:["accessibility","exposeAsGroupOnly"],pointDescriptionFormatter:["accessibility","pointDescriptionFormatter"],skipKeyboardNavigation:["accessibility","keyboardNavigation","enabled"]};a.series.forEach(function(b){Object.keys(c).forEach(function(d){var e=b.options[d];"undefined"!==typeof e&&(m(b.options,c[d],"skipKeyboardNavigation"===d?!e:e),
f(a,"series."+d,"series."+c[d].join(".")))})})}var g=a.error,p=a.pick;return function(a){l(a);e(a);a.series&&k(a);h(a,["accessibility"],["accessibility"],{pointDateFormat:["point","dateFormat"],pointDateFormatter:["point","dateFormatter"],pointDescriptionFormatter:["point","descriptionFormatter"],pointDescriptionThreshold:["series","pointDescriptionEnabledThreshold"],pointNavigationThreshold:["keyboardNavigation","seriesNavigation","pointNavigationEnabledThreshold"],pointValueDecimals:["point","valueDecimals"],
pointValuePrefix:["point","valuePrefix"],pointValueSuffix:["point","valueSuffix"],screenReaderSectionFormatter:["screenReaderSection","beforeChartFormatter"],describeSingleSeries:["series","describeSingleSeries"],seriesDescriptionFormatter:["series","descriptionFormatter"],onTableAnchorClick:["screenReaderSection","onViewDataTableClick"],axisRangeDateFormat:["screenReaderSection","axisRangeDateFormat"]});h(a,["accessibility","keyboardNavigation"],["accessibility","keyboardNavigation","seriesNavigation"],
{skipNullPoints:["skipNullPoints"],mode:["mode"]});h(a,["lang","accessibility"],["lang","accessibility"],{legendItem:["legend","legendItem"],legendLabel:["legend","legendLabel"],mapZoomIn:["zoom","mapZoomIn"],mapZoomOut:["zoom","mapZoomOut"],resetZoomButton:["zoom","resetZoomButton"],screenReaderRegionLabel:["screenReaderSection","beforeRegionLabel"],rangeSelectorButton:["rangeSelector","buttonText"],rangeSelectorMaxInput:["rangeSelector","maxInputLabel"],rangeSelectorMinInput:["rangeSelector","minInputLabel"],
svgContainerEnd:["screenReaderSection","endOfChartMarker"],viewAsDataTable:["table","viewAsDataTableButtonText"],tableSummary:["table","tableSummary"]})}});q(a,"modules/accessibility/a11y-i18n.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,f){function m(a,f){var e=a.indexOf("#each("),k=a.indexOf("#plural("),d=a.indexOf("["),c=a.indexOf("]");if(-1<e){d=a.slice(e).indexOf(")")+e;var b=a.substring(0,e);k=a.substring(d+1);d=a.substring(e+6,d).split(",");e=Number(d[1]);a="";if(f=f[d[0]])for(e=
isNaN(e)?f.length:e,e=0>e?f.length+e:Math.min(e,f.length),d=0;d<e;++d)a+=b+f[d]+k;return a.length?a:""}if(-1<k){b=a.slice(k).indexOf(")")+k;a=a.substring(k+8,b).split(",");switch(Number(f[a[0]])){case 0:a=l(a[4],a[1]);break;case 1:a=l(a[2],a[1]);break;case 2:a=l(a[3],a[1]);break;default:a=a[1]}a?(f=a,f=f.trim&&f.trim()||f.replace(/^\s+|\s+$/g,"")):f="";return f}return-1<d?(k=a.substring(0,d),a=Number(a.substring(d+1,c)),f=f[k],!isNaN(a)&&f&&(0>a?(b=f[f.length+a],"undefined"===typeof b&&(b=f[0])):
(b=f[a],"undefined"===typeof b&&(b=f[f.length-1]))),"undefined"!==typeof b?b:""):"{"+a+"}"}var h=f.format,l=f.pick;a.i18nFormat=function(a,f,g){var e=function(a,b){a=a.slice(b||0);var c=a.indexOf("{"),d=a.indexOf("}");if(-1<c&&d>c)return{statement:a.substring(c+1,d),begin:b+c+1,end:b+d}},d=[],c=0;do{var b=e(a,c);var k=a.substring(c,b&&b.begin-1);k.length&&d.push({value:k,type:"constant"});b&&d.push({value:b.statement,type:"statement"});c=b?b.end+1:c+1}while(b);d.forEach(function(a){"statement"===
a.type&&(a.value=m(a.value,f))});return h(d.reduce(function(a,b){return a+b.value},""),f,g)};a.Chart.prototype.langFormat=function(e,f){e=e.split(".");for(var g=this.options.lang,k=0;k<e.length;++k)g=g&&g[e[k]];return"string"===typeof g?a.i18nFormat(g,f,this):""}});q(a,"modules/accessibility/focusBorder.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,f){var m=f.addEvent,h=f.extend,l=f.pick;h(a.SVGElement.prototype,{addFocusBorder:function(a,f){this.focusBorder&&this.removeFocusBorder();
var e=this.getBBox();a=l(a,3);e.x+=this.translateX?this.translateX:0;e.y+=this.translateY?this.translateY:0;this.focusBorder=this.renderer.rect(e.x-a,e.y-a,e.width+2*a,e.height+2*a,parseInt((f&&f.borderRadius||0).toString(),10)).addClass("highcharts-focus-border").attr({zIndex:99}).add(this.parentGroup);this.renderer.styledMode||this.focusBorder.attr({stroke:f&&f.stroke,"stroke-width":f&&f.strokeWidth})},removeFocusBorder:function(){this.focusBorder&&(this.focusBorder.destroy(),delete this.focusBorder)}});
a.Chart.prototype.setFocusToElement=function(a,f){var e=this.options.accessibility.keyboardNavigation.focusBorder;(f=f||a.element)&&f.focus&&(f.hcEvents&&f.hcEvents.focusin||m(f,"focusin",function(){}),f.focus(),e.hideBrowserFocusOutline&&(f.style.outline="none"));e.enabled&&(this.focusElement&&this.focusElement.removeFocusBorder(),a.addFocusBorder(e.margin,{stroke:e.style.color,strokeWidth:e.style.lineWidth,borderRadius:e.style.borderRadius}),this.focusElement=a)}});q(a,"modules/accessibility/accessibility.js",
[a["modules/accessibility/utils/chartUtilities.js"],a["parts/Globals.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigation.js"],a["modules/accessibility/components/LegendComponent.js"],a["modules/accessibility/components/MenuComponent.js"],a["modules/accessibility/components/SeriesComponent/SeriesComponent.js"],a["modules/accessibility/components/ZoomComponent.js"],a["modules/accessibility/components/RangeSelectorComponent.js"],
a["modules/accessibility/components/InfoRegionsComponent.js"],a["modules/accessibility/components/ContainerComponent.js"],a["modules/accessibility/high-contrast-mode.js"],a["modules/accessibility/high-contrast-theme.js"],a["modules/accessibility/options/options.js"],a["modules/accessibility/options/langOptions.js"],a["modules/accessibility/options/deprecatedOptions.js"]],function(a,f,m,h,l,e,k,g,p,d,c,b,q,w,B,t,u,y){function r(a){this.init(a)}var n=h.addEvent,v=h.extend,x=h.fireEvent,z=h.merge,A=
f.win.document;z(!0,f.defaultOptions,t,{accessibility:{highContrastTheme:B},lang:u});f.A11yChartUtilities=a;f.KeyboardNavigationHandler=m;f.AccessibilityComponent=l;r.prototype={init:function(a){this.chart=a;A.addEventListener&&a.renderer.isSVG?(y(a),this.initComponents(),this.keyboardNavigation=new e(a,this.components),this.update()):a.renderTo.setAttribute("aria-hidden",!0)},initComponents:function(){var a=this.chart,e=a.options.accessibility;this.components={container:new q,infoRegions:new b,legend:new k,
chartMenu:new g,rangeSelector:new c,series:new p,zoom:new d};e.customComponents&&v(this.components,e.customComponents);var f=this.components;Object.keys(f).forEach(function(b){f[b].initBase(a);f[b].init()})},update:function(){var a=this.components,b=this.chart,c=b.options.accessibility;x(b,"beforeA11yUpdate");b.types=this.getChartTypes();Object.keys(a).forEach(function(c){a[c].onChartUpdate();x(b,"afterA11yComponentUpdate",{name:c,component:a[c]})});this.keyboardNavigation.update(c.keyboardNavigation.order);
!b.highContrastModeActive&&w.isHighContrastModeActive()&&w.setHighContrastTheme(b);x(b,"afterA11yUpdate")},destroy:function(){var a=this.chart||{},b=this.components;Object.keys(b).forEach(function(a){b[a].destroy();b[a].destroyBase()});this.keyboardNavigation&&this.keyboardNavigation.destroy();a.renderTo&&a.renderTo.setAttribute("aria-hidden",!0);a.focusElement&&a.focusElement.removeFocusBorder()},getChartTypes:function(){var a={};this.chart.series.forEach(function(b){a[b.type]=1});return Object.keys(a)}};
f.Chart.prototype.updateA11yEnabled=function(){var a=this.accessibility,b=this.options.accessibility;b&&b.enabled?a?a.update():this.accessibility=new r(this):a?(a.destroy&&a.destroy(),delete this.accessibility):this.renderTo.setAttribute("aria-hidden",!0)};n(f.Chart,"render",function(a){this.a11yDirty&&this.renderTo&&(delete this.a11yDirty,this.updateA11yEnabled());var b=this.accessibility;b&&Object.keys(b.components).forEach(function(a){b.components[a].onChartRender()})});n(f.Chart,"update",function(a){if(a=
a.options.accessibility)a.customComponents&&(this.options.accessibility.customComponents=a.customComponents,delete a.customComponents),z(!0,this.options.accessibility,a),this.accessibility&&this.accessibility.destroy&&(this.accessibility.destroy(),delete this.accessibility);this.a11yDirty=!0});n(f.Point,"update",function(){this.series.chart.accessibility&&(this.series.chart.a11yDirty=!0)});["addSeries","init"].forEach(function(a){n(f.Chart,a,function(){this.a11yDirty=!0})});["update","updatedData",
"remove"].forEach(function(a){n(f.Series,a,function(){this.chart.accessibility&&(this.chart.a11yDirty=!0)})});["afterDrilldown","drillupall"].forEach(function(a){n(f.Chart,a,function(){this.accessibility&&this.accessibility.update()})});n(f.Chart,"destroy",function(){this.accessibility&&this.accessibility.destroy()})});q(a,"masters/modules/accessibility.src.js",[],function(){})});
//# sourceMappingURL=accessibility.js.map