/*
 Highcharts JS v8.0.0 (2020-02-08)

 Annotations module

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(p){e(p);e.Highcharts=p;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function p(b,a,e,h){b.hasOwnProperty(a)||(b[a]=h.apply(null,e))}e=e?e._modules:{};p(e,"annotations/eventEmitterMixin.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(b,a){var e=a.addEvent,h=a.objectEach,
f=a.pick,v=a.removeEvent,q=b.fireEvent;return{addEvents:function(){var g=this;e(g.graphic.element,"mousedown",function(c){g.onMouseDown(c)});h(g.options.events,function(c,l){var f=function(d){"click"===l&&g.cancelClick||c.call(g,g.chart.pointer.normalize(d),g.target)};if(-1===b.inArray(l,g.nonDOMEvents||[]))g.graphic.on(l,f);else e(g,l,f)});g.options.draggable&&(e(g,"drag",g.onDrag),g.graphic.renderer.styledMode||g.graphic.css({cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[g.options.draggable]}));
g.isUpdating||q(g,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(g){var c=this,l=c.chart.pointer;g.preventDefault&&g.preventDefault();if(2!==g.button){g=l.normalize(g);var x=g.chartX;var d=g.chartY;c.cancelClick=!1;c.chart.hasDraggedAnnotation=!0;c.removeDrag=e(b.doc,"mousemove",function(k){c.hasDragged=!0;k=l.normalize(k);k.prevChartX=x;k.prevChartY=d;q(c,"drag",k);x=k.chartX;
d=k.chartY});c.removeMouseUp=e(b.doc,"mouseup",function(d){c.cancelClick=c.hasDragged;c.hasDragged=!1;c.chart.hasDraggedAnnotation=!1;q(f(c.target,c),"afterUpdate");c.onMouseUp(d)})}},onMouseUp:function(g){var c=this.chart;g=this.target||this;var l=c.options.annotations;c=c.annotations.indexOf(g);this.removeDocEvents();l[c]=g.options},onDrag:function(g){if(this.chart.isInsidePlot(g.chartX-this.chart.plotLeft,g.chartY-this.chart.plotTop)){var c=this.mouseMoveToTranslation(g);"x"===this.options.draggable&&
(c.y=0);"y"===this.options.draggable&&(c.x=0);this.points.length?this.translate(c.x,c.y):(this.shapes.forEach(function(l){l.translate(c.x,c.y)}),this.labels.forEach(function(l){l.translate(c.x,c.y)}));this.redraw(!1)}},mouseMoveToRadians:function(g,c,l){var f=g.prevChartY-l,d=g.prevChartX-c;l=g.chartY-l;g=g.chartX-c;this.chart.inverted&&(c=d,d=f,f=c,c=g,g=l,l=c);return Math.atan2(l,g)-Math.atan2(f,d)},mouseMoveToTranslation:function(g){var c=g.chartX-g.prevChartX;g=g.chartY-g.prevChartY;if(this.chart.inverted){var l=
g;g=c;c=l}return{x:c,y:g}},mouseMoveToScale:function(g,c,l){c=(g.chartX-c||1)/(g.prevChartX-c||1);g=(g.chartY-l||1)/(g.prevChartY-l||1);this.chart.inverted&&(l=g,g=c,c=l);return{x:c,y:g}},destroy:function(){this.removeDocEvents();v(this);this.hcEvents=null}}});p(e,"annotations/ControlPoint.js",[e["parts/Utilities.js"],e["annotations/eventEmitterMixin.js"]],function(b,a){var e=b.extend,h=b.merge,f=b.pick;b=function(a,b,g,c){this.chart=a;this.target=b;this.options=g;this.index=f(g.index,c)};e(b.prototype,
a);b.prototype.nonDOMEvents=["drag"];b.prototype.setVisibility=function(f){this.graphic.attr("visibility",f?"visible":"hidden");this.options.visible=f};b.prototype.render=function(){var f=this.chart,a=this.options;this.graphic=f.renderer.symbol(a.symbol,0,0,a.width,a.height).add(f.controlPointsGroup).css(a.style);this.setVisibility(a.visible);this.addEvents()};b.prototype.redraw=function(f){this.graphic[f?"animate":"attr"](this.options.positioner.call(this,this.target))};b.prototype.destroy=function(){a.destroy.call(this);
this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};b.prototype.update=function(f){var a=this.chart,g=this.target,c=this.index;f=h(!0,this.options,f);this.destroy();this.constructor(a,g,f,c);this.render(a.controlPointsGroup);this.redraw()};return b});p(e,"annotations/MockPoint.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(b,a){var e=a.defined;a=a.extend;var h=function(f,a,e){this.series={visible:!0,chart:f,getPlotBox:b.Series.prototype.getPlotBox};
this.target=a||null;this.options=e;this.applyOptions(this.getOptions())};h.fromPoint=function(f){return new h(f.series.chart,null,{x:f.x,y:f.y,xAxis:f.series.xAxis,yAxis:f.series.yAxis})};h.pointToPixels=function(f,a){var b=f.series,g=b.chart,c=f.plotX,l=f.plotY;g.inverted&&(f.mock?(c=f.plotY,l=f.plotX):(c=g.plotWidth-f.plotY,l=g.plotHeight-f.plotX));b&&!a&&(f=b.getPlotBox(),c+=f.translateX,l+=f.translateY);return{x:c,y:l}};h.pointToOptions=function(f){return{x:f.x,y:f.y,xAxis:f.series.xAxis,yAxis:f.series.yAxis}};
a(h.prototype,{mock:!0,hasDynamicOptions:function(){return"function"===typeof this.options},getOptions:function(){return this.hasDynamicOptions()?this.options(this.target):this.options},applyOptions:function(f){this.command=f.command;this.setAxis(f,"x");this.setAxis(f,"y");this.refresh()},setAxis:function(f,a){a+="Axis";f=f[a];var q=this.series.chart;this.series[a]=f instanceof b.Axis?f:e(f)?q[a][f]||q.get(f):null},toAnchor:function(){var f=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&
(f[0]=this.plotY,f[1]=this.plotX);return f},getLabelConfig:function(){return{x:this.x,y:this.y,point:this}},isInsidePane:function(){var f=this.plotX,a=this.plotY,b=this.series.xAxis,g=this.series.yAxis,c=!0;b&&(c=e(f)&&0<=f&&f<=b.len);g&&(c=c&&e(a)&&0<=a&&a<=g.len);return c},refresh:function(){var f=this.series,a=f.xAxis;f=f.yAxis;var b=this.getOptions();a?(this.x=b.x,this.plotX=a.toPixels(b.x,!0)):(this.x=null,this.plotX=b.x);f?(this.y=b.y,this.plotY=f.toPixels(b.y,!0)):(this.y=null,this.plotY=b.y);
this.isInside=this.isInsidePane()},translate:function(f,a,b,g){this.hasDynamicOptions()||(this.plotX+=b,this.plotY+=g,this.refreshOptions())},scale:function(f,a,b,g){if(!this.hasDynamicOptions()){var c=this.plotY*g;this.plotX=(1-b)*f+this.plotX*b;this.plotY=(1-g)*a+c;this.refreshOptions()}},rotate:function(f,a,b){if(!this.hasDynamicOptions()){var g=Math.cos(b);b=Math.sin(b);var c=this.plotX,l=this.plotY;c-=f;l-=a;this.plotX=c*g-l*b+f;this.plotY=c*b+l*g+a;this.refreshOptions()}},refreshOptions:function(){var a=
this.series,b=a.xAxis;a=a.yAxis;this.x=this.options.x=b?this.options.x=b.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=a?a.toValue(this.plotY,!0):this.plotY}});return h});p(e,"annotations/controllable/controllableMixin.js",[e["parts/Globals.js"],e["parts/Utilities.js"],e["annotations/ControlPoint.js"],e["annotations/MockPoint.js"]],function(b,a,e,h){var f=a.isObject,v=a.isString,q=a.merge,g=a.splat;return{init:function(c,a,b){this.annotation=c;this.chart=c.chart;this.options=a;this.points=
[];this.controlPoints=[];this.index=b;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var c=this.options;return c.points||c.point&&g(c.point)},attrsFromOptions:function(c){var a=this.constructor.attrsMap,b={},d,k=this.chart.styledMode;for(d in c){var m=a[d];!m||k&&-1!==["fill","stroke","stroke-width"].indexOf(m)||(b[m]=c[d])}return b},anchor:function(c){var a=c.series.getPlotBox();c=c.mock?c.toAnchor():b.Tooltip.prototype.getAnchor.call({chart:c.series.chart},
c);c={x:c[0]+(this.options.x||0),y:c[1]+(this.options.y||0),height:c[2]||0,width:c[3]||0};return{relativePosition:c,absolutePosition:q(c,{x:c.x+a.translateX,y:c.y+a.translateY})}},point:function(c,a){if(c&&c.series)return c;a&&null!==a.series||(f(c)?a=new h(this.chart,this,c):v(c)?a=this.chart.get(c)||null:"function"===typeof c&&(a=c.call(a,this),a=a.series?a:new h(this.chart,this,c)));return a},linkPoints:function(){var c=this.getPointsOptions(),a=this.points,b=c&&c.length||0,d;for(d=0;d<b;d++){var k=
this.point(c[d],a[d]);if(!k){a.length=0;return}k.mock&&k.refresh();a[d]=k}return a},addControlPoints:function(){var c=this.options.controlPoints;(c||[]).forEach(function(a,b){a=q(this.options.controlPointOptions,a);a.index||(a.index=b);c[b]=a;this.controlPoints.push(new e(this.chart,this,a))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(c){this.controlPoints.forEach(function(c){c.render()})},redraw:function(c){this.controlPoints.forEach(function(a){a.redraw(c)})},transform:function(c,
a,b,d,k){if(this.chart.inverted){var m=a;a=b;b=m}this.points.forEach(function(m,f){this.transformPoint(c,a,b,d,k,f)},this)},transformPoint:function(c,a,b,d,k,m){var f=this.points[m];f.mock||(f=this.points[m]=h.fromPoint(f));f[c](a,b,d,k)},translate:function(c,a){this.transform("translate",null,null,c,a)},translatePoint:function(c,a,b){this.transformPoint("translate",null,null,c,a,b)},translateShape:function(c,a){var b=this.annotation.chart,d=this.annotation.userOptions,k=b.annotations.indexOf(this.annotation);
b=b.options.annotations[k];this.translatePoint(c,a,0);b[this.collection][this.index].point=this.options.point;d[this.collection][this.index].point=this.options.point},rotate:function(c,a,b){this.transform("rotate",c,a,b)},scale:function(a,b,f,d){this.transform("scale",a,b,f,d)},setControlPointsVisibility:function(a){this.controlPoints.forEach(function(c){c.setVisibility(a)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());
this.controlPoints.forEach(function(a){a.destroy()});this.options=this.controlPoints=this.points=this.chart=null;this.annotation&&(this.annotation=null)},update:function(a){var c=this.annotation;a=q(!0,this.options,a);var b=this.graphic.parentGroup;this.destroy();this.constructor(c,a);this.render(b);this.redraw()}}});p(e,"annotations/controllable/markerMixin.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(b,a){var e=a.addEvent,h=a.defined,f=a.merge,v=a.objectEach,q={arrow:{tagName:"marker",
render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};b.SVGRenderer.prototype.addMarker=function(a,c){var b={id:a},g={stroke:c.color||"none",fill:c.color||"rgba(0, 0, 0, 0.75)"};b.children=c.children.map(function(d){return f(g,d)});c=this.definition(f(!0,
{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},c,b));c.id=a;return c};a=function(a){return function(c){this.attr(a,"url(#"+c+")")}};a={markerEndSetter:a("marker-end"),markerStartSetter:a("marker-start"),setItemMarkers:function(a){var c=a.options,g=a.chart,e=g.options.defs,d=c.fill,k=h(d)&&"none"!==d?d:c.stroke;["markerStart","markerEnd"].forEach(function(d){var m=c[d],u;if(m){for(u in e){var n=e[u];if(m===n.id&&"marker"===n.tagName){var h=n;break}}h&&(m=a[d]=g.renderer.addMarker((c.id||
b.uniqueKey())+"-"+h.id,f(h,{color:k})),a.attr(d,m.attr("id")))}})}};e(b.Chart,"afterGetContainer",function(){this.options.defs=f(q,this.options.defs||{});v(this.options.defs,function(a){"marker"===a.tagName&&!1!==a.render&&this.renderer.addMarker(a.id,a)},this)});return a});p(e,"annotations/controllable/ControllablePath.js",[e["parts/Globals.js"],e["parts/Utilities.js"],e["annotations/controllable/controllableMixin.js"],e["annotations/controllable/markerMixin.js"]],function(b,a,e,h){var f=a.extend;
a=a.merge;var v="rgba(192,192,192,"+(b.svg?.0001:.002)+")";b=function(a,b,c){this.init(a,b,c);this.collection="shapes"};b.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};a(!0,b.prototype,e,{type:"path",setMarkers:h.setItemMarkers,toD:function(){var a=this.options.d;if(a)return"function"===typeof a?a.call(this):a;var b=this.points,c=b.length,f=c,e=b[0],d=f&&this.anchor(e).absolutePosition,k=0,m=2;for(a=d&&["M",d.x,d.y];++k<c&&f;)e=b[k],f=e.command||
"L",d=this.anchor(e).absolutePosition,"Z"===f?a[++m]=f:(f!==b[k-1].command&&(a[++m]=f),a[++m]=d.x,a[++m]=d.y),f=e.series.visible;return f?this.chart.renderer.crispLine(a,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return e.shouldBeDrawn.call(this)||!!this.options.d},render:function(a){var b=this.options,c=this.attrsFromOptions(b);this.graphic=this.annotation.chart.renderer.path(["M",0,0]).attr(c).add(a);b.className&&this.graphic.addClass(b.className);this.tracker=this.annotation.chart.renderer.path(["M",
0,0]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(a);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:v,fill:v,"stroke-width":this.graphic.strokeWidth()+2*b.snap});e.render.call(this);f(this.graphic,{markerStartSetter:h.markerStartSetter,markerEndSetter:h.markerEndSetter});this.setMarkers(this)},redraw:function(a){var b=this.toD(),c=a?"animate":"attr";b?(this.graphic[c]({d:b}),this.tracker[c]({d:b})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));
this.graphic.placed=this.tracker.placed=!!b;e.redraw.call(this,a)}});return b});p(e,"annotations/controllable/ControllableRect.js",[e["parts/Utilities.js"],e["annotations/controllable/controllableMixin.js"],e["annotations/controllable/ControllablePath.js"]],function(b,a,e){b=b.merge;var h=function(a,b,e){this.init(a,b,e);this.collection="shapes"};h.attrsMap=b(e.attrsMap,{width:"width",height:"height"});b(!0,h.prototype,a,{type:"rect",translate:a.translateShape,render:function(b){var f=this.attrsFromOptions(this.options);
this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(f).add(b);a.render.call(this)},redraw:function(b){var f=this.anchor(this.points[0]).absolutePosition;if(f)this.graphic[b?"animate":"attr"]({x:f.x,y:f.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!f;a.redraw.call(this,b)}});return h});p(e,"annotations/controllable/ControllableCircle.js",[e["parts/Utilities.js"],e["annotations/controllable/controllableMixin.js"],e["annotations/controllable/ControllablePath.js"]],
function(b,a,e){b=b.merge;var h=function(a,b,e){this.init(a,b,e);this.collection="shapes"};h.attrsMap=b(e.attrsMap,{r:"r"});b(!0,h.prototype,a,{type:"circle",translate:a.translateShape,render:function(b){var f=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(f).add(b);a.render.call(this)},redraw:function(b){var f=this.anchor(this.points[0]).absolutePosition;if(f)this.graphic[b?"animate":"attr"]({x:f.x,y:f.y,r:this.options.r});else this.graphic.attr({x:0,
y:-9E9});this.graphic.placed=!!f;a.redraw.call(this,b)},setRadius:function(a){this.options.r=a}});return h});p(e,"annotations/controllable/ControllableLabel.js",[e["parts/Globals.js"],e["parts/Utilities.js"],e["annotations/controllable/controllableMixin.js"],e["annotations/MockPoint.js"]],function(b,a,e,h){var f=a.extend,v=a.format,q=a.isNumber,g=a.merge,c=a.pick,l=function(a,d,b){this.init(a,d,b);this.collection="labels"};l.shapesWithoutBackground=["connector"];l.alignedPosition=function(a,d){var b=
a.align,c=a.verticalAlign,f=(d.x||0)+(a.x||0),e=(d.y||0)+(a.y||0),g,h;"right"===b?g=1:"center"===b&&(g=2);g&&(f+=(d.width-(a.width||0))/g);"bottom"===c?h=1:"middle"===c&&(h=2);h&&(e+=(d.height-(a.height||0))/h);return{x:Math.round(f),y:Math.round(e)}};l.justifiedOptions=function(a,d,b,c){var k=b.align,f=b.verticalAlign,e=d.box?0:d.padding||0,m=d.getBBox();d={align:k,verticalAlign:f,x:b.x,y:b.y,width:d.width,height:d.height};b=c.x-a.plotLeft;var r=c.y-a.plotTop;c=b+e;0>c&&("right"===k?d.align="left":
d.x=-c);c=b+m.width-e;c>a.plotWidth&&("left"===k?d.align="right":d.x=a.plotWidth-c);c=r+e;0>c&&("bottom"===f?d.verticalAlign="top":d.y=-c);c=r+m.height-e;c>a.plotHeight&&("top"===f?d.verticalAlign="bottom":d.y=a.plotHeight-c);return d};l.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};g(!0,l.prototype,e,{translatePoint:function(a,d){e.translatePoint.call(this,a,d,0)},translate:function(a,d){var b=this.annotation.chart,
c=this.annotation.userOptions,f=b.annotations.indexOf(this.annotation);f=b.options.annotations[f];b.inverted&&(b=a,a=d,d=b);this.options.x+=a;this.options.y+=d;f[this.collection][this.index].x=this.options.x;f[this.collection][this.index].y=this.options.y;c[this.collection][this.index].x=this.options.x;c[this.collection][this.index].y=this.options.y},render:function(a){var d=this.options,b=this.attrsFromOptions(d),c=d.style;this.graphic=this.annotation.chart.renderer.label("",0,-9999,d.shape,null,
null,d.useHTML,null,"annotation-label").attr(b).add(a);this.annotation.chart.styledMode||("contrast"===c.color&&(c.color=this.annotation.chart.renderer.getContrast(-1<l.shapesWithoutBackground.indexOf(d.shape)?"#FFFFFF":d.backgroundColor)),this.graphic.css(d.style).shadow(d.shadow));d.className&&this.graphic.addClass(d.className);this.graphic.labelrank=d.labelrank;e.render.call(this)},redraw:function(a){var d=this.options,b=this.text||d.format||d.text,c=this.graphic,f=this.points[0];c.attr({text:b?
v(b,f.getLabelConfig(),this.annotation.chart):d.formatter.call(f,this)});d=this.anchor(f);(b=this.position(d))?(c.alignAttr=b,b.anchorX=d.absolutePosition.x,b.anchorY=d.absolutePosition.y,c[a?"animate":"attr"](b)):c.attr({x:0,y:-9999});c.placed=!!b;e.redraw.call(this,a)},anchor:function(){var a=e.anchor.apply(this,arguments),b=this.options.x||0,c=this.options.y||0;a.absolutePosition.x-=b;a.absolutePosition.y-=c;a.relativePosition.x-=b;a.relativePosition.y-=c;return a},position:function(a){var d=this.graphic,
k=this.annotation.chart,e=this.points[0],g=this.options,u=a.absolutePosition,n=a.relativePosition;if(a=e.series.visible&&h.prototype.isInsidePane.call(e)){if(g.distance)var w=b.Tooltip.prototype.getPosition.call({chart:k,distance:c(g.distance,16)},d.width,d.height,{plotX:n.x,plotY:n.y,negative:e.negative,ttBelow:e.ttBelow,h:n.height||n.width});else g.positioner?w=g.positioner.call(this):(e={x:u.x,y:u.y,width:0,height:0},w=l.alignedPosition(f(g,{width:d.width,height:d.height}),e),"justify"===this.options.overflow&&
(w=l.alignedPosition(l.justifiedOptions(k,d,g,w),e)));g.crop&&(g=w.x-k.plotLeft,e=w.y-k.plotTop,a=k.isInsidePlot(g,e)&&k.isInsidePlot(g+d.width,e+d.height))}return a?w:null}});b.SVGRenderer.prototype.symbols.connector=function(a,b,c,f,e){var d=e&&e.anchorX;e=e&&e.anchorY;var k=c/2;if(q(d)&&q(e)){var g=["M",d,e];var r=b-e;0>r&&(r=-f-r);r<c&&(k=d<a+c/2?r:c-r);e>b+f?g.push("L",a+k,b+f):e<b?g.push("L",a+k,b):d<a?g.push("L",a,b+f/2):d>a+c&&g.push("L",a+c,b+f/2)}return g||[]};return l});p(e,"annotations/controllable/ControllableImage.js",
[e["parts/Utilities.js"],e["annotations/controllable/controllableMixin.js"],e["annotations/controllable/ControllableLabel.js"]],function(b,a,e){b=b.merge;var h=function(a,b,e){this.init(a,b,e);this.collection="shapes"};h.attrsMap={width:"width",height:"height",zIndex:"zIndex"};b(!0,h.prototype,a,{type:"image",translate:a.translateShape,render:function(b){var f=this.attrsFromOptions(this.options),e=this.options;this.graphic=this.annotation.chart.renderer.image(e.src,0,-9E9,e.width,e.height).attr(f).add(b);
this.graphic.width=e.width;this.graphic.height=e.height;a.render.call(this)},redraw:function(b){var f=this.anchor(this.points[0]);if(f=e.prototype.position.call(this,f))this.graphic[b?"animate":"attr"]({x:f.x,y:f.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!f;a.redraw.call(this,b)}});return h});p(e,"annotations/annotations.src.js",[e["parts/Globals.js"],e["parts/Utilities.js"],e["annotations/controllable/controllableMixin.js"],e["annotations/controllable/ControllableRect.js"],e["annotations/controllable/ControllableCircle.js"],
e["annotations/controllable/ControllablePath.js"],e["annotations/controllable/ControllableImage.js"],e["annotations/controllable/ControllableLabel.js"],e["annotations/eventEmitterMixin.js"],e["annotations/MockPoint.js"],e["annotations/ControlPoint.js"]],function(b,a,e,h,f,p,q,g,c,l,x){var d=a.addEvent,k=a.defined,m=a.destroyObjectProperties,t=a.erase,u=a.extend,n=a.merge,w=a.pick,r=a.splat;a=a.wrap;var A=b.fireEvent,B=b.find,C=b.reduce,z=b.Chart.prototype,y=b.Annotation=function(a,b){this.chart=a;
this.points=[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=n(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=b.shapes;this.init(a,this.options)};n(!0,y.prototype,e,c,{nonDOMEvents:["add","afterUpdate","drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",borderRadius:3,
borderWidth:1,className:"",crop:!1,formatter:function(){return k(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},events:{},zIndex:6},
init:function(){this.linkPoints();this.addControlPoints();this.addShapes();this.addLabels();this.addClipPaths();this.setLabelCollector()},getLabelsAndShapesOptions:function(a,b){var c={};["labels","shapes"].forEach(function(d){a[d]&&(c[d]=r(b[d]).map(function(b,c){return n(a[d][c],b)}))});return c},addShapes:function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);n(!0,this.options.shapes[b],a.options)},this)},addLabels:function(){(this.options.labels||[]).forEach(function(a,
b){a=this.initLabel(a,b);n(!0,this.options.labels[b],a.options)},this)},addClipPaths:function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))},setClipAxes:function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=C((this.options.labels||[]).concat(this.options.shapes||[]),function(c,d){return[a[d&&d.point&&d.point.xAxis]||c[0],b[d&&d.point&&d.point.yAxis]||c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]},getClipBox:function(){return{x:this.clipXAxis.left,
y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}},setLabelCollector:function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)},setOptions:function(a){this.options=n(this.defaultOptions,a)},redraw:function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());this.redrawItems(this.shapes,
a);this.redrawItems(this.labels,a);e.redraw.call(this,a)},redrawItems:function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)},render:function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.clipRect&&this.graphic.clip(this.clipRect);
this.addEvents();e.render.call(this)},setVisibility:function(a){var b=this.options;a=w(a,!b.visible);this.graphic.attr("visibility",a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a},setControlPointsVisibility:function(a){var b=function(b){b.setControlPointsVisibility(a)};e.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)},destroy:function(){var a=this.chart,b=function(a){a.destroy()};this.labels.forEach(b);this.shapes.forEach(b);this.clipYAxis=
this.clipXAxis=null;t(a.labelCollectors,this.labelCollector);c.destroy.call(this);e.destroy.call(this);m(this,a)},remove:function(){return this.chart.removeAnnotation(this)},update:function(a){var b=this.chart,c=this.getLabelsAndShapesOptions(this.userOptions,a),d=b.annotations.indexOf(this);a=n(!0,this.userOptions,a);a.labels=c.labels;a.shapes=c.shapes;this.destroy();this.constructor(b,a);b.options.annotations[d]=a;this.isUpdating=!0;this.redraw();this.isUpdating=!1;A(this,"afterUpdate")},initShape:function(a,
b){a=n(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new y.shapesMap[a.type](this,a,b);b.itemType="shape";this.shapes.push(b);return b},initLabel:function(a,b){a=n(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new g(this,a,b);b.itemType="label";this.labels.push(b);return b},redrawItem:function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(w(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):
this.destroyItem(a)},adjustVisibility:function(a){var b=!1,c=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===c.visibility&&c.show():c.hide()},destroyItem:function(a){t(this[a.itemType+"s"],a);a.destroy()},renderItem:function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)}});y.shapesMap={rect:h,circle:f,path:p,image:q};y.types={};y.MockPoint=l;y.ControlPoint=x;b.extendAnnotation=function(a,b,c,d){b=b||y;n(!0,a.prototype,b.prototype,
c);a.prototype.defaultOptions=n(a.prototype.defaultOptions,d||{})};u(z,{initAnnotation:function(a){a=new (y.types[a.type]||y)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);w(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=this.annotations,c="annotations"===a.coll?a:B(b,function(b){return b.options.id===a});c&&(A(c,"remove"),t(this.options.annotations,c.options),t(b,c),c.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);
this.annotations.forEach(function(a){a.redraw()})}});z.collectionsWithUpdate.push("annotations");z.collectionsWithInit.annotations=[z.addAnnotation];z.callbacks.push(function(a){a.annotations=[];a.options.annotations||(a.options.annotations=[]);a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();a.options.annotations.forEach(function(b,c){b=a.initAnnotation(b);a.options.annotations[c]=b.options});a.drawAnnotations();
d(a,"redraw",a.drawAnnotations);d(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()})});a(b.Pointer.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,Array.prototype.slice.call(arguments,1))})});p(e,"mixins/navigation.js",[],function(){return{initUpdate:function(b){b.navigation||(b.navigation={updates:[],update:function(a,b){this.updates.forEach(function(e){e.update.call(e.context,a,b)})}})},addUpdate:function(b,a){a.navigation||
this.initUpdate(a);a.navigation.updates.push({update:b,context:a})}}});p(e,"annotations/navigationBindings.js",[e["parts/Globals.js"],e["parts/Utilities.js"],e["mixins/navigation.js"]],function(b,a,e){function h(a){var b=a.prototype.defaultOptions.events&&a.prototype.defaultOptions.events.click;m(!0,a.prototype.defaultOptions.events,{click:function(a){var d=this,e=d.chart.navigationBindings,f=e.activeAnnotation;b&&b.click.call(d,a);f!==d?(e.deselectAnnotation(),e.activeAnnotation=d,d.setControlPointsVisibility(!0),
c(e,"showPopup",{annotation:d,formType:"annotation-toolbar",options:e.annotationToFields(d),onSubmit:function(a){var b={};"remove"===a.actionType?(e.activeAnnotation=!1,e.chart.removeAnnotation(d)):(e.fieldsToOptions(a.fields,b),e.deselectAnnotation(),a=b.typeOptions,"measure"===d.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),d.update(b))}})):(e.deselectAnnotation(),c(e,"closePopup"));a.activeAnnotation=!0}})}var f=a.addEvent,p=
a.attr,q=a.extend,g=a.format,c=a.fireEvent,l=a.isArray,x=a.isFunction,d=a.isNumber,k=a.isObject,m=a.merge,t=a.objectEach,u=a.pick,n=b.doc,w=b.win;b.NavigationBindings=function(a,b){this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=n.getElementsByClassName(this.options.bindingsClassName)};b.NavigationBindings.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth",
"stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill","strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line",
"height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[]};b.NavigationBindings.annotationsNonEditable={rectangle:["crosshairX","crosshairY","label"]};q(b.NavigationBindings.prototype,{initEvents:function(){var a=this,b=a.chart,c=a.container,d=a.options;a.boundClassNames={};t(d.bindings,function(b){a.boundClassNames[b.className]=b});[].forEach.call(c,function(b){a.eventsToUnbind.push(f(b,"click",function(b){var d=a.getButtonEvents(c,b);d&&a.bindingsButtonClick(d.button,
d.events,b)}))});t(d.events||{},function(b,c){x(b)&&a.eventsToUnbind.push(f(a,c,b))});a.eventsToUnbind.push(f(b.container,"click",function(c){!b.cancelClick&&b.isInsidePlot(c.chartX-b.plotLeft,c.chartY-b.plotTop)&&a.bindingsChartClick(this,c)}));a.eventsToUnbind.push(f(b.container,"mousemove",function(b){a.bindingsContainerMouseMove(this,b)}))},initUpdate:function(){var a=this;e.addUpdate(function(b){a.update(b)},this.chart)},bindingsButtonClick:function(a,b,d){var e=this.chart;this.selectedButtonElement&&
(c(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&e.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=b;this.selectedButtonElement=a;c(this,"selectButton",{button:a});b.init&&b.init.call(this,a,d);(b.start||b.steps)&&e.renderer.boxWrapper.addClass("highcharts-draw-mode")},bindingsChartClick:function(a,b){a=this.chart;var d=this.selectedButton;a=a.renderer.boxWrapper;
var e;if(e=this.activeAnnotation&&!b.activeAnnotation&&b.target.parentNode){a:{e=b.target;var f=w.Element.prototype,k=f.matches||f.msMatchesSelector||f.webkitMatchesSelector,g=null;if(f.closest)g=f.closest.call(e,".highcharts-popup");else{do{if(k.call(e,".highcharts-popup"))break a;e=e.parentElement||e.parentNode}while(null!==e&&1===e.nodeType)}e=g}e=!e}e&&(c(this,"closePopup"),this.deselectAnnotation());d&&d.start&&(this.nextEvent?(this.nextEvent(b,this.currentUserDetails),this.steps&&(this.stepIndex++,
d.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=d.steps[this.stepIndex]:(c(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),d.end&&d.end.call(this,b,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=d.start.call(this,b),d.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=d.steps[this.stepIndex]):(c(this,"deselectButton",{button:this.selectedButtonElement}),
a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,d.end&&d.end.call(this,b,this.currentUserDetails))))},bindingsContainerMouseMove:function(a,b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)},fieldsToOptions:function(a,b){t(a,function(a,c){var e=parseFloat(a),f=c.split("."),k=b,g=f.length-1;!d(e)||a.match(/px/g)||c.match(/format/g)||(a=e);""!==a&&"undefined"!==a&&f.forEach(function(b,c){var d=u(f[c+1],"");g===c?k[b]=a:(k[b]||(k[b]=d.match(/\d/g)?[]:
{}),k=k[b])})});return b},deselectAnnotation:function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)},annotationToFields:function(a){function c(b,d,e,r){if(e&&-1===h.indexOf(d)&&(0<=(e.indexOf&&e.indexOf(d))||e[d]||!0===e))if(l(b))r[d]=[],b.forEach(function(a,b){k(a)?(r[d][b]={},t(a,function(a,e){c(a,e,f[d],r[d][b])})):c(a,0,f[d],r[d])});else if(k(b)){var n={};l(r)?(r.push(n),n[d]={},n=n[d]):r[d]=n;t(b,function(a,b){c(a,b,0===d?e:f[d],n)})}else"format"===
d?r[d]=[g(b,a.labels[0].points[0]).toString(),"text"]:l(r)?r.push([b,m(b)]):r[d]=[b,m(b)]}var d=a.options,e=b.NavigationBindings.annotationsEditable,f=e.nestedOptions,m=this.utils.getFieldType,r=u(d.type,d.shapes&&d.shapes[0]&&d.shapes[0].type,d.labels&&d.labels[0]&&d.labels[0].itemType,"label"),h=b.NavigationBindings.annotationsNonEditable[d.langKey]||[],n={langKey:d.langKey,type:r};t(d,function(a,b){"typeOptions"===b?(n[b]={},t(d[b],function(a,d){c(a,d,f,n[b],!0)})):c(a,b,e[r],n)});return n},getClickedClassNames:function(a,
b){var d=b.target;b=[];for(var c;d&&((c=p(d,"class"))&&(b=b.concat(c.split(" ").map(function(a){return[a,d]}))),d=d.parentNode,d!==a););return b},getButtonEvents:function(a,b){var d=this,c;this.getClickedClassNames(a,b).forEach(function(a){d.boundClassNames[a[0]]&&!c&&(c={events:d.boundClassNames[a[0]],button:a[1]})});return c},update:function(a){this.options=m(!0,this.options,a);this.removeEvents();this.initEvents()},removeEvents:function(){this.eventsToUnbind.forEach(function(a){a()})},destroy:function(){this.removeEvents()},
utils:{updateRectSize:function(a,b){var d=b.chart,c=b.options.typeOptions,e=d.pointer.getCoordinates(a);a=e.xAxis[0].value-c.point.x;c=c.point.y-e.yAxis[0].value;b.update({typeOptions:{background:{width:d.inverted?c:a,height:d.inverted?a:c}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}}});b.Chart.prototype.initNavigationBindings=function(){var a=this.options;a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new b.NavigationBindings(this,
a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};f(b.Chart,"load",function(){this.initNavigationBindings()});f(b.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});f(b.NavigationBindings,"deselectButton",function(){this.selectedButtonElement=null});f(b.Annotation,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});b.Annotation&&(h(b.Annotation),t(b.Annotation.types,function(a){h(a)}));
b.setOptions({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",padding:"Padding",
fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var d=this.chart.options.navigation;return this.chart.addAnnotation(m({langKey:"circle",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},r:5,controlPoints:[{positioner:function(a){var d=b.Annotation.MockPoint.pointToPixels(a.points[0]);
a=a.options.r;return{x:d.x+a*Math.cos(Math.PI/4)-this.graphic.width/2,y:d.y+a*Math.sin(Math.PI/4)-this.graphic.height/2}},events:{drag:function(a,b){var d=b.annotation;a=this.mouseMoveToTranslation(a);b.setRadius(Math.max(b.options.r+a.y/Math.sin(Math.PI/4),5));d.options.shapes[0]=d.userOptions.shapes[0]=b.options;b.redraw(!1)}}}]}]},d.annotationsOptions,d.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var d=b.options.shapes[0].point,c=this.chart.xAxis[0].toPixels(d.x);d=this.chart.yAxis[0].toPixels(d.y);
var e=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(e?d-a.chartX:c-a.chartX,2)+Math.pow(e?c-a.chartY:d-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(a){var d=this.chart.pointer.getCoordinates(a),c=this.chart.options.navigation,e=d.xAxis[0].value;d=d.yAxis[0].value;return this.chart.addAnnotation(m({langKey:"rectangle",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:e,y:d},{xAxis:0,yAxis:0,x:e,y:d},{xAxis:0,yAxis:0,x:e,
y:d},{xAxis:0,yAxis:0,x:e,y:d}]}],controlPoints:[{positioner:function(a){a=b.Annotation.MockPoint.pointToPixels(a.shapes[0].points[2]);return{x:a.x-4,y:a.y-4}},events:{drag:function(b){var d=this.chart.pointer.getCoordinates(a),c=d.xAxis[0].value;d=d.yAxis[0].value;var e=b.options.shapes[0].points;e[1].x=c;e[2].x=c;e[2].y=d;e[3].y=d;b.options.shapes[0].points=e;b.redraw(!1)}}}]},c.annotationsOptions,c.bindings.rectangleAnnotation.annotationsOptions))},steps:[function(a,b){var d=b.options.shapes[0].points,
c=this.chart.pointer.getCoordinates(a);a=c.xAxis[0].value;c=c.yAxis[0].value;d[1].x=a;d[2].x=a;d[2].y=c;d[3].y=c;b.update({shapes:[{points:d}]})}]},labelAnnotation:{className:"highcharts-label-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var d=this.chart.options.navigation;return this.chart.addAnnotation(m({langKey:"label",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},overflow:"none",crop:!0,controlPoints:[{symbol:"triangle-down",
positioner:function(a){if(!a.graphic.placed)return{x:0,y:-9E7};a=b.Annotation.MockPoint.pointToPixels(a.points[0]);return{x:a.x-this.graphic.width/2,y:a.y-this.graphic.height/2}},events:{drag:function(a,b){a=this.mouseMoveToTranslation(a);b.translatePoint(a.x,a.y);b.annotation.labels[0].options=b.options;b.redraw(!1)}}},{symbol:"square",positioner:function(a){return a.graphic.placed?{x:a.graphic.alignAttr.x-this.graphic.width/2,y:a.graphic.alignAttr.y-this.graphic.height/2}:{x:0,y:-9E7}},events:{drag:function(a,
b){a=this.mouseMoveToTranslation(a);b.translate(a.x,a.y);b.annotation.labels[0].options=b.options;b.redraw(!1)}}}]}]},d.annotationsOptions,d.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}})});p(e,"annotations/popup.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(b,a){var e=a.addEvent,h=a.createElement,f=a.defined,p=a.isArray,q=a.isObject,g=a.isString,c=a.objectEach,l=a.pick;a=a.wrap;var x=/\d/g;a(b.Pointer.prototype,"onContainerMouseDown",function(a,
b){var d=b.target&&b.target.className;g(d)&&0<=d.indexOf("highcharts-popup-field")||a.apply(this,Array.prototype.slice.call(arguments,1))});b.Popup=function(a,b){this.init(a,b)};b.Popup.prototype={init:function(a,b){this.container=h("div",{className:"highcharts-popup"},null,a);this.lang=this.getLangpack();this.iconsURL=b;this.addCloseBtn()},addCloseBtn:function(){var a=this;var b=h("div",{className:"highcharts-popup-close"},null,this.container);b.style["background-image"]="url("+this.iconsURL+"close.svg)";
["click","touchstart"].forEach(function(d){e(b,d,function(){a.closePopup()})})},addColsContainer:function(a){var b=h("div",{className:"highcharts-popup-lhs-col"},null,a);a=h("div",{className:"highcharts-popup-rhs-col"},null,a);h("div",{className:"highcharts-popup-rhs-col-wrapper"},null,a);return{lhsCol:b,rhsCol:a}},addInput:function(a,b,c,e){var d=a.split(".");d=d[d.length-1];var f=this.lang;b="highcharts-"+b+"-"+d;b.match(x)||h("label",{innerHTML:f[d]||d,htmlFor:b},null,c);h("input",{name:b,value:e[0],
type:e[1],className:"highcharts-popup-field"},null,c).setAttribute("highcharts-data-name",a)},addButton:function(a,b,c,f,g){var d=this,k=this.closePopup,m=this.getFields;var t=h("button",{innerHTML:b},null,a);["click","touchstart"].forEach(function(a){e(t,a,function(){k.call(d);return f(m(g,c))})});return t},getFields:function(a,b){var d=a.querySelectorAll("input"),c=a.querySelectorAll("#highcharts-select-series > option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume > option:checked")[0];
var e,f;var k={actionType:b,linkedTo:c&&c.getAttribute("value"),fields:{}};[].forEach.call(d,function(a){f=a.getAttribute("highcharts-data-name");(e=a.getAttribute("highcharts-data-series-id"))?k.seriesId=a.value:f?k.fields[f]=a.value:k.type=a.value});a&&(k.fields["params.volumeSeriesID"]=a.getAttribute("value"));return k},showPopup:function(){var a=this.container,b=a.querySelectorAll(".highcharts-popup-close")[0];a.innerHTML="";0<=a.className.indexOf("highcharts-annotation-toolbar")&&(a.classList.remove("highcharts-annotation-toolbar"),
a.removeAttribute("style"));a.appendChild(b);a.style.display="block"},closePopup:function(){this.popup.container.style.display="none"},showForm:function(a,b,c,e){this.popup=b.navigationBindings.popup;this.showPopup();"indicators"===a&&this.indicators.addForm.call(this,b,c,e);"annotation-toolbar"===a&&this.annotations.addToolbar.call(this,b,c,e);"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,e);"flag"===a&&this.annotations.addForm.call(this,b,c,e,!0)},getLangpack:function(){return b.getOptions().lang.navigation.popup},
annotations:{addToolbar:function(a,b,c){var d=this,e=this.lang,f=this.popup.container,k=this.showForm;-1===f.className.indexOf("highcharts-annotation-toolbar")&&(f.className+=" highcharts-annotation-toolbar");f.style.top=a.plotTop+10+"px";h("span",{innerHTML:l(e[b.langKey]||b.langKey,b.shapes&&b.shapes[0].type)},null,f);var g=this.addButton(f,e.removeButton||"remove","remove",c,f);g.className+=" highcharts-annotation-remove-button";g.style["background-image"]="url("+this.iconsURL+"destroy.svg)";g=
this.addButton(f,e.editButton||"edit","edit",function(){k.call(d,"annotation-edit",a,b,c)},f);g.className+=" highcharts-annotation-edit-button";g.style["background-image"]="url("+this.iconsURL+"edit.svg)"},addForm:function(a,b,c,e){var d=this.popup.container,f=this.lang;h("h2",{innerHTML:f[b.langKey]||b.langKey,className:"highcharts-popup-main-title"},null,d);var g=h("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},null,d);var k=h("div",{className:"highcharts-popup-bottom-row"},
null,d);this.annotations.addFormFields.call(this,g,a,"",b,[],!0);this.addButton(k,e?f.addButton||"add":f.saveButton||"save",e?"add":"save",c,d)},addFormFields:function(a,b,e,f,g,n){var d=this,k=this.annotations.addFormFields,m=this.addInput,l=this.lang,t,u;c(f,function(c,f){t=""!==e?e+"."+f:f;q(c)&&(!p(c)||p(c)&&q(c[0])?(u=l[f]||f,u.match(x)||g.push([!0,u,a]),k.call(d,a,b,t,c,g,!1)):g.push([d,t,"annotation",a,c]))});n&&(g=g.sort(function(a){return a[1].match(/format/g)?-1:1}),g.forEach(function(a){!0===
a[0]?h("span",{className:"highcharts-annotation-title",innerHTML:a[1]},null,a[2]):m.apply(a[0],a.splice(1))}))}},indicators:{addForm:function(a,b,c){var d=this.indicators,e=this.lang;this.tabs.init.call(this,a);b=this.popup.container.querySelectorAll(".highcharts-tab-item-content");this.addColsContainer(b[0]);d.addIndicatorList.call(this,a,b[0],"add");var f=b[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,e.addButton||"add","add",c,f);this.addColsContainer(b[1]);d.addIndicatorList.call(this,
a,b[1],"edit");f=b[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,e.saveButton||"save","edit",c,f);this.addButton(f,e.removeButton||"remove","remove",c,f)},addIndicatorList:function(a,b,f){var d=this,g=b.querySelectorAll(".highcharts-popup-lhs-col")[0];b=b.querySelectorAll(".highcharts-popup-rhs-col")[0];var k="edit"===f,m=k?a.series:a.options.plotOptions,l=this.indicators.addFormFields,p;var q=h("ul",{className:"highcharts-indicator-list"},null,g);var v=b.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];
c(m,function(b,c){var f=b.options;if(b.params||f&&f.params){var g=d.indicators.getNameType(b,c),n=g.type;p=h("li",{className:"highcharts-indicator-list",innerHTML:g.name},null,q);["click","touchstart"].forEach(function(c){e(p,c,function(){l.call(d,a,k?b:m[n],g.type,v);k&&b.options&&h("input",{type:"hidden",name:"highcharts-id-"+n,value:b.options.id},null,v).setAttribute("highcharts-data-series-id",b.options.id)})})}});0<q.childNodes.length&&q.childNodes[0].click()},getNameType:function(a,c){var d=
a.options,e=b.seriesTypes;e=e[c]&&e[c].prototype.nameBase||c.toUpperCase();d&&d.type&&(c=a.options.type,e=a.name);return{name:e,type:c}},listAllSeries:function(a,b,c,e,g){a="highcharts-"+b+"-type-"+a;var d;h("label",{innerHTML:this.lang[b]||b,htmlFor:a},null,e);var k=h("select",{name:a,className:"highcharts-popup-field"},null,e);k.setAttribute("id","highcharts-select-"+b);c.series.forEach(function(a){d=a.options;!d.params&&d.id&&"highcharts-navigator-series"!==d.id&&h("option",{innerHTML:d.name||
d.id,value:d.id},null,k)});f(g)&&(k.value=g)},addFormFields:function(a,b,c,e){var d=b.params||b.options.params,f=this.indicators.getNameType;e.innerHTML="";h("h3",{className:"highcharts-indicator-title",innerHTML:f(b,c).name},null,e);h("input",{type:"hidden",name:"highcharts-type-"+c,value:c},null,e);this.indicators.listAllSeries.call(this,c,"series",a,e,b.linkedParent&&d.volumeSeriesID);d.volumeSeriesID&&this.indicators.listAllSeries.call(this,c,"volume",a,e,b.linkedParent&&b.linkedParent.options.id);
this.indicators.addParamInputs.call(this,a,"params",d,c,e)},addParamInputs:function(a,b,e,f,g){var d=this,k=this.indicators.addParamInputs,h=this.addInput,l;c(e,function(c,e){l=b+"."+e;q(c)?k.call(d,a,l,c,f,g):"params.volumeSeriesID"!==l&&h.call(d,l,f,g,[c,"text"])})},getAmount:function(){var a=0;c(this.series,function(b){var c=b.options;(b.params||c&&c.params)&&a++});return a}},tabs:{init:function(a){var b=this.tabs;a=this.indicators.getAmount.call(a);var c=b.addMenuItem.call(this,"add");b.addMenuItem.call(this,
"edit",a);b.addContentItem.call(this,"add");b.addContentItem.call(this,"edit");b.switchTabs.call(this,a);b.selectTab.call(this,c,0)},addMenuItem:function(a,b){var c=this.popup.container,d="highcharts-tab-item",e=this.lang;0===b&&(d+=" highcharts-tab-disabled");b=h("span",{innerHTML:e[a+"Button"]||a,className:d},null,c);b.setAttribute("highcharts-data-tab-type",a);return b},addContentItem:function(){return h("div",{className:"highcharts-tab-item-content"},null,this.popup.container)},switchTabs:function(a){var b=
this,c;this.popup.container.querySelectorAll(".highcharts-tab-item").forEach(function(d,f){c=d.getAttribute("highcharts-data-tab-type");"edit"===c&&0===a||["click","touchstart"].forEach(function(a){e(d,a,function(){b.tabs.deselectAll.call(b);b.tabs.selectTab.call(b,this,f)})})})},selectTab:function(a,b){var c=this.popup.container.querySelectorAll(".highcharts-tab-item-content");a.className+=" highcharts-tab-item-active";c[b].className+=" highcharts-tab-item-show"},deselectAll:function(){var a=this.popup.container,
b=a.querySelectorAll(".highcharts-tab-item");a=a.querySelectorAll(".highcharts-tab-item-content");var c;for(c=0;c<b.length;c++)b[c].classList.remove("highcharts-tab-item-active"),a[c].classList.remove("highcharts-tab-item-show")}}};e(b.NavigationBindings,"showPopup",function(a){this.popup||(this.popup=new b.Popup(this.chart.container,this.chart.options.navigation.iconsURL||this.chart.options.stockTools&&this.chart.options.stockTools.gui.iconsURL||"https://code.highcharts.com/8.0.0/gfx/stock-icons/"));
this.popup.showForm(a.formType,this.chart,a.options,a.onSubmit)});e(b.NavigationBindings,"closePopup",function(){this.popup&&this.popup.closePopup()})});p(e,"masters/modules/annotations.src.js",[],function(){})});
//# sourceMappingURL=annotations.js.map