/*
 Highcharts Gantt JS v8.0.0 (2020-02-08)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(n){"object"===typeof module&&module.exports?(n["default"]=n,module.exports=n):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(I){n(I);n.Highcharts=I;return n}):n("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(n){function I(e,a,A,u){e.hasOwnProperty(a)||(e[a]=u.apply(null,A))}n=n?n._modules:{};I(n,"parts-gantt/CurrentDateIndicator.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(e,a){var A=a.addEvent,u=a.merge;a=
a.wrap;var x=e.PlotLineOrBand,n={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(a,u){return e.dateFormat(u,a)},rotation:0,style:{fontSize:"10px"}}};A(e.Axis,"afterSetOptions",function(){var a=this.options,e=a.currentDateIndicator;e&&(e="object"===typeof e?u(n,e):u(n),e.value=new Date,a.plotLines||(a.plotLines=[]),a.plotLines.push(e))});A(x,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});a(x.prototype,
"getLabelText",function(a,e){var p=this.options;return p.currentDateIndicator&&p.label&&"function"===typeof p.label.formatter?(p.value=new Date,p.label.formatter.call(this,p.value,p.label.format)):a.call(this,e)})});I(n,"parts-gantt/GridAxis.js",[n["parts/Globals.js"],n["parts/Tick.js"],n["parts/Utilities.js"]],function(e,a,A){var u=A.addEvent,x=A.defined,n=A.erase,D=A.isArray,z=A.isNumber,p=A.merge,w=A.pick,k=A.timeUnits,l=A.wrap,v=e.dateFormat,B=function(b){return A.isObject(b,!0)},q=e.Chart,c=
e.Axis,f=function(b){var d=b.options;d.labels||(d.labels={});d.labels.align=w(d.labels.align,"center");b.categories||(d.showLastLabel=!1);b.labelRotation=0;d.labels.rotation=0},t={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};c.prototype.isOuterAxis=function(){var b=this,d=b.columnIndex,g=b.linkedParent&&b.linkedParent.columns||b.columns,c=d?b.linkedParent:b,f=-1,t=0;b.chart[b.coll].forEach(function(d,h){d.side!==b.side||d.options.isInternal||(t=h,d===c&&(f=h))});return t===
f&&(z(d)?g.length===d:!0)};c.prototype.getMaxLabelDimensions=function(b,d){var g={width:0,height:0};d.forEach(function(d){d=b[d];if(B(d)){var c=B(d.label)?d.label:{};d=c.getBBox?c.getBBox().height:0;c.textStr&&!z(c.textPxLength)&&(c.textPxLength=c.getBBox().width);c=z(c.textPxLength)?Math.round(c.textPxLength):0;g.height=Math.max(d,g.height);g.width=Math.max(c,g.width)}});return g};e.dateFormats.W=function(b){b=new Date(b);b.setHours(0,0,0,0);b.setDate(b.getDate()-(b.getDay()||7));var d=new Date(b.getFullYear(),
0,1);return Math.ceil(((b-d)/864E5+1)/7)};e.dateFormats.E=function(b){return v("%a",b,!0).charAt(0)};u(a,"afterGetLabelPosition",function(b){var d=this.label,g=this.axis,c=g.reversed,f=g.chart,k=g.options,m=k&&B(k.grid)?k.grid:{};k=g.options.labels;var h=k.align,r=t[g.side],y=b.tickmarkOffset,E=g.tickPositions,K=this.pos-y;E=z(E[b.index+1])?E[b.index+1]-y:g.max+y;var J=g.tickSize("tick",!0);y=D(J)?J[0]:0;J=J&&J[1]/2;if(!0===m.enabled){if("top"===r){m=g.top+g.offset;var H=m-y}else"bottom"===r?(H=f.chartHeight-
g.bottom+g.offset,m=H+y):(m=g.top+g.len-g.translate(c?E:K),H=g.top+g.len-g.translate(c?K:E));"right"===r?(r=f.chartWidth-g.right+g.offset,c=r+y):"left"===r?(c=g.left+g.offset,r=c-y):(r=Math.round(g.left+g.translate(c?E:K))-J,c=Math.round(g.left+g.translate(c?K:E))-J);this.slotWidth=c-r;b.pos.x="left"===h?r:"right"===h?c:r+(c-r)/2;b.pos.y=H+(m-H)/2;f=f.renderer.fontMetrics(k.style.fontSize,d.element);d=d.getBBox().height;k.useHTML?b.pos.y+=f.b+-(d/2):(d=Math.round(d/f.h),b.pos.y+=(f.b-(f.h-f.f))/2+
-((d-1)*f.h/2));b.pos.x+=g.horiz&&k.x||0}});u(c,"afterTickSize",function(b){var d=this.defaultLeftAxisOptions,g=this.horiz,c=this.options.grid;c=void 0===c?{}:c;var f=this.maxLabelDimensions;c.enabled&&(d=2*Math.abs(d.labels.x),g=g?c.cellHeight||d+f.height:d+f.width,D(b.tickSize)?b.tickSize[0]=g:b.tickSize=[g])});u(c,"afterGetTitlePosition",function(b){var d=this.options;if(!0===(d&&B(d.grid)?d.grid:{}).enabled){var g=this.axisTitle,c=g&&g.getBBox().width,f=this.horiz,k=this.left,m=this.top,h=this.width,
r=this.height,y=d.title;d=this.opposite;var E=this.offset,K=this.tickSize()||[0],J=y.x||0,H=y.y||0,l=w(y.margin,f?5:10);g=this.chart.renderer.fontMetrics(y.style&&y.style.fontSize,g).f;K=(f?m+r:k)+K[0]/2*(d?-1:1)*(f?1:-1)+(this.side===t.bottom?g:0);b.titlePosition.x=f?k-c/2-l+J:K+(d?h:0)+E+J;b.titlePosition.y=f?K-(d?r:0)+(d?g:-g)/2+E+H:m-l+H}});l(c.prototype,"unsquish",function(b){var d=this.options;return!0===(d&&B(d.grid)?d.grid:{}).enabled&&this.categories?this.tickInterval:b.apply(this,Array.prototype.slice.call(arguments,
1))});u(c,"afterSetOptions",function(b){var d=this.options;b=b.userOptions;var g=d&&B(d.grid)?d.grid:{};if(!0===g.enabled){var c=p(!0,{className:"highcharts-grid-axis "+(b.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",
[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},b);"xAxis"===this.coll&&(x(b.linkedTo)&&!x(b.tickPixelInterval)&&(c.tickPixelInterval=350),x(b.tickPixelInterval)||!x(b.linkedTo)||x(b.tickPositioner)||x(b.tickInterval)||(c.tickPositioner=function(b,d){var m=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(m){var h,r=c.units;for(h=0;h<r.length;h++)if(r[h][0]===m.unitName){var g=h;break}if(r[g+1]){var f=r[g+
1][0];var C=(r[g+1][1]||[1])[0]}else"year"===m.unitName&&(f="year",C=10*m.count);m=k[f];this.tickInterval=m*C;return this.getTimeTicks({unitRange:m,count:C,unitName:f},b,d,this.options.startOfWeek)}}));p(!0,this.options,c);this.horiz&&(d.minPadding=w(b.minPadding,0),d.maxPadding=w(b.maxPadding,0));z(d.grid.borderWidth)&&(d.tickWidth=d.lineWidth=g.borderWidth)}});u(c,"afterSetAxisTranslation",function(){var b=this.options,d=b&&B(b.grid)?b.grid:{},g=this.tickPositions&&this.tickPositions.info,c=this.userOptions.labels||
{};this.horiz&&(!0===d.enabled&&this.series.forEach(function(b){b.options.pointRange=0}),g&&(!1===b.dateTimeLabelFormats[g.unitName].range||1<g.count)&&!x(c.align)&&(b.labels.align="left",x(c.x)||(b.labels.x=3)))});u(c,"trimTicks",function(){var b=this.options,d=b&&B(b.grid)?b.grid:{},g=this.categories,c=this.tickPositions,f=c[0],t=c[c.length-1],m=this.linkedParent&&this.linkedParent.min||this.min,h=this.linkedParent&&this.linkedParent.max||this.max,r=this.tickInterval;!0!==d.enabled||g||!this.horiz&&
!this.isLinked||(f<m&&f+r>m&&!b.startOnTick&&(c[0]=m),t>h&&t-r<h&&!b.endOnTick&&(c[c.length-1]=h))});u(c,"afterRender",function(){var b=this.options,d=b&&B(b.grid)?b.grid:{},g=this.chart.renderer;if(!0===d.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.isOuterAxis()&&this.axisLine){var c=b.lineWidth;if(c){var f=this.getLinePath(c);var k=f.indexOf("M")+1;var m=f.indexOf("L")+1;d=f.indexOf("M")+2;var h=f.indexOf("L")+
2;var r=(this.tickSize("tick")[0]-1)*(this.side===t.top||this.side===t.left?-1:1);this.horiz?(f[d]+=r,f[h]+=r):(f[k]+=r,f[m]+=r);this.axisLineExtra?this.axisLineExtra.animate({d:f}):(this.axisLineExtra=g.path(f).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),g.styledMode||this.axisLineExtra.attr({stroke:b.lineColor,"stroke-width":c}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(b){b.render()})}});var F={afterGetOffset:function(){(this.columns||
[]).forEach(function(b){b.getOffset()})},afterInit:function(){var b=this.chart,d=this.userOptions,g=this.options;g=g&&B(g.grid)?g.grid:{};g.enabled&&(f(this),l(this,"labelFormatter",function(b){var d=this.axis,r=d.tickPositions,m=this.value,g=(d.isLinked?d.linkedParent:d).series[0],c=m===r[0];r=m===r[r.length-1];g=g&&e.find(g.options.data,function(b){return b[d.isXAxis?"x":"y"]===m});this.isFirst=c;this.isLast=r;this.point=g;return b.call(this)}));if(g.columns)for(var C=this.columns=[],t=this.columnIndex=
0;++t<g.columns.length;){var k=p(d,g.columns[g.columns.length-t-1],{linkedTo:0,type:"category"});delete k.grid.columns;k=new c(this.chart,k,!0);k.isColumn=!0;k.columnIndex=t;n(b.axes,k);n(b[this.coll],k);C.push(k)}},afterSetOptions:function(b){b=(b=b.userOptions)&&B(b.grid)?b.grid:{};var d=b.columns;b.enabled&&d&&p(!0,this.options,d[d.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(b){b.setScale()})},destroy:function(b){(this.columns||[]).forEach(function(d){d.destroy(b.keepEvents)})},
init:function(b){var d=(b=b.userOptions)&&B(b.grid)?b.grid:{};d.enabled&&x(d.borderColor)&&(b.tickColor=b.lineColor=d.borderColor)}};Object.keys(F).forEach(function(b){u(c,b,F[b])});u(q,"afterSetChartSize",function(){this.axes.forEach(function(b){(b.columns||[]).forEach(function(b){b.setAxisSize();b.setAxisTranslation()})})})});I(n,"modules/static-scale.src.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(e,a){var A=a.addEvent,u=a.defined,x=a.isNumber,n=a.pick;a=e.Chart;A(e.Axis,"afterSetOptions",
function(){var a=this.chart.options&&this.chart.options.chart;!this.horiz&&x(this.options.staticScale)&&(!a.height||a.scrollablePlotArea&&a.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});a.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(a){var e=a.chart,p=!!e.initiatedScale&&e.options.animation,w=a.options.staticScale;if(a.staticScale&&u(a.min)){var k=n(a.unitLength,a.max+a.tickInterval-a.min)*w;k=Math.max(k,w);
w=k-e.plotHeight;1<=Math.abs(w)&&(e.plotHeight=k,e.redrawTrigger="adjustHeight",e.setSize(void 0,e.chartHeight+w,p));a.series.forEach(function(k){(k=k.sharedClipKey&&e[k.sharedClipKey])&&k.attr({height:e.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};A(a,"render",a.prototype.adjustHeight)});I(n,"mixins/tree-series.js",[n["parts/Color.js"],n["parts/Utilities.js"]],function(e,a){var A=a.extend,u=a.isArray,x=a.isNumber,n=a.isObject,D=a.merge,z=a.pick;return{getColor:function(a,w){var k=
w.index,l=w.mapOptionsToLevel,v=w.parentColor,p=w.parentColorIndex,q=w.series,c=w.colors,f=w.siblings,t=q.points,F=q.chart.options.chart,b;if(a){t=t[a.i];a=l[a.level]||{};if(l=t&&a.colorByPoint){var d=t.index%(c?c.length:F.colorCount);var g=c&&c[d]}if(!q.chart.styledMode){c=t&&t.options.color;F=a&&a.color;if(b=v)b=(b=a&&a.colorVariation)&&"brightness"===b.key?e.parse(v).brighten(k/f*b.to).get():v;b=z(c,F,g,b,q.color)}var C=z(t&&t.options.colorIndex,a&&a.colorIndex,d,p,w.colorIndex)}return{color:b,
colorIndex:C}},getLevelOptions:function(a){var e=null;if(n(a)){e={};var k=x(a.from)?a.from:1;var l=a.levels;var v={};var p=n(a.defaults)?a.defaults:{};u(l)&&(v=l.reduce(function(a,c){if(n(c)&&x(c.level)){var f=D({},c);var t="boolean"===typeof f.levelIsConstant?f.levelIsConstant:p.levelIsConstant;delete f.levelIsConstant;delete f.level;c=c.level+(t?0:k-1);n(a[c])?A(a[c],f):a[c]=f}return a},{}));l=x(a.to)?a.to:1;for(a=0;a<=l;a++)e[a]=D({},p,n(v[a])?v[a]:{})}return e},setTreeValues:function l(a,k){var v=
k.before,e=k.idRoot,q=k.mapIdToNode[e],c=k.points[a.i],f=c&&c.options||{},t=0,F=[];A(a,{levelDynamic:a.level-(("boolean"===typeof k.levelIsConstant?k.levelIsConstant:1)?0:q.level),name:z(c&&c.name,""),visible:e===a.id||("boolean"===typeof k.visible?k.visible:!1)});"function"===typeof v&&(a=v(a,k));a.children.forEach(function(b,d){var g=A({},k);A(g,{index:d,siblings:a.children.length,visible:a.visible});b=l(b,g);F.push(b);b.visible&&(t+=b.val)});a.visible=0<t||a.visible;v=z(f.value,t);A(a,{children:F,
childrenTotal:t,isLeaf:a.visible&&!t,val:v});return a},updateRootId:function(a){if(n(a)){var k=n(a.options)?a.options:{};k=z(a.rootNode,k.rootId,"");n(a.userOptions)&&(a.userOptions.rootId=k);a.rootNode=k}return k}}});I(n,"parts-gantt/Tree.js",[n["parts/Utilities.js"]],function(e){var a=e.extend,A=e.isNumber,u=e.pick,n=function(a,e){var p=a.reduce(function(a,k){var l=u(k.parent,"");"undefined"===typeof a[l]&&(a[l]=[]);a[l].push(k);return a},{});Object.keys(p).forEach(function(a,k){var l=p[a];""!==
a&&-1===e.indexOf(a)&&(l.forEach(function(a){k[""].push(a)}),delete k[a])});return p},G=function(e,n,p,w,k,l){var v=0,B=0,q=l&&l.after,c=l&&l.before;n={data:w,depth:p-1,id:e,level:p,parent:n};var f,t;"function"===typeof c&&c(n,l);c=(k[e]||[]).map(function(c){var b=G(c.id,e,p+1,c,k,l),d=c.start;c=!0===c.milestone?d:c.end;f=!A(f)||d<f?d:f;t=!A(t)||c>t?c:t;v=v+1+b.descendants;B=Math.max(b.height+1,B);return b});w&&(w.start=u(w.start,f),w.end=u(w.end,t));a(n,{children:c,descendants:v,height:B});"function"===
typeof q&&q(n,l);return n};return{getListOfParents:n,getNode:G,getTree:function(a,e){var p=a.map(function(a){return a.id});a=n(a,p);return G("",null,1,null,a,e)}}});I(n,"modules/broken-axis.src.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(e,a){var n=a.addEvent,u=a.extend,x=a.fireEvent,G=a.isArray,D=a.pick,z=e.find,p=e.Axis;a=e.Series;var w=function(a,l){return z(l,function(k){return k.from<a&&a<k.to})};u(p.prototype,{isInBreak:function(a,l){var k=a.repeat||Infinity,e=a.from,q=a.to-
a.from;l=l>=e?(l-e)%k:k-(e-l)%k;return a.inclusive?l<=q:l<q&&0!==l},isInAnyBreak:function(a,l){var k=this.options.breaks,e=k&&k.length,q;if(e){for(;e--;)if(this.isInBreak(k[e],a)){var c=!0;q||(q=D(k[e].showPoints,!this.isXAxis))}var f=c&&l?c&&!q:c}return f}});n(p,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});n(p,"afterSetTickPositions",function(){if(this.isBroken){var a=this.tickPositions,l=this.tickPositions.info,e=[],p;for(p=0;p<a.length;p++)this.isInAnyBreak(a[p])||
e.push(a[p]);this.tickPositions=e;this.tickPositions.info=l}});n(p,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});p.prototype.setBreaks=function(a,e){function k(c){var f=c,a;for(a=0;a<q.breakArray.length;a++){var b=q.breakArray[a];if(b.to<=c)f-=b.len;else if(b.from>=c)break;else if(q.isInBreak(b,c)){f-=c-b.from;break}}return f}function l(c){var f;for(f=0;f<q.breakArray.length;f++){var a=q.breakArray[f];if(a.from>=c)break;else a.to<c?c+=a.len:q.isInBreak(a,c)&&(c+=a.len)}return c}
var q=this,c=G(a)&&!!a.length;q.isDirty=q.isBroken!==c;q.isBroken=c;q.options.breaks=q.userOptions.breaks=a;q.forceRedraw=!0;q.series.forEach(function(c){c.isDirty=!0});c||q.val2lin!==k||(delete q.val2lin,delete q.lin2val);c&&(q.userOptions.ordinal=!1,q.val2lin=k,q.lin2val=l,q.setExtremes=function(c,a,k,b,d){if(this.isBroken){for(var g,f=this.options.breaks;g=w(c,f);)c=g.to;for(;g=w(a,f);)a=g.from;a<c&&(a=c)}p.prototype.setExtremes.call(this,c,a,k,b,d)},q.setAxisTranslation=function(c){p.prototype.setAxisTranslation.call(this,
c);this.unitLength=null;if(this.isBroken){c=q.options.breaks;var f=[],a=[],b=0,d,g=q.userMin||q.min,C=q.userMax||q.max,k=D(q.pointRangePadding,0),e;c.forEach(function(b){d=b.repeat||Infinity;q.isInBreak(b,g)&&(g+=b.to%d-g%d);q.isInBreak(b,C)&&(C-=C%d-b.from%d)});c.forEach(function(b){h=b.from;for(d=b.repeat||Infinity;h-d>g;)h-=d;for(;h<g;)h+=d;for(e=h;e<C;e+=d)f.push({value:e,move:"in"}),f.push({value:e+(b.to-b.from),move:"out",size:b.breakSize})});f.sort(function(b,d){return b.value===d.value?("in"===
b.move?0:1)-("in"===d.move?0:1):b.value-d.value});var m=0;var h=g;f.forEach(function(d){m+="in"===d.move?1:-1;1===m&&"in"===d.move&&(h=d.value);0===m&&(a.push({from:h,to:d.value,len:d.value-h-(d.size||0)}),b+=d.value-h-(d.size||0))});q.breakArray=a;q.unitLength=C-g-b+k;x(q,"afterBreaks");q.staticScale?q.transA=q.staticScale:q.unitLength&&(q.transA*=(C-q.min+k)/q.unitLength);k&&(q.minPixelPadding=q.transA*q.minPointOffset);q.min=g;q.max=C}});D(e,!0)&&this.chart.redraw()};n(a,"afterGeneratePoints",
function(){var a=this.options.connectNulls,e=this.points,v=this.xAxis,p=this.yAxis;if(this.isDirty)for(var q=e.length;q--;){var c=e[q],f=!(null===c.y&&!1===a)&&(v&&v.isInAnyBreak(c.x,!0)||p&&p.isInAnyBreak(c.y,!0));c.visible=f?!1:!1!==c.options.visible}});n(a,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,D(this.pointArrayMap,["y"]))});e.Series.prototype.drawBreaks=function(a,e){var k=this,l=k.points,q,c,f,t;a&&e.forEach(function(e){q=a.breakArray||[];c=a.isXAxis?
a.min:D(k.options.threshold,a.min);l.forEach(function(b){t=D(b["stack"+e.toUpperCase()],b[e]);q.forEach(function(d){f=!1;if(c<d.from&&t>d.to||c>d.from&&t<d.from)f="pointBreak";else if(c<d.from&&t>d.from&&t<d.to||c>d.from&&t>d.to&&t<d.from)f="pointInBreak";f&&x(a,f,{point:b,brk:d})})})})};e.Series.prototype.gappedPath=function(){var a=this.currentDataGrouping,l=a&&a.gapSize;a=this.options.gapSize;var v=this.points.slice(),p=v.length-1,q=this.yAxis,c;if(a&&0<p)for("value"!==this.options.gapUnit&&(a*=
this.basePointRange),l&&l>a&&l>=this.basePointRange&&(a=l),c=void 0;p--;)c&&!1!==c.visible||(c=v[p+1]),l=v[p],!1!==c.visible&&!1!==l.visible&&(c.x-l.x>a&&(c=(l.x+c.x)/2,v.splice(p+1,0,{isNull:!0,x:c}),this.options.stacking&&(c=q.stacks[this.stackKey][c]=new e.StackItem(q,q.options.stackLabels,!1,c,this.stack),c.total=0)),c=l);return this.getGraphPath(v)}});I(n,"parts-gantt/TreeGrid.js",[n["parts/Globals.js"],n["mixins/tree-series.js"],n["parts/Tick.js"],n["parts-gantt/Tree.js"],n["parts/Utilities.js"]],
function(e,a,n,u,x){var A=x.addEvent,D=x.defined,z=x.fireEvent,p=x.extend,w=x.isNumber,k=x.isString,l=x.merge,v=x.pick,B=x.wrap,q=function(b){return Array.prototype.slice.call(b,1)},c=e.find,f=a.getLevelOptions,t=function(b){return x.isObject(b,!0)};e=e.Axis;a=function(b,d){var h;for(h in d)if(Object.hasOwnProperty.call(d,h)){var c=d[h];B(b,h,c)}};var F=function(b,d){var h=b.collapseStart;b=b.collapseEnd;b>=d&&(h-=.5);return{from:h,to:b,showPoints:!1}},b=function(b){return Object.keys(b.mapOfPosToGridNode).reduce(function(d,
h){h=+h;b.min<=h&&b.max>=h&&!b.isInAnyBreak(h)&&d.push(h);return d},[])},d=function(b,d){var h=b.options.breaks||[],c=F(d,b.max);return h.some(function(b){return b.from===c.from&&b.to===c.to})},g=function(b,d){var h=b.options.breaks||[];b=F(d,b.max);h.push(b);return h},C=function(b,d){var h=b.options.breaks||[],c=F(d,b.max);return h.reduce(function(b,d){d.to===c.to&&d.from===c.from||b.push(d);return b},[])},R=function(b,d){var h=b.labelIcon,c=!h,m=d.renderer,g=d.xy,r=d.options,f=r.width,a=r.height,
C=g.x-f/2-r.padding;g=g.y-a/2;var t=d.collapsed?90:180,k=d.show&&w(g);c&&(b.labelIcon=h=m.path(m.symbols[r.type](r.x,r.y,f,a)).addClass("highcharts-label-icon").add(d.group));k||h.attr({y:-9999});m.styledMode||h.attr({"stroke-width":1,fill:v(d.color,"#666666")}).css({cursor:"pointer",stroke:r.lineColor,strokeWidth:r.lineWidth});h[c?"attr":"animate"]({translateX:C,translateY:g,rotation:t})},P=function(b,d,m){var h=[],g=[],r={},f={},a=-1,y="boolean"===typeof d?d:!1;b=u.getTree(b,{after:function(b){b=
f[b.pos];var d=0,h=0;b.children.forEach(function(b){h+=b.descendants+1;d=Math.max(b.height+1,d)});b.descendants=h;b.height=d;b.collapsed&&g.push(b)},before:function(b){var d=t(b.data)?b.data:{},m=k(d.name)?d.name:"",g=r[b.parent];g=t(g)?f[g.pos]:null;var E=function(b){return b.name===m},H;y&&t(g)&&(H=c(g.children,E))?(E=H.pos,H.nodes.push(b)):E=a++;f[E]||(f[E]=H={depth:g?g.depth+1:0,name:m,nodes:[b],children:[],pos:E},-1!==E&&h.push(m),t(g)&&g.children.push(H));k(b.id)&&(r[b.id]=b);!0===d.collapsed&&
(H.collapsed=!0);b.pos=E}});f=function(b,d){var h=function(b,c,m){var g=c+(-1===c?0:d-1),r=(g-c)/2,f=c+r;b.nodes.forEach(function(b){var d=b.data;t(d)&&(d.y=c+d.seriesIndex,delete d.seriesIndex);b.pos=f});m[f]=b;b.pos=f;b.tickmarkOffset=r+.5;b.collapseStart=g+.5;b.children.forEach(function(b){h(b,g+1,m);g=b.collapseEnd-.5});b.collapseEnd=g+.5;return m};return h(b["-1"],-1,{})}(f,m);return{categories:h,mapOfIdToNode:r,mapOfPosToGridNode:f,collapsedNodes:g,tree:b}},m=function(b){b.target.axes.filter(function(b){return"treegrid"===
b.options.type}).forEach(function(d){var h=d.options||{},c=h.labels,m,r=h.uniqueNames,a=0;if(!d.mapOfPosToGridNode||d.series.some(function(b){return!b.hasRendered||b.isDirtyData||b.isDirty})){h=d.series.reduce(function(b,d){d.visible&&(d.options.data.forEach(function(d){t(d)&&(d.seriesIndex=a,b.push(d))}),!0===r&&a++);return b},[]);var C=P(h,r,!0===r?a:1);d.categories=C.categories;d.mapOfPosToGridNode=C.mapOfPosToGridNode;d.hasNames=!0;d.tree=C.tree;d.series.forEach(function(b){var d=b.options.data.map(function(b){return t(b)?
l(b):b});b.visible&&b.setData(d,!1)});d.mapOptionsToLevel=f({defaults:c,from:1,levels:c.levels,to:d.tree.height});"beforeRender"===b.type&&(m=A(d,"foundExtremes",function(){C.collapsedNodes.forEach(function(b){b=g(d,b);d.setBreaks(b,!1)});m()}))}})};a(e.prototype,{init:function(b,d,c){var h="treegrid"===c.type;h&&(A(d,"beforeRender",m),A(d,"beforeRedraw",m),c=l({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,
width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));b.apply(this,[d,c]);h&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(b){var d=this.options,h=d&&d.labels;d=h&&w(h.indentation)?d.labels.indentation:0;h=b.apply(this,q(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var c=this.mapOfPosToGridNode[-1].height;h.width+=d*(c-1)}return h},generateTick:function(b,d){var h=t(this.mapOptionsToLevel)?this.mapOptionsToLevel:
{},c=this.ticks,m=c[d],g;if("treegrid"===this.options.type){var f=this.mapOfPosToGridNode[d];(h=h[f.depth])&&(g={labels:h});m?(m.parameters.category=f.name,m.options=g,m.addLabel()):c[d]=new n(this,d,null,void 0,{category:f.name,tickmarkOffset:f.tickmarkOffset,options:g})}else b.apply(this,q(arguments))},setTickInterval:function(d){var h=this.options;"treegrid"===h.type?(this.min=v(this.userMin,h.min,this.dataMin),this.max=v(this.userMax,h.max,this.dataMax),z(this,"foundExtremes"),this.setAxisTranslation(!0),
this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?b(this):[]):d.apply(this,q(arguments))}});a(n.prototype,{getLabelPosition:function(b,d,c,m,g,f,a,C,k){var h=v(this.options&&this.options.labels,f);f=this.pos;var r=this.axis,E="treegrid"===r.options.type;b=b.apply(this,[d,c,m,g,h,a,C,k]);E&&(d=h&&t(h.symbol)?h.symbol:{},h=h&&w(h.indentation)?h.indentation:0,f=(f=(r=r.mapOfPosToGridNode)&&r[f])&&f.depth||1,b.x+=d.width+2*d.padding+(f-1)*h);return b},renderLabel:function(b){var h=
this,c=h.pos,m=h.axis,g=h.label,f=m.mapOfPosToGridNode,a=m.options,C=v(h.options&&h.options.labels,a&&a.labels),k=C&&t(C.symbol)?C.symbol:{},e=(f=f&&f[c])&&f.depth;a="treegrid"===a.type;var l=!(!g||!g.element),p=-1<m.tickPositions.indexOf(c);c=m.chart.styledMode;a&&f&&l&&g.addClass("highcharts-treegrid-node-level-"+e);b.apply(h,q(arguments));a&&f&&l&&0<f.descendants&&(m=d(m,f),R(h,{color:!c&&g.styles.color,collapsed:m,group:g.parentGroup,options:k,renderer:g.renderer,show:p,xy:g.xy}),k="highcharts-treegrid-node-"+
(m?"expanded":"collapsed"),g.addClass("highcharts-treegrid-node-"+(m?"collapsed":"expanded")).removeClass(k),c||g.css({cursor:"pointer"}),[g,h.labelIcon].forEach(function(b){b.attachedTreeGridEvents||(A(b.element,"mouseover",function(){g.addClass("highcharts-treegrid-node-active");g.renderer.styledMode||g.css({textDecoration:"underline"})}),A(b.element,"mouseout",function(){var b=D(C.style)?C.style:{};g.removeClass("highcharts-treegrid-node-active");g.renderer.styledMode||g.css({textDecoration:b.textDecoration})}),
A(b.element,"click",function(){h.toggleCollapse()}),b.attachedTreeGridEvents=!0)}))}});p(n.prototype,{collapse:function(b){var d=this.axis,h=g(d,d.mapOfPosToGridNode[this.pos]);d.setBreaks(h,v(b,!0))},expand:function(b){var d=this.axis,h=C(d,d.mapOfPosToGridNode[this.pos]);d.setBreaks(h,v(b,!0))},toggleCollapse:function(b){var h=this.axis;var c=h.mapOfPosToGridNode[this.pos];c=d(h,c)?C(h,c):g(h,c);h.setBreaks(c,v(b,!0))}});e.prototype.utils={getNode:u.getNode}});I(n,"parts-gantt/PathfinderAlgorithms.js",
[n["parts/Utilities.js"]],function(e){function a(a,e,p){p=p||0;var k=a.length-1;e-=1e-7;for(var l,c;p<=k;)if(l=k+p>>1,c=e-a[l].xMin,0<c)p=l+1;else if(0>c)k=l-1;else return l;return 0<p?p-1:0}function n(k,e){for(var l=a(k,e.x+1)+1;l--;){var p;if(p=k[l].xMax>=e.x)p=k[l],p=e.x<=p.xMax&&e.x>=p.xMin&&e.y<=p.yMax&&e.y>=p.yMin;if(p)return l}return-1}function u(a){var e=[];if(a.length){e.push("M",a[0].start.x,a[0].start.y);for(var k=0;k<a.length;++k)e.push("L",a[k].end.x,a[k].end.y)}return e}function x(a,
e){a.yMin=p(a.yMin,e.yMin);a.yMax=z(a.yMax,e.yMax);a.xMin=p(a.xMin,e.xMin);a.xMax=z(a.xMax,e.xMax)}var G=e.extend,D=e.pick,z=Math.min,p=Math.max,w=Math.abs;return{straight:function(a,e){return{path:["M",a.x,a.y,"L",e.x,e.y],obstacles:[{start:a,end:e}]}},simpleConnect:G(function(a,e,p){function k(b,d,c,a,m){b={x:b.x,y:b.y};b[d]=c[a||d]+(m||0);return b}function l(b,d,c){var g=w(d[c]-b[c+"Min"])>w(d[c]-b[c+"Max"]);return k(d,c,b,c+(g?"Max":"Min"),g?1:-1)}var c=[],f=D(p.startDirectionX,w(e.x-a.x)>w(e.y-
a.y))?"x":"y",t=p.chartObstacles,F=n(t,a);p=n(t,e);if(-1<p){var b=t[p];p=l(b,e,f);b={start:p,end:e};var d=p}else d=e;-1<F&&(t=t[F],p=l(t,a,f),c.push({start:a,end:p}),p[f]>=a[f]===p[f]>=d[f]&&(f="y"===f?"x":"y",e=a[f]<e[f],c.push({start:p,end:k(p,f,t,f+(e?"Max":"Min"),e?1:-1)}),f="y"===f?"x":"y"));a=c.length?c[c.length-1].end:a;p=k(a,f,d);c.push({start:a,end:p});f=k(p,"y"===f?"x":"y",d);c.push({start:p,end:f});c.push(b);return{path:u(c),obstacles:c}},{requiresObstacles:!0}),fastAvoid:G(function(e,
l,v){function k(b,d,c){var m,g=b.x<d.x?1:-1;if(b.x<d.x){var f=b;var r=d}else f=d,r=b;if(b.y<d.y){var e=b;var C=d}else e=d,C=b;for(m=0>g?z(a(h,r.x),h.length-1):0;h[m]&&(0<g&&h[m].xMin<=r.x||0>g&&h[m].xMax>=f.x);){if(h[m].xMin<=r.x&&h[m].xMax>=f.x&&h[m].yMin<=C.y&&h[m].yMax>=e.y)return c?{y:b.y,x:b.x<d.x?h[m].xMin-1:h[m].xMax+1,obstacle:h[m]}:{x:b.x,y:b.y<d.y?h[m].yMin-1:h[m].yMax+1,obstacle:h[m]};m+=g}return d}function q(b,d,h,c,m){var g=m.soft,a=m.hard,f=c?"x":"y",r={x:d.x,y:d.y},e={x:d.x,y:d.y};
m=b[f+"Max"]>=g[f+"Max"];g=b[f+"Min"]<=g[f+"Min"];var C=b[f+"Max"]>=a[f+"Max"];a=b[f+"Min"]<=a[f+"Min"];var E=w(b[f+"Min"]-d[f]),y=w(b[f+"Max"]-d[f]);h=10>w(E-y)?d[f]<h[f]:y<E;e[f]=b[f+"Min"];r[f]=b[f+"Max"];b=k(d,e,c)[f]!==e[f];d=k(d,r,c)[f]!==r[f];h=b?d?h:!0:d?!1:h;h=g?m?h:!0:m?!1:h;return a?C?h:!0:C?!1:h}function c(b,g,f){if(b.x===g.x&&b.y===g.y)return[];var a=f?"x":"y",r=v.obstacleOptions.margin;var e={soft:{xMin:C,xMax:R,yMin:P,yMax:m},hard:v.hardBounds};var y=n(h,b);if(-1<y){y=h[y];e=q(y,b,
g,f,e);x(y,v.hardBounds);var t=f?{y:b.y,x:y[e?"xMax":"xMin"]+(e?1:-1)}:{x:b.x,y:y[e?"yMax":"yMin"]+(e?1:-1)};var E=n(h,t);-1<E&&(E=h[E],x(E,v.hardBounds),t[a]=e?p(y[a+"Max"]-r+1,(E[a+"Min"]+y[a+"Max"])/2):z(y[a+"Min"]+r-1,(E[a+"Max"]+y[a+"Min"])/2),b.x===t.x&&b.y===t.y?(d&&(t[a]=e?p(y[a+"Max"],E[a+"Max"])+1:z(y[a+"Min"],E[a+"Min"])-1),d=!d):d=!1);b=[{start:b,end:t}]}else a=k(b,{x:f?g.x:b.x,y:f?b.y:g.y},f),b=[{start:b,end:{x:a.x,y:a.y}}],a[f?"x":"y"]!==g[f?"x":"y"]&&(e=q(a.obstacle,a,g,!f,e),x(a.obstacle,
v.hardBounds),e={x:f?a.x:a.obstacle[e?"xMax":"xMin"]+(e?1:-1),y:f?a.obstacle[e?"yMax":"yMin"]+(e?1:-1):a.y},f=!f,b=b.concat(c({x:a.x,y:a.y},e,f)));return b=b.concat(c(b[b.length-1].end,g,!f))}function f(b,d,h){var c=z(b.xMax-d.x,d.x-b.xMin)<z(b.yMax-d.y,d.y-b.yMin);h=q(b,d,h,c,{soft:v.hardBounds,hard:v.hardBounds});return c?{y:d.y,x:b[h?"xMax":"xMin"]+(h?1:-1)}:{x:d.x,y:b[h?"yMax":"yMin"]+(h?1:-1)}}var t=D(v.startDirectionX,w(l.x-e.x)>w(l.y-e.y)),F=t?"x":"y",b=[],d=!1,g=v.obstacleMetrics,C=z(e.x,
l.x)-g.maxWidth-10,R=p(e.x,l.x)+g.maxWidth+10,P=z(e.y,l.y)-g.maxHeight-10,m=p(e.y,l.y)+g.maxHeight+10,h=v.chartObstacles;var r=a(h,C);g=a(h,R);h=h.slice(r,g+1);if(-1<(g=n(h,l))){var y=f(h[g],l,e);b.push({end:l,start:y});l=y}for(;-1<(g=n(h,l));)r=0>l[F]-e[F],y={x:l.x,y:l.y},y[F]=h[g][r?F+"Max":F+"Min"]+(r?1:-1),b.push({end:l,start:y}),l=y;e=c(e,l,t);e=e.concat(b.reverse());return{path:u(e),obstacles:e}},{requiresObstacles:!0})}});I(n,"parts-gantt/ArrowSymbols.js",[n["parts/Globals.js"]],function(e){e.SVGRenderer.prototype.symbols.arrow=
function(a,e,n,x){return["M",a,e+x/2,"L",a+n,e,"L",a,e+x/2,"L",a+n,e+x]};e.SVGRenderer.prototype.symbols["arrow-half"]=function(a,n,u,x){return e.SVGRenderer.prototype.symbols.arrow(a,n,u/2,x)};e.SVGRenderer.prototype.symbols["triangle-left"]=function(a,e,n,x){return["M",a+n,e,"L",a,e+x/2,"L",a+n,e+x,"Z"]};e.SVGRenderer.prototype.symbols["arrow-filled"]=e.SVGRenderer.prototype.symbols["triangle-left"];e.SVGRenderer.prototype.symbols["triangle-left-half"]=function(a,n,u,x){return e.SVGRenderer.prototype.symbols["triangle-left"](a,
n,u/2,x)};e.SVGRenderer.prototype.symbols["arrow-filled-half"]=e.SVGRenderer.prototype.symbols["triangle-left-half"]});I(n,"parts-gantt/Pathfinder.js",[n["parts/Globals.js"],n["parts/Utilities.js"],n["parts-gantt/PathfinderAlgorithms.js"]],function(e,a,n){function u(b){var d=b.shapeArgs;return d?{xMin:d.x,xMax:d.x+d.width,yMin:d.y,yMax:d.y+d.height}:(d=b.graphic&&b.graphic.getBBox())?{xMin:b.plotX-d.width/2,xMax:b.plotX+d.width/2,yMin:b.plotY-d.height/2,yMax:b.plotY+d.height/2}:null}function x(b){for(var d=
b.length,c=0,a,f,e=[],m=function(b,d,c){c=q(c,10);var h=b.yMax+c>d.yMin-c&&b.yMin-c<d.yMax+c,g=b.xMax+c>d.xMin-c&&b.xMin-c<d.xMax+c,a=h?b.xMin>d.xMax?b.xMin-d.xMax:d.xMin-b.xMax:Infinity,f=g?b.yMin>d.yMax?b.yMin-d.yMax:d.yMin-b.yMax:Infinity;return g&&h?c?m(b,d,Math.floor(c/2)):Infinity:F(a,f)};c<d;++c)for(a=c+1;a<d;++a)f=m(b[c],b[a]),80>f&&e.push(f);e.push(80);return t(Math.floor(e.sort(function(b,d){return b-d})[Math.floor(e.length/10)]/2-1),1)}function A(b,d,c){this.init(b,d,c)}function D(b){this.init(b)}
function z(b){if(b.options.pathfinder||b.series.reduce(function(b,c){c.options&&v(!0,c.options.connectors=c.options.connectors||{},c.options.pathfinder);return b||c.options&&c.options.pathfinder},!1))v(!0,b.options.connectors=b.options.connectors||{},b.options.pathfinder),k('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}var p=a.addEvent,w=a.defined,k=a.error,l=a.extend,v=a.merge,B=a.objectEach,q=a.pick,c=a.splat,f=e.deg2rad,t=Math.max,F=Math.min;
l(e.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});A.prototype={init:function(b,d,c){this.fromPoint=b;this.toPoint=d;this.options=c;this.chart=b.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(b,d,c){var g=this.chart,a=g.styledMode,f=g.pathfinder,m=!g.options.chart.forExport&&!1!==c,h=this.graphics&&this.graphics.path;
f.group||(f.group=g.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(g.seriesGroup));f.group.translate(g.plotLeft,g.plotTop);h&&h.renderer||(h=g.renderer.path().add(f.group),a||h.attr({opacity:0}));h.attr(d);b={d:b};a||(b.opacity=1);h[m?"animate":"attr"](b,c);this.graphics=this.graphics||{};this.graphics.path=h},addMarker:function(b,d,c){var a=this.fromPoint.series.chart,g=a.pathfinder;a=a.renderer;var e="start"===b?this.fromPoint:this.toPoint,m=e.getPathfinderAnchorPoint(d);
if(d.enabled){c="start"===b?{x:c[4],y:c[5]}:{x:c[c.length-5],y:c[c.length-4]};c=e.getRadiansToVector(c,m);m=e.getMarkerVector(c,d.radius,m);c=-c/f;if(d.width&&d.height){var h=d.width;var r=d.height}else h=r=2*d.radius;this.graphics=this.graphics||{};m={x:m.x-h/2,y:m.y-r/2,width:h,height:r,rotation:c,rotationOriginX:m.x,rotationOriginY:m.y};this.graphics[b]?this.graphics[b].animate(m):(this.graphics[b]=a.symbol(d.symbol).addClass("highcharts-point-connecting-path-"+b+"-marker").attr(m).add(g.group),
a.styledMode||this.graphics[b].attr({fill:d.color||this.fromPoint.color,stroke:d.lineColor,"stroke-width":d.lineWidth,opacity:0}).animate({opacity:1},e.series.options.animation))}},getPath:function(b){var d=this.pathfinder,c=this.chart,a=d.algorithms[b.type],f=d.chartObstacles;if("function"!==typeof a)k('"'+b.type+'" is not a Pathfinder algorithm.');else return a.requiresObstacles&&!f&&(f=d.chartObstacles=d.getChartObstacles(b),c.options.connectors.algorithmMargin=b.algorithmMargin,d.chartObstacleMetrics=
d.getObstacleMetrics(f)),a(this.fromPoint.getPathfinderAnchorPoint(b.startMarker),this.toPoint.getPathfinderAnchorPoint(b.endMarker),v({chartObstacles:f,lineObstacles:d.lineObstacles||[],obstacleMetrics:d.chartObstacleMetrics,hardBounds:{xMin:0,xMax:c.plotWidth,yMin:0,yMax:c.plotHeight},obstacleOptions:{margin:b.algorithmMargin},startDirectionX:d.getAlgorithmStartDirection(b.startMarker)},b))},render:function(){var b=this.fromPoint,d=b.series,c=d.chart,a=c.pathfinder,f=v(c.options.connectors,d.options.connectors,
b.options.connectors,this.options),e={};c.styledMode||(e.stroke=f.lineColor||b.color,e["stroke-width"]=f.lineWidth,f.dashStyle&&(e.dashstyle=f.dashStyle));e["class"]="highcharts-point-connecting-path highcharts-color-"+b.colorIndex;f=v(e,f);w(f.marker.radius)||(f.marker.radius=F(t(Math.ceil((f.algorithmMargin||8)/2)-1,1),5));b=this.getPath(f);c=b.path;b.obstacles&&(a.lineObstacles=a.lineObstacles||[],a.lineObstacles=a.lineObstacles.concat(b.obstacles));this.renderPath(c,e,d.options.animation);this.addMarker("start",
v(f.marker,f.startMarker),c);this.addMarker("end",v(f.marker,f.endMarker),c)},destroy:function(){this.graphics&&(B(this.graphics,function(b){b.destroy()}),delete this.graphics)}};D.prototype={algorithms:n,init:function(b){this.chart=b;this.connections=[];p(b,"redraw",function(){this.pathfinder.update()})},update:function(b){var d=this.chart,f=this,a=f.connections;f.connections=[];d.series.forEach(function(b){b.visible&&!b.options.isInternal&&b.points.forEach(function(b){var h,m=b.options&&b.options.connect&&
c(b.options.connect);b.visible&&!1!==b.isInside&&m&&m.forEach(function(c){h=d.get("string"===typeof c?c:c.to);h instanceof e.Point&&h.series.visible&&h.visible&&!1!==h.isInside&&f.connections.push(new A(b,h,"string"===typeof c?{}:c))})})});for(var t=0,p,m,h=a.length,r=f.connections.length;t<h;++t){m=!1;for(p=0;p<r;++p)if(a[t].fromPoint===f.connections[p].fromPoint&&a[t].toPoint===f.connections[p].toPoint){f.connections[p].graphics=a[t].graphics;m=!0;break}m||a[t].destroy()}delete this.chartObstacles;
delete this.lineObstacles;f.renderConnections(b)},renderConnections:function(b){b?this.chart.series.forEach(function(b){var d=function(){var d=b.chart.pathfinder;(d&&d.connections||[]).forEach(function(d){d.fromPoint&&d.fromPoint.series===b&&d.render()});b.pathfinderRemoveRenderEvent&&(b.pathfinderRemoveRenderEvent(),delete b.pathfinderRemoveRenderEvent)};!1===b.options.animation?d():b.pathfinderRemoveRenderEvent=p(b,"afterAnimate",d)}):this.connections.forEach(function(b){b.render()})},getChartObstacles:function(b){for(var d=
[],c=this.chart.series,f=q(b.algorithmMargin,0),a,e=0,m=c.length;e<m;++e)if(c[e].visible&&!c[e].options.isInternal)for(var h=0,r=c[e].points.length,t;h<r;++h)t=c[e].points[h],t.visible&&(t=u(t))&&d.push({xMin:t.xMin-f,xMax:t.xMax+f,yMin:t.yMin-f,yMax:t.yMax+f});d=d.sort(function(b,d){return b.xMin-d.xMin});w(b.algorithmMargin)||(a=b.algorithmMargin=x(d),d.forEach(function(b){b.xMin-=a;b.xMax+=a;b.yMin-=a;b.yMax+=a}));return d},getObstacleMetrics:function(b){for(var d=0,c=0,f,a,e=b.length;e--;)f=b[e].xMax-
b[e].xMin,a=b[e].yMax-b[e].yMin,d<f&&(d=f),c<a&&(c=a);return{maxHeight:c,maxWidth:d}},getAlgorithmStartDirection:function(b){var d="top"!==b.verticalAlign&&"bottom"!==b.verticalAlign;return"left"!==b.align&&"right"!==b.align?d?void 0:!1:d?!0:void 0}};e.Connection=A;e.Pathfinder=D;l(e.Point.prototype,{getPathfinderAnchorPoint:function(b){var d=u(this);switch(b.align){case "right":var c="xMax";break;case "left":c="xMin"}switch(b.verticalAlign){case "top":var f="yMin";break;case "bottom":f="yMax"}return{x:c?
d[c]:(d.xMin+d.xMax)/2,y:f?d[f]:(d.yMin+d.yMax)/2}},getRadiansToVector:function(b,d){w(d)||(d=u(this),d={x:(d.xMin+d.xMax)/2,y:(d.yMin+d.yMax)/2});return Math.atan2(d.y-b.y,b.x-d.x)},getMarkerVector:function(b,d,c){var f=2*Math.PI,a=u(this),g=a.xMax-a.xMin,m=a.yMax-a.yMin,h=Math.atan2(m,g),e=!1;g/=2;var t=m/2,p=a.xMin+g;a=a.yMin+t;for(var k=p,l=a,H={},q=1,F=1;b<-Math.PI;)b+=f;for(;b>Math.PI;)b-=f;f=Math.tan(b);b>-h&&b<=h?(F=-1,e=!0):b>h&&b<=Math.PI-h?F=-1:b>Math.PI-h||b<=-(Math.PI-h)?(q=-1,e=!0):
q=-1;e?(k+=q*g,l+=F*g*f):(k+=m/(2*f)*q,l+=F*t);c.x!==p&&(k=c.x);c.y!==a&&(l=c.y);H.x=k+d*Math.cos(b);H.y=l-d*Math.sin(b);return H}});e.Chart.prototype.callbacks.push(function(b){!1!==b.options.connectors.enabled&&(z(b),this.pathfinder=new D(this),this.pathfinder.update(!0))})});I(n,"modules/xrange.src.js",[n["parts/Globals.js"],n["parts/Color.js"],n["parts/Utilities.js"]],function(e,a,n){var u=a.parse;a=n.addEvent;var x=n.clamp,A=n.correctFloat,D=n.defined,z=n.isNumber,p=n.isObject,w=n.merge,k=n.pick,
l=e.seriesTypes.column,v=e.find;n=e.seriesType;var B=e.Axis,q=e.Point,c=e.Series;n("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var c=this.point.partialFill;p(c)&&(c=c.amount);if(z(c)&&0<c)return A(100*c)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",
parallelArrays:["x","x2","y"],requireSorting:!1,animate:e.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:e.noop,buildKDTree:e.noop,getColumnMetrics:function(){function c(){a.series.forEach(function(b){var d=b.xAxis;b.xAxis=b.yAxis;b.yAxis=d})}var a=this.chart;c();var e=l.prototype.getColumnMetrics.call(this);c();return e},cropData:function(a,e,p,b){e=c.prototype.cropData.call(this,this.x2Data,e,p,b);e.xData=a.slice(e.start,e.end);return e},findPointIndex:function(c){var a=
this.cropped,f=this.cropStart,b=this.points,d=c.id;if(d)var g=(g=v(b,function(b){return b.id===d}))?g.index:void 0;"undefined"===typeof g&&(g=(g=v(b,function(b){return b.x===c.x&&b.x2===c.x2&&!b.touched}))?g.index:void 0);a&&z(g)&&z(f)&&g>=f&&(g-=f);return g},translatePoint:function(c){var a=this.xAxis,f=this.yAxis,b=this.columnMetrics,d=this.options,g=d.minPointLength||0,e=c.plotX,l=k(c.x2,c.x+(c.len||0)),q=a.translate(l,0,0,0,1);l=Math.abs(q-e);var m=this.chart.inverted,h=k(d.borderWidth,1)%2/2,
r=b.offset,y=Math.round(b.width);g&&(g-=l,0>g&&(g=0),e-=g/2,q+=g/2);e=Math.max(e,-10);q=x(q,-10,a.len+10);D(c.options.pointWidth)&&(r-=(Math.ceil(c.options.pointWidth)-y)/2,y=Math.ceil(c.options.pointWidth));d.pointPlacement&&z(c.plotY)&&f.categories&&(c.plotY=f.translate(c.y,0,1,0,1,d.pointPlacement));c.shapeArgs={x:Math.floor(Math.min(e,q))+h,y:Math.floor(c.plotY+r)+h,width:Math.round(Math.abs(q-e)),height:y,r:this.options.borderRadius};d=c.shapeArgs.x;g=d+c.shapeArgs.width;0>d||g>a.len?(d=x(d,
0,a.len),g=x(g,0,a.len),q=g-d,c.dlBox=w(c.shapeArgs,{x:d,width:g-d,centerX:q?q/2:null})):c.dlBox=null;d=c.tooltipPos;g=m?1:0;q=m?0:1;d[g]=x(d[g]+l/2*(a.reversed?-1:1)*(m?-1:1),0,a.len-1);d[q]=x(d[q]+b.width/2*(m?1:-1),0,f.len-1);if(b=c.partialFill)p(b)&&(b=b.amount),z(b)||(b=0),f=c.shapeArgs,c.partShapeArgs={x:f.x,y:f.y,width:f.width,height:f.height,r:this.options.borderRadius},e=Math.max(Math.round(l*b+c.plotX-e),0),c.clipRectArgs={x:a.reversed?f.x+l-e:f.x,y:f.y,width:e,height:f.height}},translate:function(){l.prototype.translate.apply(this,
arguments);this.points.forEach(function(c){this.translatePoint(c)},this)},drawPoint:function(c,a){var f=this.options,b=this.chart.renderer,d=c.graphic,g=c.shapeType,e=c.shapeArgs,t=c.partShapeArgs,l=c.clipRectArgs,m=c.partialFill,h=f.stacking&&!f.borderRadius,r=c.state,y=f.states[r||"normal"]||{},E="undefined"===typeof r?"attr":a;r=this.pointAttribs(c,r);y=k(this.chart.options.chart.animation,y.animation);if(c.isNull||!1===c.visible)d&&(c.graphic=d.destroy());else{if(d)d.rect[a](e);else c.graphic=
d=b.g("point").addClass(c.getClassName()).add(c.group||this.group),d.rect=b[g](w(e)).addClass(c.getClassName()).addClass("highcharts-partfill-original").add(d);t&&(d.partRect?(d.partRect[a](w(t)),d.partialClipRect[a](w(l))):(d.partialClipRect=b.clipRect(l.x,l.y,l.width,l.height),d.partRect=b[g](t).addClass("highcharts-partfill-overlay").add(d).clip(d.partialClipRect)));this.chart.styledMode||(d.rect[a](r,y).shadow(f.shadow,null,h),t&&(p(m)||(m={}),p(f.partialFill)&&(m=w(m,f.partialFill)),c=m.fill||
u(r.fill).brighten(-.3).get()||u(c.color||this.color).brighten(-.3).get(),r.fill=c,d.partRect[E](r,y).shadow(f.shadow,null,h)))}},drawPoints:function(){var c=this,a=c.getAnimationVerb();c.points.forEach(function(f){c.drawPoint(f,a)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var c=this.series;if(c.options.colorByPoint&&!this.options.color){var a=c.options.colors||c.chart.options.colors;var e=this.y%(a?a.length:
c.chart.options.chart.colorCount);a=a&&a[e];c.chart.styledMode||(this.color=a);this.options.colorIndex||(this.colorIndex=e)}else this.color||(this.color=c.color)},init:function(){q.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){q.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var c=q.prototype.getLabelConfig.call(this),a=this.series.yAxis.categories;c.x2=this.x2;c.yCategory=this.yCategory=
a&&a[this.y];return c},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});a(B,"afterGetSeriesExtremes",function(){var c=this.series,a;if(this.isXAxis){var e=k(this.dataMax,-Number.MAX_VALUE);c.forEach(function(b){b.x2Data&&b.x2Data.forEach(function(b){b>e&&(e=b,a=!0)})});a&&(this.dataMax=e)}});""});I(n,"parts-gantt/GanttSeries.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(e,a){var n=a.isNumber,u=a.merge,x=a.pick,G=a.splat,D=e.dateFormat;
a=e.seriesType;var z=e.seriesTypes.xrange;a("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var a=this.series,e=a.chart.tooltip,k=a.xAxis,l=a.tooltipOptions.dateTimeLabelFormats,n=k.options.startOfWeek,u=a.tooltipOptions,q=u.xDateFormat;a=this.options.milestone;var c="<b>"+(this.name||this.yCategory)+"</b>";if(u.pointFormat)return this.tooltipFormatter(u.pointFormat);q||
(q=G(e.getDateFormat(k.closestPointRange,this.start,n,l))[0]);e=D(q,this.start);k=D(q,this.end);c+="<br/>";return a?c+(e+"<br/>"):c+("Start: "+e+"<br/>End: ")+(k+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(a){z.prototype.translatePoint.call(this,a);if(a.options.milestone){var e=
a.shapeArgs;var p=e.height;a.shapeArgs={x:e.x-p/2,y:e.y,width:p,height:p}}},drawPoint:function(a,e){var k=this.options,p=this.chart.renderer,u=a.shapeArgs,w=a.plotY,q=a.graphic,c=a.selected&&"select",f=k.stacking&&!k.borderRadius;if(a.options.milestone)if(n(w)&&null!==a.y&&!1!==a.visible){u=p.symbols.diamond(u.x,u.y,u.width,u.height);if(q)q[e]({d:u});else a.graphic=p.path(u).addClass(a.getClassName(),!0).add(a.group||this.group);this.chart.styledMode||a.graphic.attr(this.pointAttribs(a,c)).shadow(k.shadow,
null,f)}else q&&(a.graphic=q.destroy());else z.prototype.drawPoint.call(this,a,e)},setData:e.Series.prototype.setData,setGanttPointAliases:function(a){function e(e,l){"undefined"!==typeof l&&(a[e]=l)}e("x",x(a.start,a.x));e("x2",x(a.end,a.x2));e("partialFill",x(a.completed,a.partialFill));e("connect",x(a.dependency,a.connect))}},u(z.prototype.pointClass.prototype,{applyOptions:function(a,n){a=u(a);e.seriesTypes.gantt.prototype.setGanttPointAliases(a);return a=z.prototype.pointClass.prototype.applyOptions.call(this,
a,n)},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});I(n,"parts-gantt/GanttChart.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(e,a){var n=a.isArray,u=a.merge,x=a.splat,G=e.Chart;e.ganttChart=function(a,z,p){var w="string"===typeof a||a.nodeName,k=z.series,l=e.getOptions(),v,A=z;z=arguments[w?1:0];n(z.xAxis)||(z.xAxis=[z.xAxis||{},{}]);z.xAxis=z.xAxis.map(function(a,c){1===
c&&(v=0);return u(l.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:v},a,{type:"datetime"})});z.yAxis=x(z.yAxis||{}).map(function(a){return u(l.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:a.categories?a.type:"treegrid"},a)});z.series=null;z=u(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1}},z,{isGantt:!0});z.series=A.series=k;z.series.forEach(function(a){a.data.forEach(function(c){e.seriesTypes.gantt.prototype.setGanttPointAliases(c)})});return w?new G(a,z,p):new G(z,z)}});
I(n,"parts/Scrollbar.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(e,a){function n(c,a,e){this.init(c,a,e)}var u=a.addEvent,x=a.correctFloat,G=a.defined,D=a.destroyObjectProperties,z=a.fireEvent,p=a.merge,w=a.pick,k=a.removeEvent;a=e.Axis;var l=e.defaultOptions,v=e.hasTouch,B,q={height:e.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",
buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};l.scrollbar=p(!0,q,l.scrollbar);e.swapXY=B=function(c,a){var f=c.length;if(a)for(a=0;a<f;a+=3){var e=c[a+1];c[a+1]=c[a+2];c[a+2]=e}return c};n.prototype={init:function(c,a,e){this.scrollbarButtons=[];this.renderer=c;this.userOptions=a;this.options=p(q,a);this.chart=e;this.size=w(this.options.size,this.options.height);a.enabled&&
(this.render(),this.initEvents(),this.addEvents())},render:function(){var c=this.renderer,a=this.options,e=this.size,k=this.chart.styledMode,b;this.group=b=c.g("scrollbar").attr({zIndex:a.zIndex,translateY:-99999}).add();this.track=c.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:a.trackBorderRadius||0,height:e,width:e}).add(b);k||this.track.attr({fill:a.trackBackgroundColor,stroke:a.trackBorderColor,"stroke-width":a.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%
2/2});this.scrollbarGroup=c.g().add(b);this.scrollbar=c.rect().addClass("highcharts-scrollbar-thumb").attr({height:e,width:e,r:a.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=c.path(B(["M",-3,e/4,"L",-3,2*e/3,"M",0,e/4,"L",0,2*e/3,"M",3,e/4,"L",3,2*e/3],a.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);k||(this.scrollbar.attr({fill:a.barBackgroundColor,stroke:a.barBorderColor,"stroke-width":a.barBorderWidth}),this.scrollbarRifles.attr({stroke:a.rifleColor,
"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(c,a,e,k){var b=this.options.vertical,d=0,f=this.rendered?"animate":"attr";this.x=c;this.y=a+this.trackBorderWidth;this.width=e;this.xOffset=this.height=k;this.yOffset=d;b?(this.width=this.yOffset=e=d=this.size,this.xOffset=a=0,this.barWidth=k-2*e,this.x=c+=this.options.margin):
(this.height=this.xOffset=k=a=this.size,this.barWidth=e-2*k,this.y+=this.options.margin);this.group[f]({translateX:c,translateY:this.y});this.track[f]({width:e,height:k});this.scrollbarButtons[1][f]({translateX:b?0:e-a,translateY:b?k-d:0})},drawScrollbarButton:function(c){var a=this.renderer,e=this.scrollbarButtons,k=this.options,b=this.size;var d=a.g().add(this.group);e.push(d);d=a.rect().addClass("highcharts-scrollbar-button").add(d);this.chart.styledMode||d.attr({stroke:k.buttonBorderColor,"stroke-width":k.buttonBorderWidth,
fill:k.buttonBackgroundColor});d.attr(d.crisp({x:-.5,y:-.5,width:b+1,height:b+1,r:k.buttonBorderRadius},d.strokeWidth()));d=a.path(B(["M",b/2+(c?-1:1),b/2-3,"L",b/2+(c?-1:1),b/2+3,"L",b/2+(c?2:-2),b/2],k.vertical)).addClass("highcharts-scrollbar-arrow").add(e[c]);this.chart.styledMode||d.attr({fill:k.buttonArrowColor})},setRange:function(c,a){var e=this.options,f=e.vertical,b=e.minWidth,d=this.barWidth,g,k=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":
"animate";if(G(d)){c=Math.max(c,0);var l=Math.ceil(d*c);this.calculatedWidth=g=x(d*Math.min(a,1)-l);g<b&&(l=(d-b+g)*c,g=b);b=Math.floor(l+this.xOffset+this.yOffset);d=g/2-.5;this.from=c;this.to=a;f?(this.scrollbarGroup[k]({translateY:b}),this.scrollbar[k]({height:g}),this.scrollbarRifles[k]({translateY:d}),this.scrollbarTop=b,this.scrollbarLeft=0):(this.scrollbarGroup[k]({translateX:b}),this.scrollbar[k]({width:g}),this.scrollbarRifles[k]({translateX:d}),this.scrollbarLeft=b,this.scrollbarTop=0);
12>=g?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===e.showFull&&(0>=c&&1<=a?this.group.hide():this.group.show());this.rendered=!0}},initEvents:function(){var c=this;c.mouseMoveHandler=function(a){var e=c.chart.pointer.normalize(a),f=c.options.vertical?"chartY":"chartX",b=c.initPositions;!c.grabbedCenter||a.touches&&0===a.touches[0][f]||(e=c.cursorToScrollbarPosition(e)[f],f=c[f],f=e-f,c.hasDragged=!0,c.updatePosition(b[0]+f,b[1]+f),c.hasDragged&&z(c,"changed",{from:c.from,to:c.to,
trigger:"scrollbar",DOMType:a.type,DOMEvent:a}))};c.mouseUpHandler=function(a){c.hasDragged&&z(c,"changed",{from:c.from,to:c.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a});c.grabbedCenter=c.hasDragged=c.chartX=c.chartY=null};c.mouseDownHandler=function(a){a=c.chart.pointer.normalize(a);a=c.cursorToScrollbarPosition(a);c.chartX=a.chartX;c.chartY=a.chartY;c.initPositions=[c.from,c.to];c.grabbedCenter=!0};c.buttonToMinClick=function(a){var e=x(c.to-c.from)*c.options.step;c.updatePosition(x(c.from-
e),x(c.to-e));z(c,"changed",{from:c.from,to:c.to,trigger:"scrollbar",DOMEvent:a})};c.buttonToMaxClick=function(a){var e=(c.to-c.from)*c.options.step;c.updatePosition(c.from+e,c.to+e);z(c,"changed",{from:c.from,to:c.to,trigger:"scrollbar",DOMEvent:a})};c.trackClick=function(a){var e=c.chart.pointer.normalize(a),f=c.to-c.from,b=c.y+c.scrollbarTop,d=c.x+c.scrollbarLeft;c.options.vertical&&e.chartY>b||!c.options.vertical&&e.chartX>d?c.updatePosition(c.from+f,c.to+f):c.updatePosition(c.from-f,c.to-f);
z(c,"changed",{from:c.from,to:c.to,trigger:"scrollbar",DOMEvent:a})}},cursorToScrollbarPosition:function(c){var a=this.options;a=a.minWidth>this.calculatedWidth?a.minWidth:0;return{chartX:(c.chartX-this.x-this.xOffset)/(this.barWidth-a),chartY:(c.chartY-this.y-this.yOffset)/(this.barWidth-a)}},updatePosition:function(a,e){1<e&&(a=x(1-x(e-a)),e=1);0>a&&(e=x(e-a),a=0);this.from=a;this.to=e},update:function(a){this.destroy();this.init(this.chart.renderer,p(!0,this.options,a),this.chart)},addEvents:function(){var a=
this.options.inverted?[1,0]:[0,1],e=this.scrollbarButtons,k=this.scrollbarGroup.element,l=this.mouseDownHandler,b=this.mouseMoveHandler,d=this.mouseUpHandler;a=[[e[a[0]].element,"click",this.buttonToMinClick],[e[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[k,"mousedown",l],[k.ownerDocument,"mousemove",b],[k.ownerDocument,"mouseup",d]];v&&a.push([k,"touchstart",l],[k.ownerDocument,"touchmove",b],[k.ownerDocument,"touchend",d]);a.forEach(function(b){u.apply(null,
b)});this._events=a},removeEvents:function(){this._events.forEach(function(a){k.apply(null,a)});this._events.length=0},destroy:function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,D(a.scrollbarButtons))}};e.Scrollbar||(u(a,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&
(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new n(a.chart.renderer,a.options.scrollbar,a.chart),u(a.scrollbar,"changed",function(c){var f=Math.min(w(a.options.min,a.min),a.min,a.dataMin),k=Math.max(w(a.options.max,a.max),a.max,a.dataMax)-f;if(a.horiz&&!a.reversed||!a.horiz&&a.reversed){var b=f+k*this.to;f+=k*this.from}else b=f+k*(1-this.from),f+=k*(1-this.to);w(this.options.liveRedraw,e.svg&&!e.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===
c.DOMType||!G(c.DOMType)?a.setExtremes(f,b,!0,"mousemove"!==c.DOMType,c):this.setRange(this.from,this.to)}))}),u(a,"afterRender",function(){var a=Math.min(w(this.options.min,this.min),this.min,w(this.dataMin,this.min)),e=Math.max(w(this.options.max,this.max),this.max,w(this.dataMax,this.max)),k=this.scrollbar,l=this.axisTitleMargin+(this.titleOffset||0),b=this.chart.scrollbarsOffsets,d=this.options.margin||0;k&&(this.horiz?(this.opposite||(b[1]+=l),k.position(this.left,this.top+this.height+2+b[1]-
(this.opposite?d:0),this.width,this.height),this.opposite||(b[1]+=d),l=1):(this.opposite&&(b[0]+=l),k.position(this.left+this.width+2+b[0]-(this.opposite?0:d),this.top,this.width,this.height),this.opposite&&(b[0]+=d),l=0),b[l]+=k.size+k.options.margin,isNaN(a)||isNaN(e)||!G(this.min)||!G(this.max)||this.min===this.max?k.setRange(0,1):(b=(this.min-a)/(e-a),a=(this.max-a)/(e-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?k.setRange(b,a):k.setRange(1-a,1-b)))}),u(a,"afterGetOffset",function(){var a=
this.horiz?2:1,e=this.scrollbar;e&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=e.size+e.options.margin)}),e.Scrollbar=n)});I(n,"parts/RangeSelector.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(e,a){function n(b){this.init(b)}var u=a.addEvent,x=a.createElement,G=a.css,D=a.defined,z=a.destroyObjectProperties,p=a.discardElement,w=a.extend,k=a.fireEvent,l=a.isNumber,v=a.merge,B=a.objectEach,q=a.pick,c=a.pInt,f=a.splat,t=e.Axis;a=e.Chart;var F=e.defaultOptions;w(F,{rangeSelector:{verticalAlign:"top",
buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});F.lang=v(F.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});n.prototype={clickButton:function(b,a){var d=this.chart,c=this.buttonOptions[b],e=d.xAxis[0],k=d.scroller&&d.scroller.getUnionExtremes()||e||{},m=k.dataMin,h=k.dataMax,r=e&&Math.round(Math.min(e.max,q(h,e.max))),y=c.type;
k=c._range;var E,n=c.dataGrouping;if(null!==m&&null!==h){d.fixedRange=k;n&&(this.forcedDataGrouping=!0,t.prototype.setDataGrouping.call(e||{chart:this.chart},n,!1),this.frozenStates=c.preserveDataGrouping);if("month"===y||"year"===y)if(e){y={range:c,max:r,chart:d,dataMin:m,dataMax:h};var p=e.minFromRange.call(y);l(y.newMax)&&(r=y.newMax)}else k=c;else if(k)p=Math.max(r-k,m),r=Math.min(p+k,h);else if("ytd"===y)if(e)"undefined"===typeof h&&(m=Number.MAX_VALUE,h=Number.MIN_VALUE,d.series.forEach(function(b){b=
b.xData;m=Math.min(b[0],m);h=Math.max(b[b.length-1],h)}),a=!1),r=this.getYTDExtremes(h,m,d.time.useUTC),p=E=r.min,r=r.max;else{this.deferredYTDClick=b;return}else"all"===y&&e&&(p=m,r=h);p+=c._offsetMin;r+=c._offsetMax;this.setSelected(b);if(e)e.setExtremes(p,r,q(a,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:c});else{var H=f(d.options.xAxis)[0];var v=H.range;H.range=k;var x=H.min;H.min=E;u(d,"load",function(){H.range=v;H.min=x})}}},setSelected:function(b){this.selected=this.options.selected=
b},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(b){var a=this,c=b.options.rangeSelector,e=c.buttons||[].concat(a.defaultButtons),f=c.selected,l=function(){var b=a.minInput,d=a.maxInput;b&&b.blur&&k(b,"blur");d&&d.blur&&k(d,"blur")};a.chart=b;a.options=c;a.buttons=[];a.buttonOptions=e;this.unMouseDown=u(b.container,"mousedown",l);this.unResize=
u(b,"resize",l);e.forEach(a.computeButtonRange);"undefined"!==typeof f&&e[f]&&this.clickButton(f,!1);u(b,"load",function(){b.xAxis&&b.xAxis[0]&&u(b.xAxis[0],"setExtremes",function(d){this.max-this.min!==b.fixedRange&&"rangeSelectorButton"!==d.trigger&&"updatedData"!==d.trigger&&a.forcedDataGrouping&&!a.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var b=this,a=this.chart,c=a.xAxis[0],e=Math.round(c.max-c.min),f=!c.hasVisibleSeries,k=a.scroller&&a.scroller.getUnionExtremes()||
c,m=k.dataMin,h=k.dataMax;a=b.getYTDExtremes(h,m,a.time.useUTC);var r=a.min,y=a.max,E=b.selected,n=l(E),p=b.options.allButtonsEnabled,H=b.buttons;b.buttonOptions.forEach(function(a,d){var g=a._range,k=a.type,l=a.count||1,q=H[d],C=0,t=a._offsetMax-a._offsetMin;a=d===E;var u=g>h-m,K=g<c.minRange,J=!1,v=!1;g=g===e;("month"===k||"year"===k)&&e+36E5>=864E5*{month:28,year:365}[k]*l-t&&e-36E5<=864E5*{month:31,year:366}[k]*l+t?g=!0:"ytd"===k?(g=y-r+t===e,J=!a):"all"===k&&(g=c.max-c.min>=h-m,v=!a&&n&&g);k=
!p&&(u||K||v||f);l=a&&g||g&&!n&&!J||a&&b.frozenStates;k?C=3:l&&(n=!0,C=2);q.state!==C&&(q.setState(C),0===C&&E===d&&b.setSelected(null))})},computeButtonRange:function(b){var a=b.type,c=b.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[a])b._range=e[a]*c;else if("month"===a||"year"===a)b._range=864E5*{month:30,year:365}[a]*c;b._offsetMin=q(b.offsetMin,0);b._offsetMax=q(b.offsetMax,0);b._range+=b._offsetMax-b._offsetMin},setInputValue:function(b,a){var c=this.chart.options.rangeSelector,
d=this.chart.time,e=this[b+"Input"];D(a)&&(e.previousValue=e.HCTime,e.HCTime=a);e.value=d.dateFormat(c.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[b+"DateBox"].attr({text:d.dateFormat(c.inputDateFormat||"%b %e, %Y",e.HCTime)})},showInput:function(b){var a=this.inputGroup,c=this[b+"DateBox"];G(this[b+"Input"],{left:a.translateX+c.x+"px",top:a.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})},hideInput:function(b){G(this[b+"Input"],{border:0,width:"1px",height:"1px"});
this.setInputValue(b)},drawInput:function(b){function a(){var b=y.value,a=(m.inputDateParser||Date.parse)(b),d=f.xAxis[0],h=f.scroller&&f.scroller.xAxis?f.scroller.xAxis:d,e=h.dataMin;h=h.dataMax;a!==y.previousValue&&(y.previousValue=a,l(a)||(a=b.split("-"),a=Date.UTC(c(a[0]),c(a[1])-1,c(a[2]))),l(a)&&(f.time.useUTC||(a+=6E4*(new Date).getTimezoneOffset()),r?a>g.maxInput.HCTime?a=void 0:a<e&&(a=e):a<g.minInput.HCTime?a=void 0:a>h&&(a=h),"undefined"!==typeof a&&d.setExtremes(r?a:d.min,r?d.max:a,void 0,
void 0,{trigger:"rangeSelectorInput"})))}var g=this,f=g.chart,k=f.renderer.style||{},n=f.renderer,m=f.options.rangeSelector,h=g.div,r="min"===b,y,E,p=this.inputGroup;this[b+"Label"]=E=n.label(F.lang[r?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(p);p.offset+=E.width+5;this[b+"DateBox"]=n=n.label("",p.offset).addClass("highcharts-range-input").attr({padding:2,width:m.inputBoxWidth||90,height:m.inputBoxHeight||17,"text-align":"center"}).on("click",
function(){g.showInput(b);g[b+"Input"].focus()});f.styledMode||n.attr({stroke:m.inputBoxBorderColor||"#cccccc","stroke-width":1});n.add(p);p.offset+=n.width+(r?10:0);this[b+"Input"]=y=x("input",{name:b,className:"highcharts-range-selector",type:"text"},{top:f.plotTop+"px"},h);f.styledMode||(E.css(v(k,m.labelStyle)),n.css(v({color:"#333333"},k,m.inputStyle)),G(y,w({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:k.fontSize,fontFamily:k.fontFamily,top:"-9999em"},
m.inputStyle)));y.onfocus=function(){g.showInput(b)};y.onblur=function(){y===e.doc.activeElement&&a();g.hideInput(b);y.blur()};y.onchange=a;y.onkeypress=function(b){13===b.keyCode&&a()}},getPosition:function(){var b=this.chart,a=b.options.rangeSelector;b="top"===a.verticalAlign?b.plotTop-b.axisOffset[0]:0;return{buttonTop:b+a.buttonPosition.y,inputTop:b+a.inputPosition.y-10}},getYTDExtremes:function(b,a,c){var d=this.chart.time,e=new d.Date(b),f=d.get("FullYear",e);c=c?d.Date.UTC(f,0,1):+new d.Date(f,
0,1);a=Math.max(a||0,c);e=e.getTime();return{max:Math.min(b||e,e),min:a}},render:function(b,a){var c=this,d=c.chart,e=d.renderer,f=d.container,m=d.options,h=m.exporting&&!1!==m.exporting.enabled&&m.navigation&&m.navigation.buttonOptions,r=F.lang,k=c.div,l=m.rangeSelector,n=q(m.chart.style&&m.chart.style.zIndex,0)+1;m=l.floating;var p=c.buttons;k=c.inputGroup;var H=l.buttonTheme,t=l.buttonPosition,u=l.inputPosition,v=l.inputEnabled,w=H&&H.states,z=d.plotLeft,A=c.buttonGroup;var B=c.rendered;var D=
c.options.verticalAlign,G=d.legend,I=G&&G.options,Q=t.y,O=u.y,S=B||!1,T=S?"animate":"attr",N=0,L=0,M;if(!1!==l.enabled){B||(c.group=B=e.g("range-selector-group").attr({zIndex:7}).add(),c.buttonGroup=A=e.g("range-selector-buttons").add(B),c.zoomText=e.text(r.rangeSelectorZoom,0,15).add(A),d.styledMode||(c.zoomText.css(l.labelStyle),H["stroke-width"]=q(H["stroke-width"],0)),c.buttonOptions.forEach(function(b,a){p[a]=e.button(b.text,0,0,function(d){var e=b.events&&b.events.click,h;e&&(h=e.call(b,d));
!1!==h&&c.clickButton(a);c.isActive=!0},H,w&&w.hover,w&&w.select,w&&w.disabled).attr({"text-align":"center"}).add(A)}),!1!==v&&(c.div=k=x("div",null,{position:"relative",height:0,zIndex:n}),f.parentNode.insertBefore(k,f),c.inputGroup=k=e.g("input-group").add(B),k.offset=0,c.drawInput("min"),c.drawInput("max")));c.zoomText[T]({x:q(z+t.x,z)});var U=q(z+t.x,z)+c.zoomText.getBBox().width+5;c.buttonOptions.forEach(function(b,a){p[a][T]({x:U});U+=p[a].width+q(l.buttonSpacing,5)});z=d.plotLeft-d.spacing[3];
c.updateButtonStates();h&&this.titleCollision(d)&&"top"===D&&"right"===t.align&&t.y+A.getBBox().height-12<(h.y||0)+h.height&&(N=-40);"left"===t.align?M=t.x-d.spacing[3]:"right"===t.align&&(M=t.x+N-d.spacing[1]);A.align({y:t.y,width:A.getBBox().width,align:t.align,x:M},!0,d.spacingBox);c.group.placed=S;c.buttonGroup.placed=S;!1!==v&&(N=h&&this.titleCollision(d)&&"top"===D&&"right"===u.align&&u.y-k.getBBox().height-12<(h.y||0)+h.height+d.spacing[0]?-40:0,"left"===u.align?M=z:"right"===u.align&&(M=-Math.max(d.axisOffset[1],
-N)),k.align({y:u.y,width:k.getBBox().width,align:u.align,x:u.x+M-2},!0,d.spacingBox),f=k.alignAttr.translateX+k.alignOptions.x-N+k.getBBox().x+2,h=k.alignOptions.width,r=A.alignAttr.translateX+A.getBBox().x,M=A.getBBox().width+20,(u.align===t.align||r+M>f&&f+h>r&&Q<O+k.getBBox().height)&&k.attr({translateX:k.alignAttr.translateX+(d.axisOffset[1]>=-N?0:-N),translateY:k.alignAttr.translateY+A.getBBox().height+10}),c.setInputValue("min",b),c.setInputValue("max",a),c.inputGroup.placed=S);c.group.align({verticalAlign:D},
!0,d.spacingBox);b=c.group.getBBox().height+20;a=c.group.alignAttr.translateY;"bottom"===D&&(G=I&&"bottom"===I.verticalAlign&&I.enabled&&!I.floating?G.legendHeight+q(I.margin,10):0,b=b+G-20,L=a-b-(m?0:l.y)-(d.titleOffset?d.titleOffset[2]:0)-10);if("top"===D)m&&(L=0),d.titleOffset&&d.titleOffset[0]&&(L=d.titleOffset[0]),L+=d.margin[0]-d.spacing[0]||0;else if("middle"===D)if(O===Q)L=0>O?a+void 0:a;else if(O||Q)L=0>O||0>Q?L-Math.min(O,Q):a-b+NaN;c.group.translate(l.x,l.y+Math.floor(L));!1!==v&&(c.minInput.style.marginTop=
c.group.translateY+"px",c.maxInput.style.marginTop=c.group.translateY+"px");c.rendered=!0}},getHeight:function(){var b=this.options,a=this.group,c=b.y,e=b.buttonPosition.y,f=b.inputPosition.y;if(b.height)return b.height;b=a?a.getBBox(!0).height+13+c:0;a=Math.min(f,e);if(0>f&&0>e||0<f&&0<e)b+=Math.abs(a);return b},titleCollision:function(b){return!(b.options.title.text||b.options.subtitle.text)},update:function(b){var a=this.chart;v(!0,a.options.rangeSelector,b);this.destroy();this.init(a);a.rangeSelector.render()},
destroy:function(){var b=this,a=b.minInput,c=b.maxInput;b.unMouseDown();b.unResize();z(b.buttons);a&&(a.onfocus=a.onblur=a.onchange=null);c&&(c.onfocus=c.onblur=c.onchange=null);B(b,function(a,c){a&&"chart"!==c&&(a.destroy?a.destroy():a.nodeType&&p(this[c]));a!==n.prototype[c]&&(b[c]=null)},this)}};t.prototype.minFromRange=function(){var b=this.range,a={month:"Month",year:"FullYear"}[b.type],c=this.max,e=this.chart.time,f=function(b,c){var d=new e.Date(b),h=e.get(a,d);e.set(a,d,h+c);h===e.get(a,d)&&
e.set("Date",d,0);return d.getTime()-b};if(l(b)){var k=c-b;var m=b}else k=c+f(c,-b.count),this.chart&&(this.chart.fixedRange=c-k);var h=q(this.dataMin,Number.MIN_VALUE);l(k)||(k=h);k<=h&&(k=h,"undefined"===typeof m&&(m=f(k,b.count)),this.newMax=Math.min(k+m,this.dataMax));l(c)||(k=void 0);return k};e.RangeSelector||(u(a,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new n(this))}),u(a,"beforeRender",function(){var b=this.axes,a=this.rangeSelector;a&&(l(a.deferredYTDClick)&&
(a.clickButton(a.deferredYTDClick),delete a.deferredYTDClick),b.forEach(function(b){b.updateNames();b.setScale()}),this.getAxisMargins(),a.render(),b=a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)))}),u(a,"update",function(b){var a=b.options.rangeSelector;b=this.rangeSelector;var c=this.extraBottomMargin,e=this.extraTopMargin;a&&a.enabled&&!D(b)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new n(this));this.extraTopMargin=
this.extraBottomMargin=!1;b&&(b.render(),a=a&&a.verticalAlign||b.options&&b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==e)&&(this.isDirtyBox=!0)}),u(a,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),u(a,"getMargins",function(){var a=
this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),a.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();l(c.min)&&e.render(c.min,c.max)}var c,e=a.rangeSelector;if(e){var f=u(a.xAxis[0],"afterSetExtremes",function(a){e.render(a.min,a.max)});var k=u(a,"redraw",b);b()}u(a,"destroy",function(){e&&(k(),f())})}),e.RangeSelector=n)});I(n,"parts/Navigator.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],
function(e,a){function n(a){this.init(a)}var u=a.addEvent,x=a.clamp,G=a.correctFloat,D=a.defined,z=a.destroyObjectProperties,p=a.erase,w=a.extend,k=a.isArray,l=a.isNumber,v=a.merge,B=a.pick,q=a.removeEvent,c=a.splat,f=e.Axis;a=e.Chart;var t=e.color,F=e.defaultOptions,b=e.hasTouch,d=e.isTouchDevice,g=e.Scrollbar,C=e.Series,I=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,l);if(b.length)return Math[a].apply(0,b)};var P="undefined"===typeof e.seriesTypes.areaspline?
"line":"areaspline";w(F,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:t("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:P,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,
2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},
yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});e.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=e.width/2;b=Math.round(a/3)+.5;e=e.height;return["M",-a-1,.5,"L",a,.5,"L",a,e+.5,"L",-a-1,e+.5,"L",-a-1,.5,"M",-b,4,"L",-b,e-3,"M",b-1,4,"L",b-1,e-3]};f.prototype.toFixedRange=function(a,b,c,d){var e=this.chart&&this.chart.fixedRange,
h=(this.pointRange||0)/2;a=B(c,this.translate(a,!0,!this.horiz));b=B(d,this.translate(b,!0,!this.horiz));var m=e&&(b-a)/e;D(c)||(a=G(a+h));D(d)||(b=G(b-h));.7<m&&1.3>m&&(d?a=b-e:b=a+e);l(a)&&l(b)||(a=b=void 0);return{min:a,max:b}};n.prototype={drawHandle:function(a,b,c,d){var e=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+
this.height/2-e/2-1)})},drawOutline:function(a,b,c,d){var e=this.navigatorOptions.maskInside,h=this.outline.strokeWidth(),m=h/2;h=h%2/2;var f=this.outlineHeight,g=this.scrollbarHeight,k=this.size,r=this.left-g,l=this.top;c?(r-=m,c=l+b+h,b=l+a+h,a=["M",r+f,l-g-h,"L",r+f,c,"L",r,c,"L",r,b,"L",r+f,b,"L",r+f,l+k+g].concat(e?["M",r+f,c-m,"L",r+f,b+m]:[])):(a+=r+g-h,b+=r+g-h,l+=m,a=["M",r,l,"L",a,l,"L",a,l+f,"L",b,l+f,"L",b,l,"L",r+k+2*g,l].concat(e?["M",a-m,l,"L",b+m,l]:[]));this.outline[d]({d:a})},drawMasks:function(a,
b,c,d){var e=this.left,h=this.top,m=this.height;if(c){var f=[e,e,e];var g=[h,h+a,h+b];var k=[m,m,m];var r=[a,b-a,this.size-b]}else f=[e,e+a,e+b],g=[h,h,h],k=[a,b-a,this.size-b],r=[m,m,m];this.shades.forEach(function(a,b){a[d]({x:f[b],y:g[b],width:k[b],height:r[b]})})},renderElements:function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,g={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,
h){a.shades[h]=e.rect().addClass("highcharts-navigator-mask"+(1===h?"-inside":"-outside")).add(f);d.styledMode||a.shades[h].attr({fill:c?b.maskFill:"rgba(0,0,0,0)"}).css(1===h&&g)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,
b.handles);a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var h=b.handles;a.handles[c].attr({fill:h.backgroundColor,stroke:h.borderColor,"stroke-width":h.lineWidth}).css(g)}})},update:function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();v(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)},render:function(a,b,c,d){var e=
this.chart,h=this.scrollbarHeight,f,m=this.xAxis,g=m.pointRange||0;var k=m.fake?e.xAxis[0]:m;var r=this.navigatorEnabled,n,p=this.rendered;var q=e.inverted;var y=e.xAxis[0].minRange,t=e.xAxis[0].options.maxRange;if(!this.hasDragged||D(c)){a=G(a-g/2);b=G(b+g/2);if(!l(a)||!l(b))if(p)c=0,d=B(m.width,k.width);else return;this.left=B(m.left,e.plotLeft+h+(q?e.plotWidth:0));this.size=n=f=B(m.len,(q?e.plotHeight:e.plotWidth)-2*h);e=q?h:f+2*h;c=B(c,m.toPixels(a,!0));d=B(d,m.toPixels(b,!0));l(c)&&Infinity!==
Math.abs(c)||(c=0,d=e);a=m.toValue(c,!0);b=m.toValue(d,!0);var u=Math.abs(G(b-a));u<y?this.grabbedLeft?c=m.toPixels(b-y-g,!0):this.grabbedRight&&(d=m.toPixels(a+y+g,!0)):D(t)&&G(u-g)>t&&(this.grabbedLeft?c=m.toPixels(b-t-g,!0):this.grabbedRight&&(d=m.toPixels(a+t+g,!0)));this.zoomedMax=x(Math.max(c,d),0,n);this.zoomedMin=x(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,n);this.range=this.zoomedMax-this.zoomedMin;n=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);r&&(this.navigatorGroup.attr({visibility:"visible"}),
p=p&&!this.hasDragged?"animate":"attr",this.drawMasks(c,n,q,p),this.drawOutline(c,n,q,p),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,q,p),this.drawHandle(n,1,q,p)));this.scrollbar&&(q?(q=this.top-h,k=this.left-h+(r||!k.opposite?0:(k.titleOffset||0)+k.axisTitleMargin),h=f+2*h):(q=this.top+(r?this.height:-h),k=this.left-h),this.scrollbar.position(k,q,e,h),this.scrollbar.setRange(this.zoomedMin/(f||1),this.zoomedMax/(f||1)));this.rendered=!0}},addMouseEvents:function(){var a=this,c=a.chart,
d=c.container,e=[],f,g;a.mouseMoveHandler=f=function(b){a.onMouseMove(b)};a.mouseUpHandler=g=function(b){a.onMouseUp(b)};e=a.getPartsEvents("mousedown");e.push(u(c.renderTo,"mousemove",f),u(d.ownerDocument,"mouseup",g));b&&(e.push(u(c.renderTo,"touchmove",f),u(d.ownerDocument,"touchend",g)),e.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=e;a.series&&a.series[0]&&e.push(u(a.series[0].xAxis,"foundExtremes",function(){c.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var b=
this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,h){c.push(u(e.element,a,function(a){b[d+"Mousedown"](a,h)}))})});return c},shadesMousedown:function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,h=this.left,f=this.size,m=this.range,g=a.chartX;c.inverted&&(g=a.chartY,h=this.top);if(1===b)this.grabbedCenter=g,this.fixedWidth=m,this.dragOffset=g-e;else{a=g-h-m/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+m>=f)if(a=f-m,this.reversedExtremes){a-=
m;var k=this.getUnionExtremes().dataMin}else var l=this.getUnionExtremes().dataMax;a!==e&&(this.fixedWidth=m,b=d.toFixedRange(a,a+m,k,l),D(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}},handlesMousedown:function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=
this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null},onMouseMove:function(a){var b=this,c=b.chart,f=b.left,m=b.navigatorSize,g=b.range,k=b.dragOffset,l=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,l&&(f=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-f,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-f)):b.grabbedCenter&&(b.hasDragged=!0,c<k?c=k:c>m+k-g&&(c=m+k-g),b.render(0,0,c-k,c-k+g)),b.hasDragged&&
b.scrollbar&&B(b.scrollbar.options.liveRedraw,e.svg&&!d&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))},onMouseUp:function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a,f=b.inverted,m=this.rendered&&!this.hasDragged?"animate":"attr",g=Math.round(this.zoomedMax),k=Math.round(this.zoomedMin);if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var l=this.fixedExtreme;
else if(this.zoomedMax===this.otherHandlePos)var n=this.fixedExtreme;this.zoomedMax===this.size&&(n=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(l=this.reversedExtremes?d.dataMax:d.dataMin);c=c.toFixedRange(this.zoomedMin,this.zoomedMax,l,n);D(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=
this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(k,g,f,m),this.outline&&this.drawOutline(k,g,f,m),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(k,0,f,m),this.drawHandle(g,1,f,m)))},removeEvents:function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},
removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){q(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&q(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(a){var b=a.options,c=b.navigator,d=c.enabled,e=b.scrollbar,m=e.enabled;b=d?c.height:0;var k=m?e.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=k;
this.scrollbarEnabled=m;this.navigatorEnabled=d;this.navigatorOptions=c;this.scrollbarOptions=e;this.outlineHeight=b+k;this.opposite=B(c.opposite,!(d||!a.inverted));var l=this;d=l.baseSeries;e=a.xAxis.length;m=a.yAxis.length;var n=d&&d[0]&&d[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;l.navigatorEnabled?(l.xAxis=new f(a,v({breaks:n.options.breaks,ordinal:n.options.ordinal},c.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:e,isInternal:!0,offset:0,keepOrdinalPadding:!0,
startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[k,0,-k,0],width:b}:{offsets:[0,-k,0,k],height:b})),l.yAxis=new f(a,v(c.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:m,isInternal:!0,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),d||c.series.data?l.updateNavigatorSeries(!1):0===a.series.length&&(l.unbindRedraw=u(a,"beforeRedraw",function(){0<a.series.length&&!l.series&&(l.setBaseSeries(),l.unbindRedraw())})),l.reversedExtremes=a.inverted&&!l.xAxis.reversed||
!a.inverted&&l.xAxis.reversed,l.renderElements(),l.addMouseEvents()):l.xAxis={translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*k,h=I("min",d.options.min,e.dataMin);d=I("max",d.options.max,e.dataMax)-h;return c?b*d/f+h:f*(b-h)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:f.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=l.scrollbar=new g(a.renderer,v(a.options.scrollbar,{margin:l.navigatorEnabled?
0:10,vertical:a.inverted}),a),u(l.scrollbar,"changed",function(b){var c=l.size,d=c*this.to;c*=this.from;l.hasDragged=l.scrollbar.hasDragged;l.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){l.onMouseUp(b)})}));l.addBaseSeriesEvents();l.addChartEvents()},getUnionExtremes:function(a){var b=this.chart.xAxis[0],c=this.xAxis,d=c.options,e=b.options,f;a&&null===b.dataMin||(f={dataMin:B(d&&d.min,I("min",e.min,b.dataMin,c.dataMin,c.min)),
dataMax:B(d&&d.max,I("max",e.max,b.dataMax,c.dataMax,c.max))});return f},setBaseSeries:function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?e.find(c.series,function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,b)},updateNavigatorSeries:function(a,
b){var d=this,e=d.chart,f=d.baseSeries,h,m,g=d.navigatorOptions.series,l,n={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},p=d.series=(d.series||[]).filter(function(a){var b=a.baseSeries;return 0>f.indexOf(b)?(b&&(q(b,"updatedData",d.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});f&&f.length&&f.forEach(function(a){var c=a.navigatorSeries,
r=w({color:a.color,visible:a.visible},k(g)?F.navigator.series:g);c&&!1===d.navigatorOptions.adaptToUpdatedData||(n.name="Navigator "+f.length,h=a.options||{},l=h.navigatorOptions||{},m=v(h,n,r,l),m.pointRange=B(r.pointRange,l.pointRange,F.plotOptions[m.type||"line"].pointRange),r=l.data||r.data,d.hasNavigatorData=d.hasNavigatorData||!!r,m.data=r||h.data&&h.data.slice(0),c&&c.options?c.update(m,b):(a.navigatorSeries=e.initSeries(m),a.navigatorSeries.baseSeries=a,p.push(a.navigatorSeries)))});if(g.data&&
(!f||!f.length)||k(g))d.hasNavigatorData=!1,g=c(g),g.forEach(function(a,b){n.name="Navigator "+(p.length+1);m=v(F.navigator.series,{color:e.series[b]&&!e.series[b].options.isInternal&&e.series[b].color||e.options.colors[b]||e.options.colors[0]},n,a);m.data=a.data;m.data&&(d.hasNavigatorData=!0,p.push(e.initSeries(m)))});a&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&u(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);b.forEach(function(b){u(b,
"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});u(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&u(b,"updatedData",this.updatedDataHandler);u(b,"remove",function(){this.navigatorSeries&&(p(a.series,this.navigatorSeries),D(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},getBaseSeriesMin:function(a){return this.baseSeries.reduce(function(a,
b){return Math.min(a,b.xData?b.xData[0]:a)},a)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,g=B(this.options.overscroll,0),k=a.series&&a.series[0],n=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==
this.eventArgs.trigger){if(e){var p=c;var q=p+b}f&&(q=d+g,e||(p=Math.max(q-b,a.getBaseSeriesMin(k&&k.xData?k.xData[0]:-Number.MAX_VALUE))));n&&(e||f)&&l(p)&&(this.min=this.userMin=p,this.max=this.userMax=q)}a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=l(this.xAxis.min)&&this.xAxis.min<=
c&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(u(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,b.max)}),u(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";
this.inverted&&(b=a.opposite?"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))},destroy:function(){this.removeEvents();this.xAxis&&(p(this.chart.xAxis,this.xAxis),p(this.chart.axes,this.xAxis));this.yAxis&&(p(this.chart.yAxis,this.yAxis),p(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&
this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){z(a)},this)}};e.Navigator||(e.Navigator=n,u(f,"zoom",function(a){var b=this.chart.options,c=b.chart.zoomType,e=b.chart.pinchType,f=b.navigator;b=b.rangeSelector;this.isXAxis&&(f&&f.enabled||b&&b.enabled)&&("y"===c?a.zoomed=!1:(!d&&"xy"===c||d&&"xy"===e)&&this.options.range&&(c=this.previousZoom,D(a.newMin)?this.previousZoom=[this.min,this.max]:c&&(a.newMin=c[0],a.newMax=c[1],delete this.previousZoom)));"undefined"!==
typeof a.zoomed&&a.preventDefault()}),u(a,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!d&&"x"===a.chart.zoomType||d&&"x"===a.chart.pinchType))return!1}),u(a,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new n(this)}),u(a,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var f=b.scrollbarHeight;
this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?a.legendHeight+B(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),
e.setAxisSize())}}),u(a,"update",function(a){var b=a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(v(!0,this.options.navigator,b),v(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),u(a,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new n(this),B(a.redraw,!0)&&this.redraw(a.animation))}),u(a,"afterAddSeries",
function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),u(C,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),a.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}))});I(n,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map