/*
 Highcharts Gantt JS v8.0.0 (2020-02-08)

 GridAxis

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/modules/grid-axis",["highcharts"],function(p){e(p);e.Highcharts=p;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function p(e,p,g,f){e.hasOwnProperty(p)||(e[p]=f.apply(null,g))}e=e?e._modules:{};p(e,"parts-gantt/GridAxis.js",[e["parts/Globals.js"],e["parts/Tick.js"],e["parts/Utilities.js"]],function(e,p,g){var f=g.addEvent,
q=g.defined,A=g.erase,B=g.isArray,u=g.isNumber,v=g.merge,w=g.pick,E=g.timeUnits,C=g.wrap,F=e.dateFormat,r=function(a){return g.isObject(a,!0)},G=e.Chart,m=e.Axis,H=function(a){var b=a.options;b.labels||(b.labels={});b.labels.align=w(b.labels.align,"center");a.categories||(b.showLastLabel=!1);a.labelRotation=0;b.labels.rotation=0},x={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};m.prototype.isOuterAxis=function(){var a=this,b=a.columnIndex,c=a.linkedParent&&a.linkedParent.columns||
a.columns,h=b?a.linkedParent:a,d=-1,l=0;a.chart[a.coll].forEach(function(b,c){b.side!==a.side||b.options.isInternal||(l=c,b===h&&(d=c))});return l===d&&(u(b)?c.length===b:!0)};m.prototype.getMaxLabelDimensions=function(a,b){var c={width:0,height:0};b.forEach(function(b){b=a[b];if(r(b)){var d=r(b.label)?b.label:{};b=d.getBBox?d.getBBox().height:0;d.textStr&&!u(d.textPxLength)&&(d.textPxLength=d.getBBox().width);d=u(d.textPxLength)?Math.round(d.textPxLength):0;c.height=Math.max(b,c.height);c.width=
Math.max(d,c.width)}});return c};e.dateFormats.W=function(a){a=new Date(a);a.setHours(0,0,0,0);a.setDate(a.getDate()-(a.getDay()||7));var b=new Date(a.getFullYear(),0,1);return Math.ceil(((a-b)/864E5+1)/7)};e.dateFormats.E=function(a){return F("%a",a,!0).charAt(0)};f(p,"afterGetLabelPosition",function(a){var b=this.label,c=this.axis,h=c.reversed,d=c.chart,l=c.options,e=l&&r(l.grid)?l.grid:{};l=c.options.labels;var y=l.align,k=x[c.side],n=a.tickmarkOffset,t=c.tickPositions,z=this.pos-n;t=u(t[a.index+
1])?t[a.index+1]-n:c.max+n;var g=c.tickSize("tick",!0);n=B(g)?g[0]:0;g=g&&g[1]/2;if(!0===e.enabled){if("top"===k){e=c.top+c.offset;var f=e-n}else"bottom"===k?(f=d.chartHeight-c.bottom+c.offset,e=f+n):(e=c.top+c.len-c.translate(h?t:z),f=c.top+c.len-c.translate(h?z:t));"right"===k?(k=d.chartWidth-c.right+c.offset,h=k+n):"left"===k?(h=c.left+c.offset,k=h-n):(k=Math.round(c.left+c.translate(h?t:z))-g,h=Math.round(c.left+c.translate(h?z:t))-g);this.slotWidth=h-k;a.pos.x="left"===y?k:"right"===y?h:k+(h-
k)/2;a.pos.y=f+(e-f)/2;d=d.renderer.fontMetrics(l.style.fontSize,b.element);b=b.getBBox().height;l.useHTML?a.pos.y+=d.b+-(b/2):(b=Math.round(b/d.h),a.pos.y+=(d.b-(d.h-d.f))/2+-((b-1)*d.h/2));a.pos.x+=c.horiz&&l.x||0}});f(m,"afterTickSize",function(a){var b=this.defaultLeftAxisOptions,c=this.horiz,h=this.options.grid;h=void 0===h?{}:h;var d=this.maxLabelDimensions;h.enabled&&(b=2*Math.abs(b.labels.x),c=c?h.cellHeight||b+d.height:b+d.width,B(a.tickSize)?a.tickSize[0]=c:a.tickSize=[c])});f(m,"afterGetTitlePosition",
function(a){var b=this.options;if(!0===(b&&r(b.grid)?b.grid:{}).enabled){var c=this.axisTitle,h=c&&c.getBBox().width,d=this.horiz,e=this.left,g=this.top,y=this.width,k=this.height,n=b.title;b=this.opposite;var t=this.offset,f=this.tickSize()||[0],m=n.x||0,p=n.y||0,q=w(n.margin,d?5:10);c=this.chart.renderer.fontMetrics(n.style&&n.style.fontSize,c).f;f=(d?g+k:e)+f[0]/2*(b?-1:1)*(d?1:-1)+(this.side===x.bottom?c:0);a.titlePosition.x=d?e-h/2-q+m:f+(b?y:0)+t+m;a.titlePosition.y=d?f-(b?k:0)+(b?c:-c)/2+t+
p:g-q+p}});C(m.prototype,"unsquish",function(a){var b=this.options;return!0===(b&&r(b.grid)?b.grid:{}).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))});f(m,"afterSetOptions",function(a){var b=this.options;a=a.userOptions;var c=b&&r(b.grid)?b.grid:{};if(!0===c.enabled){var h=v(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},
month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(q(a.linkedTo)&&!q(a.tickPixelInterval)&&(h.tickPixelInterval=350),q(a.tickPixelInterval)||!q(a.linkedTo)||q(a.tickPositioner)||q(a.tickInterval)||(h.tickPositioner=function(a,b){var c=this.linkedParent&&
this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(c){var d,e=h.units;for(d=0;d<e.length;d++)if(e[d][0]===c.unitName){var l=d;break}if(e[l+1]){var g=e[l+1][0];var f=(e[l+1][1]||[1])[0]}else"year"===c.unitName&&(g="year",f=10*c.count);c=E[g];this.tickInterval=c*f;return this.getTimeTicks({unitRange:c,count:f,unitName:g},a,b,this.options.startOfWeek)}}));v(!0,this.options,h);this.horiz&&(b.minPadding=w(a.minPadding,0),b.maxPadding=w(a.maxPadding,0));u(b.grid.borderWidth)&&(b.tickWidth=
b.lineWidth=c.borderWidth)}});f(m,"afterSetAxisTranslation",function(){var a=this.options,b=a&&r(a.grid)?a.grid:{},c=this.tickPositions&&this.tickPositions.info,e=this.userOptions.labels||{};this.horiz&&(!0===b.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),c&&(!1===a.dateTimeLabelFormats[c.unitName].range||1<c.count)&&!q(e.align)&&(a.labels.align="left",q(e.x)||(a.labels.x=3)))});f(m,"trimTicks",function(){var a=this.options,b=a&&r(a.grid)?a.grid:{},c=this.categories,e=this.tickPositions,
d=e[0],l=e[e.length-1],g=this.linkedParent&&this.linkedParent.min||this.min,f=this.linkedParent&&this.linkedParent.max||this.max,k=this.tickInterval;!0!==b.enabled||c||!this.horiz&&!this.isLinked||(d<g&&d+k>g&&!a.startOnTick&&(e[0]=g),l>f&&l-k<f&&!a.endOnTick&&(e[e.length-1]=f))});f(m,"afterRender",function(){var a=this.options,b=a&&r(a.grid)?a.grid:{},c=this.chart.renderer;if(!0===b.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();
if(this.isOuterAxis()&&this.axisLine){var e=a.lineWidth;if(e){var d=this.getLinePath(e);var g=d.indexOf("M")+1;var f=d.indexOf("L")+1;b=d.indexOf("M")+2;var m=d.indexOf("L")+2;var k=(this.tickSize("tick")[0]-1)*(this.side===x.top||this.side===x.left?-1:1);this.horiz?(d[b]+=k,d[m]+=k):(d[g]+=k,d[f]+=k);this.axisLineExtra?this.axisLineExtra.animate({d:d}):(this.axisLineExtra=c.path(d).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),c.styledMode||this.axisLineExtra.attr({stroke:a.lineColor,
"stroke-width":e}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(a){a.render()})}});var D={afterGetOffset:function(){(this.columns||[]).forEach(function(a){a.getOffset()})},afterInit:function(){var a=this.chart,b=this.userOptions,c=this.options;c=c&&r(c.grid)?c.grid:{};c.enabled&&(H(this),C(this,"labelFormatter",function(a){var b=this.axis,c=b.tickPositions,d=this.value,f=(b.isLinked?b.linkedParent:b).series[0],g=d===c[0];c=d===c[c.length-1];f=f&&e.find(f.options.data,
function(a){return a[b.isXAxis?"x":"y"]===d});this.isFirst=g;this.isLast=c;this.point=f;return a.call(this)}));if(c.columns)for(var g=this.columns=[],d=this.columnIndex=0;++d<c.columns.length;){var f=v(b,c.columns[c.columns.length-d-1],{linkedTo:0,type:"category"});delete f.grid.columns;f=new m(this.chart,f,!0);f.isColumn=!0;f.columnIndex=d;A(a.axes,f);A(a[this.coll],f);g.push(f)}},afterSetOptions:function(a){a=(a=a.userOptions)&&r(a.grid)?a.grid:{};var b=a.columns;a.enabled&&b&&v(!0,this.options,
b[b.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(a){a.setScale()})},destroy:function(a){(this.columns||[]).forEach(function(b){b.destroy(a.keepEvents)})},init:function(a){var b=(a=a.userOptions)&&r(a.grid)?a.grid:{};b.enabled&&q(b.borderColor)&&(a.tickColor=a.lineColor=b.borderColor)}};Object.keys(D).forEach(function(a){f(m,a,D[a])});f(G,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})})});
p(e,"masters/modules/grid-axis.src.js",[],function(){})});
//# sourceMappingURL=grid-axis.js.map