/*
 Highmaps JS v8.0.0 (2020-02-08)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(z){f(z);f.Highcharts=z;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function z(a,b,f,n){a.hasOwnProperty(b)||(a[b]=n.apply(null,f))}f=f?f._modules:{};z(f,"parts-map/MapAxis.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){var f=b.addEvent,n=b.pick;a=a.Axis;f(a,"getSeriesExtremes",
function(){var a=[];this.isXAxis&&(this.series.forEach(function(b,p){b.useMapGeometry&&(a[p]=b.xData,b.xData=[])}),this.seriesXData=a)});f(a,"afterGetSeriesExtremes",function(){var a=this.seriesXData,b;if(this.isXAxis){var f=n(this.dataMin,Number.MAX_VALUE);var B=n(this.dataMax,-Number.MAX_VALUE);this.series.forEach(function(p,v){p.useMapGeometry&&(f=Math.min(f,n(p.minX,f)),B=Math.max(B,n(p.maxX,B)),p.xData=a[v],b=!0)});b&&(this.dataMin=f,this.dataMax=B);delete this.seriesXData}});f(a,"afterSetAxisTranslation",
function(){var a=this.chart;var b=a.plotWidth/a.plotHeight;a=a.xAxis[0];var f;"yAxis"===this.coll&&"undefined"!==typeof a.transA&&this.series.forEach(function(a){a.preserveAspectRatio&&(f=!0)});if(f&&(this.transA=a.transA=Math.min(this.transA,a.transA),b/=(a.max-a.min)/(this.max-this.min),b=1>b?this:a,a=(b.max-b.min)*b.transA,b.pixelPadding=b.len-a,b.minPixelPadding=b.pixelPadding/2,a=b.fixTo)){a=a[1]-b.toValue(a[0],!0);a*=b.transA;if(Math.abs(a)>b.minPixelPadding||b.min===b.dataMin&&b.max===b.dataMax)a=
0;b.minPixelPadding-=a}});f(a,"render",function(){this.fixTo=null})});z(f,"parts-map/ColorSeriesMixin.js",[f["parts/Globals.js"]],function(a){a.colorPointMixin={setVisible:function(a){var b=this,f=a?"show":"hide";b.visible=b.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(b[a])b[a][f]()})}};a.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,f=this.options.nullColor,n=this.colorAxis,p=this.colorKey;(this.data.length?this.data:this.points).forEach(function(b){var v=
b.getNestedProperty(p);if(v=b.options.color||(b.isNull?f:n&&"undefined"!==typeof v?n.toColor(v,b):b.color||a.color))b.color=v})}}});z(f,"parts-map/ColorAxis.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){"";var f=b.addEvent,n=b.erase,p=b.extend,v=b.isNumber,w=b.merge,y=b.pick,r=b.splat,h=a.Axis;b=a.Chart;var e=a.Series,g=a.Point,m=a.color,u=a.Legend,x=a.LegendSymbolMixin,t=a.colorPointMixin,k=a.noop;p(e.prototype,a.colorSeriesMixin);p(g.prototype,t);b.prototype.collectionsWithUpdate.push("colorAxis");
b.prototype.collectionsWithInit.colorAxis=[b.prototype.addColorAxis];var c=a.ColorAxis=function(){this.init.apply(this,arguments)};p(c.prototype,h.prototype);p(c.prototype,{defaultColorAxisOptions:{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0},keepProps:["legendGroup",
"legendItemHeight","legendItemWidth","legendItem","legendSymbol"].concat(h.prototype.keepProps),init:function(d,c){this.coll="colorAxis";var l=this.buildOptions.call(d,this.defaultColorAxisOptions,c);h.prototype.init.call(this,d,l);c.dataClasses&&this.initDataClasses(c);this.initStops();this.horiz=!l.opposite;this.zoomEnabled=!1;this.defaultLegendLength=200},initDataClasses:function(d){var c=this.chart,e,q=0,a=c.options.chart.colorCount,b=this.options,g=d.dataClasses.length;this.dataClasses=e=[];
this.legendItems=[];d.dataClasses.forEach(function(d,l){d=w(d);e.push(d);if(c.styledMode||!d.color)"category"===b.dataClassColor?(c.styledMode||(l=c.options.colors,a=l.length,d.color=l[q]),d.colorIndex=q,q++,q===a&&(q=0)):d.color=m(b.minColor).tweenTo(m(b.maxColor),2>g?.5:l/(g-1))})},hasData:function(){return!(!this.tickPositions||!this.tickPositions.length)},setTickPositions:function(){if(!this.dataClasses)return h.prototype.setTickPositions.call(this)},initStops:function(){this.stops=this.options.stops||
[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(d){d.color=m(d[1])})},buildOptions:function(d,c){var l=this.options.legend,e=c.layout?"vertical"!==c.layout:"vertical"!==l.layout;return w(d,{side:e?2:1,reversed:!e},c,{opposite:!e,showEmpty:!1,title:null,visible:l.enabled&&(c?!1!==c.visible:!0)})},setOptions:function(d){h.prototype.setOptions.call(this,d);this.options.crosshair=this.options.marker},setAxisSize:function(){var d=this.legendSymbol,c=this.chart,e=c.options.legend||
{},q,a;d?(this.left=e=d.attr("x"),this.top=q=d.attr("y"),this.width=a=d.attr("width"),this.height=d=d.attr("height"),this.right=c.chartWidth-e-a,this.bottom=c.chartHeight-q-d,this.len=this.horiz?a:d,this.pos=this.horiz?e:q):this.len=(this.horiz?e.symbolWidth:e.symbolHeight)||this.defaultLegendLength},normalizedValue:function(d){this.isLog&&(d=this.val2lin(d));return 1-(this.max-d)/(this.max-this.min||1)},toColor:function(d,c){var l=this.stops,e=this.dataClasses,a;if(e)for(a=e.length;a--;){var b=e[a];
var g=b.from;l=b.to;if(("undefined"===typeof g||d>=g)&&("undefined"===typeof l||d<=l)){var m=b.color;c&&(c.dataClass=a,c.colorIndex=b.colorIndex);break}}else{d=this.normalizedValue(d);for(a=l.length;a--&&!(d>l[a][0]););g=l[a]||l[a+1];l=l[a+1]||g;d=1-(l[0]-d)/(l[0]-g[0]||1);m=g.color.tweenTo(l.color,d)}return m},getOffset:function(){var d=this.legendGroup,c=this.chart.axisOffset[this.side];d&&(this.axisParent=d,h.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=
this.width),this.chart.axisOffset[this.side]=c)},setLegendColor:function(){var d=this.reversed;var c=d?1:0;d=d?0:1;c=this.horiz?[c,0,d,0]:[0,d,0,c];this.legendColor={linearGradient:{x1:c[0],y1:c[1],x2:c[2],y2:c[3]},stops:this.stops}},drawLegendSymbol:function(d,c){var l=d.padding,e=d.options,a=this.horiz,b=y(e.symbolWidth,a?this.defaultLegendLength:12),g=y(e.symbolHeight,a?12:this.defaultLegendLength),m=y(e.labelPadding,a?16:30);e=y(e.itemDistance,10);this.setLegendColor();c.legendSymbol=this.chart.renderer.rect(0,
d.baseline-11,b,g).attr({zIndex:1}).add(c.legendGroup);this.legendItemWidth=b+l+(a?e:m);this.legendItemHeight=g+l+(a?m:0)},setState:function(d){this.series.forEach(function(c){c.setState(d)})},visible:!0,setVisible:k,getSeriesExtremes:function(){var d=this.series,c=d.length,a;this.dataMin=Infinity;for(this.dataMax=-Infinity;c--;){var q=d[c];var b=q.colorKey=y(q.options.colorKey,q.colorKey,q.pointValKey,q.zoneAxis,"y");var g=q.pointArrayMap;var m=q[b+"Min"]&&q[b+"Max"];if(q[b+"Data"])var p=q[b+"Data"];
else if(g){p=[];g=g.indexOf(b);var k=q.yData;if(0<=g&&k)for(a=0;a<k.length;a++)p.push(y(k[a][g],k[a]))}else p=q.yData;m?(q.minColorValue=q[b+"Min"],q.maxColorValue=q[b+"Max"]):(e.prototype.getExtremes.call(q,p),q.minColorValue=q.dataMin,q.maxColorValue=q.dataMax);"undefined"!==typeof q.minColorValue&&(this.dataMin=Math.min(this.dataMin,q.minColorValue),this.dataMax=Math.max(this.dataMax,q.maxColorValue));m||e.prototype.getExtremes.call(q)}},drawCrosshair:function(d,c){var e=c&&c.plotX,l=c&&c.plotY,
a=this.pos,b=this.len;if(c){var g=this.toPixels(c.getNestedProperty(c.series.colorKey));g<a?g=a-2:g>a+b&&(g=a+b+2);c.plotX=g;c.plotY=this.len-g;h.prototype.drawCrosshair.call(this,d,c);c.plotX=e;c.plotY=l;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||this.cross.attr({fill:this.crosshair.color}))}},getPlotLinePath:function(c){var d=c.translatedValue;return v(d)?
this.horiz?["M",d-4,this.top-6,"L",d+4,this.top-6,d,this.top,"Z"]:["M",this.left,d,"L",this.left-6,d+6,this.left-6,d-6,"Z"]:h.prototype.getPlotLinePath.apply(this,arguments)},update:function(c,e){var d=this.chart,l=d.legend,a=this.buildOptions.call(d,{},c);this.series.forEach(function(c){c.isDirtyData=!0});(c.dataClasses&&l.allItems||this.dataClasses)&&this.destroyItems();d.options[this.coll]=w(this.userOptions,a);h.prototype.update.call(this,a,e);this.legendItem&&(this.setLegendColor(),l.colorizeItem(this,
!0))},destroyItems:function(){var c=this.chart;this.legendItem?c.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(d){c.legend.destroyItem(d)});c.isDirtyLegend=!0},remove:function(c){this.destroyItems();h.prototype.remove.call(this,c)},getDataClassLegendSymbols:function(){var c=this,e=this.chart,a=this.legendItems,b=e.options.legend,g=b.valueDecimals,m=b.valueSuffix||"",t;a.length||this.dataClasses.forEach(function(d,l){var b=!0,q=d.from,A=d.to,C=e.numberFormatter;t="";
"undefined"===typeof q?t="< ":"undefined"===typeof A&&(t="> ");"undefined"!==typeof q&&(t+=C(q,g)+m);"undefined"!==typeof q&&"undefined"!==typeof A&&(t+=" - ");"undefined"!==typeof A&&(t+=C(A,g)+m);a.push(p({chart:e,name:t,options:{},drawLegendSymbol:x.drawRectangle,visible:!0,setState:k,isDataClass:!0,setVisible:function(){b=this.visible=!b;c.series.forEach(function(c){c.points.forEach(function(c){c.dataClass===l&&c.setVisible(b)})});e.legend.colorizeItem(this,b)}},d))});return a},beforePadding:!1,
name:""});["fill","stroke"].forEach(function(c){a.Fx.prototype[c+"Setter"]=function(){this.elem.attr(c,m(this.start).tweenTo(m(this.end),this.pos),null,!0)}});f(b,"afterGetAxes",function(){var d=this,e=d.options;this.colorAxis=[];e.colorAxis&&(e.colorAxis=r(e.colorAxis),e.colorAxis.forEach(function(e,a){e.index=a;new c(d,e)}))});f(e,"bindAxes",function(){var c=this.axisTypes;c?-1===c.indexOf("colorAxis")&&c.push("colorAxis"):this.axisTypes=["colorAxis"]});f(u,"afterGetAllItems",function(c){var d=
[],e,a;(this.chart.colorAxis||[]).forEach(function(a){(e=a.options)&&e.showInLegend&&(e.dataClasses&&e.visible?d=d.concat(a.getDataClassLegendSymbols()):e.visible&&d.push(a),a.series.forEach(function(d){if(!d.options.showInLegend||e.dataClasses)"point"===d.options.legendType?d.points.forEach(function(d){n(c.allItems,d)}):n(c.allItems,d)}))});for(a=d.length;a--;)c.allItems.unshift(d[a])});f(u,"afterColorizeItem",function(c){c.visible&&c.item.legendColor&&c.item.legendSymbol.attr({fill:c.item.legendColor})});
f(u,"afterUpdate",function(){var c=this.chart.colorAxis;c&&c.forEach(function(c,d,e){c.update({},e)})});f(e,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()})});z(f,"parts-map/ColorMapSeriesMixin.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){var f=b.defined;b=a.noop;var n=a.seriesTypes;a.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==
this.value},setState:function(b){a.Point.prototype.setState.call(this,b);this.graphic&&this.graphic.attr({zIndex:"hover"===b?1:0})}};a.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:b,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:n.column.prototype.pointAttribs,colorAttribs:function(a){var b={};f(a.color)&&(b[this.colorProp||"fill"]=a.color);return b}}});z(f,"parts-map/MapNavigation.js",
[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){function f(e){e&&(e.preventDefault&&e.preventDefault(),e.stopPropagation&&e.stopPropagation(),e.cancelBubble=!0)}function n(e){this.init(e)}var p=b.addEvent,v=b.extend,w=b.merge,y=b.objectEach,r=b.pick;b=a.Chart;var h=a.doc;n.prototype.init=function(e){this.chart=e;e.mapNavButtons=[]};n.prototype.update=function(e){var a=this.chart,b=a.options.mapNavigation,h,x,t,k,c,d=function(c){this.handler.call(a,c);f(c)},l=a.mapNavButtons;e&&(b=a.options.mapNavigation=
w(a.options.mapNavigation,e));for(;l.length;)l.pop().destroy();r(b.enableButtons,b.enabled)&&!a.renderer.forExport&&y(b.buttons,function(e,g){h=w(b.buttonOptions,e);a.styledMode||(x=h.theme,x.style=w(h.theme.style,h.style),k=(t=x.states)&&t.hover,c=t&&t.select);e=a.renderer.button(h.text,0,0,d,x,k,c,0,"zoomIn"===g?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[g]).attr({width:h.width,height:h.height,title:a.options.lang[g],padding:h.padding,
zIndex:5}).add();e.handler=h.onclick;p(e.element,"dblclick",f);l.push(e);var q=h,A=p(a,"load",function(){e.align(v(q,{width:e.width,height:2*e.height}),null,q.alignTo);A()})});this.updateEvents(b)};n.prototype.updateEvents=function(e){var a=this.chart;r(e.enableDoubleClickZoom,e.enabled)||e.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||p(a.container,"dblclick",function(e){a.pointer.onContainerDblClick(e)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());r(e.enableMouseWheelZoom,
e.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||p(a.container,"undefined"===typeof h.onmousewheel?"DOMMouseScroll":"mousewheel",function(e){a.pointer.onContainerMouseWheel(e);f(e);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};v(b.prototype,{fitToBox:function(e,a){[["x","width"],["y","height"]].forEach(function(b){var g=b[0];b=b[1];e[g]+e[b]>a[g]+a[b]&&(e[b]>a[b]?(e[b]=a[b],e[g]=a[g]):e[g]=a[g]+a[b]-e[b]);e[b]>a[b]&&(e[b]=a[b]);e[g]<a[g]&&(e[g]=a[g])});
return e},mapZoom:function(e,a,b,f,h){var g=this.xAxis[0],k=g.max-g.min,c=r(a,g.min+k/2),d=k*e;k=this.yAxis[0];var l=k.max-k.min,A=r(b,k.min+l/2);l*=e;c=this.fitToBox({x:c-d*(f?(f-g.pos)/g.len:.5),y:A-l*(h?(h-k.pos)/k.len:.5),width:d,height:l},{x:g.dataMin,y:k.dataMin,width:g.dataMax-g.dataMin,height:k.dataMax-k.dataMin});d=c.x<=g.dataMin&&c.width>=g.dataMax-g.dataMin&&c.y<=k.dataMin&&c.height>=k.dataMax-k.dataMin;f&&(g.fixTo=[f-g.pos,a]);h&&(k.fixTo=[h-k.pos,b]);"undefined"===typeof e||d?(g.setExtremes(void 0,
void 0,!1),k.setExtremes(void 0,void 0,!1)):(g.setExtremes(c.x,c.x+c.width,!1),k.setExtremes(c.y,c.y+c.height,!1));this.redraw()}});p(b,"beforeRender",function(){this.mapNavigation=new n(this);this.mapNavigation.update()});a.MapNavigation=n});z(f,"parts-map/MapPointer.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){var f=b.extend,n=b.pick;b=b.wrap;a=a.Pointer;f(a.prototype,{onContainerDblClick:function(a){var b=this.chart;a=this.normalize(a);b.options.mapNavigation.enableDoubleClickZoomTo?
b.pointer.inClass(a.target,"highcharts-tracker")&&b.hoverPoint&&b.hoverPoint.zoomTo():b.isInsidePlot(a.chartX-b.plotLeft,a.chartY-b.plotTop)&&b.mapZoom(.5,b.xAxis[0].toValue(a.chartX),b.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var b=this.chart;a=this.normalize(a);var f=a.detail||-(a.wheelDelta/120);b.isInsidePlot(a.chartX-b.plotLeft,a.chartY-b.plotTop)&&b.mapZoom(Math.pow(b.options.mapNavigation.mouseWheelSensitivity,f),b.xAxis[0].toValue(a.chartX),b.yAxis[0].toValue(a.chartY),
a.chartX,a.chartY)}});b(a.prototype,"zoomOption",function(a){var b=this.chart.options.mapNavigation;n(b.enableTouchZoom,b.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});b(a.prototype,"pinchTranslate",function(a,b,f,n,r,h,e){a.call(this,b,f,n,r,h,e);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=n.scaleX>n.scaleY,this.pinchTranslateDirection(!a,b,f,n,r,h,e,a?n.scaleX:n.scaleY))})});z(f,"parts-map/MapSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],
function(a,b){var f=b.extend,n=b.getNestedProperty,p=b.isArray,v=b.isNumber,w=b.merge,y=b.objectEach,r=b.pick,h=b.splat,e=a.colorMapPointMixin,g=a.noop,m=a.fireEvent,u=a.Point,x=a.Series,t=a.seriesType,k=a.seriesTypes;t("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,
allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},w(a.colorMapSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:g,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(c){c=x.prototype.setOptions.call(this,c);var d=c.joinBy;null===d&&(d="_i");d=this.joinBy=h(d);d[1]||(d[1]=d[0]);return c},getBox:function(c){var d=
Number.MAX_VALUE,e=-d,b=d,g=-d,f=d,h=d,k=this.xAxis,m=this.yAxis,t;(c||[]).forEach(function(c){if(c.path){"string"===typeof c.path&&(c.path=a.splitPath(c.path));var l=c.path||[],q=l.length,A=!1,k=-d,m=d,C=-d,D=d,E=c.properties;if(!c._foundBox){for(;q--;)v(l[q])&&(A?(k=Math.max(k,l[q]),m=Math.min(m,l[q])):(C=Math.max(C,l[q]),D=Math.min(D,l[q])),A=!A);c._midX=m+(k-m)*r(c.middleX,E&&E["hc-middle-x"],.5);c._midY=D+(C-D)*r(c.middleY,E&&E["hc-middle-y"],.5);c._maxX=k;c._minX=m;c._maxY=C;c._minY=D;c.labelrank=
r(c.labelrank,(k-m)*(C-D));c._foundBox=!0}e=Math.max(e,c._maxX);b=Math.min(b,c._minX);g=Math.max(g,c._maxY);f=Math.min(f,c._minY);h=Math.min(c._maxX-c._minX,c._maxY-c._minY,h);t=!0}});t&&(this.minY=Math.min(f,r(this.minY,d)),this.maxY=Math.max(g,r(this.maxY,-d)),this.minX=Math.min(b,r(this.minX,d)),this.maxX=Math.max(e,r(this.maxX,-d)),k&&"undefined"===typeof k.options.minRange&&(k.minRange=Math.min(5*h,(this.maxX-this.minX)/5,k.minRange||d)),m&&"undefined"===typeof m.options.minRange&&(m.minRange=
Math.min(5*h,(this.maxY-this.minY)/5,m.minRange||d)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){x.prototype.getExtremes.call(this,this.valueData);this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);this.valueMin=this.dataMin;this.valueMax=this.dataMax;this.dataMin=this.minY;this.dataMax=this.maxY},translatePath:function(c){var d=!1,a=this.xAxis,e=this.yAxis,b=a.min,g=a.transA;a=a.minPixelPadding;var f=e.min,k=e.transA;e=e.minPixelPadding;var h,
m=[];if(c)for(h=c.length;h--;)v(c[h])?(m[h]=d?(c[h]-b)*g+a:(c[h]-f)*k+e,d=!d):m[h]=c[h];return m},setData:function(c,d,e,b){var g=this.options,l=this.chart.options.chart,A=l&&l.map,f=g.mapData,h=this.joinBy,k=g.keys||this.pointArrayMap,m=[],t={},u=this.chart.mapTransforms;!f&&A&&(f="string"===typeof A?a.maps[A]:A);c&&c.forEach(function(d,e){var b=0;if(v(d))c[e]={value:d};else if(p(d)){c[e]={};!g.keys&&d.length>k.length&&"string"===typeof d[0]&&(c[e]["hc-key"]=d[0],++b);for(var l=0;l<k.length;++l,
++b)k[l]&&"undefined"!==typeof d[b]&&(0<k[l].indexOf(".")?a.Point.prototype.setNestedProperty(c[e],d[b],k[l]):c[e][k[l]]=d[b])}h&&"_i"===h[0]&&(c[e]._i=e)});this.getBox(c);(this.chart.mapTransforms=u=l&&l.mapTransforms||f&&f["hc-transform"]||u)&&y(u,function(c){c.rotation&&(c.cosAngle=Math.cos(c.rotation),c.sinAngle=Math.sin(c.rotation))});if(f){"FeatureCollection"===f.type&&(this.mapTitle=f.title,f=a.geojson(f,this.type,this));this.mapData=f;this.mapMap={};for(u=0;u<f.length;u++)l=f[u],A=l.properties,
l._i=u,h[0]&&A&&A[h[0]]&&(l[h[0]]=A[h[0]]),t[l[h[0]]]=l;this.mapMap=t;if(c&&h[1]){var r=h[1];c.forEach(function(c){c=n(r,c);t[c]&&m.push(t[c])})}if(g.allAreas){this.getBox(f);c=c||[];if(h[1]){var B=h[1];c.forEach(function(c){m.push(n(B,c))})}m="|"+m.map(function(c){return c&&c[h[0]]}).join("|")+"|";f.forEach(function(d){h[0]&&-1!==m.indexOf("|"+d[h[0]]+"|")||(c.push(w(d,{value:null})),b=!1)})}else this.getBox(m)}x.prototype.setData.call(this,c,d,e,b)},drawGraph:g,drawDataLabels:g,doFullTranslate:function(){return this.isDirtyData||
this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans},translate:function(){var c=this,d=c.xAxis,a=c.yAxis,e=c.doFullTranslate();c.generatePoints();c.data.forEach(function(b){v(b._midX)&&v(b._midY)&&(b.plotX=d.toPixels(b._midX,!0),b.plotY=a.toPixels(b._midY,!0));e&&(b.shapeType="path",b.shapeArgs={d:c.translatePath(b.path)})});m(c,"afterTranslate")},pointAttribs:function(c,d){d=c.series.chart.styledMode?this.colorAttribs(c):k.column.prototype.pointAttribs.call(this,c,d);d["stroke-width"]=
r(c.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return d},drawPoints:function(){var c=this,d=c.xAxis,a=c.yAxis,e=c.group,b=c.chart,g=b.renderer,f=this.baseTrans;c.transformGroup||(c.transformGroup=g.g().attr({scaleX:1,scaleY:1}).add(e),c.transformGroup.survive=!0);if(c.doFullTranslate())b.hasRendered&&!b.styledMode&&c.points.forEach(function(d){d.shapeArgs&&(d.shapeArgs.fill=c.pointAttribs(d,d.state).fill)}),c.group=c.transformGroup,k.column.prototype.drawPoints.apply(c),
c.group=e,c.points.forEach(function(d){if(d.graphic){var a="";d.name&&(a+="highcharts-name-"+d.name.replace(/ /g,"-").toLowerCase());d.properties&&d.properties["hc-key"]&&(a+=" highcharts-key-"+d.properties["hc-key"].toLowerCase());a&&d.graphic.addClass(a);b.styledMode&&d.graphic.css(c.pointAttribs(d,d.selected&&"select"||void 0))}}),this.baseTrans={originX:d.min-d.minPixelPadding/d.transA,originY:a.min-a.minPixelPadding/a.transA+(a.reversed?0:a.len/a.transA),transAX:d.transA,transAY:a.transA},this.transformGroup.animate({translateX:0,
translateY:0,scaleX:1,scaleY:1});else{var h=d.transA/f.transAX;var m=a.transA/f.transAY;var t=d.toPixels(f.originX,!0);var p=a.toPixels(f.originY,!0);.99<h&&1.01>h&&.99<m&&1.01>m&&(m=h=1,t=Math.round(t),p=Math.round(p));var u=this.transformGroup;if(b.renderer.globalAnimation){var n=u.attr("translateX");var x=u.attr("translateY");var v=u.attr("scaleX");var w=u.attr("scaleY");u.attr({animator:0}).animate({animator:1},{step:function(c,d){u.attr({translateX:n+(t-n)*d.pos,translateY:x+(p-x)*d.pos,scaleX:v+
(h-v)*d.pos,scaleY:w+(m-w)*d.pos})}})}else u.attr({translateX:t,translateY:p,scaleX:h,scaleY:m})}b.styledMode||e.element.setAttribute("stroke-width",r(c.options[c.pointAttrToOptions&&c.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(h||1));this.drawMapDataLabels()},drawMapDataLabels:function(){x.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var c=this,d=x.prototype.render;c.chart.renderer.isVML&&3E3<c.data.length?
setTimeout(function(){d.call(c)}):d.call(c)},animate:function(c){var d=this.options.animation,a=this.group,e=this.xAxis,b=this.yAxis,g=e.pos,f=b.pos;this.chart.renderer.isSVG&&(!0===d&&(d={duration:1E3}),c?a.attr({translateX:g+e.len/2,translateY:f+b.len/2,scaleX:.001,scaleY:.001}):(a.animate({translateX:g,translateY:f,scaleX:1,scaleY:1},d),this.animate=null))},animateDrilldown:function(c){var d=this.chart.plotBox,a=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],e=a.bBox,b=this.chart.options.drilldown.animation;
c||(c=Math.min(e.width/d.width,e.height/d.height),a.shapeArgs={scaleX:c,scaleY:c,translateX:e.x,translateY:e.y},this.points.forEach(function(c){c.graphic&&c.graphic.attr(a.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},b)}),this.animate=null)},drawLegendSymbol:a.LegendSymbolMixin.drawRectangle,animateDrillupFrom:function(c){k.column.prototype.animateDrillupFrom.call(this,c)},animateDrillupTo:function(c){k.column.prototype.animateDrillupTo.call(this,c)}}),f({applyOptions:function(c,
d){var a=this.series;c=u.prototype.applyOptions.call(this,c,d);d=a.joinBy;a.mapData&&a.mapMap&&(d=u.prototype.getNestedProperty.call(c,d[1]),(d="undefined"!==typeof d&&a.mapMap[d])?(a.xyFromShape&&(c.x=d._midX,c.y=d._midY),f(c,d)):c.value=c.value||null);return c},onMouseOver:function(c){b.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)u.prototype.onMouseOver.call(this,c);else this.series.onMouseOut(c)},zoomTo:function(){var c=this.series;c.xAxis.setExtremes(this._minX,
this._maxX,!1);c.yAxis.setExtremes(this._minY,this._maxY,!1);c.chart.redraw()}},e));""});z(f,"parts-map/MapLineSeries.js",[f["parts/Globals.js"]],function(a){var b=a.seriesType,f=a.seriesTypes;b("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,b){a=f.map.prototype.pointAttribs.call(this,a,b);a.fill=this.options.fillColor;return a},drawLegendSymbol:f.line.prototype.drawLegendSymbol});
""});z(f,"parts-map/MapPointSeries.js",[f["parts/Globals.js"]],function(a){var b=a.merge,f=a.Point,n=a.Series;a=a.seriesType;a("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0,drawDataLabels:function(){n.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}},{applyOptions:function(a,n){a="undefined"!==typeof a.lat&&"undefined"!==
typeof a.lon?b(a,this.series.chart.fromLatLonToPoint(a)):a;return f.prototype.applyOptions.call(this,a,n)}});""});z(f,"parts-more/BubbleLegend.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){var f=b.addEvent,n=b.arrayMax,p=b.arrayMin,v=b.isNumber,w=b.merge,y=b.objectEach,r=b.pick,h=b.stableSort,e=b.wrap,g=a.Series,m=a.Legend,u=a.Chart,x=a.color,t=a.noop,k=a.setOptions;k({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,
connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});a.BubbleLegend=function(c,d){this.init(c,d)};a.BubbleLegend.prototype={init:function(c,d){this.options=c;this.visible=!0;this.chart=
d.chart;this.legend=d},setState:t,addToLegend:function(c){c.splice(this.options.legendIndex,0,this)},drawLegendSymbol:function(c){var d=this.chart,a=this.options,e=r(c.options.itemDistance,20),b=a.ranges;var g=a.connectorDistance;this.fontMetrics=d.renderer.fontMetrics(a.labels.style.fontSize.toString()+"px");b&&b.length&&v(b[0].value)?(h(b,function(c,d){return d.value-c.value}),this.ranges=b,this.setOptions(),this.render(),d=this.getMaxLabelSize(),b=this.ranges[0].radius,c=2*b,g=g-b+d.width,g=0<
g?g:0,this.maxLabel=d,this.movementX="left"===a.labels.align?g:0,this.legendItemWidth=c+g+e,this.legendItemHeight=c+this.fontMetrics.h/2):c.options.bubbleLegend.autoRanges=!0},setOptions:function(){var c=this.ranges,d=this.options,a=this.chart.series[d.seriesIndex],e=this.legend.baseline,b={"z-index":d.zIndex,"stroke-width":d.borderWidth},g={"z-index":d.zIndex,"stroke-width":d.connectorWidth},f=this.getLabelStyles(),h=a.options.marker.fillOpacity,m=this.chart.styledMode;c.forEach(function(l,k){m||
(b.stroke=r(l.borderColor,d.borderColor,a.color),b.fill=r(l.color,d.color,1!==h?x(a.color).setOpacity(h).get("rgba"):a.color),g.stroke=r(l.connectorColor,d.connectorColor,a.color));c[k].radius=this.getRangeRadius(l.value);c[k]=w(c[k],{center:c[0].radius-c[k].radius+e});m||w(!0,c[k],{bubbleStyle:w(!1,b),connectorStyle:w(!1,g),labelStyle:f})},this)},getLabelStyles:function(){var c=this.options,d={},a="left"===c.labels.align,e=this.legend.options.rtl;y(c.labels.style,function(c,a){"color"!==a&&"fontSize"!==
a&&"z-index"!==a&&(d[a]=c)});return w(!1,d,{"font-size":c.labels.style.fontSize,fill:r(c.labels.style.color,"#000000"),"z-index":c.zIndex,align:e||a?"right":"left"})},getRangeRadius:function(c){var d=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,d.ranges[d.ranges.length-1].value,d.ranges[0].value,d.minSize,d.maxSize,c)},render:function(){var c=this.chart.renderer,d=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=
c.g("bubble-legend");this.legendItem=c.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(c){c.value>=d&&this.renderRange(c)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()},renderRange:function(c){var d=this.options,a=d.labels,e=this.chart.renderer,b=this.symbols,g=b.labels,f=c.center,h=Math.abs(c.radius),k=d.connectorDistance,m=a.align,t=a.style.fontSize;k=this.legend.options.rtl||
"left"===m?-k:k;a=d.connectorWidth;var u=this.ranges[0].radius,n=f-h-d.borderWidth/2+a/2;t=t/2-(this.fontMetrics.h-t)/2;var x=e.styledMode;"center"===m&&(k=0,d.connectorDistance=0,c.labelStyle.align="center");m=n+d.labels.y;var p=u+k+d.labels.x;b.bubbleItems.push(e.circle(u,f+((n%1?1:.5)-(a%2?0:.5)),h).attr(x?{}:c.bubbleStyle).addClass((x?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(d.className||"")).add(this.legendSymbol));b.connectors.push(e.path(e.crispLine(["M",
u,n,"L",u+k,n],d.connectorWidth)).attr(x?{}:c.connectorStyle).addClass((x?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(d.connectorClassName||"")).add(this.legendSymbol));c=e.text(this.formatLabel(c),p,m+t).attr(x?{}:c.labelStyle).addClass("highcharts-bubble-legend-labels "+(d.labels.className||"")).add(this.legendSymbol);g.push(c);c.placed=!0;c.alignAttr={x:p,y:m+t}},getMaxLabelSize:function(){var c,d;this.symbols.labels.forEach(function(a){d=a.getBBox(!0);
c=c?d.width>c.width?d:c:d});return c||{}},formatLabel:function(c){var d=this.options,a=d.labels.formatter;d=d.labels.format;var e=this.chart.numberFormatter;return d?b.format(d,c):a?a.call(c):e(c.value,1)},hideOverlappingLabels:function(){var c=this.chart,d=this.symbols;!this.options.labels.allowOverlap&&d&&(c.hideOverlappingLabels(d.labels),d.labels.forEach(function(c,a){c.newOpacity?c.newOpacity!==c.oldOpacity&&d.connectors[a].show():d.connectors[a].hide()}))},getRanges:function(){var c=this.legend.bubbleLegend,
a=c.options.ranges,e,b=Number.MAX_VALUE,g=-Number.MAX_VALUE;c.chart.series.forEach(function(c){c.isBubble&&!c.ignoreSeries&&(e=c.zData.filter(v),e.length&&(b=r(c.options.zMin,Math.min(b,Math.max(p(e),!1===c.options.displayNegative?c.options.zThreshold:-Number.MAX_VALUE))),g=r(c.options.zMax,Math.max(g,n(e)))))});var f=b===g?[{value:g}]:[{value:b},{value:(b+g)/2},{value:g,autoRanges:!0}];a.length&&a[0].radius&&f.reverse();f.forEach(function(c,d){a&&a[d]&&(f[d]=w(!1,a[d],c))});return f},predictBubbleSizes:function(){var c=
this.chart,a=this.fontMetrics,e=c.legend.options,b="horizontal"===e.layout,g=b?c.legend.lastLineHeight:0,f=c.plotSizeX,h=c.plotSizeY,k=c.series[this.options.seriesIndex];c=Math.ceil(k.minPxSize);var m=Math.ceil(k.maxPxSize);k=k.options.maxSize;var t=Math.min(h,f);if(e.floating||!/%$/.test(k))a=m;else if(k=parseFloat(k),a=(t+g-a.h/2)*k/100/(k/100+1),b&&h-a>=f||!b&&f-a>=h)a=m;return[c,Math.ceil(a)]},updateRanges:function(c,a){var d=this.legend.options.bubbleLegend;d.minSize=c;d.maxSize=a;d.ranges=this.getRanges()},
correctSizes:function(){var c=this.legend,a=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,a.maxPxSize),c.render())}};f(a.Legend,"afterGetAllItems",function(c){var d=this.bubbleLegend,e=this.options,b=e.bubbleLegend,g=this.chart.getVisibleBubbleSeriesIndex();d&&d.ranges&&d.ranges.length&&(b.ranges.length&&(b.autoRanges=!!b.ranges[0].autoRanges),this.destroyItem(d));0<=g&&e.enabled&&b.enabled&&(b.seriesIndex=
g,this.bubbleLegend=new a.BubbleLegend(b,this),this.bubbleLegend.addToLegend(c.allItems))});u.prototype.getVisibleBubbleSeriesIndex=function(){for(var c=this.series,a=0;a<c.length;){if(c[a]&&c[a].isBubble&&c[a].visible&&c[a].zData.length)return a;a++}return-1};m.prototype.getLinesHeights=function(){var c=this.allItems,a=[],e=c.length,b,g=0;for(b=0;b<e;b++)if(c[b].legendItemHeight&&(c[b].itemHeight=c[b].legendItemHeight),c[b]===c[e-1]||c[b+1]&&c[b]._legendItemPos[1]!==c[b+1]._legendItemPos[1]){a.push({height:0});
var f=a[a.length-1];for(g;g<=b;g++)c[g].itemHeight>f.height&&(f.height=c[g].itemHeight);f.step=b}return a};m.prototype.retranslateItems=function(c){var a,b,e,g=this.options.rtl,f=0;this.allItems.forEach(function(d,h){a=d.legendGroup.translateX;b=d._legendItemPos[1];if((e=d.movementX)||g&&d.ranges)e=g?a-d.options.maxSize/2:a+e,d.legendGroup.attr({translateX:e});h>c[f].step&&f++;d.legendGroup.attr({translateY:Math.round(b+c[f].height/2)});d._legendItemPos[1]=b+c[f].height/2})};f(g,"legendItemClick",
function(){var c=this.chart,a=this.visible,b=this.chart.legend;b&&b.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,c=0<=c.getVisibleBubbleSeriesIndex(),b.bubbleLegend.visible!==c&&(b.update({bubbleLegend:{enabled:c}}),b.bubbleLegend.visible=c),this.visible=a)});e(u.prototype,"drawChartBox",function(c,a,b){var d=this.legend,e=0<=this.getVisibleBubbleSeriesIndex();if(d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&e){var g=d.bubbleLegend.options;e=d.bubbleLegend.predictBubbleSizes();
d.bubbleLegend.updateRanges(e[0],e[1]);g.placed||(d.group.placed=!1,d.allItems.forEach(function(c){c.legendGroup.translateY=null}));d.render();this.getMargins();this.axes.forEach(function(c){c.visible&&c.render();g.placed||(c.setScale(),c.updateNames(),y(c.ticks,function(c){c.isNew=!0;c.isNewLabel=!0}))});g.placed=!0;this.getMargins();c.call(this,a,b);d.bubbleLegend.correctSizes();d.retranslateItems(d.getLinesHeights())}else c.call(this,a,b),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),d.retranslateItems(d.getLinesHeights()))})});
z(f,"parts-more/BubbleSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){var f=b.arrayMax,n=b.arrayMin,p=b.clamp,v=b.extend,w=b.isNumber,y=b.pick,r=b.pInt;b=a.Axis;var h=a.color,e=a.noop,g=a.Point,m=a.Series,u=a.seriesType,x=a.seriesTypes;u("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,
maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,b){var c=this.options.marker.fillOpacity;a=m.prototype.pointAttribs.call(this,a,b);1!==c&&(a.fill=h(a.fill).setOpacity(c).get("rgba"));
return a},getRadii:function(a,b,c){var d=this.zData,e=this.yData,g=c.minPxSize,f=c.maxPxSize,h=[];var k=0;for(c=d.length;k<c;k++){var m=d[k];h.push(this.getRadius(a,b,g,f,m,e[k]))}this.radii=h},getRadius:function(a,b,c,d,e,g){var f=this.options,h="width"!==f.sizeBy,k=f.zThreshold,m=b-a,l=.5;if(null===g||null===e)return null;if(w(e)){f.sizeByAbsoluteValue&&(e=Math.abs(e-k),m=Math.max(b-k,Math.abs(a-k)),a=0);if(e<a)return c/2-1;0<m&&(l=(e-a)/m)}h&&0<=l&&(l=Math.sqrt(l));return Math.ceil(c+l*(d-c))/
2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&(this.points.forEach(function(a){var c=a.graphic;if(c&&c.width){var d={x:c.x,y:c.y,width:c.width,height:c.height};c.attr({x:a.plotX,y:a.plotY,width:1,height:1});c.animate(d,this.options.animation)}},this),this.animate=null)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,b=this.data,c=this.radii;x.scatter.prototype.translate.call(this);for(a=b.length;a--;){var d=b[a];var e=c?c[a]:0;w(e)&&
e>=this.minPxSize/2?(d.marker=v(d.marker,{radius:e,width:2*e,height:2*e}),d.dlBox={x:d.plotX-e,y:d.plotY-e,width:2*e,height:2*e}):d.shapeArgs=d.plotY=d.dlBox=void 0}},alignDataLabel:x.column.prototype.alignDataLabel,buildKDTree:e,applyZones:e},{haloPath:function(a){return g.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});b.prototype.beforePadding=function(){var a=this,b=this.len,c=this.chart,d=0,e=b,g=this.isXAxis,h=g?"xData":"yData",m=this.min,u={},x=Math.min(c.plotWidth,
c.plotHeight),v=Number.MAX_VALUE,z=-Number.MAX_VALUE,B=this.max-m,F=b/B,G=[];this.series.forEach(function(b){var e=b.options;!b.bubblePadding||!b.visible&&c.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,G.push(b),g&&(["minSize","maxSize"].forEach(function(c){var a=e[c],b=/%$/.test(a);a=r(a);u[c]=b?x*a/100:a}),b.minPxSize=u.minSize,b.maxPxSize=Math.max(u.maxSize,u.minSize),b=b.zData.filter(w),b.length&&(v=y(e.zMin,p(n(b),!1===e.displayNegative?e.zThreshold:-Number.MAX_VALUE,v)),z=y(e.zMax,
Math.max(z,f(b))))))});G.forEach(function(c){var b=c[h],f=b.length;g&&c.getRadii(v,z,c);if(0<B)for(;f--;)if(w(b[f])&&a.dataMin<=b[f]&&b[f]<=a.max){var k=c.radii?c.radii[f]:0;d=Math.min((b[f]-m)*F-k,d);e=Math.max((b[f]-m)*F+k,e)}});G.length&&0<B&&!this.isLog&&(e-=b,F*=(b+Math.max(0,d)-Math.min(e,b))/b,[["min","userMin",d],["max","userMax",e]].forEach(function(c){"undefined"===typeof y(a.options[c[0]],a[c[1]])&&(a[c[0]]+=c[2]/F)}))};""});z(f,"parts-map/MapBubbleSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],
function(a,b){var f=b.merge,n=a.Point;b=a.seriesType;var p=a.seriesTypes;p.bubble&&b("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:p.map.prototype.getMapData,getBox:p.map.prototype.getBox,setData:p.map.prototype.setData,setOptions:p.map.prototype.setOptions},{applyOptions:function(a,b){return a&&"undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?n.prototype.applyOptions.call(this,f(a,this.series.chart.fromLatLonToPoint(a)),
b):p.map.prototype.pointClass.prototype.applyOptions.call(this,a,b)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});z(f,"parts-map/HeatmapSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){var f=b.clamp,n=b.extend,p=b.merge,v=b.pick;b=a.colorMapPointMixin;var w=a.noop,y=a.fireEvent,r=a.Series,h=a.seriesType,e=a.seriesTypes;h("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,
verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:null,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},p(a.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){e.scatter.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=v(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1},translate:function(){this.generatePoints();
var a=this.options,b=a.colsize,e=a.pointPadding,h=void 0===e?0:e;a=a.rowsize;e=this.points;var t=this.xAxis,k=this.yAxis,c=(void 0===b?1:b)/2,d=(void 0===a?1:a)/2,l=this.pointPlacementToXValue(),n=function(c){return Math.round(f(t.translate(c,!1,!1,!1,!0,l),0,t.len))};e.forEach(function(a){var b=n(a.x-c),e=n(a.x+c),g=Math.round(f(k.translate(a.y-d,!1,!0,!1,!0),0,k.len)),m=Math.round(f(k.translate(a.y+d,!1,!0,!1,!0),0,k.len)),l=v(a.pointPadding,h);a.plotX=a.clientX=(b+e)/2;a.plotY=(g+m)/2;a.shapeType=
"rect";a.shapeArgs={x:Math.min(b,e)+l,y:Math.min(g,m)+l,width:Math.max(Math.abs(e-b)-2*l,0),height:Math.max(Math.abs(m-g)-2*l,0)}});y(this,"afterTranslate")},drawPoints:function(){var a=this.chart.styledMode?"css":"animate";e.column.prototype.drawPoints.call(this);this.points.forEach(function(b){b.graphic[a](this.colorAttribs(b))},this)},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,b){return r.prototype.getValidPoints.call(this,a,b,!0)},animate:w,getBox:w,drawLegendSymbol:a.LegendSymbolMixin.drawRectangle,
alignDataLabel:e.column.prototype.alignDataLabel,getExtremes:function(){r.prototype.getExtremes.call(this,this.valueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;r.prototype.getExtremes.call(this)}}),n({haloPath:function(a){if(!a)return[];var b=this.shapeArgs;return["M",b.x-a,b.y-a,"L",b.x-a,b.y+b.height+a,b.x+b.width+a,b.y+b.height+a,b.x+b.width+a,b.y-a,"Z"]}},b));""});z(f,"parts-map/GeoJSON.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){function f(a,b){var e,f=!1,
h=a.x,n=a.y;a=0;for(e=b.length-1;a<b.length;e=a++){var t=b[a][1]>n;var k=b[e][1]>n;t!==k&&h<(b[e][0]-b[a][0])*(n-b[a][1])/(b[e][1]-b[a][1])+b[a][0]&&(f=!f)}return f}var n=b.error,p=b.extend,v=b.format,w=b.merge;b=b.wrap;var y=a.Chart,r=a.win;y.prototype.transformFromLatLon=function(a,b){var e,f=(null===(e=this.userOptions.chart)||void 0===e?void 0:e.proj4)||r.proj4;if(!f)return n(21,!1,this),{x:0,y:null};a=f(b.crs,[a.lon,a.lat]);e=b.cosAngle||b.rotation&&Math.cos(b.rotation);f=b.sinAngle||b.rotation&&
Math.sin(b.rotation);a=b.rotation?[a[0]*e+a[1]*f,-a[0]*f+a[1]*e]:a;return{x:((a[0]-(b.xoffset||0))*(b.scale||1)+(b.xpan||0))*(b.jsonres||1)+(b.jsonmarginX||0),y:(((b.yoffset||0)-a[1])*(b.scale||1)+(b.ypan||0))*(b.jsonres||1)-(b.jsonmarginY||0)}};y.prototype.transformToLatLon=function(a,b){if("undefined"===typeof r.proj4)n(21,!1,this);else{a={x:((a.x-(b.jsonmarginX||0))/(b.jsonres||1)-(b.xpan||0))/(b.scale||1)+(b.xoffset||0),y:((-a.y-(b.jsonmarginY||0))/(b.jsonres||1)+(b.ypan||0))/(b.scale||1)+(b.yoffset||
0)};var e=b.cosAngle||b.rotation&&Math.cos(b.rotation),f=b.sinAngle||b.rotation&&Math.sin(b.rotation);b=r.proj4(b.crs,"WGS84",b.rotation?{x:a.x*e+a.y*-f,y:a.x*f+a.y*e}:a);return{lat:b.y,lon:b.x}}};y.prototype.fromPointToLatLon=function(a){var b=this.mapTransforms,g;if(b){for(g in b)if(Object.hasOwnProperty.call(b,g)&&b[g].hitZone&&f({x:a.x,y:-a.y},b[g].hitZone.coordinates[0]))return this.transformToLatLon(a,b[g]);return this.transformToLatLon(a,b["default"])}n(22,!1,this)};y.prototype.fromLatLonToPoint=
function(a){var b=this.mapTransforms,g;if(!b)return n(22,!1,this),{x:0,y:null};for(g in b)if(Object.hasOwnProperty.call(b,g)&&b[g].hitZone){var h=this.transformFromLatLon(a,b[g]);if(f({x:h.x,y:-h.y},b[g].hitZone.coordinates[0]))return h}return this.transformFromLatLon(a,b["default"])};a.geojson=function(a,b,f){var e=[],g=[],h=function(a){var b,c=a.length;g.push("M");for(b=0;b<c;b++)1===b&&g.push("L"),g.push(a[b][0],-a[b][1])};b=b||"map";a.features.forEach(function(a){var f=a.geometry,c=f.type;f=f.coordinates;
a=a.properties;var d;g=[];"map"===b||"mapbubble"===b?("Polygon"===c?(f.forEach(h),g.push("Z")):"MultiPolygon"===c&&(f.forEach(function(a){a.forEach(h)}),g.push("Z")),g.length&&(d={path:g})):"mapline"===b?("LineString"===c?h(f):"MultiLineString"===c&&f.forEach(h),g.length&&(d={path:g})):"mappoint"===b&&"Point"===c&&(d={x:f[0],y:-f[1]});d&&e.push(p(d,{name:a.name||a.NAME,properties:a}))});f&&a.copyrightShort&&(f.chart.mapCredits=v(f.chart.options.credits.mapText,{geojson:a}),f.chart.mapCreditsFull=
v(f.chart.options.credits.mapTextFull,{geojson:a}));return e};b(y.prototype,"addCredits",function(a,b){b=w(!0,this.options.credits,b);this.mapCredits&&(b.href=null);a.call(this,b);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});z(f,"parts-map/Map.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(a,b){function f(a,b,f,h,n,p,k,c){return["M",a+n,b,"L",a+f-p,b,"C",a+f-p/2,b,a+f,b+p/2,a+f,b+p,"L",a+f,b+h-k,"C",a+f,b+h-k/2,a+f-k/2,b+h,a+f-k,b+h,"L",a+c,b+
h,"C",a+c/2,b+h,a,b+h-c/2,a,b+h-c,"L",a,b+n,"C",a,b+n/2,a+n/2,b,a+n,b,"Z"]}var n=b.extend,p=b.merge,v=b.pick,w=a.Chart;b=a.defaultOptions;var y=a.Renderer,r=a.SVGRenderer,h=a.VMLRenderer;n(b.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});b.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",
y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};a.splitPath=function(a){var b;a=a.replace(/([A-Za-z])/g," $1 ");a=a.replace(/^\s*/,"").replace(/\s*$/,"");a=a.split(/[ ,]+/);for(b=0;b<a.length;b++)/[a-zA-Z]/.test(a[b])||(a[b]=parseFloat(a[b]));return a};a.maps={};r.prototype.symbols.topbutton=function(a,b,h,n,p){return f(a-1,b-1,h,n,p.r,p.r,0,0)};r.prototype.symbols.bottombutton=function(a,b,h,n,p){return f(a-1,b-1,h,n,0,0,p.r,p.r)};y===h&&["topbutton",
"bottombutton"].forEach(function(a){h.prototype.symbols[a]=r.prototype.symbols[a]});a.Map=a.mapChart=function(b,f,h){var e="string"===typeof b||b.nodeName,g=arguments[e?1:0],m=g,k={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},c=a.getOptions().credits;var d=g.series;g.series=null;g=p({chart:{panning:"xy",type:"map"},credits:{mapText:v(c.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:v(c.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},
xAxis:k,yAxis:p(k,{reversed:!0})},g,{chart:{inverted:!1,alignTicks:!1}});g.series=m.series=d;return e?new w(b,g,h):new w(g,f)}});z(f,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map