/*
 Highstock JS v8.0.0 (2020-02-08)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(z){"object"===typeof module&&module.exports?(z["default"]=z,module.exports=z):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(I){z(I);z.Highcharts=I;return z}):z("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(z){function I(m,c,x,v){m.hasOwnProperty(c)||(m[c]=v.apply(null,x))}z=z?z._modules:{};I(z,"parts/Scrollbar.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){function x(a,f,l){this.init(a,f,l)}var v=c.addEvent,
H=c.correctFloat,w=c.defined,F=c.destroyObjectProperties,t=c.fireEvent,u=c.merge,E=c.pick,b=c.removeEvent;c=m.Axis;var r=m.defaultOptions,n=m.hasTouch,B,g={height:m.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",
trackBorderColor:"#f2f2f2",trackBorderWidth:1};r.scrollbar=u(!0,g,r.scrollbar);m.swapXY=B=function(a,f){var l=a.length;if(f)for(f=0;f<l;f+=3){var b=a[f+1];a[f+1]=a[f+2];a[f+2]=b}return a};x.prototype={init:function(a,f,l){this.scrollbarButtons=[];this.renderer=a;this.userOptions=f;this.options=u(g,f);this.chart=l;this.size=E(this.options.size,this.options.height);f.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,f=this.options,l=this.size,b=this.chart.styledMode,
d;this.group=d=a.g("scrollbar").attr({zIndex:f.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:f.trackBorderRadius||0,height:l,width:l}).add(d);b||this.track.attr({fill:f.trackBackgroundColor,stroke:f.trackBorderColor,"stroke-width":f.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(d);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:l,
width:l,r:f.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(B(["M",-3,l/4,"L",-3,2*l/3,"M",0,l/4,"L",0,2*l/3,"M",3,l/4,"L",3,2*l/3],f.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);b||(this.scrollbar.attr({fill:f.barBackgroundColor,stroke:f.barBorderColor,"stroke-width":f.barBorderWidth}),this.scrollbarRifles.attr({stroke:f.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%
2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,f,l,b){var d=this.options.vertical,k=0,q=this.rendered?"animate":"attr";this.x=a;this.y=f+this.trackBorderWidth;this.width=l;this.xOffset=this.height=b;this.yOffset=k;d?(this.width=this.yOffset=l=k=this.size,this.xOffset=f=0,this.barWidth=b-2*l,this.x=a+=this.options.margin):(this.height=this.xOffset=b=f=this.size,this.barWidth=l-2*b,this.y+=this.options.margin);this.group[q]({translateX:a,
translateY:this.y});this.track[q]({width:l,height:b});this.scrollbarButtons[1][q]({translateX:d?0:l-f,translateY:d?b-k:0})},drawScrollbarButton:function(a){var f=this.renderer,l=this.scrollbarButtons,b=this.options,d=this.size;var k=f.g().add(this.group);l.push(k);k=f.rect().addClass("highcharts-scrollbar-button").add(k);this.chart.styledMode||k.attr({stroke:b.buttonBorderColor,"stroke-width":b.buttonBorderWidth,fill:b.buttonBackgroundColor});k.attr(k.crisp({x:-.5,y:-.5,width:d+1,height:d+1,r:b.buttonBorderRadius},
k.strokeWidth()));k=f.path(B(["M",d/2+(a?-1:1),d/2-3,"L",d/2+(a?-1:1),d/2+3,"L",d/2+(a?2:-2),d/2],b.vertical)).addClass("highcharts-scrollbar-arrow").add(l[a]);this.chart.styledMode||k.attr({fill:b.buttonArrowColor})},setRange:function(a,f){var l=this.options,b=l.vertical,d=l.minWidth,k=this.barWidth,q,g=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(w(k)){a=Math.max(a,0);var r=Math.ceil(k*a);this.calculatedWidth=q=H(k*Math.min(f,1)-r);q<
d&&(r=(k-d+q)*a,q=d);d=Math.floor(r+this.xOffset+this.yOffset);k=q/2-.5;this.from=a;this.to=f;b?(this.scrollbarGroup[g]({translateY:d}),this.scrollbar[g]({height:q}),this.scrollbarRifles[g]({translateY:k}),this.scrollbarTop=d,this.scrollbarLeft=0):(this.scrollbarGroup[g]({translateX:d}),this.scrollbar[g]({width:q}),this.scrollbarRifles[g]({translateX:k}),this.scrollbarLeft=d,this.scrollbarTop=0);12>=q?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===l.showFull&&(0>=a&&1<=f?this.group.hide():
this.group.show());this.rendered=!0}},initEvents:function(){var a=this;a.mouseMoveHandler=function(f){var l=a.chart.pointer.normalize(f),b=a.options.vertical?"chartY":"chartX",d=a.initPositions;!a.grabbedCenter||f.touches&&0===f.touches[0][b]||(l=a.cursorToScrollbarPosition(l)[b],b=a[b],b=l-b,a.hasDragged=!0,a.updatePosition(d[0]+b,d[1]+b),a.hasDragged&&t(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:f.type,DOMEvent:f}))};a.mouseUpHandler=function(f){a.hasDragged&&t(a,"changed",{from:a.from,
to:a.to,trigger:"scrollbar",DOMType:f.type,DOMEvent:f});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(f){f=a.chart.pointer.normalize(f);f=a.cursorToScrollbarPosition(f);a.chartX=f.chartX;a.chartY=f.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(f){var l=H(a.to-a.from)*a.options.step;a.updatePosition(H(a.from-l),H(a.to-l));t(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:f})};a.buttonToMaxClick=function(f){var l=
(a.to-a.from)*a.options.step;a.updatePosition(a.from+l,a.to+l);t(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:f})};a.trackClick=function(f){var l=a.chart.pointer.normalize(f),b=a.to-a.from,d=a.y+a.scrollbarTop,k=a.x+a.scrollbarLeft;a.options.vertical&&l.chartY>d||!a.options.vertical&&l.chartX>k?a.updatePosition(a.from+b,a.to+b):a.updatePosition(a.from-b,a.to-b);t(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:f})}},cursorToScrollbarPosition:function(a){var f=this.options;
f=f.minWidth>this.calculatedWidth?f.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-f),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-f)}},updatePosition:function(a,f){1<f&&(a=H(1-H(f-a)),f=1);0>a&&(f=H(f-a),a=0);this.from=a;this.to=f},update:function(a){this.destroy();this.init(this.chart.renderer,u(!0,this.options,a),this.chart)},addEvents:function(){var a=this.options.inverted?[1,0]:[0,1],f=this.scrollbarButtons,b=this.scrollbarGroup.element,g=this.mouseDownHandler,
d=this.mouseMoveHandler,k=this.mouseUpHandler;a=[[f[a[0]].element,"click",this.buttonToMinClick],[f[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[b,"mousedown",g],[b.ownerDocument,"mousemove",d],[b.ownerDocument,"mouseup",k]];n&&a.push([b,"touchstart",g],[b.ownerDocument,"touchmove",d],[b.ownerDocument,"touchend",k]);a.forEach(function(a){v.apply(null,a)});this._events=a},removeEvents:function(){this._events.forEach(function(a){b.apply(null,a)});this._events.length=
0},destroy:function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,F(a.scrollbarButtons))}};m.Scrollbar||(v(c,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new x(a.chart.renderer,
a.options.scrollbar,a.chart),v(a.scrollbar,"changed",function(f){var b=Math.min(E(a.options.min,a.min),a.min,a.dataMin),g=Math.max(E(a.options.max,a.max),a.max,a.dataMax)-b;if(a.horiz&&!a.reversed||!a.horiz&&a.reversed){var d=b+g*this.to;b+=g*this.from}else d=b+g*(1-this.from),b+=g*(1-this.to);E(this.options.liveRedraw,m.svg&&!m.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===f.DOMType||!w(f.DOMType)?a.setExtremes(b,d,!0,"mousemove"!==f.DOMType,f):this.setRange(this.from,this.to)}))}),v(c,"afterRender",
function(){var a=Math.min(E(this.options.min,this.min),this.min,E(this.dataMin,this.min)),f=Math.max(E(this.options.max,this.max),this.max,E(this.dataMax,this.max)),b=this.scrollbar,g=this.axisTitleMargin+(this.titleOffset||0),d=this.chart.scrollbarsOffsets,k=this.options.margin||0;b&&(this.horiz?(this.opposite||(d[1]+=g),b.position(this.left,this.top+this.height+2+d[1]-(this.opposite?k:0),this.width,this.height),this.opposite||(d[1]+=k),g=1):(this.opposite&&(d[0]+=g),b.position(this.left+this.width+
2+d[0]-(this.opposite?0:k),this.top,this.width,this.height),this.opposite&&(d[0]+=k),g=0),d[g]+=b.size+b.options.margin,isNaN(a)||isNaN(f)||!w(this.min)||!w(this.max)||this.min===this.max?b.setRange(0,1):(d=(this.min-a)/(f-a),a=(this.max-a)/(f-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?b.setRange(d,a):b.setRange(1-a,1-d)))}),v(c,"afterGetOffset",function(){var a=this.horiz?2:1,f=this.scrollbar;f&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=f.size+f.options.margin)}),
m.Scrollbar=x)});I(z,"parts/Navigator.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){function x(h){this.init(h)}var v=c.addEvent,H=c.clamp,w=c.correctFloat,F=c.defined,t=c.destroyObjectProperties,u=c.erase,E=c.extend,b=c.isArray,r=c.isNumber,n=c.merge,B=c.pick,g=c.removeEvent,a=c.splat,f=m.Axis;c=m.Chart;var l=m.color,J=m.defaultOptions,d=m.hasTouch,k=m.isTouchDevice,q=m.Scrollbar,y=m.Series,D=function(h){for(var e=[],a=1;a<arguments.length;a++)e[a-1]=arguments[a];e=[].filter.call(e,
r);if(e.length)return Math[h].apply(0,e)};var p="undefined"===typeof m.seriesTypes.areaspline?"line":"areaspline";E(J,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:l("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:p,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,
smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,
labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});m.Renderer.prototype.symbols["navigator-handle"]=function(h,e,a,d,k){h=k.width/2;e=Math.round(h/3)+.5;k=k.height;return["M",-h-1,.5,"L",h,.5,"L",h,k+.5,"L",-h-1,k+.5,"L",-h-1,.5,"M",-e,4,"L",-e,k-3,"M",e-1,4,"L",e-1,k-3]};f.prototype.toFixedRange=
function(h,e,a,d){var C=this.chart&&this.chart.fixedRange,A=(this.pointRange||0)/2;h=B(a,this.translate(h,!0,!this.horiz));e=B(d,this.translate(e,!0,!this.horiz));var k=C&&(e-h)/C;F(a)||(h=w(h+A));F(d)||(e=w(e-A));.7<k&&1.3>k&&(d?h=e-C:e=h+C);r(h)&&r(e)||(h=e=void 0);return{min:h,max:e}};x.prototype={drawHandle:function(h,e,a,d){var C=this.navigatorOptions.handles.height;this.handles[e][d](a?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(h,10)+.5-C)}:{translateX:Math.round(this.left+
parseInt(h,10)),translateY:Math.round(this.top+this.height/2-C/2-1)})},drawOutline:function(h,e,a,d){var C=this.navigatorOptions.maskInside,A=this.outline.strokeWidth(),k=A/2;A=A%2/2;var f=this.outlineHeight,b=this.scrollbarHeight,q=this.size,p=this.left-b,g=this.top;a?(p-=k,a=g+e+A,e=g+h+A,h=["M",p+f,g-b-A,"L",p+f,a,"L",p,a,"L",p,e,"L",p+f,e,"L",p+f,g+q+b].concat(C?["M",p+f,a-k,"L",p+f,e+k]:[])):(h+=p+b-A,e+=p+b-A,g+=k,h=["M",p,g,"L",h,g,"L",h,g+f,"L",e,g+f,"L",e,g,"L",p+q+2*b,g].concat(C?["M",h-
k,g,"L",e+k,g]:[]));this.outline[d]({d:h})},drawMasks:function(h,e,a,d){var C=this.left,A=this.top,k=this.height;if(a){var f=[C,C,C];var b=[A,A+h,A+e];var q=[k,k,k];var p=[h,e-h,this.size-e]}else f=[C,C+h,C+e],b=[A,A,A],q=[h,e-h,this.size-e],p=[k,k,k];this.shades.forEach(function(e,h){e[d]({x:f[h],y:b[h],width:q[h],height:p[h]})})},renderElements:function(){var h=this,e=h.navigatorOptions,a=e.maskInside,d=h.chart,k=d.renderer,f,b={cursor:d.inverted?"ns-resize":"ew-resize"};h.navigatorGroup=f=k.g("navigator").attr({zIndex:8,
visibility:"hidden"}).add();[!a,a,!a].forEach(function(a,C){h.shades[C]=k.rect().addClass("highcharts-navigator-mask"+(1===C?"-inside":"-outside")).add(f);d.styledMode||h.shades[C].attr({fill:a?e.maskFill:"rgba(0,0,0,0)"}).css(1===C&&b)});h.outline=k.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||h.outline.attr({"stroke-width":e.outlineWidth,stroke:e.outlineColor});e.handles.enabled&&[0,1].forEach(function(a){e.handles.inverted=d.inverted;h.handles[a]=k.symbol(e.handles.symbols[a],
-e.handles.width/2-1,0,e.handles.width,e.handles.height,e.handles);h.handles[a].attr({zIndex:7-a}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][a]).add(f);if(!d.styledMode){var C=e.handles;h.handles[a].attr({fill:C.backgroundColor,stroke:C.borderColor,"stroke-width":C.lineWidth}).css(b)}})},update:function(h){(this.series||[]).forEach(function(e){e.baseSeries&&delete e.baseSeries.navigatorSeries});this.destroy();n(!0,this.chart.options.navigator,this.options,
h);this.init(this.chart)},render:function(h,e,a,d){var C=this.chart,A=this.scrollbarHeight,k,f=this.xAxis,b=f.pointRange||0;var q=f.fake?C.xAxis[0]:f;var p=this.navigatorEnabled,g,l=this.rendered;var y=C.inverted;var c=C.xAxis[0].minRange,n=C.xAxis[0].options.maxRange;if(!this.hasDragged||F(a)){h=w(h-b/2);e=w(e+b/2);if(!r(h)||!r(e))if(l)a=0,d=B(f.width,q.width);else return;this.left=B(f.left,C.plotLeft+A+(y?C.plotWidth:0));this.size=g=k=B(f.len,(y?C.plotHeight:C.plotWidth)-2*A);C=y?A:k+2*A;a=B(a,
f.toPixels(h,!0));d=B(d,f.toPixels(e,!0));r(a)&&Infinity!==Math.abs(a)||(a=0,d=C);h=f.toValue(a,!0);e=f.toValue(d,!0);var D=Math.abs(w(e-h));D<c?this.grabbedLeft?a=f.toPixels(e-c-b,!0):this.grabbedRight&&(d=f.toPixels(h+c+b,!0)):F(n)&&w(D-b)>n&&(this.grabbedLeft?a=f.toPixels(e-n-b,!0):this.grabbedRight&&(d=f.toPixels(h+n+b,!0)));this.zoomedMax=H(Math.max(a,d),0,g);this.zoomedMin=H(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(a,d),0,g);this.range=this.zoomedMax-this.zoomedMin;g=Math.round(this.zoomedMax);
a=Math.round(this.zoomedMin);p&&(this.navigatorGroup.attr({visibility:"visible"}),l=l&&!this.hasDragged?"animate":"attr",this.drawMasks(a,g,y,l),this.drawOutline(a,g,y,l),this.navigatorOptions.handles.enabled&&(this.drawHandle(a,0,y,l),this.drawHandle(g,1,y,l)));this.scrollbar&&(y?(y=this.top-A,q=this.left-A+(p||!q.opposite?0:(q.titleOffset||0)+q.axisTitleMargin),A=k+2*A):(y=this.top+(p?this.height:-A),q=this.left-A),this.scrollbar.position(q,y,C,A),this.scrollbar.setRange(this.zoomedMin/(k||1),this.zoomedMax/
(k||1)));this.rendered=!0}},addMouseEvents:function(){var h=this,e=h.chart,a=e.container,A=[],k,f;h.mouseMoveHandler=k=function(e){h.onMouseMove(e)};h.mouseUpHandler=f=function(e){h.onMouseUp(e)};A=h.getPartsEvents("mousedown");A.push(v(e.renderTo,"mousemove",k),v(a.ownerDocument,"mouseup",f));d&&(A.push(v(e.renderTo,"touchmove",k),v(a.ownerDocument,"touchend",f)),A.concat(h.getPartsEvents("touchstart")));h.eventsToUnbind=A;h.series&&h.series[0]&&A.push(v(h.series[0].xAxis,"foundExtremes",function(){e.navigator.modifyNavigatorAxisExtremes()}))},
getPartsEvents:function(h){var e=this,a=[];["shades","handles"].forEach(function(d){e[d].forEach(function(C,A){a.push(v(C.element,h,function(h){e[d+"Mousedown"](h,A)}))})});return a},shadesMousedown:function(h,e){h=this.chart.pointer.normalize(h);var a=this.chart,d=this.xAxis,k=this.zoomedMin,f=this.left,b=this.size,q=this.range,p=h.chartX;a.inverted&&(p=h.chartY,f=this.top);if(1===e)this.grabbedCenter=p,this.fixedWidth=q,this.dragOffset=p-k;else{h=p-f-q/2;if(0===e)h=Math.max(0,h);else if(2===e&&
h+q>=b)if(h=b-q,this.reversedExtremes){h-=q;var g=this.getUnionExtremes().dataMin}else var l=this.getUnionExtremes().dataMax;h!==k&&(this.fixedWidth=q,e=d.toFixedRange(h,h+q,g,l),F(e.min)&&a.xAxis[0].setExtremes(Math.min(e.min,e.max),Math.max(e.min,e.max),!0,null,{trigger:"navigator"}))}},handlesMousedown:function(h,e){this.chart.pointer.normalize(h);h=this.chart;var a=h.xAxis[0],d=this.reversedExtremes;0===e?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?a.min:a.max):
(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?a.max:a.min);h.fixedRange=null},onMouseMove:function(h){var e=this,a=e.chart,d=e.left,f=e.navigatorSize,b=e.range,q=e.dragOffset,p=a.inverted;h.touches&&0===h.touches[0].pageX||(h=a.pointer.normalize(h),a=h.chartX,p&&(d=e.top,a=h.chartY),e.grabbedLeft?(e.hasDragged=!0,e.render(0,0,a-d,e.otherHandlePos)):e.grabbedRight?(e.hasDragged=!0,e.render(0,0,e.otherHandlePos,a-d)):e.grabbedCenter&&(e.hasDragged=!0,a<q?a=q:a>f+q-b&&
(a=f+q-b),e.render(0,0,a-q,a-q+b)),e.hasDragged&&e.scrollbar&&B(e.scrollbar.options.liveRedraw,m.svg&&!k&&!this.chart.isBoosting)&&(h.DOMType=h.type,setTimeout(function(){e.onMouseUp(h)},0)))},onMouseUp:function(h){var e=this.chart,a=this.xAxis,d=this.scrollbar,k=h.DOMEvent||h,f=e.inverted,b=this.rendered&&!this.hasDragged?"animate":"attr",q=Math.round(this.zoomedMax),p=Math.round(this.zoomedMin);if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===h.trigger){d=this.getUnionExtremes();if(this.zoomedMin===
this.otherHandlePos)var g=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var l=this.fixedExtreme;this.zoomedMax===this.size&&(l=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(g=this.reversedExtremes?d.dataMax:d.dataMin);a=a.toFixedRange(this.zoomedMin,this.zoomedMax,g,l);F(a.min)&&e.xAxis[0].setExtremes(Math.min(a.min,a.max),Math.max(a.min,a.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:k})}"mousemove"!==h.DOMType&&"touchmove"!==
h.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(p,q,f,b),this.outline&&this.drawOutline(p,q,f,b),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(p,0,f,b),this.drawHandle(q,1,f,b)))},removeEvents:function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(h){h()}),this.eventsToUnbind=
void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var h=this.baseSeries||[];this.navigatorEnabled&&h[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&h.forEach(function(e){g(e,"updatedData",this.updatedDataHandler)},this),h[0].xAxis&&g(h[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(h){var e=h.options,a=e.navigator,d=a.enabled,k=e.scrollbar,b=k.enabled;e=d?a.height:0;var p=b?k.height:0;this.handles=[];this.shades=[];this.chart=h;this.setBaseSeries();
this.height=e;this.scrollbarHeight=p;this.scrollbarEnabled=b;this.navigatorEnabled=d;this.navigatorOptions=a;this.scrollbarOptions=k;this.outlineHeight=e+p;this.opposite=B(a.opposite,!(d||!h.inverted));var g=this;d=g.baseSeries;k=h.xAxis.length;b=h.yAxis.length;var l=d&&d[0]&&d[0].xAxis||h.xAxis[0]||{options:{}};h.isDirtyBox=!0;g.navigatorEnabled?(g.xAxis=new f(h,n({breaks:l.options.breaks,ordinal:l.options.ordinal},a.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:k,
isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},h.inverted?{offsets:[p,0,-p,0],width:e}:{offsets:[0,-p,0,p],height:e})),g.yAxis=new f(h,n(a.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:b,isInternal:!0,zoomEnabled:!1},h.inverted?{width:e}:{height:e})),d||a.series.data?g.updateNavigatorSeries(!1):0===h.series.length&&(g.unbindRedraw=v(h,"beforeRedraw",function(){0<h.series.length&&!g.series&&(g.setBaseSeries(),g.unbindRedraw())})),
g.reversedExtremes=h.inverted&&!g.xAxis.reversed||!h.inverted&&g.xAxis.reversed,g.renderElements(),g.addMouseEvents()):g.xAxis={translate:function(e,a){var d=h.xAxis[0],k=d.getExtremes(),f=d.len-2*p,b=D("min",d.options.min,k.dataMin);d=D("max",d.options.max,k.dataMax)-b;return a?e*d/f+b:f*(e-b)/d},toPixels:function(e){return this.translate(e)},toValue:function(e){return this.translate(e,!0)},toFixedRange:f.prototype.toFixedRange,fake:!0};h.options.scrollbar.enabled&&(h.scrollbar=g.scrollbar=new q(h.renderer,
n(h.options.scrollbar,{margin:g.navigatorEnabled?0:10,vertical:h.inverted}),h),v(g.scrollbar,"changed",function(e){var a=g.size,d=a*this.to;a*=this.from;g.hasDragged=g.scrollbar.hasDragged;g.render(0,0,a,d);(h.options.scrollbar.liveRedraw||"mousemove"!==e.DOMType&&"touchmove"!==e.DOMType)&&setTimeout(function(){g.onMouseUp(e)})}));g.addBaseSeriesEvents();g.addChartEvents()},getUnionExtremes:function(a){var e=this.chart.xAxis[0],h=this.xAxis,d=h.options,k=e.options,f;a&&null===e.dataMin||(f={dataMin:B(d&&
d.min,D("min",k.min,e.dataMin,h.dataMin,h.min)),dataMax:B(d&&d.max,D("max",k.max,e.dataMax,h.dataMax,h.max))});return f},setBaseSeries:function(a,e){var h=this.chart,d=this.baseSeries=[];a=a||h.options&&h.options.navigator.baseSeries||(h.series.length?m.find(h.series,function(e){return!e.options.isInternal}).index:0);(h.series||[]).forEach(function(e,h){e.options.isInternal||!e.options.showInNavigator&&(h!==a&&e.options.id!==a||!1===e.options.showInNavigator)||d.push(e)});this.xAxis&&!this.xAxis.fake&&
this.updateNavigatorSeries(!0,e)},updateNavigatorSeries:function(h,e){var d=this,k=d.chart,f=d.baseSeries,q,p,l=d.navigatorOptions.series,r,y={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},c=d.series=(d.series||[]).filter(function(e){var a=e.baseSeries;return 0>f.indexOf(a)?(a&&(g(a,"updatedData",d.updatedDataHandler),delete a.navigatorSeries),e.chart&&
e.destroy(),!1):!0});f&&f.length&&f.forEach(function(a){var h=a.navigatorSeries,g=E({color:a.color,visible:a.visible},b(l)?J.navigator.series:l);h&&!1===d.navigatorOptions.adaptToUpdatedData||(y.name="Navigator "+f.length,q=a.options||{},r=q.navigatorOptions||{},p=n(q,y,g,r),p.pointRange=B(g.pointRange,r.pointRange,J.plotOptions[p.type||"line"].pointRange),g=r.data||g.data,d.hasNavigatorData=d.hasNavigatorData||!!g,p.data=g||q.data&&q.data.slice(0),h&&h.options?h.update(p,e):(a.navigatorSeries=k.initSeries(p),
a.navigatorSeries.baseSeries=a,c.push(a.navigatorSeries)))});if(l.data&&(!f||!f.length)||b(l))d.hasNavigatorData=!1,l=a(l),l.forEach(function(e,a){y.name="Navigator "+(c.length+1);p=n(J.navigator.series,{color:k.series[a]&&!k.series[a].options.isInternal&&k.series[a].color||k.options.colors[a]||k.options.colors[0]},y,e);p.data=e.data;p.data&&(d.hasNavigatorData=!0,c.push(k.initSeries(p)))});h&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,e=a.baseSeries||[];e[0]&&e[0].xAxis&&
v(e[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);e.forEach(function(e){v(e,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});v(e,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&e.xAxis&&v(e,"updatedData",this.updatedDataHandler);v(e,"remove",function(){this.navigatorSeries&&(u(a.series,this.navigatorSeries),F(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},
this)},getBaseSeriesMin:function(a){return this.baseSeries.reduce(function(e,a){return Math.min(e,a.xData?a.xData[0]:e)},a)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,e;"undefined"!==typeof a.getExtremes&&(!(e=this.getUnionExtremes(!0))||e.dataMin===a.min&&e.dataMax===a.max||(a.min=e.dataMin,a.max=e.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,e=this.getExtremes(),d=e.dataMin,k=e.dataMax;e=e.max-e.min;var f=a.stickToMin,b=a.stickToMax,g=B(this.options.overscroll,
0),q=a.series&&a.series[0],p=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(f){var l=d;var y=l+e}b&&(y=k+g,f||(l=Math.max(y-e,a.getBaseSeriesMin(q&&q.xData?q.xData[0]:-Number.MAX_VALUE))));p&&(f||b)&&r(l)&&(this.min=this.userMin=l,this.max=this.userMax=y)}a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,e=this.navigatorSeries,d=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):
Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=r(this.xAxis.min)&&this.xAxis.min<=d&&(!this.chart.fixedRange||!a.stickToMax);e&&!a.hasNavigatorData&&(e.options.pointStart=this.xData[0],e.setData(this.options.data,!1,null,!1))},addChartEvents:function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(v(this.chart,"redraw",function(){var a=this.navigator,e=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);e&&a.render(e.min,e.max)}),
v(this.chart,"getMargins",function(){var a=this.navigator,e=a.opposite?"plotTop":"marginBottom";this.inverted&&(e=a.opposite?"marginRight":"plotLeft");this[e]=(this[e]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))},destroy:function(){this.removeEvents();this.xAxis&&(u(this.chart.xAxis,this.xAxis),u(this.chart.axes,this.xAxis));this.yAxis&&(u(this.chart.yAxis,this.yAxis),u(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});
"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){t(a)},this)}};m.Navigator||(m.Navigator=x,v(f,"zoom",function(a){var e=this.chart.options,d=e.chart.zoomType,h=e.chart.pinchType,f=e.navigator;e=e.rangeSelector;this.isXAxis&&(f&&f.enabled||e&&e.enabled)&&("y"===d?a.zoomed=!1:(!k&&"xy"===d||k&&"xy"===h)&&
this.options.range&&(d=this.previousZoom,F(a.newMin)?this.previousZoom=[this.min,this.max]:d&&(a.newMin=d[0],a.newMax=d[1],delete this.previousZoom)));"undefined"!==typeof a.zoomed&&a.preventDefault()}),v(c,"beforeShowResetZoom",function(){var a=this.options,e=a.navigator,d=a.rangeSelector;if((e&&e.enabled||d&&d.enabled)&&(!k&&"x"===a.chart.zoomType||k&&"x"===a.chart.pinchType))return!1}),v(c,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=
new x(this)}),v(c,"afterSetChartSize",function(){var a=this.legend,e=this.navigator;if(e){var d=a&&a.options;var f=e.xAxis;var k=e.yAxis;var b=e.scrollbarHeight;this.inverted?(e.left=e.opposite?this.chartWidth-b-e.height:this.spacing[3]+b,e.top=this.plotTop+b):(e.left=this.plotLeft+b,e.top=e.navigatorOptions.top||this.chartHeight-e.height-b-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(d&&"bottom"===d.verticalAlign&&d.enabled&&!d.floating?a.legendHeight+
B(d.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));f&&k&&(this.inverted?f.options.left=k.options.left=e.left:f.options.top=k.options.top=e.top,f.setAxisSize(),k.setAxisSize())}}),v(c,"update",function(a){var e=a.options.navigator||{},d=a.options.scrollbar||{};this.navigator||this.scroller||!e.enabled&&!d.enabled||(n(!0,this.options.navigator,e),n(!0,this.options.scrollbar,d),delete a.options.navigator,delete a.options.scrollbar)}),v(c,"afterUpdate",function(a){this.navigator||this.scroller||
!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new x(this),B(a.redraw,!0)&&this.redraw(a.animation))}),v(c,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),v(y,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),c.prototype.callbacks.push(function(a){var e=a.navigator;e&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),e.render(a.min,a.max))}))});I(z,"parts/OrdinalAxis.js",
[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){var x=c.addEvent,v=c.css,H=c.defined,w=c.extend,F=c.pick,t=c.timeUnits,u=m.Axis;c=m.Chart;var E=m.noop;x(m.Series,"updatedData",function(){var b=this.xAxis;b&&b.options.ordinal&&delete b.ordinalIndex});u.prototype.getTimeTicks=function(b,r,c,B,g,a,f){var l=0,n,d,k={},q=[],y=-Number.MAX_VALUE,D=this.options.tickPixelInterval,p=this.chart.time,h=[];if(!this.options.ordinal&&!this.options.breaks||!g||3>g.length||"undefined"===typeof r)return p.getTimeTicks.apply(p,
arguments);var e=g.length;for(n=0;n<e;n++){var C=n&&g[n-1]>c;g[n]<r&&(l=n);if(n===e-1||g[n+1]-g[n]>5*a||C){if(g[n]>y){for(d=p.getTimeTicks(b,g[l],g[n],B);d.length&&d[0]<=y;)d.shift();d.length&&(y=d[d.length-1]);h.push(q.length);q=q.concat(d)}l=n+1}if(C)break}d=d.info;if(f&&d.unitRange<=t.hour){n=q.length-1;for(l=1;l<n;l++)if(p.dateFormat("%d",q[l])!==p.dateFormat("%d",q[l-1])){k[q[l]]="day";var A=!0}A&&(k[q[0]]="day");d.higherRanks=k}d.segmentStarts=h;q.info=d;if(f&&H(D)){l=h=q.length;A=[];var G;
for(p=[];l--;)n=this.translate(q[l]),G&&(p[l]=G-n),A[l]=G=n;p.sort();p=p[Math.floor(p.length/2)];p<.6*D&&(p=null);l=q[h-1]>c?h-1:h;for(G=void 0;l--;)n=A[l],h=Math.abs(G-n),G&&h<.8*D&&(null===p||h<.8*p)?(k[q[l]]&&!k[q[l+1]]?(h=l+1,G=n):h=l,q.splice(h,1)):G=n}return q};w(u.prototype,{beforeSetTickPositions:function(){var b=[],r,n=!1,c=this.getExtremes(),g=c.min,a=c.max,f,l=this.isXAxis&&!!this.options.breaks;c=this.options.ordinal;var m=Number.MAX_VALUE,d=this.chart.options.chart.ignoreHiddenSeries,
k;if(c||l){this.series.forEach(function(a,f){r=[];if(!(d&&!1===a.visible||!1===a.takeOrdinalPosition&&!l)&&(b=b.concat(a.processedXData),q=b.length,b.sort(function(a,e){return a-e}),m=Math.min(m,F(a.closestPointRange,m)),q)){for(f=0;f<q-1;)b[f]!==b[f+1]&&r.push(b[f+1]),f++;r[0]!==b[0]&&r.unshift(b[0]);b=r}a.isSeriesBoosting&&(k=!0)});k&&(b.length=0);var q=b.length;if(2<q){var y=b[1]-b[0];for(f=q-1;f--&&!n;)b[f+1]-b[f]!==y&&(n=!0);!this.options.keepOrdinalPadding&&(b[0]-g>y||a-b[b.length-1]>y)&&(n=
!0)}else this.options.overscroll&&(2===q?m=b[1]-b[0]:1===q?(m=this.options.overscroll,b=[b[0],b[0]+m]):m=this.overscrollPointsRange);n?(this.options.overscroll&&(this.overscrollPointsRange=m,b=b.concat(this.getOverscrollPositions())),this.ordinalPositions=b,y=this.ordinal2lin(Math.max(g,b[0]),!0),f=Math.max(this.ordinal2lin(Math.min(a,b[b.length-1]),!0),1),this.ordinalSlope=a=(a-g)/(f-y),this.ordinalOffset=g-y*a):(this.overscrollPointsRange=F(this.closestPointRange,this.overscrollPointsRange),this.ordinalPositions=
this.ordinalSlope=this.ordinalOffset=void 0)}this.isOrdinal=c&&n;this.groupIntervalFactor=null},val2lin:function(b,r){var n=this.ordinalPositions;if(n){var c=n.length,g;for(g=c;g--;)if(n[g]===b){var a=g;break}for(g=c-1;g--;)if(b>n[g]||0===g){b=(b-n[g])/(n[g+1]-n[g]);a=g+b;break}r=r?a:this.ordinalSlope*(a||0)+this.ordinalOffset}else r=b;return r},lin2val:function(b,r){var n=this.ordinalPositions;if(n){var c=this.ordinalSlope,g=this.ordinalOffset,a=n.length-1;if(r)if(0>b)b=n[0];else if(b>a)b=n[a];else{a=
Math.floor(b);var f=b-a}else for(;a--;)if(r=c*a+g,b>=r){c=c*(a+1)+g;f=(b-r)/(c-r);break}return"undefined"!==typeof f&&"undefined"!==typeof n[a]?n[a]+(f?f*(n[a+1]-n[a]):0):b}return b},getExtendedPositions:function(){var b=this,c=b.chart,n=b.series[0].currentDataGrouping,B=b.ordinalIndex,g=n?n.count+n.unitName:"raw",a=b.options.overscroll,f=b.getExtremes(),l;B||(B=b.ordinalIndex={});if(!B[g]){var m={series:[],chart:c,getExtremes:function(){return{min:f.dataMin,max:f.dataMax+a}},options:{ordinal:!0},
val2lin:u.prototype.val2lin,ordinal2lin:u.prototype.ordinal2lin};b.series.forEach(function(a){l={xAxis:m,xData:a.xData.slice(),chart:c,destroyGroupedData:E};l.xData=l.xData.concat(b.getOverscrollPositions());l.options={dataGrouping:n?{enabled:!0,forced:!0,approximation:"open",units:[[n.unitName,[n.count]]]}:{enabled:!1}};a.processData.apply(l);m.series.push(l)});b.beforeSetTickPositions.apply(m);B[g]=m.ordinalPositions}return B[g]},getOverscrollPositions:function(){var b=this.options.overscroll,c=
this.overscrollPointsRange,n=[],m=this.dataMax;if(H(c))for(n.push(m);m<=this.dataMax+b;)m+=c,n.push(m);return n},getGroupIntervalFactor:function(b,c,n){n=n.processedXData;var r=n.length,g=[];var a=this.groupIntervalFactor;if(!a){for(a=0;a<r-1;a++)g[a]=n[a+1]-n[a];g.sort(function(a,b){return a-b});g=g[Math.floor(r/2)];b=Math.max(b,n[0]);c=Math.min(c,n[r-1]);this.groupIntervalFactor=a=r*g/(c-b)}return a},postProcessTickInterval:function(b){var c=this.ordinalSlope;return c?this.options.breaks?this.closestPointRange||
b:b/(c/this.closestPointRange):b}});u.prototype.ordinal2lin=u.prototype.val2lin;x(c,"pan",function(b){var c=this.xAxis[0],n=c.options.overscroll,m=b.originalEvent.chartX,g=this.options.chart&&this.options.chart.panning,a=!1;if(g&&"y"!==g.type&&c.options.ordinal&&c.series.length){var f=this.mouseDownX,l=c.getExtremes(),u=l.dataMax,d=l.min,k=l.max,q=this.hoverPoints,y=c.closestPointRange||c.overscrollPointsRange;f=(f-m)/(c.translationSlope*(c.ordinalSlope||y));var D={ordinalPositions:c.getExtendedPositions()};
y=c.lin2val;var p=c.val2lin;if(!D.ordinalPositions)a=!0;else if(1<Math.abs(f)){q&&q.forEach(function(a){a.setState()});if(0>f){q=D;var h=c.ordinalPositions?c:D}else q=c.ordinalPositions?c:D,h=D;D=h.ordinalPositions;u>D[D.length-1]&&D.push(u);this.fixedRange=k-d;f=c.toFixedRange(null,null,y.apply(q,[p.apply(q,[d,!0])+f,!0]),y.apply(h,[p.apply(h,[k,!0])+f,!0]));f.min>=Math.min(l.dataMin,d)&&f.max<=Math.max(u,k)+n&&c.setExtremes(f.min,f.max,!0,!1,{trigger:"pan"});this.mouseDownX=m;v(this.container,{cursor:"move"})}}else a=
!0;a||g&&/y/.test(g.type)?n&&(c.max=c.dataMax+n):b.preventDefault()});x(u,"foundExtremes",function(){this.isXAxis&&H(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&H(this.userMin)&&(this.min+=this.options.overscroll))});x(u,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&
!this.chart.navigator.adaptToUpdatedData)})});I(z,"modules/broken-axis.src.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){var x=c.addEvent,v=c.extend,H=c.fireEvent,w=c.isArray,F=c.pick,t=m.find,u=m.Axis;c=m.Series;var E=function(b,c){return t(c,function(c){return c.from<b&&b<c.to})};v(u.prototype,{isInBreak:function(b,c){var n=b.repeat||Infinity,r=b.from,g=b.to-b.from;c=c>=r?(c-r)%n:n-(r-c)%n;return b.inclusive?c<=g:c<g&&0!==c},isInAnyBreak:function(b,c){var n=this.options.breaks,
r=n&&n.length,g;if(r){for(;r--;)if(this.isInBreak(n[r],b)){var a=!0;g||(g=F(n[r].showPoints,!this.isXAxis))}var f=a&&c?a&&!g:a}return f}});x(u,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});x(u,"afterSetTickPositions",function(){if(this.isBroken){var b=this.tickPositions,c=this.tickPositions.info,n=[],m;for(m=0;m<b.length;m++)this.isInAnyBreak(b[m])||n.push(b[m]);this.tickPositions=n;this.tickPositions.info=c}});x(u,"afterSetOptions",function(){this.isBroken&&
(this.options.ordinal=!1)});u.prototype.setBreaks=function(b,c){function n(a){var f=a,b;for(b=0;b<g.breakArray.length;b++){var d=g.breakArray[b];if(d.to<=a)f-=d.len;else if(d.from>=a)break;else if(g.isInBreak(d,a)){f-=a-d.from;break}}return f}function m(a){var f;for(f=0;f<g.breakArray.length;f++){var b=g.breakArray[f];if(b.from>=a)break;else b.to<a?a+=b.len:g.isInBreak(b,a)&&(a+=b.len)}return a}var g=this,a=w(b)&&!!b.length;g.isDirty=g.isBroken!==a;g.isBroken=a;g.options.breaks=g.userOptions.breaks=
b;g.forceRedraw=!0;g.series.forEach(function(a){a.isDirty=!0});a||g.val2lin!==n||(delete g.val2lin,delete g.lin2val);a&&(g.userOptions.ordinal=!1,g.val2lin=n,g.lin2val=m,g.setExtremes=function(a,b,g,d,k){if(this.isBroken){for(var f,c=this.options.breaks;f=E(a,c);)a=f.to;for(;f=E(b,c);)b=f.from;b<a&&(b=a)}u.prototype.setExtremes.call(this,a,b,g,d,k)},g.setAxisTranslation=function(a){u.prototype.setAxisTranslation.call(this,a);this.unitLength=null;if(this.isBroken){a=g.options.breaks;var b=[],f=[],
d=0,k,q=g.userMin||g.min,c=g.userMax||g.max,n=F(g.pointRangePadding,0),p;a.forEach(function(a){k=a.repeat||Infinity;g.isInBreak(a,q)&&(q+=a.to%k-q%k);g.isInBreak(a,c)&&(c-=c%k-a.from%k)});a.forEach(function(a){e=a.from;for(k=a.repeat||Infinity;e-k>q;)e-=k;for(;e<q;)e+=k;for(p=e;p<c;p+=k)b.push({value:p,move:"in"}),b.push({value:p+(a.to-a.from),move:"out",size:a.breakSize})});b.sort(function(a,e){return a.value===e.value?("in"===a.move?0:1)-("in"===e.move?0:1):a.value-e.value});var h=0;var e=q;b.forEach(function(a){h+=
"in"===a.move?1:-1;1===h&&"in"===a.move&&(e=a.value);0===h&&(f.push({from:e,to:a.value,len:a.value-e-(a.size||0)}),d+=a.value-e-(a.size||0))});g.breakArray=f;g.unitLength=c-q-d+n;H(g,"afterBreaks");g.staticScale?g.transA=g.staticScale:g.unitLength&&(g.transA*=(c-g.min+n)/g.unitLength);n&&(g.minPixelPadding=g.transA*g.minPointOffset);g.min=q;g.max=c}});F(c,!0)&&this.chart.redraw()};x(c,"afterGeneratePoints",function(){var b=this.options.connectNulls,c=this.points,n=this.xAxis,m=this.yAxis;if(this.isDirty)for(var g=
c.length;g--;){var a=c[g],f=!(null===a.y&&!1===b)&&(n&&n.isInAnyBreak(a.x,!0)||m&&m.isInAnyBreak(a.y,!0));a.visible=f?!1:!1!==a.options.visible}});x(c,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,F(this.pointArrayMap,["y"]))});m.Series.prototype.drawBreaks=function(b,c){var n=this,m=n.points,g,a,f,l;b&&c.forEach(function(c){g=b.breakArray||[];a=b.isXAxis?b.min:F(n.options.threshold,b.min);m.forEach(function(d){l=F(d["stack"+c.toUpperCase()],d[c]);g.forEach(function(k){f=
!1;if(a<k.from&&l>k.to||a>k.from&&l<k.from)f="pointBreak";else if(a<k.from&&l>k.from&&l<k.to||a>k.from&&l>k.to&&l<k.from)f="pointInBreak";f&&H(b,f,{point:d,brk:k})})})})};m.Series.prototype.gappedPath=function(){var b=this.currentDataGrouping,c=b&&b.gapSize;b=this.options.gapSize;var n=this.points.slice(),u=n.length-1,g=this.yAxis,a;if(b&&0<u)for("value"!==this.options.gapUnit&&(b*=this.basePointRange),c&&c>b&&c>=this.basePointRange&&(b=c),a=void 0;u--;)a&&!1!==a.visible||(a=n[u+1]),c=n[u],!1!==a.visible&&
!1!==c.visible&&(a.x-c.x>b&&(a=(c.x+a.x)/2,n.splice(u+1,0,{isNull:!0,x:a}),this.options.stacking&&(a=g.stacks[this.stackKey][a]=new m.StackItem(g,g.options.stackLabels,!1,a,this.stack),a.total=0)),a=c);return this.getGraphPath(n)}});I(z,"masters/modules/broken-axis.src.js",[],function(){});I(z,"parts/DataGrouping.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){var x=c.addEvent,v=c.arrayMax,H=c.arrayMin,w=c.correctFloat,F=c.defined,t=c.error,u=c.extend,E=c.format,b=c.isNumber,r=c.merge,
n=c.pick,B=m.Axis,g=m.defaultPlotOptions;c=m.Point;var a=m.Series,f=m.Tooltip,l=m.approximations={sum:function(a){var e=a.length;if(!e&&a.hasNulls)var d=null;else if(e)for(d=0;e--;)d+=a[e];return d},average:function(a){var e=a.length;a=l.sum(a);b(a)&&e&&(a=w(a/e));return a},averages:function(){var a=[];[].forEach.call(arguments,function(e){a.push(l.average(e))});return"undefined"===typeof a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?
v(a):a.hasNulls?null:void 0},low:function(a){return a.length?H(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,d,h,k){a=l.open(a);d=l.high(d);h=l.low(h);k=l.close(k);if(b(a)||b(d)||b(h)||b(k))return[a,d,h,k]},range:function(a,d){a=l.low(a);d=l.high(d);if(b(a)||b(d))return[a,d];if(null===a&&null===d)return null}},z=function(a,d,h,k){var e=this,f=e.data,g=e.options&&e.options.data,c=[],q=[],p=[],A=a.length,n=!!d,y=[],C=e.pointArrayMap,
m=C&&C.length,D=["x"].concat(C||["y"]),u=0,G=0,t;k="function"===typeof k?k:l[k]?l[k]:l[e.getDGApproximation&&e.getDGApproximation()||"average"];m?C.forEach(function(){y.push([])}):y.push([]);var v=m||1;for(t=0;t<=A&&!(a[t]>=h[0]);t++);for(t;t<=A;t++){for(;"undefined"!==typeof h[u+1]&&a[t]>=h[u+1]||t===A;){var w=h[u];e.dataGroupInfo={start:e.cropStart+G,length:y[0].length};var B=k.apply(e,y);e.pointClass&&!F(e.dataGroupInfo.options)&&(e.dataGroupInfo.options=r(e.pointClass.prototype.optionsToObject.call({series:e},
e.options.data[e.cropStart+G])),D.forEach(function(a){delete e.dataGroupInfo.options[a]}));"undefined"!==typeof B&&(c.push(w),q.push(B),p.push(e.dataGroupInfo));G=t;for(w=0;w<v;w++)y[w].length=0,y[w].hasNulls=!1;u+=1;if(t===A)break}if(t===A)break;if(C)for(w=e.cropStart+t,B=f&&f[w]||e.pointClass.prototype.applyOptions.apply({series:e},[g[w]]),w=0;w<m;w++){var x=B[C[w]];b(x)?y[w].push(x):null===x&&(y[w].hasNulls=!0)}else w=n?d[t]:null,b(w)?y[0].push(w):null===w&&(y[0].hasNulls=!0)}return{groupedXData:c,
groupedYData:q,groupMap:p}},d={approximations:l,groupData:z},k=a.prototype,q=k.processData,y=k.generatePoints,D={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e",
"-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},p={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},h=m.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];k.getDGApproximation=function(){return this.is("arearange")?
"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};k.groupData=z;k.processData=function(){var a=this.chart,d=this.options.dataGrouping,b=!1!==this.allowDG&&d&&n(d.enabled,a.options.isStock),f=this.visible||!a.options.chart.ignoreHiddenSeries,g,c=this.currentDataGrouping,p=!1;this.forceCrop=b;this.groupPixelWidth=null;this.hasProcessed=!0;b&&!this.requireSorting&&(this.requireSorting=p=!0);b=!1===q.apply(this,arguments)||!b;p&&(this.requireSorting=!1);if(!b){this.destroyGroupedData();
b=d.groupAll?this.xData:this.processedXData;var l=d.groupAll?this.yData:this.processedYData,y=a.plotSizeX;a=this.xAxis;var m=a.options.ordinal,D=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(D){this.isDirty=g=!0;this.points=null;p=a.getExtremes();var r=p.min;p=p.max;m=m&&a.getGroupIntervalFactor(r,p,this)||1;D=D*(p-r)/y*m;y=a.getTimeTicks(a.normalizeTimeTickInterval(D,d.units||h),Math.min(r,b[0]),Math.max(p,b[b.length-1]),a.options.startOfWeek,b,this.closestPointRange);l=k.groupData.apply(this,
[b,l,y,d.approximation]);b=l.groupedXData;m=l.groupedYData;var u=0;if(d.smoothed&&b.length){var t=b.length-1;for(b[t]=Math.min(b[t],p);t--&&0<t;)b[t]+=D/2;b[0]=Math.max(b[0],r)}for(t=1;t<y.length;t++)y.info.segmentStarts&&-1!==y.info.segmentStarts.indexOf(t)||(u=Math.max(y[t]-y[t-1],u));r=y.info;r.gapSize=u;this.closestPointRange=y.info.totalRange;this.groupMap=l.groupMap;if(F(b[0])&&b[0]<a.min&&f){if(!F(a.options.min)&&a.min<=a.dataMin||a.min===a.dataMin)a.min=Math.min(b[0],a.min);a.dataMin=Math.min(b[0],
a.dataMin)}d.groupAll&&(d=this.cropData(b,m,a.min,a.max,1),b=d.xData,m=d.yData);this.processedXData=b;this.processedYData=m}else this.groupMap=null;this.hasGroupedData=g;this.currentDataGrouping=r;this.preventGraphAnimation=(c&&c.totalRange)!==(r&&r.totalRange)}};k.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(a,d){a&&(this.groupedData[d]=a.destroy?a.destroy():null)},this),this.groupedData.length=0)};k.generatePoints=function(){y.apply(this);this.destroyGroupedData();
this.groupedData=this.hasGroupedData?this.points:null};x(c,"update",function(){if(this.dataGroup)return t(24,!1,this.series.chart),!1});x(f,"headerFormatter",function(a){var e=this.chart,d=e.time,h=a.labelConfig,k=h.series,f=k.tooltipOptions,g=k.options.dataGrouping,c=f.xDateFormat,p=k.xAxis,q=f[(a.isFooter?"footer":"header")+"Format"];if(p&&"datetime"===p.options.type&&g&&b(h.key)){var l=k.currentDataGrouping;g=g.dateTimeLabelFormats||D.dateTimeLabelFormats;if(l)if(f=g[l.unitName],1===l.count)c=
f[0];else{c=f[1];var y=f[2]}else!c&&g&&(c=this.getXDateFormat(h,f,p));c=d.dateFormat(c,h.key);y&&(c+=d.dateFormat(y,h.key+l.totalRange-1));k.chart.styledMode&&(q=this.styledModeFormat(q));a.text=E(q,{point:u(h.point,{key:c}),series:k},e);a.preventDefault()}});x(a,"destroy",k.destroyGroupedData);x(a,"afterSetOptions",function(a){a=a.options;var e=this.type,d=this.chart.options.plotOptions,h=g[e].dataGrouping,b=this.useCommonDataGrouping&&D;if(p[e]||b)h||(h=r(D,p[e])),a.dataGrouping=r(b,h,d.series&&
d.series.dataGrouping,d[e].dataGrouping,this.userOptions.dataGrouping)});x(B,"afterSetScale",function(){this.series.forEach(function(a){a.hasProcessed=!1})});B.prototype.getGroupPixelWidth=function(){var a=this.series,d=a.length,h,b=0,k=!1,f;for(h=d;h--;)(f=a[h].options.dataGrouping)&&(b=Math.max(b,n(f.groupPixelWidth,D.groupPixelWidth)));for(h=d;h--;)(f=a[h].options.dataGrouping)&&a[h].hasProcessed&&(d=(a[h].processedXData||a[h].data).length,a[h].groupPixelWidth||d>this.chart.plotSizeX/b||d&&f.forced)&&
(k=!0);return k?b:0};B.prototype.setDataGrouping=function(a,d){var e;d=n(d,!0);a||(a={forced:!1,units:null});if(this instanceof B)for(e=this.series.length;e--;)this.series[e].update({dataGrouping:a},!1);else this.chart.options.series.forEach(function(e){e.dataGrouping=a},!1);this.ordinalSlope=null;d&&this.chart.redraw()};m.dataGrouping=d;"";return d});I(z,"parts/OHLCSeries.js",[z["parts/Globals.js"]],function(m){var c=m.Point,x=m.seriesType,v=m.seriesTypes;x("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},
threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(c){return[c.open,c.high,c.low,c.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){v.column.prototype.init.apply(this,arguments);this.options.stacking=!1},pointAttribs:function(c,m){m=v.column.prototype.pointAttribs.call(this,c,m);var w=this.options;delete m.fill;!c.options.color&&w.upColor&&c.open<c.close&&
(m.stroke=w.upColor);return m},translate:function(){var c=this,m=c.yAxis,x=!!c.modifyValue,t=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];v.column.prototype.translate.apply(c);c.points.forEach(function(u){[u.open,u.high,u.low,u.close,u.low].forEach(function(w,b){null!==w&&(x&&(w=c.modifyValue(w)),u[t[b]]=m.toPixels(w,!0))});u.tooltipPos[1]=u.plotHigh+m.pos-c.chart.plotTop})},drawPoints:function(){var c=this,m=c.chart,v=function(c,m,w){c[2]=Math.max(w+m,c[2]);c[5]=Math.min(w-m,c[5])};c.points.forEach(function(t){var u=
t.graphic,w=!u;if("undefined"!==typeof t.plotY){u||(t.graphic=u=m.renderer.path().add(c.group));m.styledMode||u.attr(c.pointAttribs(t,t.selected&&"select"));var b=u.strokeWidth();var r=b%2/2;var n=Math.round(t.plotX)-r;var B=Math.round(t.shapeArgs.width/2);var g=["M",n,Math.round(t.yBottom),"L",n,Math.round(t.plotHigh)];if(null!==t.open){var a=Math.round(t.plotOpen)+r;g.push("M",n,a,"L",n-B,a);v(g,b/2,a)}null!==t.close&&(a=Math.round(t.plotClose)+r,g.push("M",n,a,"L",n+B,a),v(g,b/2,a));u[w?"attr":
"animate"]({d:g}).addClass(t.getClassName(),!0)}})},animate:null},{getClassName:function(){return c.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});I(z,"parts/CandlestickSeries.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){c=c.merge;var x=m.defaultPlotOptions,v=m.seriesType,z=m.seriesTypes;v("candlestick","ohlc",c(x.column,{states:{hover:{lineWidth:2}},tooltip:x.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,
upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(c,m){var t=z.column.prototype.pointAttribs.call(this,c,m),u=this.options,w=c.open<c.close,b=u.lineColor||this.color;t["stroke-width"]=u.lineWidth;t.fill=c.options.color||(w?u.upColor||this.color:this.color);t.stroke=c.options.lineColor||(w?u.upLineColor||b:b);m&&(c=u.states[m],t.fill=c.color||t.fill,t.stroke=c.lineColor||t.stroke,t["stroke-width"]=c.lineWidth||t["stroke-width"]);return t},drawPoints:function(){var c=this,m=c.chart,t=c.yAxis.reversed;
c.points.forEach(function(u){var v=u.graphic,b=!v;if("undefined"!==typeof u.plotY){v||(u.graphic=v=m.renderer.path().add(c.group));c.chart.styledMode||v.attr(c.pointAttribs(u,u.selected&&"select")).shadow(c.options.shadow);var r=v.strokeWidth()%2/2;var n=Math.round(u.plotX)-r;var w=u.plotOpen;var g=u.plotClose;var a=Math.min(w,g);w=Math.max(w,g);var f=Math.round(u.shapeArgs.width/2);g=t?w!==u.yBottom:Math.round(a)!==Math.round(u.plotHigh);var l=t?Math.round(a)!==Math.round(u.plotHigh):w!==u.yBottom;
a=Math.round(a)+r;w=Math.round(w)+r;r=[];r.push("M",n-f,w,"L",n-f,a,"L",n+f,a,"L",n+f,w,"Z","M",n,a,"L",n,g?Math.round(t?u.yBottom:u.plotHigh):a,"M",n,w,"L",n,l?Math.round(t?u.plotHigh:u.yBottom):w);v[b?"attr":"animate"]({d:r}).addClass(u.getClassName(),!0)}})}});""});I(z,"mixins/on-series.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){var x=c.defined,v=c.stableSort,z=m.seriesTypes;return{getPlotBox:function(){return m.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||
this)},translate:function(){z.column.prototype.translate.apply(this);var c=this,m=c.options,t=c.chart,u=c.points,E=u.length-1,b,r=m.onSeries;r=r&&t.get(r);m=m.onKey||"y";var n=r&&r.options.step,B=r&&r.points,g=B&&B.length,a=t.inverted,f=c.xAxis,l=c.yAxis,J=0,d;if(r&&r.visible&&g){J=(r.pointXOffset||0)+(r.barW||0)/2;t=r.currentDataGrouping;var k=B[g-1].x+(t?t.totalRange:0);v(u,function(a,d){return a.x-d.x});for(m="plot"+m[0].toUpperCase()+m.substr(1);g--&&u[E];){var q=B[g];t=u[E];t.y=q.y;if(q.x<=t.x&&
"undefined"!==typeof q[m]){if(t.x<=k&&(t.plotY=q[m],q.x<t.x&&!n&&(d=B[g+1])&&"undefined"!==typeof d[m])){var y=(t.x-q.x)/(d.x-q.x);t.plotY+=y*(d[m]-q[m]);t.y+=y*(d.y-q.y)}E--;g++;if(0>E)break}}}u.forEach(function(d,k){d.plotX+=J;if("undefined"===typeof d.plotY||a)0<=d.plotX&&d.plotX<=f.len?a?(d.plotY=f.translate(d.x,0,1,0,1),d.plotX=x(d.y)?l.translate(d.y,0,0,0,1):0):d.plotY=(f.opposite?0:c.yAxis.len)+f.offset:d.shapeArgs={};if((b=u[k-1])&&b.plotX===d.plotX){"undefined"===typeof b.stackIndex&&(b.stackIndex=
0);var h=b.stackIndex+1}d.stackIndex=h});this.onSeries=r}}});I(z,"parts/FlagsSeries.js",[z["parts/Globals.js"],z["parts/Utilities.js"],z["mixins/on-series.js"]],function(m,c,x){function v(b){a[b+"pin"]=function(c,f,d,k,g){var q=g&&g.anchorX;g=g&&g.anchorY;"circle"===b&&k>d&&(c-=Math.round((k-d)/2),d=k);var l=a[b](c,f,d,k);q&&g&&(l.push("M","circle"===b?c+d/2:l[1]+l[4]/2,f>g?f:f+k,"L",q,g),l=l.concat(a.circle(q-1,g-1,2,2)));return l}}var z=c.addEvent,w=c.defined,F=c.isNumber,t=c.merge,u=c.objectEach,
E=c.wrap;c=m.noop;var b=m.Renderer,r=m.Series,n=m.seriesType,B=m.TrackerMixin,g=m.VMLRenderer,a=m.SVGRenderer.prototype.symbols;n("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],
forceCrop:!0,init:r.prototype.init,pointAttribs:function(a,b){var c=this.options,d=a&&a.color||this.color,k=c.lineColor,f=a&&a.lineWidth;a=a&&a.fillColor||c.fillColor;b&&(a=c.states[b].fillColor,k=c.states[b].lineColor,f=c.states[b].lineWidth);return{fill:a||d,stroke:k||d,"stroke-width":f||c.lineWidth||0}},translate:x.translate,getPlotBox:x.getPlotBox,drawPoints:function(){var a=this.points,b=this.chart,c=b.renderer,d=b.inverted,k=this.options,g=k.y,y,n=this.yAxis,p={},h=[];for(y=a.length;y--;){var e=
a[y];var r=(d?e.plotY:e.plotX)>this.xAxis.len;var A=e.plotX;var G=e.stackIndex;var v=e.options.shape||k.shape;var x=e.plotY;"undefined"!==typeof x&&(x=e.plotY+g-("undefined"!==typeof G&&G*k.stackDistance));e.anchorX=G?void 0:e.plotX;var V=G?void 0:e.plotY;var R="flag"!==v;G=e.graphic;"undefined"!==typeof x&&0<=A&&!r?(G||(G=e.graphic=c.label("",null,null,v,null,null,k.useHTML),b.styledMode||G.attr(this.pointAttribs(e)).css(t(k.style,e.style)),G.attr({align:R?"center":"left",width:k.width,height:k.height,
"text-align":k.textAlign}).addClass("highcharts-point").add(this.markerGroup),e.graphic.div&&(e.graphic.div.point=e),b.styledMode||G.shadow(k.shadow),G.isNew=!0),0<A&&(A-=G.strokeWidth()%2),v={y:x,anchorY:V},k.allowOverlapX&&(v.x=A,v.anchorX=e.anchorX),G.attr({text:e.options.title||k.title||"A"})[G.isNew?"attr":"animate"](v),k.allowOverlapX||(p[e.plotX]?p[e.plotX].size=Math.max(p[e.plotX].size,G.width):p[e.plotX]={align:R?.5:0,size:G.width,target:A,anchorX:A}),e.tooltipPos=[A,x+n.pos-b.plotTop]):
G&&(e.graphic=G.destroy())}k.allowOverlapX||(u(p,function(a){a.plotX=a.anchorX;h.push(a)}),m.distribute(h,d?n.len:this.xAxis.len,100),a.forEach(function(a){var d=a.graphic&&p[a.plotX];d&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:d.pos+d.align*d.size,anchorX:a.anchorX}),w(d.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,anchorX:-9999}),a.graphic.isNew=!0))}));k.useHTML&&E(this.markerGroup,"on",function(a){return m.SVGElement.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,
1))})},drawTracker:function(){var a=this.points;B.drawTrackerPoint.apply(this);a.forEach(function(b){var c=b.graphic;c&&z(c.element,"mouseover",function(){0<b.stackIndex&&!b.raised&&(b._y=c.y,c.attr({y:b._y-8}),b.raised=!0);a.forEach(function(a){a!==b&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:function(a){a?this.setClip():this.animate=null},setClip:function(){r.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},
buildKDTree:c,invertGroups:c},{isValid:function(){return F(this.y)||"undefined"===typeof this.y}});a.flag=function(b,c,g,d,k){var f=k&&k.anchorX||b;k=k&&k.anchorY||c;return a.circle(f-1,k-1,2,2).concat(["M",f,k,"L",b,c+d,b,c,b+g,c,b+g,c+d,b,c+d,"Z"])};v("circle");v("square");b===g&&["circlepin","flag","squarepin"].forEach(function(b){g.prototype.symbols[b]=a[b]});""});I(z,"parts/RangeSelector.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){function x(a){this.init(a)}var v=c.addEvent,
z=c.createElement,w=c.css,F=c.defined,t=c.destroyObjectProperties,u=c.discardElement,E=c.extend,b=c.fireEvent,r=c.isNumber,n=c.merge,B=c.objectEach,g=c.pick,a=c.pInt,f=c.splat,l=m.Axis;c=m.Chart;var I=m.defaultOptions;E(I,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});I.lang=n(I.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",
rangeSelectorTo:"To"});x.prototype={clickButton:function(a,b){var d=this.chart,c=this.buttonOptions[a],k=d.xAxis[0],p=d.scroller&&d.scroller.getUnionExtremes()||k||{},h=p.dataMin,e=p.dataMax,m=k&&Math.round(Math.min(k.max,g(e,k.max))),n=c.type;p=c._range;var u,t=c.dataGrouping;if(null!==h&&null!==e){d.fixedRange=p;t&&(this.forcedDataGrouping=!0,l.prototype.setDataGrouping.call(k||{chart:this.chart},t,!1),this.frozenStates=c.preserveDataGrouping);if("month"===n||"year"===n)if(k){n={range:c,max:m,chart:d,
dataMin:h,dataMax:e};var w=k.minFromRange.call(n);r(n.newMax)&&(m=n.newMax)}else p=c;else if(p)w=Math.max(m-p,h),m=Math.min(w+p,e);else if("ytd"===n)if(k)"undefined"===typeof e&&(h=Number.MAX_VALUE,e=Number.MIN_VALUE,d.series.forEach(function(a){a=a.xData;h=Math.min(a[0],h);e=Math.max(a[a.length-1],e)}),b=!1),m=this.getYTDExtremes(e,h,d.time.useUTC),w=u=m.min,m=m.max;else{this.deferredYTDClick=a;return}else"all"===n&&k&&(w=h,m=e);w+=c._offsetMin;m+=c._offsetMax;this.setSelected(a);if(k)k.setExtremes(w,
m,g(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:c});else{var x=f(d.options.xAxis)[0];var R=x.range;x.range=p;var z=x.min;x.min=u;v(d,"load",function(){x.range=R;x.min=z})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var d=this,c=a.options.rangeSelector,
f=c.buttons||[].concat(d.defaultButtons),g=c.selected,p=function(){var a=d.minInput,e=d.maxInput;a&&a.blur&&b(a,"blur");e&&e.blur&&b(e,"blur")};d.chart=a;d.options=c;d.buttons=[];d.buttonOptions=f;this.unMouseDown=v(a.container,"mousedown",p);this.unResize=v(a,"resize",p);f.forEach(d.computeButtonRange);"undefined"!==typeof g&&f[g]&&this.clickButton(g,!1);v(a,"load",function(){a.xAxis&&a.xAxis[0]&&v(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&
"updatedData"!==b.trigger&&d.forcedDataGrouping&&!d.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,b=this.chart,c=b.xAxis[0],f=Math.round(c.max-c.min),g=!c.hasVisibleSeries,p=b.scroller&&b.scroller.getUnionExtremes()||c,h=p.dataMin,e=p.dataMax;b=a.getYTDExtremes(e,h,b.time.useUTC);var m=b.min,n=b.max,l=a.selected,u=r(l),t=a.options.allButtonsEnabled,v=a.buttons;a.buttonOptions.forEach(function(d,b){var k=d._range,p=d.type,q=d.count||1,y=v[b],A=0,r=d._offsetMax-
d._offsetMin;d=b===l;var C=k>e-h,w=k<c.minRange,D=!1,x=!1;k=k===f;("month"===p||"year"===p)&&f+36E5>=864E5*{month:28,year:365}[p]*q-r&&f-36E5<=864E5*{month:31,year:366}[p]*q+r?k=!0:"ytd"===p?(k=n-m+r===f,D=!d):"all"===p&&(k=c.max-c.min>=e-h,x=!d&&u&&k);p=!t&&(C||w||x||g);q=d&&k||k&&!u&&!D||d&&a.frozenStates;p?A=3:q&&(u=!0,A=2);y.state!==A&&(y.setState(A),0===A&&l===b&&a.setSelected(null))})},computeButtonRange:function(a){var d=a.type,b=a.count||1,c={millisecond:1,second:1E3,minute:6E4,hour:36E5,
day:864E5,week:6048E5};if(c[d])a._range=c[d]*b;else if("month"===d||"year"===d)a._range=864E5*{month:30,year:365}[d]*b;a._offsetMin=g(a.offsetMin,0);a._offsetMax=g(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,b){var d=this.chart.options.rangeSelector,c=this.chart.time,k=this[a+"Input"];F(b)&&(k.previousValue=k.HCTime,k.HCTime=b);k.value=c.dateFormat(d.inputEditDateFormat||"%Y-%m-%d",k.HCTime);this[a+"DateBox"].attr({text:c.dateFormat(d.inputDateFormat||"%b %e, %Y",
k.HCTime)})},showInput:function(a){var d=this.inputGroup,b=this[a+"DateBox"];w(this[a+"Input"],{left:d.translateX+b.x+"px",top:d.translateY+"px",width:b.width-2+"px",height:b.height-2+"px",border:"2px solid silver"})},hideInput:function(a){w(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(d){function b(){var d=A.value,e=(h.inputDateParser||Date.parse)(d),b=f.xAxis[0],k=f.scroller&&f.scroller.xAxis?f.scroller.xAxis:b,g=k.dataMin;k=k.dataMax;e!==A.previousValue&&
(A.previousValue=e,r(e)||(e=d.split("-"),e=Date.UTC(a(e[0]),a(e[1])-1,a(e[2]))),r(e)&&(f.time.useUTC||(e+=6E4*(new Date).getTimezoneOffset()),l?e>c.maxInput.HCTime?e=void 0:e<g&&(e=g):e<c.minInput.HCTime?e=void 0:e>k&&(e=k),"undefined"!==typeof e&&b.setExtremes(l?e:b.min,l?b.max:e,void 0,void 0,{trigger:"rangeSelectorInput"})))}var c=this,f=c.chart,g=f.renderer.style||{},p=f.renderer,h=f.options.rangeSelector,e=c.div,l="min"===d,A,u,t=this.inputGroup;this[d+"Label"]=u=p.label(I.lang[l?"rangeSelectorFrom":
"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(t);t.offset+=u.width+5;this[d+"DateBox"]=p=p.label("",t.offset).addClass("highcharts-range-input").attr({padding:2,width:h.inputBoxWidth||90,height:h.inputBoxHeight||17,"text-align":"center"}).on("click",function(){c.showInput(d);c[d+"Input"].focus()});f.styledMode||p.attr({stroke:h.inputBoxBorderColor||"#cccccc","stroke-width":1});p.add(t);t.offset+=p.width+(l?10:0);this[d+"Input"]=A=z("input",{name:d,
className:"highcharts-range-selector",type:"text"},{top:f.plotTop+"px"},e);f.styledMode||(u.css(n(g,h.labelStyle)),p.css(n({color:"#333333"},g,h.inputStyle)),w(A,E({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:g.fontSize,fontFamily:g.fontFamily,top:"-9999em"},h.inputStyle)));A.onfocus=function(){c.showInput(d)};A.onblur=function(){A===m.doc.activeElement&&b();c.hideInput(d);A.blur()};A.onchange=b;A.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=
this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}},getYTDExtremes:function(a,b,c){var d=this.chart.time,k=new d.Date(a),f=d.get("FullYear",k);c=c?d.Date.UTC(f,0,1):+new d.Date(f,0,1);b=Math.max(b||0,c);k=k.getTime();return{max:Math.min(a||k,k),min:b}},render:function(a,b){var d=this,c=d.chart,f=c.renderer,k=c.container,h=c.options,e=h.exporting&&!1!==h.exporting.enabled&&h.navigation&&h.navigation.buttonOptions,
m=I.lang,l=d.div,n=h.rangeSelector,r=g(h.chart.style&&h.chart.style.zIndex,0)+1;h=n.floating;var u=d.buttons;l=d.inputGroup;var t=n.buttonTheme,v=n.buttonPosition,w=n.inputPosition,x=n.inputEnabled,B=t&&t.states,F=c.plotLeft,E=d.buttonGroup;var H=d.rendered;var N=d.options.verticalAlign,P=c.legend,Q=P&&P.options,J=v.y,O=w.y,S=H||!1,T=S?"animate":"attr",M=0,L=0,K;if(!1!==n.enabled){H||(d.group=H=f.g("range-selector-group").attr({zIndex:7}).add(),d.buttonGroup=E=f.g("range-selector-buttons").add(H),
d.zoomText=f.text(m.rangeSelectorZoom,0,15).add(E),c.styledMode||(d.zoomText.css(n.labelStyle),t["stroke-width"]=g(t["stroke-width"],0)),d.buttonOptions.forEach(function(a,e){u[e]=f.button(a.text,0,0,function(b){var c=a.events&&a.events.click,h;c&&(h=c.call(a,b));!1!==h&&d.clickButton(e);d.isActive=!0},t,B&&B.hover,B&&B.select,B&&B.disabled).attr({"text-align":"center"}).add(E)}),!1!==x&&(d.div=l=z("div",null,{position:"relative",height:0,zIndex:r}),k.parentNode.insertBefore(l,k),d.inputGroup=l=f.g("input-group").add(H),
l.offset=0,d.drawInput("min"),d.drawInput("max")));d.zoomText[T]({x:g(F+v.x,F)});var U=g(F+v.x,F)+d.zoomText.getBBox().width+5;d.buttonOptions.forEach(function(a,d){u[d][T]({x:U});U+=u[d].width+g(n.buttonSpacing,5)});F=c.plotLeft-c.spacing[3];d.updateButtonStates();e&&this.titleCollision(c)&&"top"===N&&"right"===v.align&&v.y+E.getBBox().height-12<(e.y||0)+e.height&&(M=-40);"left"===v.align?K=v.x-c.spacing[3]:"right"===v.align&&(K=v.x+M-c.spacing[1]);E.align({y:v.y,width:E.getBBox().width,align:v.align,
x:K},!0,c.spacingBox);d.group.placed=S;d.buttonGroup.placed=S;!1!==x&&(M=e&&this.titleCollision(c)&&"top"===N&&"right"===w.align&&w.y-l.getBBox().height-12<(e.y||0)+e.height+c.spacing[0]?-40:0,"left"===w.align?K=F:"right"===w.align&&(K=-Math.max(c.axisOffset[1],-M)),l.align({y:w.y,width:l.getBBox().width,align:w.align,x:w.x+K-2},!0,c.spacingBox),k=l.alignAttr.translateX+l.alignOptions.x-M+l.getBBox().x+2,e=l.alignOptions.width,m=E.alignAttr.translateX+E.getBBox().x,K=E.getBBox().width+20,(w.align===
v.align||m+K>k&&k+e>m&&J<O+l.getBBox().height)&&l.attr({translateX:l.alignAttr.translateX+(c.axisOffset[1]>=-M?0:-M),translateY:l.alignAttr.translateY+E.getBBox().height+10}),d.setInputValue("min",a),d.setInputValue("max",b),d.inputGroup.placed=S);d.group.align({verticalAlign:N},!0,c.spacingBox);a=d.group.getBBox().height+20;b=d.group.alignAttr.translateY;"bottom"===N&&(P=Q&&"bottom"===Q.verticalAlign&&Q.enabled&&!Q.floating?P.legendHeight+g(Q.margin,10):0,a=a+P-20,L=b-a-(h?0:n.y)-(c.titleOffset?
c.titleOffset[2]:0)-10);if("top"===N)h&&(L=0),c.titleOffset&&c.titleOffset[0]&&(L=c.titleOffset[0]),L+=c.margin[0]-c.spacing[0]||0;else if("middle"===N)if(O===J)L=0>O?b+void 0:b;else if(O||J)L=0>O||0>J?L-Math.min(O,J):b-a+NaN;d.group.translate(n.x,n.y+Math.floor(L));!1!==x&&(d.minInput.style.marginTop=d.group.translateY+"px",d.maxInput.style.marginTop=d.group.translateY+"px");d.rendered=!0}},getHeight:function(){var a=this.options,b=this.group,c=a.y,f=a.buttonPosition.y,g=a.inputPosition.y;if(a.height)return a.height;
a=b?b.getBBox(!0).height+13+c:0;b=Math.min(g,f);if(0>g&&0>f||0<g&&0<f)a+=Math.abs(b);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var d=this.chart;n(!0,d.options.rangeSelector,a);this.destroy();this.init(d);d.rangeSelector.render()},destroy:function(){var a=this,b=a.minInput,c=a.maxInput;a.unMouseDown();a.unResize();t(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);c&&(c.onfocus=c.onblur=c.onchange=null);B(a,function(d,b){d&&"chart"!==
b&&(d.destroy?d.destroy():d.nodeType&&u(this[b]));d!==x.prototype[b]&&(a[b]=null)},this)}};l.prototype.minFromRange=function(){var a=this.range,b={month:"Month",year:"FullYear"}[a.type],c=this.max,f=this.chart.time,m=function(a,e){var d=new f.Date(a),c=f.get(b,d);f.set(b,d,c+e);c===f.get(b,d)&&f.set("Date",d,0);return d.getTime()-a};if(r(a)){var p=c-a;var h=a}else p=c+m(c,-a.count),this.chart&&(this.chart.fixedRange=c-p);var e=g(this.dataMin,Number.MIN_VALUE);r(p)||(p=e);p<=e&&(p=e,"undefined"===
typeof h&&(h=m(p,a.count)),this.newMax=Math.min(p+h,this.dataMax));r(c)||(p=void 0);return p};m.RangeSelector||(v(c,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new x(this))}),v(c,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(r(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||
("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),v(c,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var d=this.extraBottomMargin,c=this.extraTopMargin;b&&b.enabled&&!F(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new x(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=
!0)),this.extraBottomMargin!==d||this.extraTopMargin!==c)&&(this.isDirtyBox=!0)}),v(c,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),v(c,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),c.prototype.callbacks.push(function(a){function b(){d=a.xAxis[0].getExtremes();
r(d.min)&&c.render(d.min,d.max)}var d,c=a.rangeSelector;if(c){var f=v(a.xAxis[0],"afterSetExtremes",function(a){c.render(a.min,a.max)});var g=v(a,"redraw",b);b()}v(a,"destroy",function(){c&&(g(),f())})}),m.RangeSelector=x)});I(z,"parts/StockChart.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(m,c){var x=c.addEvent,v=c.arrayMax,z=c.arrayMin,w=c.clamp,F=c.defined,t=c.extend,u=c.format,E=c.isNumber,b=c.isString,r=c.merge,n=c.pick,B=c.splat;c=m.Axis;var g=m.Chart,a=m.Point,f=m.Renderer,
l=m.Series,I=m.SVGRenderer,d=m.VMLRenderer,k=l.prototype,q=k.init,y=k.processData,D=a.prototype.tooltipFormatter;m.StockChart=m.stockChart=function(a,d,e){var c=b(a)||a.nodeName,h=arguments[c?1:0],f=h,k=h.series,p=m.getOptions(),l,q=h.chart&&h.chart.panning,t=n(h.navigator&&h.navigator.enabled,p.navigator.enabled,!0),u=q&&/y/.test(q.type),v={startOnTick:!1,endOnTick:!1};h.xAxis=B(h.xAxis||{}).map(function(a,b){return r({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},
showLastLabel:!0},p.xAxis,p.xAxis&&p.xAxis[b],a,{type:"datetime",categories:null},t?v:null)});h.yAxis=B(h.yAxis||{}).map(function(a,b){l=n(a.opposite,!0);return r({labels:{y:-2},opposite:l,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},p.yAxis,p.yAxis&&p.yAxis[b],a,u?v:null)});h.series=null;h=r({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:t},scrollbar:{enabled:n(p.scrollbar.enabled,!0)},rangeSelector:{enabled:n(p.rangeSelector.enabled,!0)},title:{text:null},
tooltip:{split:n(p.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},h,{isStock:!0});h.series=f.series=k;return c?new g(a,h,e):new g(h,d)};x(l,"setOptions",function(a){var b;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?b={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(b={marker:{enabled:!1,radius:2}}),b&&(a.plotOptions[this.type]=r(a.plotOptions[this.type],b)))});x(c,"autoLabelAlign",function(a){var b=this.chart,e=this.options;b=b._labelPanes=b._labelPanes||
{};var d=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(e=e.top+","+e.height,!b[e]&&d.enabled&&(15===d.x&&(d.x=0),"undefined"===typeof d.align&&(d.align="right"),b[e]=this,a.align="right",a.preventDefault()))});x(c,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});x(c,"getPlotLinePath",function(a){function d(a){var d="xAxis"===a?"yAxis":"xAxis";a=e.options[d];return E(a)?
[f[d][a]]:b(a)?[f.get(a)]:c.map(function(a){return a[d]})}var e=this,c=this.isLinked&&!this.series?this.linkedParent.series:this.series,f=e.chart,g=f.renderer,k=e.left,p=e.top,l,q,r,t,u=[],v=[],x=a.translatedValue,y=a.value,z=a.force;if(f.options.isStock&&!1!==a.acrossPanes&&"xAxis"===e.coll||"yAxis"===e.coll){a.preventDefault();v=d(e.coll);var B=e.isXAxis?f.yAxis:f.xAxis;B.forEach(function(a){if(F(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=F(a.options[b])?
f[b][a.options[b]]:f[b][0];e===b&&v.push(a)}});var D=v.length?[]:[e.isXAxis?f.yAxis[0]:f.xAxis[0]];v.forEach(function(a){-1!==D.indexOf(a)||m.find(D,function(b){return b.pos===a.pos&&b.len===a.len})||D.push(a)});var H=n(x,e.translate(y,null,null,a.old));E(H)&&(e.horiz?D.forEach(function(a){var b;q=a.pos;t=q+a.len;l=r=Math.round(H+e.transB);"pass"!==z&&(l<k||l>k+e.width)&&(z?l=r=w(l,k,k+e.width):b=!0);b||u.push("M",l,q,"L",r,t)}):D.forEach(function(a){var b;l=a.pos;r=l+a.len;q=t=Math.round(p+e.height-
H);"pass"!==z&&(q<p||q>p+e.height)&&(z?q=t=w(q,p,p+e.height):b=!0);b||u.push("M",l,q,"L",r,t)}));a.path=0<u.length?g.crispPolyLine(u,a.lineWidth||1):null}});I.prototype.crispPolyLine=function(a,b){var e;for(e=0;e<a.length;e+=6)a[e+1]===a[e+4]&&(a[e+1]=a[e+4]=Math.round(a[e+1])-b%2/2),a[e+2]===a[e+5]&&(a[e+2]=a[e+5]=Math.round(a[e+2])+b%2/2);return a};f===d&&(d.prototype.crispPolyLine=I.prototype.crispPolyLine);x(c,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});
x(c,"afterDrawCrosshair",function(a){var b,e;if(F(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,c=this.options.crosshair.label,f=this.horiz,g=this.opposite,k=this.left,p=this.top,l=this.crossLabel,m=c.format,q="",r="inside"===this.options.tickPosition,v=!1!==this.crosshair.snap,w=0,x=a.e||this.cross&&this.cross.e,y=a.point;var z=this.lin2log;if(this.isLog){a=z(this.min);var B=z(this.max)}else a=this.min,B=this.max;z=f?"center":g?"right"===this.labelAlign?"right":
"left":"left"===this.labelAlign?"left":"center";l||(l=this.crossLabel=d.renderer.label(null,null,null,c.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:c.align||z,padding:n(c.padding,8),r:n(c.borderRadius,3),zIndex:2}).add(this.labelGroup),d.styledMode||l.attr({fill:c.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:c.borderColor||"","stroke-width":c.borderWidth||0}).css(t({color:"#ffffff",
fontWeight:"normal",fontSize:"11px",textAlign:"center"},c.style)));f?(z=v?y.plotX+k:x.chartX,p+=g?0:this.height):(z=g?this.width+k:0,p=v?y.plotY+p:x.chartY);m||c.formatter||(this.isDatetimeAxis&&(q="%b %d, %Y"),m="{value"+(q?":"+q:"")+"}");q=v?y[this.isXAxis?"x":"y"]:this.toValue(f?x.chartX:x.chartY);l.attr({text:m?u(m,{value:q},d):c.formatter.call(this,q),x:z,y:p,visibility:q<a||q>B?"hidden":"visible"});c=l.getBBox();if(f){if(r&&!g||!r&&g)p=l.y-c.height}else p=l.y-c.height/2;f?(b=k-c.x,e=k+this.width-
c.x):(b="left"===this.labelAlign?k:0,e="right"===this.labelAlign?k+this.width:d.chartWidth);l.translateX<b&&(w=b-l.translateX);l.translateX+c.width>=e&&(w=-(l.translateX+c.width-e));l.attr({x:z+w,y:p,anchorX:f?z:this.opposite?0:d.chartWidth,anchorY:f?this.opposite?d.chartHeight:0:p+c.height/2})}});k.init=function(){q.apply(this,arguments);this.setCompare(this.options.compare)};k.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,e){var c=this.compareValue;return"undefined"!==
typeof b&&"undefined"!==typeof c?(b="value"===a?b-c:b/c*100-(100===this.options.compareBase?0:100),e&&(e.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};k.processData=function(a){var b,c=-1,d=!0===this.options.compareStart?0:1;y.apply(this,arguments);if(this.xAxis&&this.processedYData){var f=this.processedXData;var g=this.processedYData;var k=g.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=
0;b<k-d;b++){var p=g[b]&&-1<c?g[b][c]:g[b];if(E(p)&&f[b+d]>=this.xAxis.min&&0!==p){this.compareValue=p;break}}}};x(l,"afterGetExtremes",function(){if(this.modifyValue){var a=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)];this.dataMin=z(a);this.dataMax=v(a)}});c.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),n(b,!0)&&this.chart.redraw())};a.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",
(0<this.change?"+":"")+b(this.change,n(this.series.tooltipOptions.changeDecimals,2)));return D.apply(this,[a])};x(l,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var c=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,d=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=c&&(b-=Math.max(d-c,0))}!this.clipBox&&this.animate?(this.clipBox=r(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=
b):a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len}))}});x(g,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(r(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)});x(c,"afterSetScale",function(){var a=this,b=a.chart.options.chart&&a.chart.options.chart.panning;if(b&&("y"===b.type||"xy"===b.type)&&!a.isXAxis&&!F(a.panningState)){var c=
Number.MAX_VALUE,d=Number.MIN_VALUE;a.series.forEach(function(b){c=Math.min(m.arrayMin(b.yData),c)-(a.min&&a.dataMin?a.dataMin-a.min:0);d=Math.max(m.arrayMax(b.yData),d)+(a.max&&a.dataMax?a.max-a.dataMax:0)});a.panningState={startMin:c,startMax:d}}})});I(z,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map