/*
 Highcharts Gantt JS v8.0.0 (2020-02-08)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(C){d(C);d.Highcharts=C;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function C(d,v,n,F){d.hasOwnProperty(v)||(d[v]=F.apply(null,n))}d=d?d._modules:{};C(d,"mixins/tree-series.js",[d["parts/Color.js"],d["parts/Utilities.js"]],function(d,v){var n=v.extend,y=v.isArray,k=v.isNumber,x=
v.isObject,D=v.merge,A=v.pick;return{getColor:function(h,c){var e=c.index,g=c.mapOptionsToLevel,q=c.parentColor,t=c.parentColorIndex,a=c.series,b=c.colors,u=c.siblings,p=a.points,B=a.chart.options.chart,f;if(h){p=p[h.i];h=g[h.level]||{};if(g=p&&h.colorByPoint){var m=p.index%(b?b.length:B.colorCount);var z=b&&b[m]}if(!a.chart.styledMode){b=p&&p.options.color;B=h&&h.color;if(f=q)f=(f=h&&h.colorVariation)&&"brightness"===f.key?d.parse(q).brighten(e/u*f.to).get():q;f=A(b,B,z,f,a.color)}var E=A(p&&p.options.colorIndex,
h&&h.colorIndex,m,t,c.colorIndex)}return{color:f,colorIndex:E}},getLevelOptions:function(h){var c=null;if(x(h)){c={};var e=k(h.from)?h.from:1;var g=h.levels;var q={};var t=x(h.defaults)?h.defaults:{};y(g)&&(q=g.reduce(function(a,b){if(x(b)&&k(b.level)){var c=D({},b);var p="boolean"===typeof c.levelIsConstant?c.levelIsConstant:t.levelIsConstant;delete c.levelIsConstant;delete c.level;b=b.level+(p?0:e-1);x(a[b])?n(a[b],c):a[b]=c}return a},{}));g=k(h.to)?h.to:1;for(h=0;h<=g;h++)c[h]=D({},t,x(q[h])?q[h]:
{})}return c},setTreeValues:function g(c,e){var q=e.before,t=e.idRoot,a=e.mapIdToNode[t],b=e.points[c.i],u=b&&b.options||{},p=0,B=[];n(c,{levelDynamic:c.level-(("boolean"===typeof e.levelIsConstant?e.levelIsConstant:1)?0:a.level),name:A(b&&b.name,""),visible:t===c.id||("boolean"===typeof e.visible?e.visible:!1)});"function"===typeof q&&(c=q(c,e));c.children.forEach(function(f,m){var z=n({},e);n(z,{index:m,siblings:c.children.length,visible:c.visible});f=g(f,z);B.push(f);f.visible&&(p+=f.val)});c.visible=
0<p||c.visible;q=A(u.value,p);n(c,{children:B,childrenTotal:p,isLeaf:c.visible&&!p,val:q});return c},updateRootId:function(c){if(x(c)){var e=x(c.options)?c.options:{};e=A(c.rootNode,e.rootId,"");x(c.userOptions)&&(c.userOptions.rootId=e);c.rootNode=e}return e}}});C(d,"parts-gantt/Tree.js",[d["parts/Utilities.js"]],function(d){var v=d.extend,n=d.isNumber,y=d.pick,k=function(d,n){var h=d.reduce(function(c,e){var g=y(e.parent,"");"undefined"===typeof c[g]&&(c[g]=[]);c[g].push(e);return c},{});Object.keys(h).forEach(function(c,
e){var g=h[c];""!==c&&-1===n.indexOf(c)&&(g.forEach(function(c){e[""].push(c)}),delete e[c])});return h},x=function(d,k,h,c,e,g){var q=0,t=0,a=g&&g.after,b=g&&g.before;k={data:c,depth:h-1,id:d,level:h,parent:k};var u,p;"function"===typeof b&&b(k,g);b=(e[d]||[]).map(function(a){var f=x(a.id,d,h+1,a,e,g),m=a.start;a=!0===a.milestone?m:a.end;u=!n(u)||m<u?m:u;p=!n(p)||a>p?a:p;q=q+1+f.descendants;t=Math.max(f.height+1,t);return f});c&&(c.start=y(c.start,u),c.end=y(c.end,p));v(k,{children:b,descendants:q,
height:t});"function"===typeof a&&a(k,g);return k};return{getListOfParents:k,getNode:x,getTree:function(d,n){var h=d.map(function(c){return c.id});d=k(d,h);return x("",null,1,null,d,n)}}});C(d,"parts-gantt/GridAxis.js",[d["parts/Globals.js"],d["parts/Tick.js"],d["parts/Utilities.js"]],function(d,v,n){var y=n.addEvent,k=n.defined,x=n.erase,D=n.isArray,A=n.isNumber,h=n.merge,c=n.pick,e=n.timeUnits,g=n.wrap,q=d.dateFormat,t=function(f){return n.isObject(f,!0)},a=d.Chart,b=d.Axis,u=function(f){var m=
f.options;m.labels||(m.labels={});m.labels.align=c(m.labels.align,"center");f.categories||(m.showLastLabel=!1);f.labelRotation=0;m.labels.rotation=0},p={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};b.prototype.isOuterAxis=function(){var f=this,m=f.columnIndex,a=f.linkedParent&&f.linkedParent.columns||f.columns,c=m?f.linkedParent:f,b=-1,e=0;f.chart[f.coll].forEach(function(m,r){m.side!==f.side||m.options.isInternal||(e=r,m===c&&(b=r))});return e===b&&(A(m)?a.length===m:!0)};
b.prototype.getMaxLabelDimensions=function(f,m){var a={width:0,height:0};m.forEach(function(m){m=f[m];if(t(m)){var z=t(m.label)?m.label:{};m=z.getBBox?z.getBBox().height:0;z.textStr&&!A(z.textPxLength)&&(z.textPxLength=z.getBBox().width);z=A(z.textPxLength)?Math.round(z.textPxLength):0;a.height=Math.max(m,a.height);a.width=Math.max(z,a.width)}});return a};d.dateFormats.W=function(f){f=new Date(f);f.setHours(0,0,0,0);f.setDate(f.getDate()-(f.getDay()||7));var m=new Date(f.getFullYear(),0,1);return Math.ceil(((f-
m)/864E5+1)/7)};d.dateFormats.E=function(f){return q("%a",f,!0).charAt(0)};y(v,"afterGetLabelPosition",function(f){var m=this.label,a=this.axis,b=a.reversed,c=a.chart,e=a.options,g=e&&t(e.grid)?e.grid:{};e=a.options.labels;var r=e.align,l=p[a.side],w=f.tickmarkOffset,d=a.tickPositions,q=this.pos-w;d=A(d[f.index+1])?d[f.index+1]-w:a.max+w;var h=a.tickSize("tick",!0);w=D(h)?h[0]:0;h=h&&h[1]/2;if(!0===g.enabled){if("top"===l){g=a.top+a.offset;var u=g-w}else"bottom"===l?(u=c.chartHeight-a.bottom+a.offset,
g=u+w):(g=a.top+a.len-a.translate(b?d:q),u=a.top+a.len-a.translate(b?q:d));"right"===l?(l=c.chartWidth-a.right+a.offset,b=l+w):"left"===l?(b=a.left+a.offset,l=b-w):(l=Math.round(a.left+a.translate(b?d:q))-h,b=Math.round(a.left+a.translate(b?q:d))-h);this.slotWidth=b-l;f.pos.x="left"===r?l:"right"===r?b:l+(b-l)/2;f.pos.y=u+(g-u)/2;c=c.renderer.fontMetrics(e.style.fontSize,m.element);m=m.getBBox().height;e.useHTML?f.pos.y+=c.b+-(m/2):(m=Math.round(m/c.h),f.pos.y+=(c.b-(c.h-c.f))/2+-((m-1)*c.h/2));f.pos.x+=
a.horiz&&e.x||0}});y(b,"afterTickSize",function(f){var a=this.defaultLeftAxisOptions,b=this.horiz,c=this.options.grid;c=void 0===c?{}:c;var e=this.maxLabelDimensions;c.enabled&&(a=2*Math.abs(a.labels.x),b=b?c.cellHeight||a+e.height:a+e.width,D(f.tickSize)?f.tickSize[0]=b:f.tickSize=[b])});y(b,"afterGetTitlePosition",function(f){var a=this.options;if(!0===(a&&t(a.grid)?a.grid:{}).enabled){var b=this.axisTitle,e=b&&b.getBBox().width,g=this.horiz,d=this.left,q=this.top,r=this.width,l=this.height,w=a.title;
a=this.opposite;var h=this.offset,u=this.tickSize()||[0],H=w.x||0,k=w.y||0,n=c(w.margin,g?5:10);b=this.chart.renderer.fontMetrics(w.style&&w.style.fontSize,b).f;u=(g?q+l:d)+u[0]/2*(a?-1:1)*(g?1:-1)+(this.side===p.bottom?b:0);f.titlePosition.x=g?d-e/2-n+H:u+(a?r:0)+h+H;f.titlePosition.y=g?u-(a?l:0)+(a?b:-b)/2+h+k:q-n+k}});g(b.prototype,"unsquish",function(f){var a=this.options;return!0===(a&&t(a.grid)?a.grid:{}).enabled&&this.categories?this.tickInterval:f.apply(this,Array.prototype.slice.call(arguments,
1))});y(b,"afterSetOptions",function(a){var f=this.options;a=a.userOptions;var b=f&&t(f.grid)?f.grid:{};if(!0===b.enabled){var g=h(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",
[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(k(a.linkedTo)&&!k(a.tickPixelInterval)&&(g.tickPixelInterval=350),k(a.tickPixelInterval)||!k(a.linkedTo)||k(a.tickPositioner)||k(a.tickInterval)||(g.tickPositioner=function(a,f){var b=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(b){var r,l=g.units;for(r=0;r<l.length;r++)if(l[r][0]===b.unitName){var w=r;break}if(l[w+1]){var m=l[w+
1][0];var c=(l[w+1][1]||[1])[0]}else"year"===b.unitName&&(m="year",c=10*b.count);b=e[m];this.tickInterval=b*c;return this.getTimeTicks({unitRange:b,count:c,unitName:m},a,f,this.options.startOfWeek)}}));h(!0,this.options,g);this.horiz&&(f.minPadding=c(a.minPadding,0),f.maxPadding=c(a.maxPadding,0));A(f.grid.borderWidth)&&(f.tickWidth=f.lineWidth=b.borderWidth)}});y(b,"afterSetAxisTranslation",function(){var a=this.options,b=a&&t(a.grid)?a.grid:{},c=this.tickPositions&&this.tickPositions.info,e=this.userOptions.labels||
{};this.horiz&&(!0===b.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),c&&(!1===a.dateTimeLabelFormats[c.unitName].range||1<c.count)&&!k(e.align)&&(a.labels.align="left",k(e.x)||(a.labels.x=3)))});y(b,"trimTicks",function(){var a=this.options,b=a&&t(a.grid)?a.grid:{},c=this.categories,e=this.tickPositions,g=e[0],d=e[e.length-1],p=this.linkedParent&&this.linkedParent.min||this.min,r=this.linkedParent&&this.linkedParent.max||this.max,l=this.tickInterval;!0!==b.enabled||c||!this.horiz&&
!this.isLinked||(g<p&&g+l>p&&!a.startOnTick&&(e[0]=p),d>r&&d-l<r&&!a.endOnTick&&(e[e.length-1]=r))});y(b,"afterRender",function(){var a=this.options,b=a&&t(a.grid)?a.grid:{},c=this.chart.renderer;if(!0===b.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.isOuterAxis()&&this.axisLine){var e=a.lineWidth;if(e){var g=this.getLinePath(e);var d=g.indexOf("M")+1;var q=g.indexOf("L")+1;b=g.indexOf("M")+2;var r=g.indexOf("L")+
2;var l=(this.tickSize("tick")[0]-1)*(this.side===p.top||this.side===p.left?-1:1);this.horiz?(g[b]+=l,g[r]+=l):(g[d]+=l,g[q]+=l);this.axisLineExtra?this.axisLineExtra.animate({d:g}):(this.axisLineExtra=c.path(g).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),c.styledMode||this.axisLineExtra.attr({stroke:a.lineColor,"stroke-width":e}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(a){a.render()})}});var B={afterGetOffset:function(){(this.columns||
[]).forEach(function(a){a.getOffset()})},afterInit:function(){var a=this.chart,c=this.userOptions,e=this.options;e=e&&t(e.grid)?e.grid:{};e.enabled&&(u(this),g(this,"labelFormatter",function(a){var b=this.axis,l=b.tickPositions,f=this.value,e=(b.isLinked?b.linkedParent:b).series[0],c=f===l[0];l=f===l[l.length-1];e=e&&d.find(e.options.data,function(a){return a[b.isXAxis?"x":"y"]===f});this.isFirst=c;this.isLast=l;this.point=e;return a.call(this)}));if(e.columns)for(var p=this.columns=[],q=this.columnIndex=
0;++q<e.columns.length;){var k=h(c,e.columns[e.columns.length-q-1],{linkedTo:0,type:"category"});delete k.grid.columns;k=new b(this.chart,k,!0);k.isColumn=!0;k.columnIndex=q;x(a.axes,k);x(a[this.coll],k);p.push(k)}},afterSetOptions:function(a){a=(a=a.userOptions)&&t(a.grid)?a.grid:{};var b=a.columns;a.enabled&&b&&h(!0,this.options,b[b.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(a){a.setScale()})},destroy:function(a){(this.columns||[]).forEach(function(b){b.destroy(a.keepEvents)})},
init:function(a){var b=(a=a.userOptions)&&t(a.grid)?a.grid:{};b.enabled&&k(b.borderColor)&&(a.tickColor=a.lineColor=b.borderColor)}};Object.keys(B).forEach(function(a){y(b,a,B[a])});y(a,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})})});C(d,"modules/broken-axis.src.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(d,v){var n=v.addEvent,y=v.extend,k=v.fireEvent,x=v.isArray,D=v.pick,A=d.find,h=d.Axis;
v=d.Series;var c=function(e,c){return A(c,function(c){return c.from<e&&e<c.to})};y(h.prototype,{isInBreak:function(e,c){var g=e.repeat||Infinity,d=e.from,a=e.to-e.from;c=c>=d?(c-d)%g:g-(d-c)%g;return e.inclusive?c<=a:c<a&&0!==c},isInAnyBreak:function(c,g){var e=this.options.breaks,d=e&&e.length,a;if(d){for(;d--;)if(this.isInBreak(e[d],c)){var b=!0;a||(a=D(e[d].showPoints,!this.isXAxis))}var h=b&&g?b&&!a:b}return h}});n(h,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,
!1)});n(h,"afterSetTickPositions",function(){if(this.isBroken){var c=this.tickPositions,d=this.tickPositions.info,h=[],k;for(k=0;k<c.length;k++)this.isInAnyBreak(c[k])||h.push(c[k]);this.tickPositions=h;this.tickPositions.info=d}});n(h,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});h.prototype.setBreaks=function(e,d){function g(b){var c=b,e;for(e=0;e<a.breakArray.length;e++){var f=a.breakArray[e];if(f.to<=b)c-=f.len;else if(f.from>=b)break;else if(a.isInBreak(f,b)){c-=b-f.from;
break}}return c}function t(b){var c;for(c=0;c<a.breakArray.length;c++){var e=a.breakArray[c];if(e.from>=b)break;else e.to<b?b+=e.len:a.isInBreak(e,b)&&(b+=e.len)}return b}var a=this,b=x(e)&&!!e.length;a.isDirty=a.isBroken!==b;a.isBroken=b;a.options.breaks=a.userOptions.breaks=e;a.forceRedraw=!0;a.series.forEach(function(a){a.isDirty=!0});b||a.val2lin!==g||(delete a.val2lin,delete a.lin2val);b&&(a.userOptions.ordinal=!1,a.val2lin=g,a.lin2val=t,a.setExtremes=function(a,b,e,f,d){if(this.isBroken){for(var g,
m=this.options.breaks;g=c(a,m);)a=g.to;for(;g=c(b,m);)b=g.from;b<a&&(b=a)}h.prototype.setExtremes.call(this,a,b,e,f,d)},a.setAxisTranslation=function(b){h.prototype.setAxisTranslation.call(this,b);this.unitLength=null;if(this.isBroken){b=a.options.breaks;var c=[],e=[],f=0,d,g=a.userMin||a.min,q=a.userMax||a.max,t=D(a.pointRangePadding,0),n;b.forEach(function(b){d=b.repeat||Infinity;a.isInBreak(b,g)&&(g+=b.to%d-g%d);a.isInBreak(b,q)&&(q-=q%d-b.from%d)});b.forEach(function(a){r=a.from;for(d=a.repeat||
Infinity;r-d>g;)r-=d;for(;r<g;)r+=d;for(n=r;n<q;n+=d)c.push({value:n,move:"in"}),c.push({value:n+(a.to-a.from),move:"out",size:a.breakSize})});c.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var u=0;var r=g;c.forEach(function(a){u+="in"===a.move?1:-1;1===u&&"in"===a.move&&(r=a.value);0===u&&(e.push({from:r,to:a.value,len:a.value-r-(a.size||0)}),f+=a.value-r-(a.size||0))});a.breakArray=e;a.unitLength=q-g-f+t;k(a,"afterBreaks");a.staticScale?a.transA=
a.staticScale:a.unitLength&&(a.transA*=(q-a.min+t)/a.unitLength);t&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=g;a.max=q}});D(d,!0)&&this.chart.redraw()};n(v,"afterGeneratePoints",function(){var c=this.options.connectNulls,d=this.points,h=this.xAxis,k=this.yAxis;if(this.isDirty)for(var a=d.length;a--;){var b=d[a],n=!(null===b.y&&!1===c)&&(h&&h.isInAnyBreak(b.x,!0)||k&&k.isInAnyBreak(b.y,!0));b.visible=n?!1:!1!==b.options.visible}});n(v,"afterRender",function(){this.drawBreaks(this.xAxis,
["x"]);this.drawBreaks(this.yAxis,D(this.pointArrayMap,["y"]))});d.Series.prototype.drawBreaks=function(c,d){var e=this,g=e.points,a,b,h,p;c&&d.forEach(function(d){a=c.breakArray||[];b=c.isXAxis?c.min:D(e.options.threshold,c.min);g.forEach(function(e){p=D(e["stack"+d.toUpperCase()],e[d]);a.forEach(function(a){h=!1;if(b<a.from&&p>a.to||b>a.from&&p<a.from)h="pointBreak";else if(b<a.from&&p>a.from&&p<a.to||b>a.from&&p>a.to&&p<a.from)h="pointInBreak";h&&k(c,h,{point:e,brk:a})})})})};d.Series.prototype.gappedPath=
function(){var c=this.currentDataGrouping,g=c&&c.gapSize;c=this.options.gapSize;var h=this.points.slice(),k=h.length-1,a=this.yAxis,b;if(c&&0<k)for("value"!==this.options.gapUnit&&(c*=this.basePointRange),g&&g>c&&g>=this.basePointRange&&(c=g),b=void 0;k--;)b&&!1!==b.visible||(b=h[k+1]),g=h[k],!1!==b.visible&&!1!==g.visible&&(b.x-g.x>c&&(b=(g.x+b.x)/2,h.splice(k+1,0,{isNull:!0,x:b}),this.options.stacking&&(b=a.stacks[this.stackKey][b]=new d.StackItem(a,a.options.stackLabels,!1,b,this.stack),b.total=
0)),b=g);return this.getGraphPath(h)}});C(d,"parts-gantt/TreeGrid.js",[d["parts/Globals.js"],d["mixins/tree-series.js"],d["parts/Tick.js"],d["parts-gantt/Tree.js"],d["parts/Utilities.js"]],function(d,v,n,C,k){var x=k.addEvent,y=k.defined,A=k.fireEvent,h=k.extend,c=k.isNumber,e=k.isString,g=k.merge,q=k.pick,t=k.wrap,a=function(a){return Array.prototype.slice.call(a,1)},b=d.find,u=v.getLevelOptions,p=function(a){return k.isObject(a,!0)};d=d.Axis;v=function(a,b){var c;for(c in b)if(Object.hasOwnProperty.call(b,
c)){var l=b[c];t(a,c,l)}};var B=function(a,b){var c=a.collapseStart;a=a.collapseEnd;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}},f=function(a){return Object.keys(a.mapOfPosToGridNode).reduce(function(b,c){c=+c;a.min<=c&&a.max>=c&&!a.isInAnyBreak(c)&&b.push(c);return b},[])},m=function(a,b){var c=a.options.breaks||[],d=B(b,a.max);return c.some(function(a){return a.from===d.from&&a.to===d.to})},z=function(a,b){var c=a.options.breaks||[];a=B(b,a.max);c.push(a);return c},E=function(a,b){var c=a.options.breaks||
[],d=B(b,a.max);return c.reduce(function(a,b){b.to===d.to&&b.from===d.from||a.push(b);return a},[])},F=function(a,b){var d=a.labelIcon,e=!d,l=b.renderer,g=b.xy,f=b.options,h=f.width,k=f.height,r=g.x-h/2-f.padding;g=g.y-k/2;var m=b.collapsed?90:180,p=b.show&&c(g);e&&(a.labelIcon=d=l.path(l.symbols[f.type](f.x,f.y,h,k)).addClass("highcharts-label-icon").add(b.group));p||d.attr({y:-9999});l.styledMode||d.attr({"stroke-width":1,fill:q(b.color,"#666666")}).css({cursor:"pointer",stroke:f.lineColor,strokeWidth:f.lineWidth});
d[e?"attr":"animate"]({translateX:r,translateY:g,rotation:m})},I=function(a,c,d){var g=[],l=[],f={},h={},k=-1,r="boolean"===typeof c?c:!1;a=C.getTree(a,{after:function(a){a=h[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=a.descendants+1;b=Math.max(a.height+1,b)});a.descendants=c;a.height=b;a.collapsed&&l.push(a)},before:function(a){var c=p(a.data)?a.data:{},d=e(c.name)?c.name:"",l=f[a.parent];l=p(l)?h[l.pos]:null;var w=function(a){return a.name===d},m;r&&p(l)&&(m=b(l.children,w))?(w=m.pos,
m.nodes.push(a)):w=k++;h[w]||(h[w]=m={depth:l?l.depth+1:0,name:d,nodes:[a],children:[],pos:w},-1!==w&&g.push(d),p(l)&&l.children.push(m));e(a.id)&&(f[a.id]=a);!0===c.collapsed&&(m.collapsed=!0);a.pos=w}});h=function(a,b){var c=function(a,d,e){var l=d+(-1===d?0:b-1),g=(l-d)/2,f=d+g;a.nodes.forEach(function(a){var b=a.data;p(b)&&(b.y=d+b.seriesIndex,delete b.seriesIndex);a.pos=f});e[f]=a;a.pos=f;a.tickmarkOffset=g+.5;a.collapseStart=l+.5;a.children.forEach(function(a){c(a,l+1,e);l=a.collapseEnd-.5});
a.collapseEnd=l+.5;return e};return c(a["-1"],-1,{})}(h,d);return{categories:g,mapOfIdToNode:f,mapOfPosToGridNode:h,collapsedNodes:l,tree:a}},G=function(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(b){var c=b.options||{},d=c.labels,e,f=c.uniqueNames,l=0;if(!b.mapOfPosToGridNode||b.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){c=b.series.reduce(function(a,b){b.visible&&(b.options.data.forEach(function(b){p(b)&&(b.seriesIndex=l,
a.push(b))}),!0===f&&l++);return a},[]);var h=I(c,f,!0===f?l:1);b.categories=h.categories;b.mapOfPosToGridNode=h.mapOfPosToGridNode;b.hasNames=!0;b.tree=h.tree;b.series.forEach(function(a){var b=a.options.data.map(function(a){return p(a)?g(a):a});a.visible&&a.setData(b,!1)});b.mapOptionsToLevel=u({defaults:d,from:1,levels:d.levels,to:b.tree.height});"beforeRender"===a.type&&(e=x(b,"foundExtremes",function(){h.collapsedNodes.forEach(function(a){a=z(b,a);b.setBreaks(a,!1)});e()}))}})};v(d.prototype,
{init:function(a,b,c){var d="treegrid"===c.type;d&&(x(b,"beforeRender",G),x(b,"beforeRedraw",G),c=g({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));a.apply(this,[b,c]);d&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(b){var d=this.options,e=d&&d.labels;d=e&&c(e.indentation)?d.labels.indentation:
0;e=b.apply(this,a(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var f=this.mapOfPosToGridNode[-1].height;e.width+=d*(f-1)}return e},generateTick:function(b,c){var d=p(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},e=this.ticks,f=e[c],g;if("treegrid"===this.options.type){var h=this.mapOfPosToGridNode[c];(d=d[h.depth])&&(g={labels:d});f?(f.parameters.category=h.name,f.options=g,f.addLabel()):e[c]=new n(this,c,null,void 0,{category:h.name,tickmarkOffset:h.tickmarkOffset,
options:g})}else b.apply(this,a(arguments))},setTickInterval:function(b){var c=this.options;"treegrid"===c.type?(this.min=q(this.userMin,c.min,this.dataMin),this.max=q(this.userMax,c.max,this.dataMax),A(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?f(this):[]):b.apply(this,a(arguments))}});v(n.prototype,{getLabelPosition:function(a,b,d,e,f,g,h,k,m){var l=q(this.options&&this.options.labels,g);g=this.pos;var n=
this.axis,r="treegrid"===n.options.type;a=a.apply(this,[b,d,e,f,l,h,k,m]);r&&(b=l&&p(l.symbol)?l.symbol:{},l=l&&c(l.indentation)?l.indentation:0,g=(g=(n=n.mapOfPosToGridNode)&&n[g])&&g.depth||1,a.x+=b.width+2*b.padding+(g-1)*l);return a},renderLabel:function(b){var c=this,d=c.pos,e=c.axis,f=c.label,g=e.mapOfPosToGridNode,h=e.options,k=q(c.options&&c.options.labels,h&&h.labels),n=k&&p(k.symbol)?k.symbol:{},r=(g=g&&g[d])&&g.depth;h="treegrid"===h.type;var t=!(!f||!f.element),u=-1<e.tickPositions.indexOf(d);
d=e.chart.styledMode;h&&g&&t&&f.addClass("highcharts-treegrid-node-level-"+r);b.apply(c,a(arguments));h&&g&&t&&0<g.descendants&&(e=m(e,g),F(c,{color:!d&&f.styles.color,collapsed:e,group:f.parentGroup,options:n,renderer:f.renderer,show:u,xy:f.xy}),n="highcharts-treegrid-node-"+(e?"expanded":"collapsed"),f.addClass("highcharts-treegrid-node-"+(e?"collapsed":"expanded")).removeClass(n),d||f.css({cursor:"pointer"}),[f,c.labelIcon].forEach(function(a){a.attachedTreeGridEvents||(x(a.element,"mouseover",
function(){f.addClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:"underline"})}),x(a.element,"mouseout",function(){var a=y(k.style)?k.style:{};f.removeClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:a.textDecoration})}),x(a.element,"click",function(){c.toggleCollapse()}),a.attachedTreeGridEvents=!0)}))}});h(n.prototype,{collapse:function(a){var b=this.axis,c=z(b,b.mapOfPosToGridNode[this.pos]);b.setBreaks(c,q(a,!0))},expand:function(a){var b=
this.axis,c=E(b,b.mapOfPosToGridNode[this.pos]);b.setBreaks(c,q(a,!0))},toggleCollapse:function(a){var b=this.axis;var c=b.mapOfPosToGridNode[this.pos];c=m(b,c)?E(b,c):z(b,c);b.setBreaks(c,q(a,!0))}});d.prototype.utils={getNode:C.getNode}});C(d,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map