/*
 Highstock JS v8.0.0 (2020-02-08)

 Indicator series type for Highstock

 (c) 2010-2019 Daniel Studencki

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/acceleration-bands",["highcharts","highcharts/modules/stock"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,c,f,k){a.hasOwnProperty(c)||(a[c]=k.apply(null,f))}a=a?a._modules:{};f(a,"mixins/multipe-lines.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,c){var f=
c.defined,k=c.error,r=c.merge,e=a.each,w=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(b){var a=[];e(this.pointArrayMap,function(e){e!==b&&a.push("plot"+e.charAt(0).toUpperCase()+e.slice(1))});return a},toYData:function(b){var a=[];e(this.pointArrayMap,function(e){a.push(b[e])});return a},translate:function(){var b=this,a=b.pointArrayMap,c=[],h;c=b.getTranslatedLinesNames();w.prototype.translate.apply(b,arguments);
e(b.points,function(f){e(a,function(a,e){h=f[a];null!==h&&(f[c[e]]=b.yAxis.toPixels(h,!0))})})},drawGraph:function(){var b=this,a=b.linesApiNames,c=b.points,h=c.length,l=b.options,t=b.graph,u={options:{gapSize:l.gapSize}},m=[],v=b.getTranslatedLinesNames(b.pointValKey),d;e(v,function(a,b){for(m[b]=[];h--;)d=c[h],m[b].push({x:d.x,plotX:d.plotX,plotY:d[a],isNull:!f(d[a])});h=c.length});e(a,function(a,e){m[e]?(b.points=m[e],l[a]?b.options=r(l[a].styles,u):k('Error: "There is no '+a+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),
b.graph=b["graph"+a],w.prototype.drawGraph.call(b),b["graph"+a]=b.graph):k('Error: "'+a+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});b.points=c;b.options=l;b.graph=t;w.prototype.drawGraph.call(b)}}});f(a,"indicators/acceleration-bands.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/multipe-lines.js"]],function(a,c,f){var k=c.correctFloat;c=c.merge;var r=a.seriesTypes.sma;a.seriesType("abands","sma",{params:{period:20,
factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},c(f,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Acceleration Bands",nameComponents:["period","factor"],linesApiNames:["topLine","bottomLine"],getValues:function(a,c){var b=c.period,e=c.factor;c=c.index;var f=a.xData,h=(a=a.yData)?a.length:0,l=[],t=[],u=[],m=[],v=[],d;if(!(h<b)){for(d=0;d<=h;d++){if(d<h){var g=a[d][2];var n=a[d][1];var q=
e;g=k(n-g)/(k(n+g)/2)*1E3*q;l.push(a[d][1]*k(1+2*g));t.push(a[d][2]*k(1-2*g))}if(d>=b){g=f.slice(d-b,d);var p=a.slice(d-b,d);q=r.prototype.getValues.call(this,{xData:g,yData:l.slice(d-b,d)},{period:b});n=r.prototype.getValues.call(this,{xData:g,yData:t.slice(d-b,d)},{period:b});p=r.prototype.getValues.call(this,{xData:g,yData:p},{period:b,index:c});g=p.xData[0];q=q.yData[0];n=n.yData[0];p=p.yData[0];u.push([g,q,p,n]);m.push(g);v.push([q,p,n])}}return{values:u,xData:m,yData:v}}}}));""});f(a,"masters/indicators/acceleration-bands.src.js",
[],function(){})});
//# sourceMappingURL=acceleration-bands.js.map