/*
 Highstock JS v8.0.0 (2020-02-08)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/aroon",["highcharts","highcharts/modules/stock"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,c,f,m){a.hasOwnProperty(c)||(a[c]=m.apply(null,f))}a=a?a._modules:{};f(a,"mixins/multipe-lines.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,c){var f=c.defined,
m=c.error,q=c.merge,k=a.each,l=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(b){var a=[];k(this.pointArrayMap,function(d){d!==b&&a.push("plot"+d.charAt(0).toUpperCase()+d.slice(1))});return a},toYData:function(b){var a=[];k(this.pointArrayMap,function(d){a.push(b[d])});return a},translate:function(){var b=this,a=b.pointArrayMap,d=[],e;d=b.getTranslatedLinesNames();l.prototype.translate.apply(b,arguments);k(b.points,
function(l){k(a,function(a,g){e=l[a];null!==e&&(l[d[g]]=b.yAxis.toPixels(e,!0))})})},drawGraph:function(){var b=this,a=b.linesApiNames,d=b.points,e=d.length,c=b.options,r=b.graph,g={options:{gapSize:c.gapSize}},h=[],n=b.getTranslatedLinesNames(b.pointValKey),p;k(n,function(a,b){for(h[b]=[];e--;)p=d[e],h[b].push({x:p.x,plotX:p.plotX,plotY:p[a],isNull:!f(p[a])});e=d.length});k(a,function(a,d){h[d]?(b.points=h[d],c[a]?b.options=q(c[a].styles,g):m('Error: "There is no '+a+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),
b.graph=b["graph"+a],l.prototype.drawGraph.call(b),b["graph"+a]=b.graph):m('Error: "'+a+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});b.points=d;b.options=c;b.graph=r;l.prototype.drawGraph.call(b)}}});f(a,"indicators/aroon.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/multipe-lines.js"]],function(a,c,f){function m(a,b){var c=a[0],d=0,e;for(e=1;e<a.length;e++)if("max"===b&&a[e]>=c||"min"===b&&a[e]<=c)c=a[e],d=e;return d}
var q=c.merge,k=c.pick;a.seriesType("aroon","sma",{params:{period:25},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},q(f,{nameBase:"Aroon",pointArrayMap:["y","aroonDown"],pointValKey:"y",linesApiNames:["aroonDown"],getValues:function(a,b){b=b.period;var c=a.xData,d=(a=a.yData)?a.length:
0,e=[],f=[],l=[],g;for(g=b-1;g<d;g++){var h=a.slice(g-b+1,g+2);var n=m(h.map(function(a){return k(a[2],a)}),"min");h=m(h.map(function(a){return k(a[1],a)}),"max");h=h/b*100;n=n/b*100;c[g+1]&&(e.push([c[g+1],h,n]),f.push(c[g+1]),l.push([h,n]))}return{values:e,xData:f,yData:l}}}));""});f(a,"masters/indicators/aroon.src.js",[],function(){})});
//# sourceMappingURL=aroon.js.map