/*
 Highstock JS v8.0.0 (2020-02-08)

 Indicator series type for Highstock

 (c) 2010-2019 Pawe Fus

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/bollinger-bands",["highcharts","highcharts/modules/stock"],function(c){a(c);a.Highcharts=c;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function c(a,e,c,m){a.hasOwnProperty(e)||(a[e]=m.apply(null,c))}a=a?a._modules:{};c(a,"mixins/multipe-lines.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,e){var c=
e.defined,m=e.error,n=e.merge,f=a.each,g=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(b){var a=[];f(this.pointArrayMap,function(d){d!==b&&a.push("plot"+d.charAt(0).toUpperCase()+d.slice(1))});return a},toYData:function(b){var a=[];f(this.pointArrayMap,function(d){a.push(b[d])});return a},translate:function(){var b=this,a=b.pointArrayMap,d=[],c;d=b.getTranslatedLinesNames();g.prototype.translate.apply(b,arguments);
f(b.points,function(g){f(a,function(a,e){c=g[a];null!==c&&(g[d[e]]=b.yAxis.toPixels(c,!0))})})},drawGraph:function(){var a=this,e=a.linesApiNames,d=a.points,w=d.length,t=a.options,A=a.graph,B={options:{gapSize:t.gapSize}},p=[],h=a.getTranslatedLinesNames(a.pointValKey),q;f(h,function(a,b){for(p[b]=[];w--;)q=d[w],p[b].push({x:q.x,plotX:q.plotX,plotY:q[a],isNull:!c(q[a])});w=d.length});f(e,function(b,d){p[d]?(a.points=p[d],t[b]?a.options=n(t[b].styles,B):m('Error: "There is no '+b+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),
a.graph=a["graph"+b],g.prototype.drawGraph.call(a),a["graph"+b]=a.graph):m('Error: "'+b+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=d;a.options=t;a.graph=A;g.prototype.drawGraph.call(a)}}});c(a,"indicators/bollinger-bands.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/multipe-lines.js"]],function(a,c,z){var e=c.isArray,n=c.merge,f=a.seriesTypes.sma;a.seriesType("bb","sma",{params:{period:20,standardDeviation:2,
index:3},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"}},n(z,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],init:function(){f.prototype.init.apply(this,
arguments);this.options=n({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(a,b){var c=b.period,d=b.standardDeviation,g=a.xData,t=(a=a.yData)?a.length:0,m=[],n=[],p=[],h;if(!(g.length<c)){var q=e(a[0]);for(h=c;h<=t;h++){var u=g.slice(h-c,h);var r=a.slice(h-c,h);var k=f.prototype.getValues.call(this,{xData:u,yData:r},b);u=k.xData[0];k=k.yData[0];for(var x=0,y=r.length,v=0;v<y;v++){var l=(q?r[v][b.index]:r[v])-k;x+=l*l}l=Math.sqrt(x/
(y-1));r=k+d*l;l=k-d*l;m.push([u,r,k,l]);n.push(u);p.push([r,k,l])}return{values:m,xData:n,yData:p}}}}));""});c(a,"masters/indicators/bollinger-bands.src.js",[],function(){})});
//# sourceMappingURL=bollinger-bands.js.map