/*
 Highstock JS v8.0.0 (2020-02-08)

 Indicator series type for Highstock

 (c) 2010-2019 Pawel Fus, Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators",["highcharts","highcharts/modules/stock"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,e,p,g){a.hasOwnProperty(e)||(a[e]=g.apply(null,p))}a=a?a._modules:{};f(a,"mixins/indicator-required.js",[a["parts/Utilities.js"]],function(a){var e=a.error;return{isParentLoaded:function(a,
g,f,k,q){if(a)return k?k(a):!0;e(q||this.generateMessage(f,g));return!1},generateMessage:function(a,e){return'Error: "'+a+'" indicator type requires "'+e+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});f(a,"indicators/indicators.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],function(a,e,f){var g=e.addEvent,k=e.error,p=e.extend,q=e.isArray,t=e.pick,u=e.splat,l=a.Series;e=a.seriesType;var r=a.seriesTypes,
m=a.seriesTypes.ohlc.prototype,v=f.generateMessage;g(a.Series,"init",function(c){c=c.options;c.useOhlcData&&"highcharts-navigator-series"!==c.id&&p(this,{pointValKey:m.pointValKey,keys:m.keys,pointArrayMap:m.pointArrayMap,toYData:m.toYData})});g(l,"afterSetOptions",function(c){c=c.options;var a=c.dataGrouping;a&&c.useOhlcData&&"highcharts-navigator-series"!==c.id&&(a.approximation="ohlc")});e("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},
{processData:function(){var a=this.options.compareToMain,d=this.linkedParent;l.prototype.processData.apply(this,arguments);d&&d.compareValue&&a&&(this.compareValue=d.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){r[c]?r[c].prototype.requireIndicators():(a.allLoaded=!1,a.needed=
c)});return a},init:function(a,d){function c(){var a=b.points||[],c=(b.xData||[]).length,d=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},e=[],f=!0;if(c&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var h=b.xAxis.min;var g=b.xAxis.max}c=b.cropData(d.xData,d.yData,h,g);for(h=0;h<c.xData.length;h++)e.push([c.xData[h]].concat(u(c.yData[h])));c=d.xData.indexOf(b.xData[0]);h=d.xData.indexOf(b.xData[b.xData.length-1]);-1===c&&h===d.xData.length-2&&e[0][0]===
a[0].x&&e.shift();b.updateData(e)}else d.xData.length!==c-1&&d.xData.length!==c+1&&(f=!1,b.updateData(d.values));f&&(b.xData=d.xData,b.yData=d.yData,b.options.data=d.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,e=b.requireIndicators();if(!e.allLoaded)return k(v(b.type,e.needed));l.prototype.init.call(b,a,d);a.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return k("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",!1,
a);b.dataEventsToUnbind.push(g(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,c));if("init"===b.calculateOn)c();else var f=g(b.chart,b.calculateOn,function(){c();f()});return b},getName:function(){var a=this.name,d=[];a||((this.nameComponents||[]).forEach(function(a,b){d.push(this.options.params[a]+t(this.nameSuffixes[b],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return a},getValues:function(a,d){var c=d.period,b=
a.xData;a=a.yData;var e=a.length,f=0,g=0,k=[],l=[],m=[],n=-1;if(!(b.length<c)){for(q(a[0])&&(n=d.index?d.index:0);f<c-1;)g+=0>n?a[f]:a[f][n],f++;for(d=f;d<e;d++){g+=0>n?a[d]:a[d][n];var h=[b[d],g/c];k.push(h);l.push(h[0]);m.push(h[1]);g-=0>n?a[d-f]:a[d-f][n]}return{values:k,xData:l,yData:m}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});l.prototype.destroy.apply(this,arguments)}});""});f(a,"masters/indicators/indicators.src.js",[],function(){})});
//# sourceMappingURL=indicators.js.map