/*
 Highstock JS v8.0.0 (2020-02-08)

 All technical indicators for Highstock

 (c) 2010-2019 Pawel Fus

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators-all",["highcharts","highcharts/modules/stock"],function(v){a(v);a.Highcharts=v;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function v(m,g,a,k){m.hasOwnProperty(g)||(m[g]=k.apply(null,a))}a=a?a._modules:{};v(a,"mixins/indicator-required.js",[a["parts/Utilities.js"]],function(m){var g=m.error;return{isParentLoaded:function(m,
k,e,d,c){if(m)return d?d(m):!0;g(c||this.generateMessage(e,k));return!1},generateMessage:function(g,k){return'Error: "'+g+'" indicator type requires "'+k+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+g}}});v(a,"indicators/indicators.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],function(m,g,a){var k=g.addEvent,e=g.error,d=g.extend,c=g.isArray,b=g.pick,f=g.splat,u=m.Series;g=m.seriesType;var l=m.seriesTypes,
z=m.seriesTypes.ohlc.prototype,r=a.generateMessage;k(m.Series,"init",function(b){b=b.options;b.useOhlcData&&"highcharts-navigator-series"!==b.id&&d(this,{pointValKey:z.pointValKey,keys:z.keys,pointArrayMap:z.pointArrayMap,toYData:z.toYData})});k(u,"afterSetOptions",function(b){b=b.options;var c=b.dataGrouping;c&&b.useOhlcData&&"highcharts-navigator-series"!==b.id&&(c.approximation="ohlc")});g("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},
{processData:function(){var b=this.options.compareToMain,c=this.linkedParent;u.prototype.processData.apply(this,arguments);c&&c.compareValue&&b&&(this.compareValue=c.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var b={allLoaded:!0};this.requiredIndicators.forEach(function(c){l[c]?l[c].prototype.requireIndicators():(b.allLoaded=!1,b.needed=
c)});return b},init:function(b,c){function d(){var b=q.points||[],c=(q.xData||[]).length,d=q.getValues(q.linkedParent,q.options.params)||{values:[],xData:[],yData:[]},u=[],l=!0;if(c&&!q.hasGroupedData&&q.visible&&q.points)if(q.cropped){if(q.xAxis){var h=q.xAxis.min;var e=q.xAxis.max}c=q.cropData(d.xData,d.yData,h,e);for(h=0;h<c.xData.length;h++)u.push([c.xData[h]].concat(f(c.yData[h])));c=d.xData.indexOf(q.xData[0]);h=d.xData.indexOf(q.xData[q.xData.length-1]);-1===c&&h===d.xData.length-2&&u[0][0]===
b[0].x&&u.shift();q.updateData(u)}else d.xData.length!==c-1&&d.xData.length!==c+1&&(l=!1,q.updateData(d.values));l&&(q.xData=d.xData,q.yData=d.yData,q.options.data=d.values);!1===q.bindTo.series&&(delete q.processedXData,q.isDirty=!0,q.redraw());q.isDirtyData=!1}var q=this,l=q.requireIndicators();if(!l.allLoaded)return e(r(q.type,l.needed));u.prototype.init.call(q,b,c);b.linkSeries();q.dataEventsToUnbind=[];if(!q.linkedParent)return e("Series "+q.options.linkedTo+" not found! Check `linkedTo`.",!1,
b);q.dataEventsToUnbind.push(k(q.bindTo.series?q.linkedParent:q.linkedParent.xAxis,q.bindTo.eventName,d));if("init"===q.calculateOn)d();else var h=k(q.chart,q.calculateOn,function(){d();h()});return q},getName:function(){var c=this.name,d=[];c||((this.nameComponents||[]).forEach(function(c,f){d.push(this.options.params[c]+b(this.nameSuffixes[f],""))},this),c=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return c},getValues:function(b,d){var f=d.period,q=
b.xData;b=b.yData;var u=b.length,l=0,e=0,h=[],p=[],z=[],k=-1;if(!(q.length<f)){for(c(b[0])&&(k=d.index?d.index:0);l<f-1;)e+=0>k?b[l]:b[l][k],l++;for(d=l;d<u;d++){e+=0>k?b[d]:b[d][k];var r=[q[d],e/f];h.push(r);p.push(r[0]);z.push(r[1]);e-=0>k?b[d-l]:b[d-l][k]}return{values:h,xData:p,yData:z}}},destroy:function(){this.dataEventsToUnbind.forEach(function(b){b()});u.prototype.destroy.apply(this,arguments)}});""});v(a,"indicators/accumulation-distribution.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],
function(m,g){var a=g.error;m=m.seriesType;m("ad","sma",{params:{volumeSeriesID:"volume"}},{nameComponents:!1,nameBase:"Accumulation/Distribution",getValues:function(k,e){var d=e.period,c=k.xData,b=k.yData,f=e.volumeSeriesID,u=k.chart.get(f);e=u&&u.yData;var l=b?b.length:0,z=[],r=[],h=[];if(!(c.length<=d&&l&&4!==b[0].length)){if(u){for(;d<l;d++){k=z.length;f=b[d][1];u=b[d][2];var p=b[d][3],n=e[d];f=[c[d],p===f&&p===u||f===u?0:(2*p-u-f)/(f-u)*n];0<k&&(f[1]+=z[k-1][1]);z.push(f);r.push(f[0]);h.push(f[1])}return{values:z,
xData:r,yData:h}}a("Series "+f+" not found! Check `volumeSeriesID`.",!0,k.chart)}}});""});v(a,"indicators/ao.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(m,g){var a=g.correctFloat,k=g.isArray;m.seriesType("ao","sma",{greaterBarColor:"#06B535",lowerBarColor:"#F21313",threshold:0,groupPadding:.2,pointPadding:.2,states:{hover:{halo:{size:0}}}},{nameBase:"AO",nameComponents:!1,markerAttribs:m.noop,getColumnMetrics:m.seriesTypes.column.prototype.getColumnMetrics,crispCol:m.seriesTypes.column.prototype.crispCol,
translate:m.seriesTypes.column.prototype.translate,drawPoints:m.seriesTypes.column.prototype.drawPoints,drawGraph:function(){var e=this.options,d=this.points,c=e.greaterBarColor;e=e.lowerBarColor;var b=d[0];if(!this.userOptions.color&&b)for(b.color=c,b=1;b<d.length;b++)d[b].color=d[b].y>d[b-1].y?c:d[b].y<d[b-1].y?e:d[b-1].color},getValues:function(e){var d=e.xData||[];e=e.yData||[];var c=e.length,b=[],f=[],u=[],l=0,z=0,r;if(!(34>=d.length)&&k(e[0])&&4===e[0].length){for(r=0;33>r;r++){var h=(e[r][1]+
e[r][2])/2;29<=r&&(l=a(l+h));z=a(z+h)}for(r=33;r<c;r++){h=(e[r][1]+e[r][2])/2;l=a(l+h);z=a(z+h);h=l/5;var p=z/34;h=a(h-p);b.push([d[r],h]);f.push(d[r]);u.push(h);h=r+1-5;p=r+1-34;l=a(l-(e[h][1]+e[h][2])/2);z=a(z-(e[p][1]+e[p][2])/2)}return{values:b,xData:f,yData:u}}}});""});v(a,"mixins/multipe-lines.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.defined,k=g.error,e=g.merge,d=a.each,c=a.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],
getTranslatedLinesNames:function(b){var c=[];d(this.pointArrayMap,function(d){d!==b&&c.push("plot"+d.charAt(0).toUpperCase()+d.slice(1))});return c},toYData:function(b){var c=[];d(this.pointArrayMap,function(d){c.push(b[d])});return c},translate:function(){var b=this,f=b.pointArrayMap,u=[],l;u=b.getTranslatedLinesNames();c.prototype.translate.apply(b,arguments);d(b.points,function(c){d(f,function(d,f){l=c[d];null!==l&&(c[u[f]]=b.yAxis.toPixels(l,!0))})})},drawGraph:function(){var b=this,f=b.linesApiNames,
u=b.points,l=u.length,z=b.options,r=b.graph,h={options:{gapSize:z.gapSize}},p=[],n=b.getTranslatedLinesNames(b.pointValKey),q;d(n,function(b,c){for(p[c]=[];l--;)q=u[l],p[c].push({x:q.x,plotX:q.plotX,plotY:q[b],isNull:!m(q[b])});l=u.length});d(f,function(d,f){p[f]?(b.points=p[f],z[d]?b.options=e(z[d].styles,h):k('Error: "There is no '+d+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),b.graph=b["graph"+d],c.prototype.drawGraph.call(b),
b["graph"+d]=b.graph):k('Error: "'+d+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});b.points=u;b.options=z;b.graph=r;c.prototype.drawGraph.call(b)}}});v(a,"indicators/aroon.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/multipe-lines.js"]],function(a,g,t){function k(c,b){var d=c[0],u=0,l;for(l=1;l<c.length;l++)if("max"===b&&c[l]>=d||"min"===b&&c[l]<=d)d=c[l],u=l;return u}var e=g.merge,d=g.pick;a.seriesType("aroon","sma",
{params:{period:25},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},e(t,{nameBase:"Aroon",pointArrayMap:["y","aroonDown"],pointValKey:"y",linesApiNames:["aroonDown"],getValues:function(c,b){b=b.period;var f=c.xData,u=(c=c.yData)?c.length:0,l=[],e=[],r=[],h;for(h=b-1;h<u;h++){var p=
c.slice(h-b+1,h+2);var n=k(p.map(function(b){return d(b[2],b)}),"min");p=k(p.map(function(b){return d(b[1],b)}),"max");p=p/b*100;n=n/b*100;f[h+1]&&(l.push([f[h+1],p,n]),e.push(f[h+1]),r.push([p,n]))}return{values:l,xData:e,yData:r}}}));""});v(a,"indicators/aroon-oscillator.src.js",[a["parts/Globals.js"],a["mixins/multipe-lines.js"],a["mixins/indicator-required.js"],a["parts/Utilities.js"]],function(a,g,t,k){k=k.merge;var e=a.seriesTypes.aroon;a.seriesType("aroonoscillator","aroon",{params:{period:25},
tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b>: {point.y}'}},k(g,{nameBase:"Aroon Oscillator",pointArrayMap:["y"],pointValKey:"y",linesApiNames:[],init:function(){var d=arguments,c=this;t.isParentLoaded(e,"aroon",c.type,function(b){b.prototype.init.apply(c,d)})},getValues:function(d,c){var b=[],f=[],u=[];d=e.prototype.getValues.call(this,d,c);for(c=0;c<d.yData.length;c++){var l=d.yData[c][0];var k=d.yData[c][1];l-=k;b.push([d.xData[c],l]);f.push(d.xData[c]);
u.push(l)}return{values:b,xData:f,yData:u}}}));""});v(a,"indicators/atr.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function m(d,c){return Math.max(d[1]-d[2],c===e?0:Math.abs(d[1]-c[3]),c===e?0:Math.abs(d[2]-c[3]))}var k=g.isArray;a=a.seriesType;var e;a("atr","sma",{params:{period:14}},{getValues:function(d,c){c=c.period;var b=d.xData,f=(d=d.yData)?d.length:0,u=1,l=0,e=0,r=[],h=[],p=[],n;var q=[[b[0],d[0]]];if(!(b.length<=c)&&k(d[0])&&4===d[0].length){for(n=1;n<=f;n++)if(q.push([b[n],
d[n]]),c<u){var y=c;var a=b[n-1],g=m(d[n-1],d[n-2]);y=[a,(l*(y-1)+g)/y];l=y[1];r.push(y);h.push(y[0]);p.push(y[1])}else c===u?(l=e/(n-1),r.push([b[n-1],l]),h.push(b[n-1]),p.push(l)):e+=m(d[n-1],d[n-2]),u++;return{values:r,xData:h,yData:p}}}});""});v(a,"indicators/bollinger-bands.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/multipe-lines.js"]],function(a,g,t){var k=g.isArray,e=g.merge,d=a.seriesTypes.sma;a.seriesType("bb","sma",{params:{period:20,standardDeviation:2,index:3},bottomLine:{styles:{lineWidth:1,
lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"}},e(t,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],init:function(){d.prototype.init.apply(this,arguments);
this.options=e({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(c,b){var f=b.period,u=b.standardDeviation,l=c.xData,e=(c=c.yData)?c.length:0,r=[],h=[],p=[],n;if(!(l.length<f)){var q=k(c[0]);for(n=f;n<=e;n++){var y=l.slice(n-f,n);var a=c.slice(n-f,n);var g=d.prototype.getValues.call(this,{xData:y,yData:a},b);y=g.xData[0];g=g.yData[0];for(var m=0,t=a.length,x=0;x<t;x++){var I=(q?a[x][b.index]:a[x])-g;m+=I*I}I=Math.sqrt(m/(t-1));a=
g+u*I;I=g-u*I;r.push([y,a,g,I]);h.push(y);p.push([a,g,I])}return{values:r,xData:h,yData:p}}}}));""});v(a,"indicators/cci.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function m(e){return e.reduce(function(d,c){return d+c},0)}var k=g.isArray;a=a.seriesType;a("cci","sma",{params:{period:14}},{getValues:function(e,d){d=d.period;var c=e.xData,b=(e=e.yData)?e.length:0,f=[],u=1,l=[],z=[],r=[];if(!(c.length<=d)&&k(e[0])&&4===e[0].length){for(;u<d;){var h=e[u-1];f.push((h[1]+h[2]+
h[3])/3);u++}for(u=d;u<=b;u++){h=e[u-1];h=(h[1]+h[2]+h[3])/3;var p=f.push(h);var n=f.slice(p-d);p=m(n)/d;var q,a=n.length,g=0;for(q=0;q<a;q++)g+=Math.abs(p-n[q]);n=g/d;h=(h-p)/(.015*n);l.push([c[u-1],h]);z.push(c[u-1]);r.push(h)}return{values:l,xData:z,yData:r}}}});""});v(a,"indicators/cmf.src.js",[a["parts/Globals.js"]],function(a){a.seriesType("cmf","sma",{params:{period:14,volumeSeriesID:"volume"}},{nameBase:"Chaikin Money Flow",isValid:function(){var a=this.chart,m=this.options,k=this.linkedParent;
a=this.volumeSeries||(this.volumeSeries=a.get(m.params.volumeSeriesID));var e=k&&k.yData&&4===k.yData[0].length;return!!(k&&a&&k.xData&&k.xData.length>=m.params.period&&a.xData&&a.xData.length>=m.params.period&&e)},getValues:function(a,m){if(this.isValid())return this.getMoneyFlow(a.xData,a.yData,this.volumeSeries.yData,m.period)},getMoneyFlow:function(a,m,k,e){function d(b,c){var d=b[1],f=b[2];b=b[3];return null!==c&&null!==d&&null!==f&&null!==b&&d!==f?(b-f-(d-b))/(d-f)*c:(p=h,null)}var c=m.length,
b=[],f=0,u=0,l=[],z=[],r=[],h,p=-1;if(0<e&&e<=c){for(h=0;h<e;h++)b[h]=d(m[h],k[h]),f+=k[h],u+=b[h];l.push(a[h-1]);z.push(h-p>=e&&0!==f?u/f:null);for(r.push([l[0],z[0]]);h<c;h++){b[h]=d(m[h],k[h]);f-=k[h-e];f+=k[h];u-=b[h-e];u+=b[h];var n=[a[h],h-p>=e?u/f:null];l.push(n[0]);z.push(n[1]);r.push([n[0],n[1]])}}return{values:r,xData:l,yData:z}}});""});v(a,"indicators/dpo.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function m(d,c,b,f,u){c=e(c[b][f],c[b]);return u?k(d-c):k(d+c)}
var k=g.correctFloat,e=g.pick;a.seriesType("dpo","sma",{params:{period:21}},{nameBase:"DPO",getValues:function(d,c){var b=c.period;c=c.index;var f=b+Math.floor(b/2+1),u=d.xData||[];d=d.yData||[];var l=d.length,k=[],a=[],h=[],p=0,n,q;if(!(u.length<=f)){for(n=0;n<b-1;n++)p=m(p,d,n,c);for(q=0;q<=l-f;q++){var y=q+b-1;n=q+f-1;p=m(p,d,y,c);y=e(d[n][c],d[n]);y-=p/b;p=m(p,d,q,c,!0);k.push([u[n],y]);a.push(u[n]);h.push(y)}return{values:k,xData:a,yData:h}}}});""});v(a,"indicators/ema.src.js",[a["parts/Globals.js"],
a["parts/Utilities.js"]],function(a,g){var m=g.correctFloat,k=g.isArray;a=a.seriesType;a("ema","sma",{params:{index:3,period:9}},{accumulatePeriodPoints:function(e,d,c){for(var b=0,f=0,u;f<e;)u=0>d?c[f]:c[f][d],b+=u,f++;return b},calculateEma:function(e,d,c,b,f,u,l){e=e[c-1];d=0>u?d[c-1]:d[c-1][u];b="undefined"===typeof f?l:m(d*b+f*(1-b));return[e,b]},getValues:function(e,d){var c=d.period,b=e.xData,f=(e=e.yData)?e.length:0,u=2/(c+1),l=[],a=[],r=[],h=-1;if(!(f<c)){k(e[0])&&(h=d.index?d.index:0);d=
this.accumulatePeriodPoints(c,h,e);for(d/=c;c<f+1;c++){var p=this.calculateEma(b,e,c,u,p,h,d);l.push(p);a.push(p[0]);r.push(p[1]);p=p[1]}return{values:l,xData:a,yData:r}}}});""});v(a,"indicators/chaikin.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],function(a,g,t){var k=g.correctFloat,e=g.error,d=a.seriesTypes.ema,c=a.seriesTypes.ad;a.seriesType("chaikin","ema",{params:{volumeSeriesID:"volume",periods:[3,10]}},{nameBase:"Chaikin Osc",nameComponents:["periods"],
init:function(){var b=arguments,c=this;t.isParentLoaded(d,"ema",c.type,function(d){d.prototype.init.apply(c,b)})},getValues:function(b,f){var u=f.periods,l=f.period,a=[],r=[],h=[],p;if(2!==u.length||u[1]<=u[0])e('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."');else if(f=c.prototype.getValues.call(this,b,{volumeSeriesID:f.volumeSeriesID,period:l}))if(b=d.prototype.getValues.call(this,f,{period:u[0]}),f=d.prototype.getValues.call(this,f,{period:u[1]}),
b&&f){u=u[1]-u[0];for(p=0;p<f.yData.length;p++)l=k(b.yData[p+u]-f.yData[p]),a.push([f.xData[p],l]),r.push(f.xData[p]),h.push(l);return{values:a,xData:r,yData:h}}}});""});v(a,"indicators/dema.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],function(a,g,t){var k=g.correctFloat,e=g.isArray,d=a.seriesTypes.ema;a.seriesType("dema","ema",{},{init:function(){var c=arguments,b=this;t.isParentLoaded(d,"ema",b.type,function(d){d.prototype.init.apply(b,c)})},getEMA:function(c,
b,f,e,l,a){return d.prototype.calculateEma(a||[],c,"undefined"===typeof l?1:l,this.chart.series[0].EMApercent,b,"undefined"===typeof e?-1:e,f)},getValues:function(c,b){var f=b.period,u=2*f,l=c.xData,a=c.yData,r=a?a.length:0,h=-1,p=[],n=[],q=[],y=0,g=[],m;c.EMApercent=2/(f+1);if(!(r<2*f-1)){e(a[0])&&(h=b.index?b.index:0);c=d.prototype.accumulatePeriodPoints(f,h,a);b=c/f;c=0;for(m=f;m<r+2;m++){m<r+1&&(y=this.getEMA(a,w,b,h,m)[1],g.push(y));var w=y;if(m<u)c+=y;else{m===u&&(b=c/f);y=g[m-f-1];var t=this.getEMA([y],
t,b)[1];var x=[l[m-2],k(2*y-t)];p.push(x);n.push(x[0]);q.push(x[1])}}return{values:p,xData:n,yData:q}}}});""});v(a,"indicators/tema.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],function(a,g,t){var k=g.correctFloat,e=g.isArray,d=a.seriesTypes.ema;a.seriesType("tema","ema",{},{init:function(){var c=arguments,b=this;t.isParentLoaded(d,"ema",b.type,function(d){d.prototype.init.apply(b,c)})},getEMA:function(c,b,f,e,l,a){return d.prototype.calculateEma(a||[],
c,"undefined"===typeof l?1:l,this.chart.series[0].EMApercent,b,"undefined"===typeof e?-1:e,f)},getTemaPoint:function(c,b,d,e){return[c[e-3],k(3*d.level1-3*d.level2+d.level3)]},getValues:function(c,b){var f=b.period,u=2*f,l=3*f,a=c.xData,k=c.yData,h=k?k.length:0,p=-1,n=[],q=[],y=[],g=[],m=[],w,t,x={};c.EMApercent=2/(f+1);if(!(h<3*f-2)){e(k[0])&&(p=b.index?b.index:0);c=d.prototype.accumulatePeriodPoints(f,p,k);b=c/f;c=0;for(w=f;w<h+3;w++){w<h+1&&(x.level1=this.getEMA(k,I,b,p,w)[1],g.push(x.level1));
var I=x.level1;if(w<u)c+=x.level1;else{w===u&&(b=c/f,c=0);x.level1=g[w-f-1];x.level2=this.getEMA([x.level1],B,b)[1];m.push(x.level2);var B=x.level2;if(w<l)c+=x.level2;else{w===l&&(b=c/f);w===h+1&&(x.level1=g[w-f-1],x.level2=this.getEMA([x.level1],B,b)[1],m.push(x.level2));x.level1=g[w-f-2];x.level2=m[w-2*f-1];x.level3=this.getEMA([x.level2],x.prevLevel3,b)[1];if(t=this.getTemaPoint(a,l,x,w))n.push(t),q.push(t[0]),y.push(t[1]);x.prevLevel3=x.level3}}}return{values:n,xData:q,yData:y}}}});""});v(a,"indicators/trix.src.js",
[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],function(a,g,t){var k=g.correctFloat,e=a.seriesTypes.tema;a.seriesType("trix","tema",{},{init:function(){var d=arguments,c=this;t.isParentLoaded(e,"tema",c.type,function(b){b.prototype.init.apply(c,d)})},getTemaPoint:function(d,c,b,f){if(f>c)var e=[d[f-3],0!==b.prevLevel3?k(b.level3-b.prevLevel3)/b.prevLevel3*100:null];return e}});""});v(a,"indicators/apo.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],
function(a,g,t){var k=g.error,e=a.seriesTypes.ema;a.seriesType("apo","ema",{params:{periods:[10,20]}},{nameBase:"APO",nameComponents:["periods"],init:function(){var d=arguments,c=this;t.isParentLoaded(e,"ema",c.type,function(b){b.prototype.init.apply(c,d)})},getValues:function(d,c){var b=c.periods,f=c.index;c=[];var u=[],l=[],a;if(2!==b.length||b[1]<=b[0])k('Error: "APO requires two periods. Notice, first period should be lower than the second one."');else{var r=e.prototype.getValues.call(this,d,
{index:f,period:b[0]});d=e.prototype.getValues.call(this,d,{index:f,period:b[1]});if(r&&d){b=b[1]-b[0];for(a=0;a<d.yData.length;a++)f=r.yData[a+b]-d.yData[a],c.push([d.xData[a],f]),u.push(d.xData[a]),l.push(f);return{values:c,xData:u,yData:l}}}}});""});v(a,"indicators/ichimoku-kinko-hyo.src.js",[a["parts/Globals.js"],a["parts/Color.js"],a["parts/Utilities.js"]],function(a,g,t){function k(b){return b.reduce(function(b,c){return Math.max(b,c[1])},-Infinity)}function e(b){return b.reduce(function(b,
c){return Math.min(b,c[2])},Infinity)}function d(b){return{high:k(b),low:e(b)}}function c(b){var c,d,f,q,e;b.series.forEach(function(b){if(b.xData)for(q=b.xData,e=d=b.xIncrement?1:q.length-1;0<e;e--)if(f=q[e]-q[e-1],c===p||f<c)c=f});return c}function b(b,c,d,f){if(b&&c&&d&&f){var e=c.plotX-b.plotX;c=c.plotY-b.plotY;var q=f.plotX-d.plotX;f=f.plotY-d.plotY;var l=b.plotX-d.plotX,a=b.plotY-d.plotY;d=(-c*l+e*a)/(-q*c+e*f);q=(q*a-f*l)/(-q*c+e*f);if(0<=d&&1>=d&&0<=q&&1>=q)return{plotX:b.plotX+q*e,plotY:b.plotY+
q*c}}return!1}function f(b){var c=b.indicator;c.points=b.points;c.nextPoints=b.nextPoints;c.color=b.color;c.options=r(b.options.senkouSpan.styles,b.gap);c.graph=b.graph;c.fillGraph=!0;n.prototype.drawGraph.call(c)}var u=g.parse,l=t.defined,z=t.isArray,r=t.merge,h=t.objectEach,p;g=a.seriesType;var n=a.seriesTypes.sma;a.approximations["ichimoku-averages"]=function(){var b=[],c;[].forEach.call(arguments,function(d,f){b.push(a.approximations.average(d));c=!c&&"undefined"===typeof b[f]});return c?void 0:
b};g("ikh","sma",{params:{period:26,periodTenkan:9,periodSenkouSpanB:52},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>TENKAN SEN: {point.tenkanSen:.3f}<br/>KIJUN SEN: {point.kijunSen:.3f}<br/>CHIKOU SPAN: {point.chikouSpan:.3f}<br/>SENKOU SPAN A: {point.senkouSpanA:.3f}<br/>SENKOU SPAN B: {point.senkouSpanB:.3f}<br/>'},tenkanLine:{styles:{lineWidth:1,lineColor:void 0}},kijunLine:{styles:{lineWidth:1,lineColor:void 0}},chikouLine:{styles:{lineWidth:1,
lineColor:void 0}},senkouSpanA:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanB:{styles:{lineWidth:1,lineColor:void 0}},senkouSpan:{styles:{fill:"rgba(255, 0, 0, 0.5)"}},dataGrouping:{approximation:"ichimoku-averages"}},{pointArrayMap:["tenkanSen","kijunSen","chikouSpan","senkouSpanA","senkouSpanB"],pointValKey:"tenkanSen",nameComponents:["periodSenkouSpanB","period","periodTenkan"],init:function(){n.prototype.init.apply(this,arguments);this.options=r({tenkanLine:{styles:{lineColor:this.color}},
kijunLine:{styles:{lineColor:this.color}},chikouLine:{styles:{lineColor:this.color}},senkouSpanA:{styles:{lineColor:this.color,fill:u(this.color).setOpacity(.5).get()}},senkouSpanB:{styles:{lineColor:this.color,fill:u(this.color).setOpacity(.5).get()}},senkouSpan:{styles:{fill:u(this.color).setOpacity(.2).get()}}},this.options)},toYData:function(b){return[b.tenkanSen,b.kijunSen,b.chikouSpan,b.senkouSpanA,b.senkouSpanB]},translate:function(){var b=this;n.prototype.translate.apply(b);b.points.forEach(function(c){b.pointArrayMap.forEach(function(d){l(c[d])&&
(c["plot"+d]=b.yAxis.toPixels(c[d],!0),c.plotY=c["plot"+d],c.tooltipPos=[c.plotX,c["plot"+d]],c.isNull=!1)})})},drawGraph:function(){var c=this,d=c.points,e=d.length,a=c.options,u=c.graph,p=c.color,k={options:{gapSize:a.gapSize}},g=c.pointArrayMap.length,z=[[],[],[],[],[],[]],m={tenkanLine:z[0],kijunLine:z[1],chikouLine:z[2],senkouSpanA:z[3],senkouSpanB:z[4],senkouSpan:z[5]},t=[],A=c.options.senkouSpan,v=A.color||A.styles.fill,J=A.negativeColor,K=[[],[]],M=[[],[]],N=0,H,O,L;for(c.ikhMap=m;e--;){var C=
d[e];for(H=0;H<g;H++)A=c.pointArrayMap[H],l(C[A])&&z[H].push({plotX:C.plotX,plotY:C["plot"+A],isNull:!1});J&&e!==d.length-1&&(A=m.senkouSpanB.length-1,C=b(m.senkouSpanA[A-1],m.senkouSpanA[A],m.senkouSpanB[A-1],m.senkouSpanB[A]),H={plotX:C.plotX,plotY:C.plotY,isNull:!1,intersectPoint:!0},C&&(m.senkouSpanA.splice(A,0,H),m.senkouSpanB.splice(A,0,H),t.push(A)))}h(m,function(b,d){a[d]&&"senkouSpan"!==d&&(c.points=z[N],c.options=r(a[d].styles,k),c.graph=c["graph"+d],c.fillGraph=!1,c.color=p,n.prototype.drawGraph.call(c),
c["graph"+d]=c.graph);N++});c.graphCollection&&c.graphCollection.forEach(function(b){c[b].destroy();delete c[b]});c.graphCollection=[];if(J&&m.senkouSpanA[0]&&m.senkouSpanB[0]){t.unshift(0);t.push(m.senkouSpanA.length-1);for(g=0;g<t.length-1;g++){A=t[g];C=t[g+1];e=m.senkouSpanB.slice(A,C+1);A=m.senkouSpanA.slice(A,C+1);if(1<=Math.floor(e.length/2))if(C=Math.floor(e.length/2),e[C].plotY===A[C].plotY){for(L=H=C=0;L<e.length;L++)C+=e[L].plotY,H+=A[L].plotY;C=C>H?0:1}else C=e[C].plotY>A[C].plotY?0:1;
else C=e[0].plotY>A[0].plotY?0:1;K[C]=K[C].concat(e);M[C]=M[C].concat(A)}["graphsenkouSpanColor","graphsenkouSpanNegativeColor"].forEach(function(b,d){K[d].length&&M[d].length&&(O=0===d?v:J,f({indicator:c,points:K[d],nextPoints:M[d],color:O,options:a,gap:k,graph:c[b]}),c[b]=c.graph,c.graphCollection.push(b))})}else f({indicator:c,points:m.senkouSpanB,nextPoints:m.senkouSpanA,color:v,options:a,gap:k,graph:c.graphsenkouSpan}),c.graphsenkouSpan=c.graph;delete c.nextPoints;delete c.fillGraph;c.points=
d;c.options=a;c.graph=u},getGraphPath:function(b){var c=[];b=b||this.points;if(this.fillGraph&&this.nextPoints){var d=n.prototype.getGraphPath.call(this,this.nextPoints);d[0]="L";var f=n.prototype.getGraphPath.call(this,b);d=d.slice(0,f.length);for(var e=d.length-1;0<e;e-=3)c.push(d[e-2],d[e-1],d[e]);f=f.concat(c)}else f=n.prototype.getGraphPath.apply(this,arguments);return f},getValues:function(b,f){var e=f.period,l=f.periodTenkan;f=f.periodSenkouSpanB;var a=b.xData,u=b.yData,h=u&&u.length||0;b=
c(b.xAxis);var k=[],q=[],n;if(!(a.length<=e)&&z(u[0])&&4===u[0].length){var r=a[0]-e*b;for(n=0;n<e;n++)q.push(r+n*b);for(n=0;n<h;n++){if(n>=l){var g=u.slice(n-l,n);g=d(g);g=(g.high+g.low)/2}if(n>=e){var m=u.slice(n-e,n);m=d(m);m=(m.high+m.low)/2;var y=(g+m)/2}if(n>=f){var t=u.slice(n-f,n);t=d(t);t=(t.high+t.low)/2}r=u[n][3];var v=a[n];k[n]===p&&(k[n]=[]);k[n+e]===p&&(k[n+e]=[]);k[n+e][0]=g;k[n+e][1]=m;k[n+e][2]=p;k[n][2]=r;n<=e&&(k[n+e][3]=p,k[n+e][4]=p);k[n+2*e]===p&&(k[n+2*e]=[]);k[n+2*e][3]=y;
k[n+2*e][4]=t;q.push(v)}for(n=1;n<=e;n++)q.push(v+n*b);return{values:k,xData:q,yData:k}}}});""});v(a,"indicators/keltner-channels.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/multipe-lines.js"]],function(a,g,t){var k=g.correctFloat,e=g.merge,d=a.seriesTypes.sma,c=a.seriesTypes.ema,b=a.seriesTypes.atr;a.seriesType("keltnerchannels","sma",{params:{period:20,periodATR:10,multiplierATR:2},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},
tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Upper Channel: {point.top}<br/>EMA({series.options.params.period}): {point.middle}<br/>Lower Channel: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"},lineWidth:1},e(t,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Keltner Channels",nameComponents:["period","periodATR","multiplierATR"],linesApiNames:["topLine","bottomLine"],requiredIndicators:["ema",
"atr"],init:function(){d.prototype.init.apply(this,arguments);this.options=e({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(d,e){var f=e.period,a=e.periodATR,u=e.multiplierATR,h=d.yData;h=h?h.length:0;var p=[];e=c.prototype.getValues(d,{period:f,index:e.index});var n=b.prototype.getValues(d,{period:a}),q=[],g=[],m;if(!(h<f)){for(m=f;m<=h;m++){var t=e.values[m-f];var w=n.values[m-a];var E=t[0];d=k(t[1]+u*w[1]);w=k(t[1]-u*w[1]);
t=t[1];p.push([E,d,t,w]);q.push(E);g.push([d,t,w])}return{values:p,xData:q,yData:g}}}}));""});v(a,"indicators/macd.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.correctFloat,k=g.defined,e=g.merge;g=a.seriesType;var d=a.seriesTypes.sma,c=a.seriesTypes.ema;g("macd","sma",{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,
pointPadding:.1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},dataGrouping:{approximation:"averages"},minPointLength:0},{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y","signal","MACD"],parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:a.noop,getColumnMetrics:a.seriesTypes.column.prototype.getColumnMetrics,
crispCol:a.seriesTypes.column.prototype.crispCol,init:function(){d.prototype.init.apply(this,arguments);this.options&&(this.options=e({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones={zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),startIndex:this.macdZones.zones.length},this.resetZones=!0)},toYData:function(b){return[b.y,b.signal,b.MACD]},translate:function(){var b=
this,c=["plotSignal","plotMACD"];a.seriesTypes.column.prototype.translate.apply(b);b.points.forEach(function(d){[d.signal,d.MACD].forEach(function(f,e){null!==f&&(d[c[e]]=b.yAxis.toPixels(f,!0))})})},destroy:function(){this.graph=null;this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();d.prototype.destroy.apply(this,arguments)},drawPoints:a.seriesTypes.column.prototype.drawPoints,drawGraph:function(){for(var b=this,c=b.points,a=c.length,
l=b.options,g=b.zones,r={options:{gapSize:l.gapSize}},h=[[],[]],p;a--;)p=c[a],k(p.plotMACD)&&h[0].push({plotX:p.plotX,plotY:p.plotMACD,isNull:!k(p.plotMACD)}),k(p.plotSignal)&&h[1].push({plotX:p.plotX,plotY:p.plotSignal,isNull:!k(p.plotMACD)});["macd","signal"].forEach(function(c,f){b.points=h[f];b.options=e(l[c+"Line"].styles,r);b.graph=b["graph"+c];b.currentLineZone=c+"Zones";b.zones=b[b.currentLineZone].zones;d.prototype.drawGraph.call(b);b["graph"+c]=b.graph});b.points=c;b.options=l;b.zones=g;
b.currentLineZone=null},getZonesGraphs:function(b){var c=d.prototype.getZonesGraphs.call(this,b),e=c;this.currentLineZone&&(e=c.splice(this[this.currentLineZone].startIndex+1),e.length?e.splice(0,0,b[0]):e=[b[0]]);return e},applyZones:function(){var b=this.zones;this.zones=this.signalZones.zones;d.prototype.applyZones.call(this);this.graphmacd&&this.options.macdLine.zones.length&&this.graphmacd.hide();this.zones=b},getValues:function(b,d){var e=0,f=[],a=[],g=[];if(!(b.xData.length<d.longPeriod+d.signalPeriod)){var h=
c.prototype.getValues(b,{period:d.shortPeriod});var p=c.prototype.getValues(b,{period:d.longPeriod});h=h.values;p=p.values;for(b=1;b<=h.length;b++)k(p[b-1])&&k(p[b-1][1])&&k(h[b+d.shortPeriod+1])&&k(h[b+d.shortPeriod+1][0])&&f.push([h[b+d.shortPeriod+1][0],0,null,h[b+d.shortPeriod+1][1]-p[b-1][1]]);for(b=0;b<f.length;b++)a.push(f[b][0]),g.push([0,null,f[b][3]]);d=c.prototype.getValues({xData:a,yData:g},{period:d.signalPeriod,index:2});d=d.values;for(b=0;b<f.length;b++)f[b][0]>=d[0][0]&&(f[b][2]=d[e][1],
g[b]=[0,d[e][1],f[b][3]],null===f[b][3]?(f[b][1]=0,g[b][0]=0):(f[b][1]=m(f[b][3]-d[e][1]),g[b][0]=m(f[b][3]-d[e][1])),e++);return{values:f,xData:a,yData:g}}}});""});v(a,"indicators/mfi.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function m(c){return c.reduce(function(b,c){return b+c})}function k(c){return(c[1]+c[2]+c[3])/3}var e=g.error,d=g.isArray;a.seriesType("mfi","sma",{params:{period:14,volumeSeriesID:"volume",decimals:4}},{nameBase:"Money Flow Index",getValues:function(c,
b){var f=b.period,a=c.xData,l=c.yData,g=l?l.length:0,r=b.decimals,h=1,p=c.chart.get(b.volumeSeriesID),n=p&&p.yData,q=[],y=[],t=[],D=[],w=[];if(!p)e("Series "+b.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,c.chart);else if(!(a.length<=f)&&d(l[0])&&4===l[0].length&&n){for(c=k(l[h]);h<f+1;)b=c,c=k(l[h]),b=c>=b,p=c*n[h],D.push(b?p:0),w.push(b?0:p),h++;for(f=h-1;f<g;f++)f>h-1&&(D.shift(),w.shift(),b=c,c=k(l[f]),b=c>b,p=c*n[f],D.push(b?p:0),w.push(b?0:p)),b=m(w),p=m(D),b=p/b,b=parseFloat((100-
100/(1+b)).toFixed(r)),q.push([a[f],b]),y.push(a[f]),t.push(b);return{values:q,xData:y,yData:t}}}});""});v(a,"indicators/momentum.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function m(e,d,c,b,f){c=c[b-1][3]-c[b-f-1][3];d=d[b-1];e.shift();return[d,c]}var k=g.isArray;a=a.seriesType;a("momentum","sma",{params:{period:14}},{nameBase:"Momentum",getValues:function(e,d){d=d.period;var c=e.xData,b=(e=e.yData)?e.length:0,f=c[0],a=[],l=[],g=[];if(!(c.length<=d)&&k(e[0])){var r=e[0][3];
r=[[f,r]];for(f=d+1;f<b;f++){var h=m(r,c,e,f,d,void 0);a.push(h);l.push(h[0]);g.push(h[1])}h=m(r,c,e,f,d,void 0);a.push(h);l.push(h[0]);g.push(h[1]);return{values:a,xData:l,yData:g}}}});""});v(a,"indicators/natr.src.js",[a["parts/Globals.js"]],function(a){var g=a.seriesTypes.atr;a.seriesType("natr","sma",{tooltip:{valueSuffix:"%"}},{requiredIndicators:["atr"],getValues:function(a,k){var e=g.prototype.getValues.apply(this,arguments),d=e.values.length,c=k.period-1,b=a.yData,f=0;if(e){for(;f<d;f++)e.yData[f]=
e.values[f][1]/b[c][3]*100,e.values[f][1]=e.yData[f],c++;return e}}});""});v(a,"indicators/pivot-points.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function m(c,b){var e=c.series.pointArrayMap,a=e.length;for(d.prototype.pointClass.prototype[b].call(c);a--;)b="dataLabel"+e[a],c[b]&&c[b].element&&c[b].destroy(),c[b]=null}var k=g.defined,e=g.isArray,d=a.seriesTypes.sma;a.seriesType("pivotpoints","sma",{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,
dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}},{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),pointValKey:"P",toYData:function(c){return[c.P]},translate:function(){var c=this;d.prototype.translate.apply(c);c.points.forEach(function(b){c.pointArrayMap.forEach(function(d){k(b[d])&&(b["plot"+d]=c.yAxis.toPixels(b[d],!0))})});c.plotEndPoint=c.xAxis.toPixels(c.endPoint,!0)},getGraphPath:function(c){for(var b=this,e=c.length,a=
[[],[],[],[],[],[],[],[],[]],l=[],g=b.plotEndPoint,r=b.pointArrayMap.length,h,p,n;e--;){p=c[e];for(n=0;n<r;n++)h=b.pointArrayMap[n],k(p[h])&&a[n].push({plotX:p.plotX,plotY:p["plot"+h],isNull:!1},{plotX:g,plotY:p["plot"+h],isNull:!1},{plotX:g,plotY:null,isNull:!0});g=p.plotX}a.forEach(function(c){l=l.concat(d.prototype.getGraphPath.call(b,c))});return l},drawDataLabels:function(){var c=this,b=c.pointArrayMap,e,a,l;if(c.options.dataLabels.enabled){var k=c.points.length;b.concat([!1]).forEach(function(f,
h){for(l=k;l--;)a=c.points[l],f?(a.y=a[f],a.pivotLine=f,a.plotY=a["plot"+f],e=a["dataLabel"+f],h&&(a["dataLabel"+b[h-1]]=a.dataLabel),a.dataLabels||(a.dataLabels=[]),a.dataLabels[0]=a.dataLabel=e=e&&e.element?e:null):a["dataLabel"+b[h-1]]=a.dataLabel;d.prototype.drawDataLabels.apply(c,arguments)})}},getValues:function(c,b){var d=b.period,a=c.xData,l=(c=c.yData)?c.length:0;b=this[b.algorithm+"Placement"];var k=[],g=[],h=[],p;if(!(a.length<d)&&e(c[0])&&4===c[0].length){for(p=d+1;p<=l+d;p+=d){var n=
a.slice(p-d-1,p);var q=c.slice(p-d-1,p);var m=n.length;var t=n[m-1];q=this.getPivotAndHLC(q);q=b(q);q=k.push([t].concat(q));g.push(t);h.push(k[q-1].slice(1))}this.endPoint=n[0]+(t-n[0])/m*d;return{values:k,xData:g,yData:h}}},getPivotAndHLC:function(c){var b=-Infinity,d=Infinity,e=c[c.length-1][3];c.forEach(function(c){b=Math.max(b,c[1]);d=Math.min(d,c[2])});return[(b+d+e)/3,b,d,e]},standardPlacement:function(c){var b=c[1]-c[2];return[null,null,c[0]+b,2*c[0]-c[2],c[0],2*c[0]-c[1],c[0]-b,null,null]},
camarillaPlacement:function(c){var b=c[1]-c[2];return[c[3]+1.5*b,c[3]+1.25*b,c[3]+1.1666*b,c[3]+1.0833*b,c[0],c[3]-1.0833*b,c[3]-1.1666*b,c[3]-1.25*b,c[3]-1.5*b]},fibonacciPlacement:function(c){var b=c[1]-c[2];return[null,c[0]+b,c[0]+.618*b,c[0]+.382*b,c[0],c[0]-.382*b,c[0]-.618*b,c[0]-b,null]}},{destroyElements:function(){m(this,"destroyElements")},destroy:function(){m(this,"destroyElements")}});""});v(a,"indicators/ppo.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],
function(a,g,t){var k=g.correctFloat,e=g.error,d=a.seriesTypes.ema;a.seriesType("ppo","ema",{params:{periods:[12,26]}},{nameBase:"PPO",nameComponents:["periods"],init:function(){var c=arguments,b=this;t.isParentLoaded(d,"ema",b.type,function(d){d.prototype.init.apply(b,c)})},getValues:function(c,b){var a=b.periods,g=b.index;b=[];var l=[],m=[],r;if(2!==a.length||a[1]<=a[0])e('Error: "PPO requires two periods. Notice, first period should be lower than the second one."');else{var h=d.prototype.getValues.call(this,
c,{index:g,period:a[0]});c=d.prototype.getValues.call(this,c,{index:g,period:a[1]});if(h&&c){a=a[1]-a[0];for(r=0;r<c.yData.length;r++)g=k((h.yData[r+a]-c.yData[r])/c.yData[r]*100),b.push([c.xData[r],g]),l.push(c.xData[r]),m.push(g);return{values:b,xData:l,yData:m}}}}});""});v(a,"mixins/reduce-array.js",[a["parts/Globals.js"]],function(a){var g=a.reduce;return{minInArray:function(a,k){return g(a,function(a,d){return Math.min(a,d[k])},Number.MAX_VALUE)},maxInArray:function(a,k){return g(a,function(a,
d){return Math.max(a,d[k])},-Number.MAX_VALUE)},getArrayExtremes:function(a,k,e){return g(a,function(d,c){return[Math.min(d[0],c[k]),Math.max(d[1],c[e])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});v(a,"indicators/price-channel.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/reduce-array.js"],a["mixins/multipe-lines.js"]],function(a,g,t,k){g=g.merge;var e=t.getArrayExtremes;a.seriesType("pc","sma",{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:"#90ed7d",lineWidth:1}},bottomLine:{styles:{lineColor:"#f45b5b",
lineWidth:1}},dataGrouping:{approximation:"averages"}},g(k,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],getValues:function(d,c){c=c.period;var b=d.xData,a=(d=d.yData)?d.length:0,k=[],l=[],g=[],r;if(!(a<c)){for(r=c;r<=a;r++){var h=b[r-1];var p=d.slice(r-c,r);var n=e(p,2,1);p=n[1];var q=n[0];n=(p+q)/2;k.push([h,p,n,q]);l.push(h);g.push([p,n,q])}return{values:k,xData:l,yData:g}}}}));""});v(a,"indicators/price-envelopes.src.js",
[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.isArray,k=g.merge,e=a.seriesTypes.sma;a.seriesType("priceenvelopes","sma",{marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},params:{period:20,topBand:.1,bottomBand:.1},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},
{nameComponents:["period","topBand","bottomBand"],nameBase:"Price envelopes",pointArrayMap:["top","middle","bottom"],parallelArrays:["x","y","top","bottom"],pointValKey:"middle",init:function(){e.prototype.init.apply(this,arguments);this.options=k({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},toYData:function(d){return[d.top,d.middle,d.bottom]},translate:function(){var d=this,c=["plotTop","plotMiddle","plotBottom"];e.prototype.translate.apply(d);
d.points.forEach(function(b){[b.top,b.middle,b.bottom].forEach(function(a,e){null!==a&&(b[c[e]]=d.yAxis.toPixels(a,!0))})})},drawGraph:function(){for(var d=this,c=d.points,b=c.length,a=d.options,g=d.graph,l={options:{gapSize:a.gapSize}},m=[[],[]],r;b--;)r=c[b],m[0].push({plotX:r.plotX,plotY:r.plotTop,isNull:r.isNull}),m[1].push({plotX:r.plotX,plotY:r.plotBottom,isNull:r.isNull});["topLine","bottomLine"].forEach(function(b,c){d.points=m[c];d.options=k(a[b].styles,l);d.graph=d["graph"+b];e.prototype.drawGraph.call(d);
d["graph"+b]=d.graph});d.points=c;d.options=a;d.graph=g;e.prototype.drawGraph.call(d)},getValues:function(d,c){var b=c.period,a=c.topBand,k=c.bottomBand,l=d.xData,g=(d=d.yData)?d.length:0,r=[],h=[],p=[],n;if(!(l.length<b)&&m(d[0])&&4===d[0].length){for(n=b;n<=g;n++){var q=l.slice(n-b,n);var y=d.slice(n-b,n);y=e.prototype.getValues.call(this,{xData:q,yData:y},c);q=y.xData[0];y=y.yData[0];var t=y*(1+a);var D=y*(1-k);r.push([q,t,y,D]);h.push(q);p.push([t,y,D])}return{values:r,xData:h,yData:p}}}});""});
v(a,"indicators/psar.src.js",[a["parts/Globals.js"]],function(a){a.seriesType("psar","sma",{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}},{nameComponents:!1,getValues:function(a,m){var k=a.xData;a=a.yData;var e=a[0][1],d=m.maxAccelerationFactor,c=m.increment,b=m.initialAccelerationFactor,f=a[0][2],g=m.decimals,l=m.index,z=[],r=[],h=[],p=1,n;if(!(l>=a.length)){for(n=0;n<l;n++)e=Math.max(a[n][1],
e),f=Math.min(a[n][2],parseFloat(f.toFixed(g)));var q=a[n][1]>f?1:-1;m=m.initialAccelerationFactor;var y=m*(e-f);z.push([k[l],f]);r.push(k[l]);h.push(parseFloat(f.toFixed(g)));for(n=l+1;n<a.length;n++){l=a[n-1][2];var t=a[n-2][2];var D=a[n-1][1];var w=a[n-2][1];var E=a[n][1];var x=a[n][2];null!==t&&null!==w&&null!==l&&null!==D&&null!==E&&null!==x&&(f=q===p?1===q?f+y<Math.min(t,l)?f+y:Math.min(t,l):f+y>Math.max(w,D)?f+y:Math.max(w,D):e,l=1===q?E>e?E:e:x<e?x:e,E=1===p&&x>f||-1===p&&E>f?1:-1,p=E,y=l,
x=c,t=d,D=b,m=p===q?1===p&&y>e?m===t?t:parseFloat((m+x).toFixed(2)):-1===p&&y<e?m===t?t:parseFloat((m+x).toFixed(2)):m:D,e=l-f,y=m*e,z.push([k[n],parseFloat(f.toFixed(g))]),r.push(k[n]),h.push(parseFloat(f.toFixed(g))),p=q,q=E,e=l)}return{values:z,xData:r,yData:h}}}});""});v(a,"indicators/roc.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.isArray;a=a.seriesType;a("roc","sma",{params:{index:3,period:9}},{nameBase:"Rate of Change",getValues:function(a,e){var d=e.period,
c=a.xData,b=(a=a.yData)?a.length:0,f=[],k=[],l=[],g=-1;if(!(c.length<=d)){m(a[0])&&(g=e.index);for(e=d;e<b;e++){var r=0>g?(r=a[e-d])?(a[e]-r)/r*100:null:(r=a[e-d][g])?(a[e][g]-r)/r*100:null;r=[c[e],r];f.push(r);k.push(r[0]);l.push(r[1])}return{values:f,xData:k,yData:l}}}});""});v(a,"indicators/rsi.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.isArray;a.seriesType("rsi","sma",{params:{period:14,decimals:4}},{getValues:function(a,e){var d=e.period,c=a.xData,b=(a=a.yData)?
a.length:0;e=e.decimals;var f=1,k=[],l=[],g=[],r=0,h=0,p;if(!(c.length<d)&&m(a[0])&&4===a[0].length){for(;f<d;){var n=parseFloat((a[f][3]-a[f-1][3]).toFixed(e));0<n?r+=n:h+=Math.abs(n);f++}var q=parseFloat((r/(d-1)).toFixed(e));for(p=parseFloat((h/(d-1)).toFixed(e));f<b;f++)n=parseFloat((a[f][3]-a[f-1][3]).toFixed(e)),0<n?(r=n,h=0):(r=0,h=Math.abs(n)),q=parseFloat(((q*(d-1)+r)/d).toFixed(e)),p=parseFloat(((p*(d-1)+h)/d).toFixed(e)),r=0===p?100:0===q?0:parseFloat((100-100/(1+q/p)).toFixed(e)),k.push([c[f],
r]),l.push(c[f]),g.push(r);return{values:k,xData:l,yData:g}}}});""});v(a,"indicators/stochastic.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/reduce-array.js"],a["mixins/multipe-lines.js"]],function(a,g,t,k){var e=g.isArray,d=g.merge,c=a.seriesTypes.sma,b=t.getArrayExtremes;a.seriesType("stochastic","sma",{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},
smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},d(k,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],init:function(){c.prototype.init.apply(this,arguments);this.options=d({smoothedLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(d,a){var f=a.periods[0];a=a.periods[1];var k=d.xData,g=(d=d.yData)?d.length:0,h=[],p=[],
n=[],q=null,u;if(!(g<f)&&e(d[0])&&4===d[0].length){for(u=f-1;u<g;u++){var m=d.slice(u-f+1,u+1);var t=b(m,2,1);var w=t[0];m=d[u][3]-w;w=t[1]-w;m=m/w*100;p.push(k[u]);n.push([m,null]);u>=f-1+(a-1)&&(q=c.prototype.getValues.call(this,{xData:p.slice(-a),yData:n.slice(-a)},{period:a}),q=q.yData[0]);h.push([k[u],m,q]);n[n.length-1][1]=q}return{values:h,xData:p,yData:n}}}}));""});v(a,"indicators/slow-stochastic.src.js",[a["parts/Globals.js"],a["mixins/indicator-required.js"]],function(a,g){var m=a.seriesTypes;
a.seriesType("slowstochastic","stochastic",{params:{periods:[14,3,3]}},{nameBase:"Slow Stochastic",init:function(){var k=arguments,e=this;g.isParentLoaded(a.seriesTypes.stochastic,"stochastic",e.type,function(d){d.prototype.init.apply(e,k)})},getValues:function(a,e){var d=e.periods,c=m.stochastic.prototype.getValues.call(this,a,e);a={values:[],xData:[],yData:[]};e=0;if(c){a.xData=c.xData.slice(d[1]-1);c=c.yData.slice(d[1]-1);var b=m.sma.prototype.getValues.call(this,{xData:a.xData,yData:c},{index:1,
period:d[2]});if(b){for(var f=a.xData.length;e<f;e++)a.yData[e]=[c[e][1],b.yData[e-d[2]+1]||null],a.values[e]=[a.xData[e],c[e][1],b.yData[e-d[2]+1]||null];return a}}}});""});v(a,"indicators/supertrend.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function m(b,c,d){return{index:c,close:b.yData[c][d],x:b.xData[c]}}var k=g.correctFloat,e=g.merge,d=g.isArray,c=g.objectEach,b=a.seriesTypes.atr,f=a.seriesTypes.sma;a.seriesType("supertrend","sma",{params:{multiplier:3,period:10},
risingTrendColor:"#06B535",fallingTrendColor:"#F21313",changeTrendLine:{styles:{lineWidth:1,lineColor:"#333333",dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){f.prototype.init.apply(this,arguments);var b=this.options;b.cropThreshold=this.linkedParent.options.cropThreshold-(b.params.period-1)},drawGraph:function(){var b=this,d=b.options,a=b.linkedParent,k=a?a.points:[],h=b.points,g=b.graph,n=h.length,q=k.length-n;q=0<
q?q:0;for(var y={options:{gapSize:d.gapSize}},t={top:[],bottom:[],intersect:[]},D={top:{styles:{lineWidth:d.lineWidth,lineColor:d.fallingTrendColor||d.color,dashStyle:d.dashStyle}},bottom:{styles:{lineWidth:d.lineWidth,lineColor:d.risingTrendColor||d.color,dashStyle:d.dashStyle}},intersect:d.changeTrendLine},w,E,x,v,B,F,G,A;n--;)w=h[n],E=h[n-1],x=k[n-1+q],v=k[n-2+q],B=k[n+q],F=k[n+q+1],G=w.options.color,A={x:w.x,plotX:w.plotX,plotY:w.plotY,isNull:!1},!v&&x&&a.yData[x.index-1]&&(v=m(a,x.index-1,3)),
!F&&B&&a.yData[B.index+1]&&(F=m(a,B.index+1,3)),!x&&v&&a.yData[v.index+1]?x=m(a,v.index+1,3):!x&&B&&a.yData[B.index-1]&&(x=m(a,B.index-1,3)),w&&x&&B&&v&&w.x!==x.x&&(w.x===B.x?(v=x,x=B):w.x===v.x?(x=v,v={close:a.yData[x.index-1][3],x:a.xData[x.index-1]}):F&&w.x===F.x&&(x=F,v=B)),E&&v&&x?(B={x:E.x,plotX:E.plotX,plotY:E.plotY,isNull:!1},w.y>=x.close&&E.y>=v.close?(w.color=G||d.fallingTrendColor||d.color,t.top.push(A)):w.y<x.close&&E.y<v.close?(w.color=G||d.risingTrendColor||d.color,t.bottom.push(A)):
(t.intersect.push(A),t.intersect.push(B),t.intersect.push(e(B,{isNull:!0})),w.y>=x.close&&E.y<v.close?(w.color=G||d.fallingTrendColor||d.color,E.color=G||d.risingTrendColor||d.color,t.top.push(A),t.top.push(e(B,{isNull:!0}))):w.y<x.close&&E.y>=v.close&&(w.color=G||d.risingTrendColor||d.color,E.color=G||d.fallingTrendColor||d.color,t.bottom.push(A),t.bottom.push(e(B,{isNull:!0}))))):x&&(w.y>=x.close?(w.color=G||d.fallingTrendColor||d.color,t.top.push(A)):(w.color=G||d.risingTrendColor||d.color,t.bottom.push(A)));
c(t,function(c,d){b.points=c;b.options=e(D[d].styles,y);b.graph=b["graph"+d+"Line"];f.prototype.drawGraph.call(b);b["graph"+d+"Line"]=b.graph});b.points=h;b.options=d;b.graph=g},getValues:function(c,a){var e=a.period;a=a.multiplier;var f=c.xData,h=c.yData,g=[],n=[],q=[],l=0===e?0:e-1,m=[],u=[],w;if(!(f.length<=e||!d(h[0])||4!==h[0].length||0>e)){c=b.prototype.getValues.call(this,c,{period:e}).yData;for(w=0;w<c.length;w++){var t=h[l+w];var x=h[l+w-1]||[];var v=m[w-1];var B=u[w-1];var F=q[w-1];0===
w&&(v=B=F=0);e=k((t[1]+t[2])/2+a*c[w]);var G=k((t[1]+t[2])/2-a*c[w]);m[w]=e<v||x[3]>v?e:v;u[w]=G>B||x[3]<B?G:B;if(F===v&&t[3]<m[w]||F===B&&t[3]<u[w])var A=m[w];else if(F===v&&t[3]>m[w]||F===B&&t[3]>u[w])A=u[w];g.push([f[l+w],A]);n.push(f[l+w]);q.push(A)}return{values:g,xData:n,yData:q}}}});""});v(a,"indicators/volume-by-price.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.addEvent,k=g.animObject,e=g.arrayMax,d=g.arrayMin,c=g.correctFloat,b=g.error,f=g.extend,u=g.isArray,
l=Math.abs;g=a.noop;var z=a.seriesType,r=a.seriesTypes.column.prototype;z("vbp","sma",{params:{ranges:12,volumeSeriesID:"volume"},zoneLines:{enabled:!0,styles:{color:"#0A9AC9",dashStyle:"LongDash",lineWidth:1}},volumeDivision:{enabled:!0,styles:{positiveColor:"rgba(144, 237, 125, 0.8)",negativeColor:"rgba(244, 91, 91, 0.8)"}},animationLimit:1E3,enableMouseTracking:!1,pointPadding:0,zIndex:-1,crisp:!0,dataGrouping:{enabled:!1},dataLabels:{allowOverlap:!0,enabled:!0,format:"P: {point.volumePos:.2f} | N: {point.volumeNeg:.2f}",
padding:0,style:{fontSize:"7px"},verticalAlign:"top"}},{nameBase:"Volume by Price",bindTo:{series:!1,eventName:"afterSetExtremes"},calculateOn:"render",markerAttribs:g,drawGraph:g,getColumnMetrics:r.getColumnMetrics,crispCol:r.crispCol,init:function(b){a.seriesTypes.sma.prototype.init.apply(this,arguments);var c=this.options.params;var d=this.linkedParent;c=b.get(c.volumeSeriesID);this.addCustomEvents(d,c);return this},addCustomEvents:function(b,c){function d(){a.chart.redraw();a.setData([]);a.zoneStarts=
[];a.zoneLinesSVG&&(a.zoneLinesSVG.destroy(),delete a.zoneLinesSVG)}var a=this;a.dataEventsToUnbind.push(m(b,"remove",function(){d()}));c&&a.dataEventsToUnbind.push(m(c,"remove",function(){d()}));return a},animate:function(b){var c=this,d={};a.svg&&!b&&(d.translateX=c.yAxis.pos,c.group.animate(d,f(k(c.options.animation),{step:function(b,d){c.group.attr({scaleX:Math.max(.001,d.pos)})}})),c.animate=null)},drawPoints:function(){this.options.volumeDivision.enabled&&(this.posNegVolume(!0,!0),r.drawPoints.apply(this,
arguments),this.posNegVolume(!1,!1));r.drawPoints.apply(this,arguments)},posNegVolume:function(b,c){var d=c?["positive","negative"]:["negative","positive"],a=this.options.volumeDivision,e=this.points.length,f=[],h=[],k=0,g;b?(this.posWidths=f,this.negWidths=h):(f=this.posWidths,h=this.negWidths);for(;k<e;k++){var l=this.points[k];l[d[0]+"Graphic"]=l.graphic;l.graphic=l[d[1]+"Graphic"];if(b){var p=l.shapeArgs.width;var m=this.priceZones[k];(g=m.wholeVolumeData)?(f.push(p/g*m.positiveVolumeData),h.push(p/
g*m.negativeVolumeData)):(f.push(0),h.push(0))}l.color=c?a.styles.positiveColor:a.styles.negativeColor;l.shapeArgs.width=c?this.posWidths[k]:this.negWidths[k];l.shapeArgs.x=c?l.shapeArgs.x:this.posWidths[k]}},translate:function(){var b=this,d=b.options,a=b.chart,f=b.yAxis,k=f.min,g=b.options.zoneLines,m=b.priceZones,u=0,t,z,v;r.translate.apply(b);var B=b.points;if(B.length){var F=.5>d.pointPadding?d.pointPadding:.1;d=b.volumeDataArray;var G=e(d);var A=a.plotWidth/2;var Q=a.plotTop;var J=l(f.toPixels(k)-
f.toPixels(k+b.rangeStep));var K=l(f.toPixels(k)-f.toPixels(k+b.rangeStep));F&&(k=l(J*(1-2*F)),u=l((J-k)/2),J=l(k));B.forEach(function(d,a){z=d.barX=d.plotX=0;v=d.plotY=f.toPixels(m[a].start)-Q-(f.reversed?J-K:J)-u;t=c(A*m[a].wholeVolumeData/G);d.pointWidth=t;d.shapeArgs=b.crispCol.apply(b,[z,v,t,J]);d.volumeNeg=m[a].negativeVolumeData;d.volumePos=m[a].positiveVolumeData;d.volumeAll=m[a].wholeVolumeData});g.enabled&&b.drawZones(a,f,b.zoneStarts,g.styles)}},getValues:function(c,d){var a=c.processedXData,
e=c.processedYData,f=this.chart,k=d.ranges,g=[],l=[],h=[],m;if(c.chart)if(m=f.get(d.volumeSeriesID))if((d=u(e[0]))&&4!==e[0].length)b("Type of "+c.name+" series is different than line, OHLC or candlestick.",!0,f);else return(this.priceZones=this.specifyZones(d,a,e,k,m)).forEach(function(b,c){g.push([b.x,b.end]);l.push(g[c][0]);h.push(g[c][1])}),{values:g,xData:l,yData:h};else b("Series "+d.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,f);else b("Base series not found! In case it has been removed, add a new one.",
!0,f)},specifyZones:function(b,a,f,k,g){if(b){var l=f.length;for(var h=f[0][3],n=h,m=1,p;m<l;m++)p=f[m][3],p<h&&(h=p),p>n&&(n=p);l={min:h,max:n}}else l=!1;l=(h=l)?h.min:d(f);p=h?h.max:e(f);h=this.zoneStarts=[];n=[];var q=0;m=1;if(!l||!p)return this.points.length&&(this.setData([]),this.zoneStarts=[],this.zoneLinesSVG.destroy()),[];var u=this.rangeStep=c(p-l)/k;for(h.push(l);q<k-1;q++)h.push(c(h[q]+u));h.push(p);for(k=h.length;m<k;m++)n.push({index:m-1,x:a[0],start:h[m-1],end:h[m]});return this.volumePerZone(b,
n,g,a,f)},volumePerZone:function(b,c,d,a,e){var f=this,k=d.processedXData,g=d.processedYData,h=c.length-1,n=e.length;d=g.length;var m,p,q,u,r;l(n-d)&&(a[0]!==k[0]&&g.unshift(0),a[n-1]!==k[d-1]&&g.push(0));f.volumeDataArray=[];c.forEach(function(c){c.wholeVolumeData=0;c.positiveVolumeData=0;for(r=c.negativeVolumeData=0;r<n;r++)q=p=!1,u=b?e[r][3]:e[r],m=r?b?e[r-1][3]:e[r-1]:u,u<=c.start&&0===c.index&&(p=!0),u>=c.end&&c.index===h&&(q=!0),(u>c.start||p)&&(u<c.end||q)&&(c.wholeVolumeData+=g[r],m>u?c.negativeVolumeData+=
g[r]:c.positiveVolumeData+=g[r]);f.volumeDataArray.push(c.wholeVolumeData)});return c},drawZones:function(b,c,d,a){var e=b.renderer,f=this.zoneLinesSVG,k=[],g=b.plotWidth,l=b.plotTop,h;d.forEach(function(d){h=c.toPixels(d)-l;k=k.concat(b.renderer.crispLine(["M",0,h,"L",g,h],a.lineWidth))});f?f.animate({d:k}):f=this.zoneLinesSVG=e.path(k).attr({"stroke-width":a.lineWidth,stroke:a.color,dashstyle:a.dashStyle,zIndex:this.group.zIndex+.1}).add(this.group)}},{destroy:function(){this.negativeGraphic&&(this.negativeGraphic=
this.negativeGraphic.destroy());return a.Point.prototype.destroy.apply(this,arguments)}});""});v(a,"indicators/vwap.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.error,k=g.isArray;a=a.seriesType;a("vwap","sma",{params:{period:30,volumeSeriesID:"volume"}},{getValues:function(a,d){var c=a.chart,b=a.xData;a=a.yData;var e=d.period,g=!0,l;if(l=c.get(d.volumeSeriesID))return k(a[0])||(g=!1),this.calculateVWAPValues(g,b,a,l,e);m("Series "+d.volumeSeriesID+" not found! Check `volumeSeriesID`.",
!0,c)},calculateVWAPValues:function(a,d,c,b,f){var e=b.yData,k=b.xData.length,g=d.length;b=[];var m=[],h=[],p=[],n=[],q;k=g<=k?g:k;for(q=g=0;g<k;g++){var t=a?(c[g][1]+c[g][2]+c[g][3])/3:c[g];t*=e[g];t=q?b[g-1]+t:t;var v=q?m[g-1]+e[g]:e[g];b.push(t);m.push(v);n.push([d[g],t/v]);h.push(n[g][0]);p.push(n[g][1]);q++;q===f&&(q=0)}return{values:n,xData:h,yData:p}}});""});v(a,"indicators/williams-r.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/reduce-array.js"]],function(a,g,t){var k=
g.isArray,e=t.getArrayExtremes;a.seriesType("williamsr","sma",{params:{period:14}},{nameBase:"Williams %R",getValues:function(d,c){c=c.period;var b=d.xData,a=(d=d.yData)?d.length:0,g=[],l=[],m=[],r;if(!(b.length<c)&&k(d[0])&&4===d[0].length){for(r=c-1;r<a;r++){var h=d.slice(r-c+1,r+1);var p=e(h,2,1);h=p[0];p=p[1];var n=d[r][3];h=(p-n)/(p-h)*-100;b[r]&&(g.push([b[r],h]),l.push(b[r]),m.push(h))}return{values:g,xData:l,yData:m}}}});""});v(a,"indicators/wma.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],
function(a,g){function m(d,c){c*=(c+1)/2;return d.reduce(function(b,c,d){return[null,b[1]+c[1]*(d+1)]})[1]/c}function k(d,c,b,a){b=m(d,d.length);c=c[a-1];d.shift();return[c,b]}var e=g.isArray;a=a.seriesType;a("wma","sma",{params:{index:3,period:9}},{getValues:function(d,c){var b=c.period,a=d.xData,g=(d=d.yData)?d.length:0,l=1,m=a[0],r=d[0],h=[],p=[],n=[],q=-1;if(!(a.length<b)){e(d[0])&&(q=c.index,r=d[0][q]);for(c=[[m,r]];l!==b;)c.push([a[l],0>q?d[l]:d[l][q]]),l++;for(b=l;b<g;b++)l=k(c,a,d,b),h.push(l),
p.push(l[0]),n.push(l[1]),c.push([a[b],0>q?d[b]:d[b][q]]);l=k(c,a,d,b);h.push(l);p.push(l[0]);n.push(l[1]);return{values:h,xData:p,yData:n}}}});""});v(a,"indicators/zigzag.src.js",[a["parts/Globals.js"]],function(a){a=a.seriesType;a("zigzag","sma",{params:{lowIndex:2,highIndex:1,deviation:1}},{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag",getValues:function(a,m){var g=m.lowIndex,e=m.highIndex,d=m.deviation/100;m=1+d;var c=1-d;d=a.xData;var b=a.yData;a=b?b.length:0;var f=[],u=
[],l=[],t,r,h=!1,p=!1;if(!(!d||1>=d.length||a&&(void 0===b[0][g]||void 0===b[0][e]))){var n=b[0][g];var q=b[0][e];for(t=1;t<a;t++){if(b[t][g]<=q*c){f.push([d[0],q]);var v=[d[t],b[t][g]];h=r=!0}else b[t][e]>=n*m&&(f.push([d[0],n]),v=[d[t],b[t][e]],r=!1,h=!0);if(h){u.push(f[0][0]);l.push(f[0][1]);var P=t++;t=a}}for(t=P;t<a;t++)r?(b[t][g]<=v[1]&&(v=[d[t],b[t][g]]),b[t][e]>=v[1]*m&&(p=e)):(b[t][e]>=v[1]&&(v=[d[t],b[t][e]]),b[t][g]<=v[1]*c&&(p=g)),!1!==p&&(f.push(v),u.push(v[0]),l.push(v[1]),v=[d[t],b[t][p]],
r=!r,p=!1);g=f.length;0!==g&&f[g-1][0]<d[a-1]&&(f.push(v),u.push(v[0]),l.push(v[1]));return{values:f,xData:u,yData:l}}}});""});v(a,"indicators/regressions.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.isArray;a=a.seriesType;a("linearRegression","sma",{params:{xAxisUnit:void 0},tooltip:{valueDecimals:4}},{nameBase:"Linear Regression Indicator",getRegressionLineParameters:function(a,e){var d=this.options.params.index,c=function(b,c){return m(b)?b[c]:b},b=a.reduce(function(b,
c){return c+b},0),f=e.reduce(function(b,a){return c(a,d)+b},0);b/=a.length;f/=e.length;var g=0,k=0,t;for(t=0;t<a.length;t++){var r=a[t]-b;var h=c(e[t],d)-f;g+=r*h;k+=Math.pow(r,2)}a=k?g/k:0;return{slope:a,intercept:f-a*b}},getEndPointY:function(a,e){return a.slope*e+a.intercept},transformXData:function(a,e){var d=a[0];return a.map(function(a){return(a-d)/e})},findClosestDistance:function(a){var e,d;for(d=1;d<a.length-1;d++){var c=a[d]-a[d-1];0<c&&("undefined"===typeof e||c<e)&&(e=c)}return e},getValues:function(a,
e){var d=a.xData;a=a.yData;e=e.period;var c,b={xData:[],yData:[],values:[]},f=this.options.params.xAxisUnit||this.findClosestDistance(d);for(c=e-1;c<=d.length-1;c++){var g=c-e+1;var k=c+1;var m=d[c];var r=d.slice(g,k);g=a.slice(g,k);k=this.transformXData(r,f);r=this.getRegressionLineParameters(k,g);g=this.getEndPointY(r,k[k.length-1]);b.values.push({regressionLineParameters:r,x:m,y:g});b.xData.push(m);b.yData.push(g)}return b}});a("linearRegressionSlope","linearRegression",{},{nameBase:"Linear Regression Slope Indicator",
getEndPointY:function(a){return a.slope}});a("linearRegressionIntercept","linearRegression",{},{nameBase:"Linear Regression Intercept Indicator",getEndPointY:function(a){return a.intercept}});a("linearRegressionAngle","linearRegression",{tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span>{series.name}: <b>{point.y}\u00b0</b><br/>'}},{nameBase:"Linear Regression Angle Indicator",slopeToAngle:function(a){return 180/Math.PI*Math.atan(a)},getEndPointY:function(a){return this.slopeToAngle(a.slope)}});
""});v(a,"indicators/acceleration-bands.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/multipe-lines.js"]],function(a,g,t){var k=g.correctFloat;g=g.merge;var e=a.seriesTypes.sma;a.seriesType("abands","sma",{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},g(t,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Acceleration Bands",nameComponents:["period",
"factor"],linesApiNames:["topLine","bottomLine"],getValues:function(a,c){var b=c.period,d=c.factor;c=c.index;var g=a.xData,l=(a=a.yData)?a.length:0,m=[],r=[],h=[],p=[],n=[],q;if(!(l<b)){for(q=0;q<=l;q++){if(q<l){var t=a[q][2];var v=a[q][1];var D=d;t=k(v-t)/(k(v+t)/2)*1E3*D;m.push(a[q][1]*k(1+2*t));r.push(a[q][2]*k(1-2*t))}if(q>=b){t=g.slice(q-b,q);var w=a.slice(q-b,q);D=e.prototype.getValues.call(this,{xData:t,yData:m.slice(q-b,q)},{period:b});v=e.prototype.getValues.call(this,{xData:t,yData:r.slice(q-
b,q)},{period:b});w=e.prototype.getValues.call(this,{xData:t,yData:w},{period:b,index:c});t=w.xData[0];D=D.yData[0];v=v.yData[0];w=w.yData[0];h.push([t,D,w,v]);p.push(t);n.push([D,w,v])}}return{values:h,xData:p,yData:n}}}}));""});v(a,"indicators/trendline.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var m=g.isArray;a=a.seriesType;a("trendline","sma",{params:{index:3}},{nameBase:"Trendline",nameComponents:!1,getValues:function(a,e){var d=a.xData,c=a.yData;a=[];var b=[],f=[],
g=0,k=0,t=0,r=0,h=d.length,p=e.index;for(e=0;e<h;e++){var n=d[e];var q=m(c[e])?c[e][p]:c[e];g+=n;k+=q;t+=n*q;r+=n*n}c=(h*t-g*k)/(h*r-g*g);isNaN(c)&&(c=0);g=(k-c*g)/h;for(e=0;e<h;e++)n=d[e],q=c*n+g,a[e]=[n,q],b[e]=n,f[e]=q;return{xData:b,yData:f,values:a}}});""});v(a,"masters/indicators/indicators-all.src.js",[],function(){})});
//# sourceMappingURL=indicators-all.js.map