/*
 Highstock JS v8.0.0 (2020-02-08)

 Indicator series type for Highstock

 (c) 2010-2019 Daniel Studencki

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/price-channel",["highcharts","highcharts/modules/stock"],function(c){a(c);a.Highcharts=c;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function c(a,b,u,d){a.hasOwnProperty(b)||(a[b]=d.apply(null,u))}a=a?a._modules:{};c(a,"mixins/reduce-array.js",[a["parts/Globals.js"]],function(a){var b=a.reduce;return{minInArray:function(a,
d){return b(a,function(a,e){return Math.min(a,e[d])},Number.MAX_VALUE)},maxInArray:function(a,d){return b(a,function(a,e){return Math.max(a,e[d])},-Number.MAX_VALUE)},getArrayExtremes:function(a,d,c){return b(a,function(a,b){return[Math.min(a[0],b[d]),Math.max(a[1],b[c])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});c(a,"mixins/multipe-lines.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,b){var c=b.defined,d=b.error,r=b.merge,e=a.each,t=a.seriesTypes.sma;return{pointArrayMap:["top",
"bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(a){var h=[];e(this.pointArrayMap,function(b){b!==a&&h.push("plot"+b.charAt(0).toUpperCase()+b.slice(1))});return h},toYData:function(a){var h=[];e(this.pointArrayMap,function(b){h.push(a[b])});return h},translate:function(){var a=this,b=a.pointArrayMap,d=[],c;d=a.getTranslatedLinesNames();t.prototype.translate.apply(a,arguments);e(a.points,function(h){e(b,function(b,e){c=h[b];null!==c&&(h[d[e]]=a.yAxis.toPixels(c,
!0))})})},drawGraph:function(){var a=this,b=a.linesApiNames,p=a.points,n=p.length,l=a.options,k=a.graph,q={options:{gapSize:l.gapSize}},f=[],m=a.getTranslatedLinesNames(a.pointValKey),g;e(m,function(a,b){for(f[b]=[];n--;)g=p[n],f[b].push({x:g.x,plotX:g.plotX,plotY:g[a],isNull:!c(g[a])});n=p.length});e(b,function(b,e){f[e]?(a.points=f[e],l[b]?a.options=r(l[b].styles,q):d('Error: "There is no '+b+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),
a.graph=a["graph"+b],t.prototype.drawGraph.call(a),a["graph"+b]=a.graph):d('Error: "'+b+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=p;a.options=l;a.graph=k;t.prototype.drawGraph.call(a)}}});c(a,"indicators/price-channel.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/reduce-array.js"],a["mixins/multipe-lines.js"]],function(a,b,c,d){b=b.merge;var r=c.getArrayExtremes;a.seriesType("pc","sma",{params:{period:20},
lineWidth:1,topLine:{styles:{lineColor:"#90ed7d",lineWidth:1}},bottomLine:{styles:{lineColor:"#f45b5b",lineWidth:1}},dataGrouping:{approximation:"averages"}},b(d,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],getValues:function(a,b){b=b.period;var c=a.xData,d=(a=a.yData)?a.length:0,e=[],n=[],l=[],k;if(!(d<b)){for(k=b;k<=d;k++){var q=c[k-1];var f=a.slice(k-b,k);var m=r(f,2,1);f=m[1];var g=m[0];
m=(f+g)/2;e.push([q,f,m,g]);n.push(q);l.push([f,m,g])}return{values:e,xData:n,yData:l}}}}));""});c(a,"masters/indicators/price-channel.src.js",[],function(){})});
//# sourceMappingURL=price-channel.js.map