/*
 Highstock JS v8.0.0 (2020-02-08)

 Indicator series type for Highstock

 (c) 2010-2019 Pawe Fus

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/stochastic",["highcharts","highcharts/modules/stock"],function(f){a(f);a.Highcharts=f;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function f(a,b,w,c){a.hasOwnProperty(b)||(a[b]=c.apply(null,w))}a=a?a._modules:{};f(a,"mixins/reduce-array.js",[a["parts/Globals.js"]],function(a){var b=a.reduce;return{minInArray:function(a,
c){return b(a,function(a,e){return Math.min(a,e[c])},Number.MAX_VALUE)},maxInArray:function(a,c){return b(a,function(a,e){return Math.max(a,e[c])},-Number.MAX_VALUE)},getArrayExtremes:function(a,c,f){return b(a,function(a,b){return[Math.min(a[0],b[c]),Math.max(a[1],b[f])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});f(a,"mixins/multipe-lines.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,b){var f=b.defined,c=b.error,t=b.merge,e=a.each,n=a.seriesTypes.sma;return{pointArrayMap:["top",
"bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(a){var h=[];e(this.pointArrayMap,function(d){d!==a&&h.push("plot"+d.charAt(0).toUpperCase()+d.slice(1))});return h},toYData:function(a){var h=[];e(this.pointArrayMap,function(d){h.push(a[d])});return h},translate:function(){var a=this,b=a.pointArrayMap,d=[],c;d=a.getTranslatedLinesNames();n.prototype.translate.apply(a,arguments);e(a.points,function(h){e(b,function(b,e){c=h[b];null!==c&&(h[d[e]]=a.yAxis.toPixels(c,
!0))})})},drawGraph:function(){var a=this,b=a.linesApiNames,d=a.points,u=d.length,q=a.options,x=a.graph,y={options:{gapSize:q.gapSize}},l=[],m=a.getTranslatedLinesNames(a.pointValKey),g;e(m,function(a,b){for(l[b]=[];u--;)g=d[u],l[b].push({x:g.x,plotX:g.plotX,plotY:g[a],isNull:!f(g[a])});u=d.length});e(b,function(b,d){l[d]?(a.points=l[d],q[b]?a.options=t(q[b].styles,y):c('Error: "There is no '+b+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),
a.graph=a["graph"+b],n.prototype.drawGraph.call(a),a["graph"+b]=a.graph):c('Error: "'+b+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=d;a.options=q;a.graph=x;n.prototype.drawGraph.call(a)}}});f(a,"indicators/stochastic.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/reduce-array.js"],a["mixins/multipe-lines.js"]],function(a,b,f,c){var t=b.isArray,e=b.merge,n=a.seriesTypes.sma,h=f.getArrayExtremes;a.seriesType("stochastic",
"sma",{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},e(c,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],init:function(){n.prototype.init.apply(this,arguments);
this.options=e({smoothedLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(a,b){var c=b.periods[0];b=b.periods[1];var d=a.xData,e=(a=a.yData)?a.length:0,f=[],l=[],m=[],g=null,k;if(!(e<c)&&t(a[0])&&4===a[0].length){for(k=c-1;k<e;k++){var p=a.slice(k-c+1,k+1);var v=h(p,2,1);var r=v[0];p=a[k][3]-r;r=v[1]-r;p=p/r*100;l.push(d[k]);m.push([p,null]);k>=c-1+(b-1)&&(g=n.prototype.getValues.call(this,{xData:l.slice(-b),yData:m.slice(-b)},{period:b}),g=g.yData[0]);f.push([d[k],p,g]);m[m.length-
1][1]=g}return{values:f,xData:l,yData:m}}}}));""});f(a,"masters/indicators/stochastic.src.js",[],function(){})});
//# sourceMappingURL=stochastic.js.map