/*
 Highstock JS v8.0.0 (2020-02-08)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/indicators/supertrend",["highcharts","highcharts/modules/stock"],function(k){c(k);c.Highcharts=k;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function k(c,v,u,k){c.hasOwnProperty(v)||(c[v]=k.apply(null,u))}c=c?c._modules:{};k(c,"indicators/supertrend.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,k){function u(e,
b,g){return{index:b,close:e.yData[b][g],x:e.xData[b]}}var v=k.correctFloat,y=k.merge,A=k.isArray,B=k.objectEach,C=c.seriesTypes.atr,z=c.seriesTypes.sma;c.seriesType("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:"#06B535",fallingTrendColor:"#F21313",changeTrendLine:{styles:{lineWidth:1,lineColor:"#333333",dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){z.prototype.init.apply(this,arguments);var e=
this.options;e.cropThreshold=this.linkedParent.options.cropThreshold-(e.params.period-1)},drawGraph:function(){var e=this,b=e.options,g=e.linkedParent,c=g?g.points:[],k=e.points,v=e.graph,r=k.length,t=c.length-r;t=0<t?t:0;for(var x={options:{gapSize:b.gapSize}},m={top:[],bottom:[],intersect:[]},w={top:{styles:{lineWidth:b.lineWidth,lineColor:b.fallingTrendColor||b.color,dashStyle:b.dashStyle}},bottom:{styles:{lineWidth:b.lineWidth,lineColor:b.risingTrendColor||b.color,dashStyle:b.dashStyle}},intersect:b.changeTrendLine},
a,l,d,f,h,n,p,q;r--;)a=k[r],l=k[r-1],d=c[r-1+t],f=c[r-2+t],h=c[r+t],n=c[r+t+1],p=a.options.color,q={x:a.x,plotX:a.plotX,plotY:a.plotY,isNull:!1},!f&&d&&g.yData[d.index-1]&&(f=u(g,d.index-1,3)),!n&&h&&g.yData[h.index+1]&&(n=u(g,h.index+1,3)),!d&&f&&g.yData[f.index+1]?d=u(g,f.index+1,3):!d&&h&&g.yData[h.index-1]&&(d=u(g,h.index-1,3)),a&&d&&h&&f&&a.x!==d.x&&(a.x===h.x?(f=d,d=h):a.x===f.x?(d=f,f={close:g.yData[d.index-1][3],x:g.xData[d.index-1]}):n&&a.x===n.x&&(d=n,f=h)),l&&f&&d?(h={x:l.x,plotX:l.plotX,
plotY:l.plotY,isNull:!1},a.y>=d.close&&l.y>=f.close?(a.color=p||b.fallingTrendColor||b.color,m.top.push(q)):a.y<d.close&&l.y<f.close?(a.color=p||b.risingTrendColor||b.color,m.bottom.push(q)):(m.intersect.push(q),m.intersect.push(h),m.intersect.push(y(h,{isNull:!0})),a.y>=d.close&&l.y<f.close?(a.color=p||b.fallingTrendColor||b.color,l.color=p||b.risingTrendColor||b.color,m.top.push(q),m.top.push(y(h,{isNull:!0}))):a.y<d.close&&l.y>=f.close&&(a.color=p||b.risingTrendColor||b.color,l.color=p||b.fallingTrendColor||
b.color,m.bottom.push(q),m.bottom.push(y(h,{isNull:!0}))))):d&&(a.y>=d.close?(a.color=p||b.fallingTrendColor||b.color,m.top.push(q)):(a.color=p||b.risingTrendColor||b.color,m.bottom.push(q)));B(m,function(a,b){e.points=a;e.options=y(w[b].styles,x);e.graph=e["graph"+b+"Line"];z.prototype.drawGraph.call(e);e["graph"+b+"Line"]=e.graph});e.points=k;e.options=b;e.graph=v},getValues:function(c,b){var g=b.period;b=b.multiplier;var e=c.xData,k=c.yData,u=[],r=[],t=[],x=0===g?0:g-1,m=[],w=[],a;if(!(e.length<=
g||!A(k[0])||4!==k[0].length||0>g)){c=C.prototype.getValues.call(this,c,{period:g}).yData;for(a=0;a<c.length;a++){var l=k[x+a];var d=k[x+a-1]||[];var f=m[a-1];var h=w[a-1];var n=t[a-1];0===a&&(f=h=n=0);g=v((l[1]+l[2])/2+b*c[a]);var p=v((l[1]+l[2])/2-b*c[a]);m[a]=g<f||d[3]>f?g:f;w[a]=p>h||d[3]<h?p:h;if(n===f&&l[3]<m[a]||n===h&&l[3]<w[a])var q=m[a];else if(n===f&&l[3]>m[a]||n===h&&l[3]>w[a])q=w[a];u.push([e[x+a],q]);r.push(e[x+a]);t.push(q)}return{values:u,xData:r,yData:t}}}});""});k(c,"masters/indicators/supertrend.src.js",
[],function(){})});
//# sourceMappingURL=supertrend.js.map